### ISSUE TITLE
strContains and strContainsIgnoreCase

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda#1016]
Would these additions be interesting for ramda?
```
  strContains('foo', 'fooBar') //=> true
  strContains('bar', 'fooBar') //=> false
  strContainsIgnoreCase('fOo', 'fooBar') //=> true
  strContainsIgnoreCase('bar', 'fooBar') //=> true
```

**Comment by buzzdecafe** [comment]
wouldn't this simply be:

```javascript
var strContains = R.curry(R.compose(Boolean, R.match));
```

http://bit.ly/1CkSeBp

**Comment by TheLudd** [comment]
Surely it can be acheived through combining other ramda functions. I just wondered if it was a common enough case to motivate a function of its own. Your example was quite nice though.

**Comment by buzzdecafe** [comment]
i'm more than a bit wary of string functions. See https://github.com/ramda/ramda/blob/master/src/trim.js for the reason why. they seem so simple on the surface ....

**Comment by TheLudd** [comment]
Ok, closing, will probably use the solution you suggested

**Comment by CrossEye** [comment]
I'm less worried about string APIS.  I believe that one was a pretty bad exception.  Moreover the suggested workaround is not as complete as might be liked (http://bit.ly/1FnGfJD) because of regex restrictions.  [This one][ex] might work, but is still somewhat nasty:

    strContains = R.pipe(R.invoker(1, 'indexOf'), R.gt(R.__, -1));

I don't have a strong feeling either way about including such functions in Ramda.

  [ex]: http://bit.ly/1FnIlcn
