### ISSUE TITLE
returning a reference to input object

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1025]
This has been discussed in #1018 and elsewhere. Let's continue the discussion here.

The question is whether it's okay for a function which usually returns a *new* object to return the input object in certain cases. Is it okay for `R.slice(0, Infinity, xs)` to return `xs`, for example, or should it return a shallow clone of `xs`?

**Comment by paldepind** [comment]
I agree with @megawac. A function that sometimes returns a new object and sometimes returns the passed object seems inconsistent to me. Then I suddenly can't rely on it to return a new object anymore.

In the cases where the difference matters I'll have a harder time reasoning about what might happen. I'll have to ask myself "could this code in any circumstances call `slice` with the specific arguments for which it won't clone it's input?" and if I conclude that the answer is "yes" I'll have to clone manually. And if I mistakenly conclude that the answer is "no" I've just introduced a bug in my program.

This is slightly similar to how functions that are sometimes synchronous and sometimes asynchronous are a disaster. Imagine if `Array.prototype.slice` had returned the exact array when passed with 0. As in `arr === arr.slice(0)`. That would have been bad right?

I think this introduces a lot of uncertainty to the API. Does `R.sort` return the passed in list if it is already sorted? I no longer know.

**Comment by buzzdecafe** [comment]
still mulling it over, but i'm pretty sure i'm on the other side. IMO we shouldn't be in the business of _enforcing_ behavior. If you want to mutate your objects, then _caveat emptor_.

> A function that sometimes returns a new object and sometimes returns the passed object seems inconsistent to me.

only if you are relying on reference equality, and that seems a bit weird. As far as I can see, what you are recommending is:

```javascript
var p = {x: 1}; 
var q = R.identity(p);
p === q; //=> false, since q is a clone
```

and that would be *very* surprising to me.

**Comment by megawac** [comment]
I'm done arguing this but it seems like a new user trap; consider someone
who decides to convert a codebase. This one may be minor but I hope no
others follow suit

**Comment by paldepind** [comment]
> only if you are relying on reference equality, and that seems a bit weird.

No. The function is inconsistent because is sometimes does one thing and sometimes does another thing. A function that returns a new object provides two guarantees:

1/ You can modify the returned object without affecting anybody.
2/ Nobody except you can modify this object.

Both of these stems from the fact that you are the only one with a reference to the object. You _own_ the object. If the function sometimes returns a new object and sometimes the input object then you can't rely on those guarantees at all. Someone else could have a reference to the object and they could modify it.

> As far as I can see, what you are recommending is: [...] and that would be very surprising to me.

No. `R.identity` is consistent because it always returns the input object. `R.identity` provides the guarantee that `obj === R.identity(obj)` for _any_ `obj` and thus you can easily reason about it.

What I don't like is functions that switch between the two types of behavior. They're hard to reason about. Just like functions that are sometimes synchronous and sometimes asynchronous are hard (impossible actually) to reason about.

Consider this example:
```javascript
var list = [1,2,3,4,5];
var list2 = R.drop(n, [1, 2, 3, 4, 5]);
console.log(list === list2);
```
Tell me, does this code log `true` or `false`? The answer is: it depends on _n_. So you don't know because you don't know what `n` is. I.e. you can't reason about the result of this code in isolation! That's bad. A proper implementation of `drop` would guarantee that the result would always be `true` (in case of a mutating function) or `false` (a pure function). The current implementation doesn't guarantee _anything_.

Now, consider this code:
```javascript
function dropAndDoSomething(n, list) {
  var clone = R.clone(list);
  var list2 = R.drop(n, [1, 2, 3, 4, 5]);
  return someAsynOperation.then(function() {
    return R.eqDeep(clone, list2);
  });
};
```
Does this function resolve to `true` or `false`? Again, you don't know. It depends on `n` and on whether or not some other code modified the list that was passed in. Since `drop` doesn't guarantee anything we can't reason about the code.

Ramda will never optimal performance and that is not why people use it. I use it because I'd like my code to be easy to reason about and I think these negligible performance optimizations partly destroys that.

**Comment by CrossEye** [comment]
I was going to try to write up some examples, but they would probably just duplicate the points made by @paldepind.  While it would be nice not to have to care ever about reference equality, we are still trying to be a library _for Javascript programmers_.  Those who are working on systems not totally converted to immutability could get in real trouble if our API is inconsistent in this matter.

> If you want to mutate your objects, then _caveat emptor_.

Sure, but what if the guy down the hall does it six months from now?  Or even better, it's in the codebase now, not causing an issue because `n` has always been much smaller than the list length, until one day...  If for no other reason, then just to enforce a consistency, and to be able to document with things like, "returns a **new** collections that...", I think it's a good idea to reverse what we've done lately on this issue.

**Comment by buzzdecafe** [comment]
if someone can point me to a reliable way to determine equality for objects maybe i'll agree.

```javascript
var list = [1,2,3,4,5];
var list2 = R.drop(n, list); //=> this must be what you meant
console.log(list === list2);
```

fair :point_right: 
but primitives are easy.

```javascript
var list = [Just(1), Nothing, Just(3), Just(4), Just(5)];
var list2 = R.drop(n, [Just(1), Nothing, Just(3), Just(4), Just(5)]);
typeof list[0].map //=> 'function'
typeof list2[0].map //=> 'undefined'
```

**Comment by paldepind** [comment]
Yes, indeed. That was what I meant to type in my example.

I don't follow your last example :confused:

**Comment by buzzdecafe** [comment]
what i'm trying to say is if you have a list of constructed objects with prototypes, what happens when you clone that?

**Comment by CrossEye** [comment]
I don't understand that example either.  `drop` was recently updated.  We could do something similar with `slice`, perhaps changing from this:

    function slice(fromIndex, toIndex, xs) {
      return Array.prototype.slice.call(xs, fromIndex, toIndex);
    }

to this:

    function slice(fromIndex, toIndex, xs) {
      return (fromIndex === 0 > toIndex >= xs.length) ? 
                 xs: 
                 Array.prototype.slice.call(xs, fromIndex, toIndex);
    }

If we do that, then it becomes unclear when `R.slice` returns a shallow clone versus the original list.

**Comment by CrossEye** [comment]
@buzzdecafe: We're only talking about shallow clones.

**Comment by buzzdecafe** [comment]
`var clone = R.clone(list);` is a deep clone

**Comment by CrossEye** [comment]
I don't think anyone is talking about doing that, though.  I'm certainly not.  `_slice` would be fine.

**Comment by megawac** [comment]
I'd definitely be surprised by a deep clone - I'd expect a new list for all
cases though

**Comment by CrossEye** [comment]
This is the sort of example we're talking about:

    var a = {}, b = {}, c = {};
    var x = [a, b, c];
    drop(0, x) === x; //=> used to be false, now is true.  I think it should be false

**Comment by megawac** [comment]
Yeah, that would take the smallest change to drop

- return n <= 0 ? list : _slice(list, n);
+ return _slice(list, Math.max(0, n));

**Comment by paldepind** [comment]
> var clone = R.clone(list); is a deep clone

I used `R.clone` in my example because I don't know of a Ramda shallow clone function. I'm not saying the list functions should do a deep clone. But they should return a new lists. Similar to `Array.prototype.slice`.

**Comment by buzzdecafe** [comment]
> I'm not saying the list functions should do a deep clone. But they should return a new list

in that case i think i am with you. 

that'll teach me to pay attention to the examples.

**Comment by scott-christopher** [comment]
I was originally in favour of returning the same object instance to simplify checking large state objects for changes by only having to compare the instance of the root, however I concede that others likely have to deal with external code that mutates instances and I would much prefer to offer safety over convenience.

And if I really want the identity behaviour, I can still do so explicitly with something like:
```js
dropIdentity = R.cond([R.eq(0), R.nthArg(1)], [R.T, R.drop]);

list = [1, 2, 3];
list === dropIdentity(0, list); //=> true
dropIdentity(1, list); //=> [2, 3]
```

**Comment by CrossEye** [comment]
@davidchambers, what say you?

**Comment by davidchambers** [comment]
I don't have a *strong* opinion on this matter. I believe the onus is on the mutator to clone, but I'm just one Ramda user. Several people have stated a preference for ensuring functions which usually return a new object *always* do so. I'm willing to accommodate these wishes. :)

We should add [`assert.notStrictEqual`][1] assertions to the test suite where appropriate and update the implementations as necessary.


[1]: https://nodejs.org/api/assert.html#assert_assert_notstrictequal_actual_expected_message

**Comment by jethrolarson** [comment]
Drop 0 seems like a no-op to me. Should logically no-op things just act as identity?

**Comment by CrossEye** [comment]
@jethrolarson: But that leads to this rather surprising behavior:

```js
var nbrs = R.range(1, 11);
R.map(R.drop(R.__, nbrs), [8, 6, 7, 5, 3, 0, 9]); //=> [
//   [9,10],  <-- new list
//   [7,8,9,10], <-- new list
//   [8,9,10], <-- new list
//   [6,7,8,9,10], <-- new list
//   [4,5,6,7,8,9,10], <-- new list
//   [1,2,3,4,5,6,7,8,9,10], <-- reference to `nbrs`
//   [10] <-- new list
// ]
```

That sort of inconsistency from the library is what some of us are objecting to.

**Comment by jethrolarson** [comment]
I can see that. I actually don't have strong feelings either way

**Comment by buzzdecafe** [comment]
> That sort of inconsistency from the library is what some of us are objecting to.

Yes, @paldepind made a good case. Still feels weird to me that we should care about *reference equality*. Seems to me we should be concerned with the values. But I think his case is stronger than my queasy feeling.

**Comment by buzzdecafe** [comment]
i think this is pretty much settled in favor of the arguments of @paldepind and @megawac. Therefore, this one is closed. 

> We should add `assert.notStrictEqual` assertions

Will make a separate issue for this.
