### ISSUE TITLE
Placeholder in partial application method

### ISSUE THREAD

**Issue by bahmutov** [ramda/ramda#1027]
Placeholder value `R.__` is not working with `R.partial`. In the example below it should leave "b" free to be applied, but never applies it. It should apply 4 to "b" in my opinion.

```js
function add(a, b, c) { 
  console.log('a', a, 'b', b, 'c', c);
  return a+b+c;
}
var add2_5 = R.partial(add, 2, R.__, 5);
add2_5(4);
// prints "a 2 b {ramda: "placeholder"} c 5"
// output 2[object Object]5
```

**Comment by buzzdecafe** [comment]
thanks, that looks like a :beetle: alright

**Comment by davidchambers** [comment]
I agree that `R.partial` and `R.partialRight` should respect the `R.__` placeholder. The implementation could be similar to jashkenas/underscore#1382.

**Comment by buzzdecafe** [comment]
that sounds like you are volunteering @davidchambers :smiling_imp:

**Comment by CrossEye** [comment]
We definitely should do this.  And that Underscore implementation looks useful.

**Comment by CrossEye** [comment]
Anyone want to create a PR for this?

Anyone?  Anyone?  @bahmutov?

**Comment by davidchambers** [comment]
I was initially excited by this idea, but I now wonder whether it's something we should support. One can use `R.curry` instead. For example,

```javascript
var add2_5 = R.partial(add, 2, R.__, 5);
```

could be written

```javascript
var add2_5 = R.curry(add)(2, R.__, 5);
```

**Comment by CrossEye** [comment]
I'd like to hear from users who actually _use_ `partial/Right` on this.

We have `partial` because of all the discussions about the difference between currying and partial application.  (I do understand the technical differences, and realize that what we call _currying_ in Ramda is something in between the two.)  It seemed that there were people who really wanted to just use partial application of their functions.

I am -- ahem -- partial to currying, and never use our `partial`-application, so I don't have a real sense if there are reasons that users who wanted the placeholder couldn't simply use `curry` instead.

Can anyone answer this?

**Comment by paldepind** [comment]
I've only used `R.partial` when fully applying a function but not wanting to invoke it yet. I.e. to apply n arguments to a n-ary function in order to get back a zero-arity function.

**Comment by davidchambers** [comment]
I never use `R.partial`, but I occasionally use `R.partialRight` to avoid using the placeholder:

```javascript
var readFile = R.partialRight(fs.readFileSync, {encoding: 'utf8'});
```

Rather than:

```javascript
var readFile = R.curry(fs.readFileSync)(R.__, {encoding: 'utf8'});
```

**Comment by davidchambers** [comment]
Closing without prejudice

**Comment by shdpl** [comment]
I just tried to use placeholders in partial() instinctively, but as you noticed it's no-go.
I believe this functionality has its place just as compose / pipe functions do.

I'm not opening a new ticket as i'm still quite fresh in ramda, and i don't feel competent reasoning more, than i just said.

**Comment by davidchambers** [comment]
@shdpl, would you mind sharing the code snippet? I'm interested to see whether it could be written naturally in terms of `R.curry` or `R.partialRight`, or whether `R.partial` with placeholders really is the most natural expression of the idea.

**Comment by shdpl** [comment]
I guess that situation will happen anytime you want to inject something in a middle, so more arguments your functions take, more chances for that. I'm not used to "classical" functional style where you need to care about parameter ordering that much. I also like to define variables only if something needs to be used at least twice, so it's quite possible that people who program in "classical way" do not have such needs.

var f = R.curry( GoogleMaps.on )( 'overlaycomplete', R.__, this.drawingDisable )
var f = R.partial( GoogleMaps.on, 'overlaycomplete', R.__, this.drawingDisable )

I'm not saying it's hell of a difference, but second definition just feels more natural ( to me ).

**Comment by davidchambers** [comment]
> I'm not saying it's hell of a difference, but second definition just feels more natural ( to me ).

I find the `R.partial` definition more natural too. The question is whether slightly more natural definitions in these cases justify the documentation complexity and implementation complexity of overloading `R.__`. My current view is that they do not, since the alternative definitions are almost as nice.

Perhaps the solution is to explain in the documentation of `R.partial` how `R.curry` can be used to mimic `_.partial` with placeholders.

I'm open to changing my mind on this matter. Feel free to post more examples here as you encounter situations where placeholder support in `R.partial` would be useful.
