### ISSUE TITLE
paritionIndexed?

### ISSUE THREAD

**Issue by jorda0mega** [ramda/ramda#1028]
Is there a way to pass in the index to the partition function to be able to partition by number of items much in the same way that clojure's partition works? Or would this have to be implemented through a separate function such as partitionIndexed?

**Comment by davidchambers** [comment]
What's your objective? Do you wish to transform something like `['r', 'a', 'm', 'd', 'a']` into something like `[['r', 'a', 'm'], ['d', 'a']]`? It might be simpler to do something like `[R.take(3, xs), R.drop(3, xs)]` in this case.

**Comment by jorda0mega** [comment]
given an array I want to partition it in equal parts of x items each. So something like this (say x is 4):
``` javascript
var a = [0,1,2,3,4,5,6,7,8,9,10,11];
R.partition(4, a) => [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
```

**Comment by davidchambers** [comment]
This was proposed in #774. Everyone seemed keen on the idea, so we'd welcome a pull request. :)

**Comment by jorda0mega** [comment]
fair enough. I'll get on it :)

**Comment by davidchambers** [comment]
> fair enough. I'll get on it :)

Terrific! Thank you!

**Comment by tipdbmp** [comment]
I don't know how to curry... =)

        // http://clojuredocs.org/clojure.core/partition
        // (partition n coll) (partition n step coll) (partition n step pad coll)
        // doesn't curry
        function partition() {
            var args_len = arguments.length;
            var n, step, pad, coll;

            if (args_len === 2) {
                n    = arguments[0];
                coll = arguments[1];
                step = n;
                pad  = undefined;
            }
            else if (args_len === 3) {
                n    = arguments[0];
                step = arguments[1];
                coll = arguments[2];
                pad  = undefined;
            }
            else if (args_len === 4) {
                n    = arguments[0];
                step = arguments[1];
                pad  = arguments[2];
                coll = arguments[3];
            }
            else {
                throw "partition takes: 2, 3 or 4 positional arguments: " 
                    + arguments.length + " given";
            }

            var result = [];
            var coll_len = coll.length;

            var i = 0;
            while (i + n <= coll_len) {
                result.push(coll.slice(i, i + n));
                i += step;
            }

            if (i < coll_len && Array.isArray(pad)) {
                var rest_plus_pad = [];
                rest_plus_pad.push.apply(rest_plus_pad, coll.slice(i, coll_len));
                rest_plus_pad.push.apply(rest_plus_pad, pad);

    //             i = 0;
    //             var rest_plus_pad_len = rest_plus_pad.length;
    //             while (i + n <= rest_plus_pad_len) {
    //                 result.push(rest_plus_pad.slice(i, i + n));
    //                 i += step;
    //             }

                result.push(rest_plus_pad.slice(0, n));
            }

            return result;
        }

**Comment by CrossEye** [comment]
1. Currying is pretty central to Ramda.   We can help with the currying once we get to a fixed list of parameters. 

  2. We already have a function named `partition`, similar to the [Haskell function][hp] of that name.  We'd have to think of another name for this one.  Nothing is coming to mind right now, but perhaps `slide` will do for this discussion, thinking about it as a sliding window.

  3. `pad` seems overkill.  I know that the Clojure function includes it, and I can see its potential utility, but not at the expense of cluttering an API.

  4. Ramda makes it a point never to do the sort of parameter juggling on display here.  If we were to skip `pad`, could we simply assume that `n`, `step`, and `coll` (better named `list` in Ramda) are required?  We might want to reverse them, though, so that `step` came before `n`.  That would allow us to rewrite `aperture` if desired as `slide(1)`.  And we could if we wanted write a `chunk` as `R.curry(function(n, list) {return slide(n, n, list);})` (anything simpler?).

  [hp]: https://hackage.haskell.org/package/base-4.8.0.0/docs/Data-List.html#v:partition

**Comment by CrossEye** [comment]
The other possibility is to consider simply adding `chunk`:

    // chunk:: Integer -> [a] -> [[a]];
   chunk(3, [1, 2, 3, 4, 5, 6, 7, 8]) //=> [[1, 2, 3], [4, 5, 6], [7, 8]]

...and assume that between this an `aperture` we have covered almost all reasonable use-cases.  Granted, this function would do all that and more (well a little less too, as there's a bug in it, I think -- not returning the last few elements if no `pad` is supplied), it still might be enough just to deal with the two simpler cases and not try to do everything this function does.
