### ISSUE TITLE
simplify R.where

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1032]
One of the things we often cite as a difference between Ramda and certain other utility libraries is its [simple][1] API. [`R.where`][2] is not simple (emphasis mine):

> Takes a spec object and a test object and returns true if the test satisfies the spec. Any property on the spec *that is not a function* is interpreted as an equality relation.
>
> *If the spec has a property mapped to a function, then `where` evaluates the function, passing in the test object's value for the property in question, as well as the whole test object.*

Making the behaviour of `R.where` dependent on the types of the spec's values increases the complexity of this function. The ability to provide a function is very useful, though. I propose that each of the spec's values *must* be a function. This offers several advantages:

  - simpler implementation;
  - simpler type signature;
  - simpler documentation;
  - it exposes users to the strictly more powerful functionality; and
  - it removes an edge case.

This demonstrates the edge case:

```javascript
> Array.prototype.foo = {}
{}
> Array.prototype.bar = function() {}
[Function]
> R.where({foo: Array.prototype.foo}, [])
true
> R.where({bar: Array.prototype.bar}, [])
false
```

Existing uses of `R.where` could then be trivially transformed thanks to [`R.eq`][3]:

```diff
-var spec = {x: 2};
+var spec = {x: R.eq(2)};
 R.where(spec, {w: 10, x: 2, y: 300}); //=> true
 R.where(spec, {x: 1, y: 'moo', z: true}); //=> false

 var spec2 = {x: function(val, obj) { return  val + obj.y > 10; }};
 R.where(spec2, {x: 2, y: 7}); //=> false
 R.where(spec2, {x: 3, y: 8}); //=> true

 var xs = [{x: 2, y: 1}, {x: 10, y: 2}, {x: 8, y: 3}, {x: 10, y: 4}];
-R.filter(R.where({x: 10}), xs); // ==> [{x: 10, y: 2}, {x: 10, y: 4}]
+R.filter(R.where({x: R.eq(10)}), xs); // ==> [{x: 10, y: 2}, {x: 10, y: 4}]
```

Actually, a trivial transformation is *not* possible due to another source of complexity: the function is passed the value *and the object in question* (as can be seen in the `spec2` example above). We'd need to stop passing this second argument as part of this change to make `R.eq` viable. This would lose us the ability to make decisions based on multiple fields, though this is a different problem for which `R.where` is not a good fit. The `spec2` example is better written *without* `R.where`:

```javascript
var pred = function(obj) { return obj.x + obj.y > 10; };
pred({x: 2, y: 7});  // => false
pred({x: 3, y: 8});  // => true
```

[1]: http://www.infoq.com/presentations/Simple-Made-Easy
[2]: http://ramdajs.com/docs/#where
[3]: http://ramdajs.com/docs/#eq

**Comment by buzzdecafe** [comment]
mostly fine with this. how do you propose to express more complex constraints like `spec2`?

**Comment by davidchambers** [comment]
> how do you propose to express more complex constraints like `spec2`?

See the code block at the end of the issue description. :)

If multiple fields must be considered together, a function which compares fields individually is not a good choice. ;)

**Comment by buzzdecafe** [comment]
while i agree this is simpler, it is also *much* less powerful. if, in addition to all my single-property constraints, i want to express the constraint that e.g. `obj.x === obj.y` i have to pass the object to another function?

**Comment by davidchambers** [comment]
Composition to the rescue:

```javascript
R.both(R.where({w: R.eq(0), z: R.gt(R.__, 0)}),
       R.converge(R.eq, R.prop('x'), R.prop('y')))
```

**Comment by CrossEye** [comment]
I think I could agree to the idea.  

But I don't follow this:

> We'd need to stop passing this second argument as part of this change to make `R.eq` viable. 

Surely any use of this would involve `R.eq(something)`, which is a unary function and would ignore any second argument passed to it.  So I don't see anything that would prevent us from continuing to supply the whole object.  Whether or not we should is a different question, though.  My example with the triangle inequality is a bit strained, although actually based on a real-world problem I worked with.  Mike's `obj.x === obj.y` seems a little more realistic.  But I agree that such cases seem at the very least less than central to the main concern.

I am still hesitant about the whole change, and exactly for the reasons of simplicity.  Granted, this function is less simple than many of the others in the library.  But of the two ways we could choose to simplify it, this is the less simple of them.  I guess it's more in the spirit of Ramda, but even more simple than this proposal would be one that removed the function parameters altogether, sticking only with matching equal values.  I know that this is less flexible, but it's really the original reason for creating the function.

There's one other strong point in favor of this.  The simplified implementation would remove what I'm guessing is a serious performance problem still lurking in our current implementation.  Reworking `where` was the start of our whole journey into building better currying.  It was the one the was demonstrated to have a serious performance issue in comparison with similar functions from other libraries.  I took it apart, and put back together a fairly horrible bit of code that worked, but it was manually curried in order to solve the main issues.  Somewhere, at some point, this came back into the fold of the functions that are automatically curried.  I'm guessing that we lost many of the performance gains in doing so, though.  This API change would presumably allow us to restore some of those lost performance gains, as it would remove the reason for the manual currying.

I guess my overall answer is that yes I like this change.

**Comment by CrossEye** [comment]
> Composition to the rescue:
> 
> ```javascript
> R.both(R.where({w: R.eq(0), z: R.gt(R.__, 0)}),
>        R.converge(R.eq, R.prop('x'), R.prop('y')))
> ```

You've got to admit though, that that's a far cry from

    R.where({w: 0, z: 0, x: (x, obj) => (x === obj.y)})

**Comment by davidchambers** [comment]
> You've got to admit though, that that's a far cry from
>
>     R.where({w: 0, z: 0, x: (x, obj) => (x === obj.y)})

I do admit this. Sugar can be a good thing. It can certainly reduce the number of characters required to express an idea. In this example, though, I dislike the misrepresentation of a multiple-field constraint as a single-field constraint at the property-name level. Also, if I were to read this code I would recognize that there is magic at play and would be forced to read the documentation and/or the source code in order to familiarize myself with the magic.

> > We'd need to stop passing this second argument as part of this change to make `R.eq` viable.
>
> Surely any use of this would involve `R.eq(something)`, which is a unary function and would ignore any second argument passed to it. So I don't see anything that would prevent us from continuing to supply the whole object.

You're absolutely right.

So we're free to continue to provide the second argument, though I'm opposed to doing so since `R.where` is not well suited to expressing multiple-field constraints.

**Comment by buzzdecafe** [comment]
that composition makes `where` itself virtually unnecessary.

`obj.x === obj.y` is a constraint on `obj.x`. it just so happens that the constraint is dynamic, since it is referring to another property on the same object. expressing that as a constraint on property `x` seems completely sensible to me. I don't see why we should remove the ability to express this kind of constraint from `where`.
