### ISSUE TITLE
Function Definition Syntax

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1035]
I'm confused about what this means:

Converge Function
 ((*… → c) → (((* → a), (* → b), …) → c)

After staring at the example, I can figure out what converge does, but I still don't get what this means...

**Comment by CrossEye** [comment]
... with good reason.   That's far off-base.   When I'm in front of a computer, I'll try to write up an accurate version.

**Comment by CrossEye** [comment]
The best I can come up with is the pretty awful:

    (x1 -> x2 -> ... -> xn -> z) -> (a -> b -> ... -> x1) -> (a -> b -> ... -> x2) -> 
        ... (a -> b -> ... -> xn) -> (a -> b -> ... -> z)

Anyone have something better?

**Comment by bergus** [comment]
Can we have that tuple back maybe? It made sense to me as the function is surely not curryed (or is it?)

    (x1->x2->…->xn -> z) -> ((a->b->… -> x1), (a->b->… -> x2), …, (a->b->… -> xn)) -> (a->b->… -> z)

I think we even can omit the `n` case for brevity

    (x1->x2->… -> z) -> ((a->b->… -> x1), (a->b->… -> x2), …) -> (a->b->… -> z)

**Comment by CrossEye** [comment]
There is a (mostly-irrelevant) currying to three places there.  But you're right; that tuple makes it clearer.  And you're also right that the `n` is not too important.  Very nice changes.

**Comment by lucasmreis** [comment]
Whenever I use `converge` I ident it this way:
```
converge(
  doSomething,
    transformA,
    transformB,
    transformC)
```
So, I can visualize better what happens when it's also idented:
```
(x1 -> x2 -> ... -> xn -> z) -> 
  (a -> b -> ... -> x1) -> 
  (a -> b -> ... -> x2) -> 
  ... 
  (a -> b -> ... -> xn) -> 
  (a -> b -> ... -> z)
```
Does it help?

**Comment by CrossEye** [comment]
That's a nice visualization, although I would outdent the response.  Unfortunately, it doesn't really fit inside our documentation.  Still, it's a very helpful way to explain the function.  Thanks.

**Comment by ccorcos** [comment]
Ahh. That make much more sense.

**Comment by CrossEye** [comment]
We need to do something similar to `useWith`.  It should be

    (x1->x2->… -> z) -> ((a->x1), (b->x2), …) -> (a->b->… -> z)

**Comment by ccorcos** [comment]
hmm. @CrossEye from the example, I think @lucasmreis is more correct, but then again, I'm not sure.

On a more educational note -- I think we should clarify the syntax here:

- `x -> y` is a function that takes x and returns y
- `x -> y -> z` is a curried function that takes x and y and returns z
- `(x -> y) -> z` is a function that takes a function and returns z

So I have a question for you. How do you represent a callback function with this syntax, or is that not possible? Maybe this: `x -> x()`? Or is that not *pure*?

**Comment by CrossEye** [comment]
@ccorcos: Note that my last comment was about a different, but somewhat similar function, `useWith`.  @lucasmreis simply found a nicer way to format the suggestion I first made, but its one that probabaly wouldn't fit well on our documentation page.

Your three points are accurate, although I would expand the third a bit:

- `(x -> y) -> z` is a function that takes a function (from x to y) and returns z

And this would be a very odd thing indeed, BTW.

But I think your question about callback functions is not well-defined.  What distinguishes a callback function from any other function passed to another one?

In one of these signatures, a function that is supplied as a parameter to another function or returned from one is surrounded with parentheses.  Single lower-case letters represent unknown, but static-across-the-signature types.  There is nothing to say that types represented by different letters have to be different, only that they _might_.  Square braces (`[` , `]`) represent lists of whatever types are included.  We have used several different things to represent objects, and need to settle on one standard.  We freely use obvious title-case names for known types, without worrying about a formal list (`String`, `Number`, `Boolean`, `Integer`, etc.)

Because we have several degrees of freedom on top of the more strongly typed languages where these signatures developed, we've had to add a bit of our own additional syntax.  We use ellipses (`…`) to represent repeated values not in lists, as parts of variadic signatures.  And where currying does not play a role, rather than separating the parameters by arrows (`->`), we use commas.  Both of those are part of the examples above.  As in the examples above, parentheses do a second job of grouping a comma-separated collection, to help promote readability.

**Comment by ccorcos** [comment]
I see. Thanks for the clarification.

My question about callbacks stems from the following: I'm creating a function to help me chain async animations together. For example:

```coffee
animation1 = (done) ->
animation2 = (done) ->
animation3 = (done) ->

# the old-fashioned way  
animation1 ->
  animation2 ->
    animation3 doneAnimating

# the new way
daisyChain(animation1, animation2, animation3, doneAnimating)
```

So what does the signature of `daisyChain` look like?

`a,b,c...y,z -> a(-> b(-> c( -> ... y(-> z()))))`

**Comment by CrossEye** [comment]
Remember that these signatures report only two things: what types of parameters a function accepts and what type it returns.  They absolutely do not explain anything about the process of how a function works.  Assuming these animation functions don't return or accept anything, this might be a reasonable description:

    daisyChain:: ((void -> void), (void -> void), ...) -> void

**Comment by ccorcos** [comment]
ah. I see. Thanks!

**Comment by bergus** [comment]
In fact those daisy-chained functions would take callbacks, so it rather would be

    daisyChain :: ( ((void->void)->void), ((void->void)->void), …) -> void

or even better with arguments:

    daisyChain :: ( (a->(b->void)->void), (b->(c->void)->void), …) -> (a -> (z->void) -> void)

which would be like `composeN` with arrows, specialised to the continuation arrow.

**Comment by ccorcos** [comment]
Hmm. The biggest difference between `daisyChain` and `composeN` is the order in which the functions are run. With compose, the right-most function is run first and the result returned as arguments to the next function. With `daisyChain`, the left-most function is fun first, then calls the second function when its done...

**Comment by bergus** [comment]
Oh right. I meant `pipe` of course :-)
