### ISSUE TITLE
wrap with a function

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1044]
I'm curious if theres some kind of function to do the following in Ramda:

suppose I have a function that takes one argument `f(x)`

What I wants `h = function() { return f(x) }`. Thats not very verbose though. I'm looking for something like `R.apply(f,x)` except its wrapped in a function...

**Comment by CrossEye** [comment]
If there are no side-effects to calling `f`, then you could just use

    var h = R.always(f(x));

But if you're looking for a technique that caters to side-effects, I can't think of anything built-in.  Since Ramda tries to enforce referential integrity, the idea that expressions should be replaceable by their values with no change in meaning, anything that works would likely be coincidental and not by design.

**Comment by davidchambers** [comment]
[`R.once`][1] may be applicable here.


[1]: http://ramdajs.com/docs/#once

**Comment by ccorcos** [comment]
`f(x)` is a login server call, so unfortunately it does have side-effects. I'll just wrap it in a function. I'm going overboard here haha.

**Comment by scott-christopher** [comment]
You could also just use a plain ol' `bind`:
```js
var h = f.bind(null, x);
```

**Comment by bergus** [comment]
Ramda can do this:

    R.compose(f, R.always(x))

**Comment by CrossEye** [comment]
> [`R.once`][1] may be applicable here.

Shhh, we try not to mention embarrassing members of the family.  :smile:

**Comment by CrossEye** [comment]
>     var h = R.compose(f, R.always(x))

Yes, of course.
