### ISSUE TITLE
Proposal: Add `fst` and `snd` functions to access a tuple pair

### ISSUE THREAD

**Issue by branneman** [ramda/ramda#1048]
I find myself using JS array with a length of 2 as if they were a tuple pair. For example, `R.zip` returns a list of pairs. But when working with pairs, `fst` and `snd` functions would be nice. The `fst` function can be emulated with `R.head`, but there's no `snd` function. There's also no way to emulate the `!!` operator from Haskell without writing your own function afaik?

I'd like to get rid of this kind of code:
```js
R.map(function(v) { return v[1]; }, data)
```

Example usecase:

```js
var combined = R.zip(list1, list2);
R.map(R.compose(R.toUpper, R.snd), combined);
```

I realize that if it were more complex than this, I would be better of using Lenses, but for usecases as simple as this, I think a new alias for the `head` function is easily created, and a `snd` function with the following definition is also easily created:
```js
var fst = R.head;
var snd = R.curry(function(pair) {
  return pair[1];
});
```

As a small optimisation with might choose to throw an error when the array that represents the pair has a length which is not 2.

Thoughts?

**Comment by buzzdecafe** [comment]
could be:

```javascript
var fst = R.nth(0);
var snd = R.nth(1);
// or this: R.map(function(v) { return v[1]; }, data) becomes simply:
R.map(R.nth(1), data)
```

**Comment by branneman** [comment]
Cool, thats quite simple. I didn't see the `R.nth` function yet, obviously ;)

I'd still love the addition of `fst` and `snd` functions tho, what do you think?

**Comment by buzzdecafe** [comment]
yeah, `nth` doesn't get the respect it deserves, it is very handy! 

> I'd still love the addition of fst and snd functions tho, what do you think?

`fst` may be a tough sell, since it essentially an alias for `head` and we have, at present, _no aliases_. and without `fst`, `snd` would be an oddball. Plus, it's easy enough to whip these up using `nth`. 

I'm curious where other stand, though.

**Comment by branneman** [comment]
Ok, makes sense.

How much thought has gone into working with pairs (as in Haskell pairs, 2-length tuples) in Ramda? Are there other specific functions that make this more easy? Are you working with pairs personally? And does it make sense in JS at all? Or might a specific Pair functor make more sense?

The selling argument could be that Ramda would then enable working with pairs, whereas now it doesn't.

> Plus, it's easy enough to whip these up using `nth`.

Well, if you want to do it the right way, I think `fst` and `snd` should throw an error when the given array doesn't have a length of 2, and thus isn't a valid pair. And that makes it a little less easy than just `var snd = R.nth(1);`

**Comment by buzzdecafe** [comment]
> Or might a specific Pair functor make more sense?

interesting for sure, but maybe more in the scope of ramda-fantasy or sanctuary. A generic `n`-tuple might be even better, but maybe tough to do with JS loose typing. By which I mean it would be tough/costly to enforce that a given tuple, e.g. `(String, Object, Number)` is always typed that way.

**Comment by CrossEye** [comment]
But you know, if we can make these efficient enough, we can reimpement everything in terms of pair-based lists, and [scare the heck][co] out of some folks.  :smiling_imp: 

-----

<sub>In case it wasn't clear, this is a joke!</sub>
  [co]: https://github.com/ramda/ramda/issues/1002#issuecomment-89425812

**Comment by DrBoolean** [comment]
Well, since you asked @branneman, I think it'd be cool to see this in ramda-fantasy as a staple type with implementations of all the usual interfaces.

The functor/monoid/apply instances differ from Array which is, in my opinion, the raison d'etre, but there are other good uses.

One can define a nice Bifunctor which does what you might expect.
```
var neat = compose(map(reverse), bimap(replace('o', '')), split("-"))
neat("hello-world")
//=> Tuple("hell", "dlrw")
```

There's the whole Reader/Writer Monad/Comonad symmetry: http://stackoverflow.com/questions/11245183/importance-of-isomorphic-functions/11247408#11247408

There's some interesting laws and properties to be exploited with tuples used as categorical products and in the pair calculus.

One cool thing I've seen is this:

```
 var _Tuple = function(x, y) {
    this[0] = x;
    this[1] = y;
    this.length = 2;
  }
```
Which keeps it working with `nth()` and `head()`

**Comment by buzzdecafe** [comment]
would love to see a PR on ramda-fantasy

**Comment by buzzdecafe** [comment]
I'm gonna close this here, but I would like to continue this conversation on ramda-fantasy.

And it would be nice to have `cons, car, cdr` for working with `Pair` too ....

**Comment by branneman** [comment]
Cool, agreed! Let's make a new issue at ramda-fantasy then, with a reference to this issue/discussion.

**Comment by buzzdecafe** [comment]
:+1:
