### ISSUE TITLE
pathOr ?

### ISSUE THREAD

**Issue by Cottin** [ramda/ramda#1054]
Since there is `propOr` would it make sense to include a `pathOr` function?

**Comment by davidchambers** [comment]
I agree that it makes sense. The problem is that since Ramda doesn't have an unambiguous way to represent a failed operation, we end up needing a `R.____Or` function for each function which may fail. We could end up with `R.propOr`, `R.pathOr`, `R.headOr`, `R.lastOr`, `R.findOr`, and several others.

[Sanctuary][1] was conceived as an alternative to a proliferation of such functions.


[1]: https://github.com/plaid/sanctuary

**Comment by CrossEye** [comment]
Nonetheless, we can make a judgment call about which functions we find worth supporting.  At the moment, we have `reduce` and `reduceRight`, and have `scan` but no `scanRight`.  Perhaps we should correct that, but ["a foolish consistency is the hobgoblin of little minds..."][rwe]


  [rwe]: http://en.wikipedia.org/wiki/Self-Reliance

**Comment by davidchambers** [comment]
`R.pathOr` seems useful to me. `R.headOr` and `R.lastOr` aren't as useful since the alternative, `xs.length > 0 ? ... : ...`, is manageable.

**Comment by CrossEye** [comment]
And I meant to say that.  I would welcome a PR for `pathOr`.

**Comment by davidchambers** [comment]
If anyone is interested in pursuing this, please submit a pull request. :)
