### ISSUE TITLE
Remove from list by value

### ISSUE THREAD

**Issue by ashaffer** [ramda/ramda#1087]
I apologize if this already exists and I am just not seeing it, but it'd be nice to have something equivalent to underscore's `without`, though non-destructive of course.  E.g.

```javascript
R.without('c', ['a', 'b', 'c']) // ['a', 'b']  
```

**Comment by ashaffer** [comment]
An equivalent of `splice` would also be nice.  I know you can achieve it with `insert` and `remove`, but the concision of Array.splice is pretty sweet.

**Comment by davidchambers** [comment]
You could use [`R.reject`][1]:

```javascript
> R.reject(R.eq('c'), ['a', 'b', 'c'])
['a', 'b']
```

If you want to reject multiple values you could use `R.reject` in conjunction with [`R.contains`][2].

```javascript
> R.reject(R.contains(R.__, ['c', 'd']), ['a', 'b', 'c', 'd', 'e', 'f'])
['a', 'b', 'e', 'f']
```


[1]: http://ramdajs.com/0.14/docs/#reject
[2]: http://ramdajs.com/0.14/docs/#contains

**Comment by CrossEye** [comment]
We rejected trying to duplicate `Array.prototype.splice` because its API is so hairy.

    var x = [1, 2, 3, 4, 5, 6];
    x.splice(3, 2, 10, 11); //=> [4, 5]
    x; //=> [1, 2, 3, 10, 11, 6]

`splice` is variadic, with several optional parameters.  It returns one thing (the removed list) but mutates another (the original list).  There just seemed no clean way to make anything remotely resembling it that fits with Ramda's philosophy.  But as you note, a combination of `remove` and `insertAll` will cover the functionality.

**Comment by YannisMarios** [comment]
Does reject work on an array of objects?

```
let array = [
  {
    a: 1
  },
  {
    b: 2
  },
  {
    c: 3
  }
];
```
let removed = remove(0, array);
console.log(removed) = undefined
