### ISSUE TITLE
R.call object prototype method

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1090]
I have a bunch of objects with prototype methods.

Right now I'm trying this, but there a problem that the method isnt bound.

```
R.compose(
  R.map(R.call),
  R.map(R.prop('methodName'))
)(objects)
```

What I need is something like this:

```
R.method = function(key, obj) {
   return obj[key].bind(obj)
}
```

Then I can do:

```
R.compose(
  R.map(R.call),
  R.map(R.method('methodName'))
)(objects)
```

Sound good?

**Comment by davidchambers** [comment]
Have you tried [`R.invoke`][1]?


[1]: http://ramdajs.com/docs/#invoke

**Comment by ccorcos** [comment]
Not sure I understand how invoke works here...

**Comment by davidchambers** [comment]
Could you provide example input and expected output?

**Comment by ccorcos** [comment]
```js
function Var(value) {
  this.value = value
}
Var.prototype.get = function() {
  return this.value
}

var list = [new Var(1), new Var(2), new Var(3)]

console.log(R.compose(R.map(R.call), R.map(R.method('get')))(list))
// => [1,2,3]
```

**Comment by davidchambers** [comment]
`R.map(R.invoke('get', []), list)` should do the trick. :)

**Comment by ccorcos** [comment]
ah. Now I get it. Thanks @davidchambers

**Comment by davidchambers** [comment]
No problem. I'm happy to be of assistance. `R.invoke` is pretty handy for working with OO APIs in a way that feels natural when using Ramda. :)

**Comment by ccorcos** [comment]
@davidchambers, invoke says it deprecated

http://ramdajs.com/docs/#invoke

**Comment by davidchambers** [comment]
We deprecated [`R.invoke`][1] because it performs the same role as [`R.invoker`][2] with a less flexible API. You should be able to replace `R.invoke('get', [])` with `R.invoker(0, 'get')`.


[1]: http://ramdajs.com/docs/#invoke
[2]: http://ramdajs.com/docs/#invoker

**Comment by iamandrewluca** [comment]
Would be great if `R.invoker` could take only method name as a parameter, and call it on first object  
like an alias or something
```js
// this two to be equal
R.invoker('get')
R.invoker(0, 'get')
```

**Comment by CrossEye** [comment]
@iamandrewluca:

I don't think that could work.  `invoker(n, name)` returns a curried function, whose length is `n + 1`.  You could easily write a function that doesn't do this:

```js
const invoke = (name) => (...args) =>
  last(args)[name].apply(last(args), init(args))

const sl = invoke('slice')

sl(2, 4, ['a', 'b', 'c', 'd', 'e', 'f']) //=> ['c', 'd']
sl(2, ['a', 'b', 'c', 'd', 'e', 'f']) //=> ['c', 'd', 'e', 'f']
```

But this would not be a typical Ramda output where you could call, e.g., `const myTail = sl(1)` to get a new function.  That would fail, because this function just assumes the last parameter is your method-containing object, and the rest are arguments to pass to that method.

I don't see an alternative that would work well.  `Array.prototype.slice` is a good example.  Its length is`1`, because the second parameter is optional.  So if we were to  use that value, there is no good way to call the second parameter. That might sometimes be acceptable, but we then have no way to override that and note that we do want the second parameter as well.  We could write `invoker`/`invokeN` similar to `curry`/`curryN`,  I suppose.  But we've actually [gone the other way][in] intentionally


  [in]: https://github.com/ramda/ramda/search?q=invokerN&type=Issues

**Comment by iamandrewluca** [comment]
@CrossEye ok, thanks! Come in mind with trying this example
```js
fetch('https://api.github.com/users/iamandrewluca/followers')
  .then(R.invoker('json'))
  .then(R.pluck('login'))
  .then(console.log)
```
vs
```js
fetch('https://api.github.com/users/iamandrewluca/followers')
  .then(R.invoker(0, 'json'))
  .then(R.pluck('login'))
  .then(console.log)
```

**Comment by CrossEye** [comment]
Or of course

```js
    .then(r => r.json())
```

**Comment by llaenowyd** [comment]
Say that, stuck at home from the covid, I had watched too much Leo DiCaprio's Inception, and arrived at a `dream` having a method `dream` that takes as its parameter a `dream`.  Now I can make some plans using a feedback loop on a simple topic, like Google's deep dream, for example `[ 'apples', 'Snow White', 'The Lion the Witch and the Wardrobe', 'Turkish Delight', 'Antalya Beach' ]`

This could be programmed in with `generateDream('apples').dream(generateDream('Snow White')).dream( ...` but that's too repetitive, every time I type `generateDream` I wish it were anonymous instead.  Can I use compose/chain/invoker somehow?  Thank you

**Comment by CrossEye** [comment]
> Say that, stuck at home from the covid, I had watched too much Leo DiCaprio's Inception, and arrived at a `dream` having a method `dream` that takes as its parameter a `dream`. 

You know, I find it extremely heartening when I find this library I've spent time on during the last seven years used for critically important work in such a variety of fields.  I'm glad you asked about this underappreciated scenario.  Who knows how many lives may actually be saved?

While I'm not particularly well-versed in the business case you present, I will tentatively suggest the following  implementation that might capture your needs:

```js
const dream = (topic) => ({dream: dream})

const inception = lift (reduce (useWith (flip (invoker(1, 'dream')), [identity, dream])) (pipe (head, dream), tail)
```

And of course we could then use it like this:

```js
const topics = [ 'apples', 'Snow White', 'The Lion the Witch and the Wardrobe', 
                 'Turkish Delight', 'Antalya Beach' ]

inception (topics)
```

I'm glad to hear about your noble pursuit of this -- shall we say? -- dream.  Keep us informed about how it turns out!
