### ISSUE TITLE
R.useWith doesn't work as expected if called with R.__ for the function argument

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1104]
See http://bit.ly/1Bdkpls vs. http://bit.ly/1K3MEZ5

**Comment by CrossEye** [comment]
I think the description of this is wrong.

The problem is not really with the use of `R.__`.  In fact, the [fixed version][fv] continues to use `R.__`.  

The problem is that this function is variadic.  If we wrote it to take one main function and a list of transformer functions, [like this][up], this problem would go away.

I think we should do this.  Any objections?  It's another API change, of course,  But it's in line with the other recent ones removing variadic signatures.

  [fv]: http://bit.ly/1K3MEZ5
  [up]: http://bit.ly/1F6mtxe

**Comment by buzzdecafe** [comment]
fine with changing to `useWith(fn, [fns])` in the near term, but longer term i'd like to find a way to combine some of the many `compose` functions we have.
