### ISSUE TITLE
Human readable type errors

### ISSUE THREAD

**Issue by raine** [ramda/ramda#1125]
Late last night I was coding and got a few TypeErrors here and there, for example from accidentally applying `toUpper` to a list.

```
node_modules/ramda/dist/ramda.js:5220
            return target[method].apply(target, args);
                                 ^
TypeError: Cannot read property 'apply' of undefined
```

So I wondered aloud on gitter room if it was in any way feasible for Ramda to provide a bit of hand holding in this respect and show a more friendly error message in case some thing like that happens.

Thoughts?

**Comment by davidchambers** [comment]
I am 100% in favour of Ramda functions checking the types of their arguments. Particularly when using `R.compose` or `R.pipe` it can be difficult to track down the location of a type mismatch.

**Comment by TGOlson** [comment]
Maybe contracts? That way even higher-order functions (like `compose`) can be contracted. [Rho-contracts](https://github.com/sefaira/rho-contracts.js) seems pretty legit, if not a little verbose, but hey, it's JavaScript.

**Comment by buzzdecafe** [comment]
this may be a good use case for metadata on the function. see @megawac 's initial work in https://github.com/ramda/ramda/pull/907

**Comment by buzzdecafe** [comment]
and this: https://github.com/sebinsua/ramda-debug

**Comment by paldepind** [comment]
Ok. What about an internal (maybe even exposed) function that does type checking.

Can be used like this:

```javascript
var nth = _curry2(typecheck([isNumber], _nth));
var add = _curry2(typecheck([isNumber, isNumber],_add));
var filter = _curry2(typecheck([isFunction, isArray], _dispatchable('filter', _xfilter, _filter)));
```

It takes an array of predicates and a function. It then decorates the function and validates passed arguments against the predicates. Validator functions should have a `name` property. Then really nice error messages could be thrown:

```javascript
filter(12, [1,2,3]); // Throws: TypeError: filter expected a function as it's first argument, received `12`
```

This would allow to very easily and concisely add type checking to functions. It would also keep the main functions free from `throw` statements which in most current JS engines harms the performance of the entire containing function.

**Comment by buzzdecafe** [comment]
i don't like the idea of folding this into the main build, but only for a debug build.

**Comment by CrossEye** [comment]
I'm not convinced that we want to do this.  This sort of thing scares me:

> ```js
> var filter = _curry2(typecheck([isFunction, isArray],
>                                _dispatchable('filter', _xfilter, _filter)));
> ```

This is clearly a mistake, but it's an easy one to make.  If this is dispatchable, we can't just check that the second parameter is an array.  And to me [this dispatch is important][co].  To do the type-checking right, we need to type-check that the second parameter either is list-like enough for us to use it as a list, or that we can dispatch `filter` to it.

And really, if we're checking types, `map :: (a -> b) -> [a] -> [b]`, is `[isFunction, isArray]` or even some expanded `[isFunction, isArray || dispatchesTo('filter')]` really enough?  Shouldn't our type-checker, if we're including one also be able to tell that

    var ss = ['a', 'b', 'c']; // :: [String]
    var fn = R.multiply(2); // :: (Number -> Number)
    map(fn, ss); //=> Error: incompatible types, String / Number

If not, how much are we really gaining?


  [co]: https://github.com/ramda/ramda/issues/729#issuecomment-70351882

**Comment by paldepind** [comment]
The only reason I see for not having this in the main build is performance. That is certainly a valid concern. But if we want Ramda to check the types of arguments passed in then using a central function will make doing a debug and a production build much easier.

@CrossEye 
That is a very good point! I have not though of that. But wouldn't it be solved simply by moving the type checking to after a dispatch? Like this:

```javascript
var filter = _curry2(_dispatchable('filter', _xfilter, typecheck([isFunction, isArray], _filter)));
```

> Shouldn't our type-checker, if we're including one, also be able to tell that

What I'm suggesting would catch such an error. Not in the `map` invocatoin but in the first invocation of `R.multiply`. An error like this would be thrown: "TypeError: multiply expected a function as it's second argument but received 'a'". And that should help a great deal.

It would help even more if you replace `multiply` with `add`:

```javascript
var ss = ['a', 'b', 'c']; // :: [String]
var fn = R.add(2); // :: (Number -> Number)
map(fn, ss); //=> No error thrown :(
```

This wouldn't throw an error today but would without a doubt result in errors or unwanted behavior further on. Catching it in the `add` would be way better.

**Comment by CrossEye** [comment]
I suppose I hadn't thought this through all the way.  But that scares me much more.  Taking a function like `add`, with a simple body like ` return a + b;` and wrapping it up in a way that turns it into something that first has to check withether each of its parameters is numeric seems very much counter to the spirit of JS.  If one really is focused on type-safety, why would she not simply use TypeScript, PureScript, or some other compile-to-js language?

**Comment by davidchambers** [comment]
It's "the spirit of JS" which scares me. The fact that a language is dynamically typed does not mean it should permit nonsensical operations (such as `'abc' + {}`). Python, for example, performs run-time checks:

```python
>>> 'abc' + {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot concatenate 'str' and 'dict' objects
>>> range(1, 2, 3, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: range expected at most 3 arguments, got 4
>>> range('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: range() integer end argument expected, got str.
```

I wish JavaScript handled programmer errors in this manner. Unfortunately it does not, but *libraries* can provide useful feedback when used incorrectly.

**Comment by paldepind** [comment]
> seems very much counter to the spirit of JS

I'm not sure what to think. JavaScript has `TypeError` built in and it is certainly not uncommon for libraries to check their parameters and throw errors.

`add` is bit special because it currently inherits the behavior of `+`. I don't think you'll find many programmers who are happy with `+` both meaning plus and concatenation and also doing type coercion. So in this case it's probably most programmers who are against the spirit of the language.

`add` aside, I'm curious if the wrapping seems just as unreasonable to you if considering something like `filter` instead, where the function clearly doesn't work if passed something other than a function and an array?

>  If one really is focused on type-safety, why would she not simply use TypeScript, PureScript, or some other compile-to-js language?

I don't know. On the other hand, what would Ramda loose by doing type checking? It is easy to see what the gain would be: human readable type errors.

**Comment by paldepind** [comment]
> seems very much counter to the spirit of JS

One could also say that Ramda already has a completely strongly typed API so it is already not embracing the dynamic aspects of JavaScript. The dispatch mechanism on the other hand embraces duck typing.

**Comment by CrossEye** [comment]
I've been trying to think this through, and I'm caught in a dilemma. I have long felt that this sort of error-checking didn't belong in Ramda, but I was always imagining a much more intrusive sort of type-checking than that in @paldepind's proposed API. This is clearly cleaner. And I could probably live with it.

But I'm still very hesitant for several reasons:

  - I think it's going to be difficult to do this properly. A simple example is for `map :: (a -> b) -> [a] -> [b]`. To do a good job of type-checking this function, we should verify that we meet that signature properly, or, ISTM, our type-checker is falling down on the job. But to test that, since there is nothing but run-time type information to go on, we need to check both that elements of the list passed to it all share some common type, and then still harder, check that the function passed actually accepts (some ancestor of) that type. I don't know how to do that. Just checking that it's a function really isn't enough.  And then if we do this, are we interested only in run-time type information, or is it declared information.  That is what is the difference in handling between

    * `map(area{shape -> Number}, [rect1, rect2, rect3])`
    * `map(area{rect -> Number}, [rect1, rect2, rect3])`
    * `map(area{shape -> Number}, [rect1, rect2, circle1])`
    * `map(area{rect -> Number}, [rect1, rect2, circle1])`

  - It's not clear enough to me if we should extend this capability to our users too.  Obviously if we're checking only Ramda's own functions but not the functions that Ramda calls, this has somewhat limited usefulness, but it sounds as if doing so would get complex.

  - I'm quite worried about the performance implications of this. Ramda, of course, is built out of a great number of functions, many calls to which are often on the stack together. This looks to add at least one more function call to the stack _for each parameter of every Ramda function call made_.  That worries me a lot.  


But I suppose I'd like to see this play out a bit.  If this isn't terribly difficult to write, perhaps we can try it, and do some significant benchmarking.  Maybe that will allay my fears.

**Comment by paldepind** [comment]
> To do a good job of type-checking this function, we should verify that we meet that signature properly, or, ISTM, our type-checker is falling down on the job.

What I'm suggesting is "shallow type checking" only. It looks to me like what you're considering would be much more obtrusive and even more against the spirit of JavaScript. It would mean that this 

```javascript
R.map(R.toString, [1, 'hello, 3']);
```

would throw an error of some kind? That means we would disallow otherwise proper meaningful JavaScript? Isn't that a much more radical proposal?

> I don't know how to do that

Me neither :) But I don't think it is necessary either. I think what I'm suggesting would go a long way in easing debugging, be quite sensible to implement and only make Ramda slightly less liberal in what types it accept than today. It should prevent things like using `R.add` to concatenate strings and throw helpful errors in cases that would have resulted in runtime errors anyway. But besides that it should allow the dynamic things that JavaScript programmers expect.

> I'm quite worried about the performance implications of this. Ramda, of course, is built out of a great number of functions, many calls to which are often on the stack together. This looks to add at least one more function call to the stack for each parameter of every Ramda function call made. That worries me a lot.

If this was included only in a debug build performance should not be a concern. Why for each parameter? As far as I can tell this would only lead to one extra function on the call stack for each function invocation.

IMO the biggest problem today with all the things Ramda adds to the call stack is that it makes debugging harder. Type checking would make debugging _easier_ due to potentially vastly decreasing the number of times a developer would receive odd errors somewhere inside Ramda.

But, you're above concern gave me a new idea! We could built the type checking into a debug-only version of curry! All functions are curried anyway so this would not lead to extra functions on the call stack. But more importantly it would give the advantage that the type checking could be performed even on partially applied functions. This would catch errors earlier and allow for even easier debugging. The previous example code I posted would only check for type errors on fully applied functions since the type checking came after the currying.

Something like this:

```javascript
var filter = checkAndCurry([isFunction, R.or(isArray, hasMethod('filter')], _dispatchable('filter', _xfilter, _filter)));
```

**Comment by buzzdecafe** [comment]
> IMO the biggest problem today with all the things Ramda adds to the call stack is that it makes debugging harder. 

Yes. How would y'all feel about relaxing the constraint on providing `function.length` *at least* internally?  I know @CrossEye will hate this. But wanted to throw it out there anyways

> We could built the type checking into a debug-only version of curry!

:+1:

Love this for debug, not thrilled with it in regular distribution.

**Comment by scott-christopher** [comment]
I would like to see something like an internal function that is similar in behaviour to `R.tap`, except that it is erased in the regular distribution build. That would be flexible enough to assert types or other invariants if desired.
Perhaps something like any of these:
```
_erase :: (() -> ())
_debugEnter :: (a* -> ()) -> (a* -> b)
_debugExit :: (a* -> b) -> (b -> ())
_debugThrough :: (a* -> ()) -> (a* -> b) -> (b -> ())
```
On a similar (but somewhat unrelated) topic, I'd also be interested to see whether there would be any benefit from an `_inline :: (a* -> b) -> (a* -> b)` that could wrap some of the internal functions, allowing the build tool to inline them at their call site for the distribution builds and remove some of the extra stack frames. No idea whether this would actually cause any real-world improvement or simply increase complexity of the build – just thinking out loud.

It is also worth remembering that there are some who `require` the individual Ramda functions directly rather than including the all-in-one `ramda.js`, as the notion of a distribution build doesn't exist there.

**Comment by davidchambers** [comment]
@paldepind, I absolutely :heart: the idea of eagerly checking types in the various :curry: functions. It would be wonderful if `R.map([1, 2, 3])` were to throw *immediately* rather than when the function is (eventually) fully applied.

---

For the record, I think having "production" and "debug" versions of __ramda.js__ is a bad idea.

**Comment by buzzdecafe** [comment]
strong :-1: against doing this all the time. if that's what you want, use purescript.

**Comment by CrossEye** [comment]
> What I'm suggesting is "shallow type checking" only. It looks to me like what you're considering would be much more obtrusive and even more against the spirit of JavaScript. It would mean that this 
> 
> ```javascript
> R.map(R.toString, [1, 'hello, 3']);
> ```
> 
> would throw an error of some kind? 

I don't see why.  That's just (for some arbitrary, but I hope clear annotation):

```js
R.map(R.toString{:: * -> String}, [ 1, 'hello, 3']{:: [*]}) :: [String]
```
> That means we would disallow otherwise proper meaningful JavaScript? Isn't that a much more radical proposal?

No, my feeling is simply that Ramda is about functions, and most often the important parameters you pass to Ramda functions are themselves functions.  The signatures of those functions are what's important about them.  If we're doing type-checking only that these are functions, then we're not really doing the important type-checking one would want.  Again, with `map`, if we are to add type-checking, and it can't report that this is nonsensical, then something is seriously wrong with it:

```js
    R.map(Math.cos, document.getElementsByTagName('div'))
```

> It should prevent things like using `R.add` to concatenate strings 

Is that a particularly compelling reason?  Developers use `+` to concatenate strings.  `R.add` was mostly created to create a pure function parallel to the language operator.


>> This looks to add at least one more function call to the stack for each parameter of every Ramda function call made. That worries me a lot.

> If this was included only in a debug build performance should not be a concern. Why for each parameter? As far as I can tell this would only lead to one extra function on the call stack for each function invocation.

Well, I haven't seen an implementation of this idea, I guess, but I was assuming that `typecheck([isFunction, isArray], ...) would involve a call to `typecheck` at function construction, and calls to `isFunction` and `isArray` (as well as some glue code and some sort of loop) on each invocation.  If you have another implementation in mind, I'm curious to hear it.

The note from @scott-christopher pointing out that we wouldn't have a clean way to get debug versions for the individual modules makes me less happy about creating a debug build.  I'm don't have a complete objection, but I'm significantly less happy about it.

**Comment by davidchambers** [comment]
#1413 provides an excellent example of a bug run-time type checking would have caught.

**Comment by davidchambers** [comment]
Here's a type error I just encountered which *happens* to do what the author intended:

```javascript
R.append('\n', 'foo')
```

**Comment by raine** [comment]
I made https://github.com/raine/ramda-t if anyone's interested.

**Comment by davidchambers** [comment]
#1491:

```javascript
> R.pluck([], 'foo')
[undefined, undefined, undefined]
```

**Comment by davidchambers** [comment]
[sanctuary-def][1] provides a solution to this problem. Someone could use it to create a strict-ramda package which specifies the type of each Ramda function. This would result in double currying, but it's an option worth considering if we decide not to add type checking to Ramda itself.


[1]: https://github.com/plaid/sanctuary-def

**Comment by davidchambers** [comment]
This isn't going to happen. [Sanctuary][1] is available to those who seek refuge from unsafe JavaScript. If you'd like a type-checked version of a particular Ramda function, please [open an issue][2].


[1]: https://github.com/plaid/sanctuary
[2]: https://github.com/plaid/sanctuary/issues/new
