### ISSUE TITLE
R.log

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1132]
I've found this to be nice convenience when debugging function compositions:

```js
function log(value) {
  console.log(value)
  return value
}

R.compose(doSomethingElse, log, doSomething)
```

**Comment by buzzdecafe** [comment]
see `tap`
http://ramdajs.com/docs/#tap

**Comment by CrossEye** [comment]
This is one of the few functions in Ramda designed to enable side-effects.  (`forEach`, what else?)  While it doesn't actually perform side-effects, it's essentially useless unless you're using it to create them.  But it's useful enough that we do include it.

**Comment by paldepind** [comment]
I think the main advantage of this function is that you won't have to worry about what `console.log` is bound to.

You can't do this:

```javascript
R.tap(console.log, 100);
```

But have to do this:

```javascript
R.tap(console.log.bind(console), 100);
```

To avoid all that typing when debugging a function like this is handy:

```javascript
var log = console.log.bind(console);
```

But something like this is even more useful:

```javascript
var log = R.curry(function(prefix, val) { console.log(prefix, val); });
```

It would be nice to have in Ramda but it obviously only useful for development.

**Comment by buzzdecafe** [comment]
> It would be nice to have in Ramda but it obviously only useful during development.

yep. and since you demonstrated how easy it is to whip up, i don't think it should be included in the main package.

**Comment by paldepind** [comment]
> yep. and since you demonstrated how easy it is to whip up, i don't think it should be included in the main package. 

There are a lot of functions in Ramda that are super easy to whip up. For instance all the functions that have `*With` counterparts. That's 8 functions right there that can all be implemented simply by partially applying another function in Ramda (it doesn't get any easier than that).

The above is not supposed to be snarky. I'm just wondering if one liners should generally not be included in Ramda? Because then there is some cleanup to do.

**Comment by buzzdecafe** [comment]
my $0.02: As a general rule, i would love to see a smaller API, and really focus on the core stuff. This means excluding easily composable functions unless there is a strong reason to include them.

**Comment by CrossEye** [comment]
Well, there's a simple reason not to include this one in Ramda: Ramda makes it a point to keep its functions pure.  Calling `console.log` is clearly not pure.

(And yes, I'm sidestepping the more difficult issue for the moment.)

**Comment by buzzdecafe** [comment]
well, we already mentioned `forEach` and `tap` ....

**Comment by ccorcos** [comment]
> yep. and since you demonstrated how easy it is to whip up, i don't think it should be included in the main package.

Yeah, I think almost every function in Ramda is easy to whip up individually. The question is whether its useful.

That said, `tap` is basically what I was looking for: `R.log = R.tap(console.log.bind(console))`

**Comment by CrossEye** [comment]
`forEach` and `tap` are certainly designed to help the user who wants to create side-effects.  But I would argue that this is still a far cry from having Ramda itself create side-effects.

(Still sashaying away...)

**Comment by raine** [comment]
[`treis`](https://github.com/raine/treis) may be of use.

**Comment by ccorcos** [comment]
cool!

**Comment by mattferrin** [comment]
I'm reticent to comment, but I do believe Ramda eventually needs to be broken into two separate things. One library (existing Ramda) to implement core building blocks. Another library that implements every function with a use case, but that conceivably tree shakes well. 

Ideally function names would group naturally into the most related functions when sorted alphabetically for sanity.

I only mention it here because it think closely related projects are healthy, like `ramda-fantasy`, and I happen to need a simple log function right now. 

If I do go ahead with this idea, I may start with just aliasing Ramda functions to group naturally by function name when sorted alphabetically. Is `ramda-more` a decent name... `ramda-plus` is slightly pompous.

**Comment by buzzdecafe** [comment]
`ramda-contrib` has been tossed around, but nobody has stepped up to own it. And [ramda-extra](https://www.npmjs.com/package/ramda-extra) is out there too

**Comment by mattferrin** [comment]
@buzzdecafe Thank you.
