### ISSUE TITLE
evolveWhere

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1133]
Here's a useful function I've been using a bunch when a changes is made to a collection:

```coffee
evolveWhere = R.curry (where, evolution, list) ->
  R.map(R.cond([
    [where, evolve(evolution)]
    [R.T, R.identity]
  ]), list)
```

You'd use it like this:

```coffee
data = [{id:1, name:'chet', score:10}, {id:2, name:'joe', score:50}]
# change the name where id:1
evolveWhere(R.propEq('id', 1), {name:'chet'}, data)
# increment the score where name:'joe'
evolveWhere(R.propEq('name', 'joe'), {score: R.add(10)}, data)
```

Do you think this is a worthy candidate?

**Comment by paldepind** [comment]
I've been thinking of something similar myself. But I think `evolveWhere` is two specific. It's also confusing since evolve is for objects and `evolveWhere` would be for arrays.

My suggestion is `updateWhere`. Kinda like this:

```javascript
function updateWhere(pred, fn, list) {
  return R.map(function(elm) { return pred(elm) === true ? fn(elm) : elm; });
}
```

I'm not sure about the name though since `R.update` doesn't take a modification function but a constant. But actually `R.update` would be move powerful if it took a modification function. Then the current behavior could be achieved with `R.always`.

**Comment by ccorcos** [comment]
I entirely agree :+1:

**Comment by buzzdecafe** [comment]
> But actually `R.update` would be move powerful if it took a modification function. 

:+1:

**Comment by paldepind** [comment]
Oops. That is `R.adjust`. Then the function I suggested above should be `R.adjustWhere`.

**Comment by ccorcos** [comment]
Seems to me like `R.update` and `R.adjust` should take a predicate function and an evolve function.

**Comment by davidchambers** [comment]
This problem could be solved using [lenses][1]:

```javascript
var data = [{id: 1, name: 'amy', score: 10},
            {id: 2, name: 'joe', score: 50}];

var transformIf = R.ifElse(_, _, R.identity);

var f = transformIf(R.propEq('id', 1),
                    R.set(R.lensProp('name'), 'chet'));
R.map(f, data);
// => [{id: 1, name: 'chet', score: 10}, {id: 2, name: 'joe', score: 50}]

var g = transformIf(R.propEq('name', 'joe'),
                    R.over(R.lensProp('score'), R.add(10)));
R.map(g, data);
// => [{id: 1, name: 'amy', score: 10}, {id: 2, name: 'joe', score: 60}]
```

`f` could use `R.assoc('name', 'chet')` rather than a lens, but it's nice to demonstrate that lenses support setting as well as transforming values.


[1]: https://github.com/ramda/ramda/pull/1205

**Comment by ccorcos** [comment]
Hmm. `R.over` isn't in the documentation yet, but it appears you're still developing the idea. This looks pretty interesting though. 

Can you make a compelling argument for lenses? Are there any more nuanced or principled reasons why you'd want to use them?

```
var g = transformIf(R.propEq('name', 'joe'),
                    R.over(R.lensProp('score'), R.add(10)));

var g = transformIf(R.propEq('name', 'joe'),
                    evolve({score: R.add(10}));
```

**Comment by davidchambers** [comment]
> `R.over` isn't in the documentation yet, but it appears you're still developing the idea.

The idea is very well developed in Haskell, and there are at least two dedicated JavaScript lens libraries: [DrBoolean/lenses][1] and [fantasyland/fantasy-lenses][2].

> Can you make a compelling argument for lenses?

I believe so.

```javascript
var alice = {
  name: 'Alice Jones',
  address: ['22 Walnut St', 'San Francisco', 'CA']
};
```

How might we want to interact with this object?

Get the value of a specific field:

```javascript
R.prop('name', alice);
```

Derive a new object with a new value for a specific field:

```javascript
R.assoc('name', 'Alice Smith', alice);
```

Derive a new object by applying a transformation to a specific field's value:

```javascript
var f = R.converge(R.assoc('name'),
                   R.pipe(R.prop('name'),
                          R.toUpper),
                   R.identity);
f(alice);
```

Note how natural getting and "setting" are, but how much work is required when a transformation is required. The problem is that when we use `R.prop` to access a field's value we lose context. We need something like `R.converge` so we can preserve our context in one branch, apply the transformation in the other branch, then combine the two branches.

Lenses exist to solve this problem. A lens provides a view of a subset of a data structure *in the context of the entire data structure*.

First, we define a lens:

```javascript
var nameLens = R.lensProp('name');
```

Getting:

```javascript
R.view(nameLens, alice);
```

Setting:

```javascript
R.set(nameLens, 'Alice Smith', alice);
```

Transforming:

```javascript
R.over(nameLens, R.toUpper, alice);
```

See how natural the transformation is using a lens? In fact, `R.set(nameLens, 'Alice Smith')` is just sugar for `R.over(nameLens, R.always('Alice Smith'))`. :)

Lenses are composable, which makes them well suited to working with nested data structures. Imagine we wanted to upper-case `address[0]` rather than the `name`.

Without lenses, we might write:

```javascript
var f = R.converge(R.assoc('address'),
                   R.pipe(R.prop('address'),
                          R.converge(R.prepend,
                                     R.pipe(R.head,
                                            R.toUpper),
                                     R.tail)),
                   R.identity);
```

This gets unwieldy. Every time we drill down we must use `R.converge` to preserve context, provide a getter (e.g. `R.head`), a function which returns the rest of the data structure (e.g. `R.tail`), and a function to combine the transformed value with the rest of the data structure (e.g. `R.prepend`).

Lenses are the abstraction we seek!

```javascript
var streetLens = R.compose(R.lensProp('address'), R.lensIndex(0));
R.over(streetLens, R.toUpper, alice);
```

Much better! We've expressed our intent clearly, and created a useful value in the process: `streetLens` can be used to view and set as well!


[1]: https://github.com/DrBoolean/lenses
[2]: https://github.com/fantasyland/fantasy-lenses

**Comment by megawac** [comment]
> The idea is very well developed in Haskell, and there are at least two dedicated JavaScript lens libraries: DrBoolean/lenses and fantasyland/fantasy-lenses.

The most popular one as far as I'm aware is https://github.com/5outh/nanoscope

**Comment by paldepind** [comment]
@davidchambers The problem can also be solved in a nicer ways _without_ using lenses. Not that using lenses is a bad solution – but for this case it is no better than what we had before with with `assoc`, `evolve`, etc.

**Comment by davidchambers** [comment]
> [F]or this case [lenses are] no better than what we had before with `assoc`, `evolve`, etc.

I argue that we *are* better off.

With lenses we define the path to the focus just once:

```javascript
var streetLens = R.compose(R.lensProp('address'), R.lensIndex(0));

var getStreet = R.view(streetLens);
var setStreet = R.set(streetLens);
var updateStreet = R.over(streetLens);
```

Without lenses we specify the path to the focus twice, in different ways:

```javascript
var getStreet = R.pipe(R.prop('address'), R.head);
var updateStreet = R.curry(function(f, o) {
  return R.evolve({address: [f]}, o);  // pretend this works
});
var setStreet = R.curry(function(v, o) {
  return updateStreet(R.always(v), o);
});
```

Lenses are equally good in cases where only one of {`view`, `set`, `over`} is required. But we may start only using `over` for a particular focus and later realize we need to `view` that focus as well. We can! It would be like `R.evolve({address: [_]})` giving us `R.pipe(R.prop('address'), R.head)` as well. :)

The other advantage is that these path specifiers can be shared. For example:

```javascript
var abc = R.compose(R.lensProp('a'), R.lensProp('b'), R.lensProp('c'));
var abc0 = R.compose(abc, R.lensIndex(0));
var abc1 = R.compose(abc, R.lensIndex(1));
```

`R.evolve` is a good idea. Lenses are an even better idea. :)

**Comment by ccorcos** [comment]
@davidchambers thanks for the explanation, that was excellent!

I'm all on board with lenses now, and yes, evolve is still a good idea.

> The most popular one as far as I'm aware is https://github.com/5outh/nanoscope

One of the biggest things I like about Ramda is point-free programming, and functional composition. I'm not a fan of all this chaining business anymore.

> The idea is very well developed in Haskell, and there are at least two dedicated JavaScript lens libraries: DrBoolean/lenses and fantasyland/fantasy-lenses.

I've become more an more interested in functional programming in the past several months. I'm starting to get the feeling that I ought to learn Haskell... Would you agree? It just seems like kind of a waste of time as a web developer, although I'm sure it will help me be a better programmer in the end...

**Comment by davidchambers** [comment]
> I'm starting to get the feeling that I ought to learn Haskell... Would you agree?

I've only scratched the surface of Haskell myself, but I highly recommend devoting some time to learning the language. It'll change the way you think about programming in general, and you'll be able to bring that knowledge to your JavaScript practice. One place to start is with [Erik Meijer's lecture series][1], which I very much enjoyed.


[1]: https://channel9.msdn.com/Series/C9-Lectures-Erik-Meijer-Functional-Programming-Fundamentals/Lecture-Series-Erik-Meijer-Functional-Programming-Fundamentals-Chapter-1

**Comment by buzzdecafe** [comment]
_https://speakerdeck.com/garann/code-is-a-job?slide=31

**Comment by ericgj** [comment]
@buzzdecafe  :+1: :+1:

**Comment by ccorcos** [comment]
@davidchambers can you use lenses for filtering collections?

`filter(pipe(scoreLens, gt(10)))`

**Comment by scott-christopher** [comment]
With the new lens API, that should just be:
```js
filter(over(scoreLens, gt(10)));
```

**Comment by ccorcos** [comment]
I see. that makes sense. And to increment all scores, would we use set or over?

 `map(set(scoreLens, add(1)))`

**Comment by davidchambers** [comment]
Filter would look something like this:

```javascript
var scoreAboveTen = R.pipe(R.view(scoreLens), R.gt(R.__, 10));

R.filter(scoreAboveTen, data);
```

Incrementing would look something like this:

```javascript
R.map(R.over(scoreLens, R.inc), data);
```

**Comment by davidchambers** [comment]
@ccorcos and @paldepind, where do you two currently stand on this?

**Comment by paldepind** [comment]
I still think this would be a very useful function.

I'd like to point out that even though this discussion ended up being about lenses, lenses do not have much to do with the suggested function.

**Comment by raine** [comment]
So, the new function would be something like:

```js
var R = require('ramda');

var data = [{
  id: 1,
  name: 'chet',
  score: 10
}, {
  id: 2,
  name: 'joe',
  score: 50
}];

// (a -> Boolean) -> (a -> b) -> [a]
function adjustWhere(pred, fn, list) {
  return R.map(function(elm) {
    return pred(elm) === true ? fn(elm) : elm;
  }, list);
}

var nameLens = R.lensProp('name');

adjustWhere(R.propEq('id', 1), R.evolve({ score: R.inc }), data);
// [ { id: 1, name: 'chet', score: 11 },
//   { id: 2, name: 'joe', score: 50 } ]

adjustWhere(R.propEq('id', 2), R.over(nameLens, R.always('Alice Smith')), data);
// [ { id: 1, name: 'chet', score: 10 },
//   { id: 2, name: 'Alice Smith', score: 50 } ]
```

**Comment by davidchambers** [comment]
Thanks for the summary, @raine.

  - `adjustWhere` needs to take a function of type `a -> a` since the result is of type `[a]`.

  - We now have `R.when(pred, fn)` as sugar for `R.ifElse(pred, fn, R.identity)`.

  - `R.over(nameLens, R.always('Alice Smith'))` is better written `R.set(nameLens, 'Alice Smith')`.

  - `R.over(nameLens, R.always('Alice Smith'))` could also be written `R.assoc('name', 'Alice Smith')`.

  - `R.evolve({ score: R.inc })` could also be written `R.over(scoreLens, R.inc)`.

`adjustWhere` seems useful. The question is whether

```javascript
R.adjustWhere(pred, fn, list)
```

is significantly more expressive than

```javascript
R.map(R.when(pred, fn), list)
```

In my view, it isn't.

**Comment by paldepind** [comment]
@davidchambers That is a great point. I agree. I don't think `when` was around when this function was suggested.

**Comment by davidchambers** [comment]
> I don't think `when` was around when this function was suggested.

You're correct: `R.when` was added two months later in #1315.

It's nice to see the more general sugar of `R.when` removing the demand for the more specific sugar proposed in this issue. I hope `R.when` is to your liking, @ccorcos. :)
