### ISSUE TITLE
Question: A question about the implementation of _curry1

### ISSUE THREAD

**Issue by benjycui** [ramda/ramda#1145]
I am reading the source code of Ramda, and I am curious with the following code:
```js
var _curry1 = function _curry1(fn) {
  return function f1(a) {
    if (arguments.length === 0) {
      return f1;
    } else if (a === __) {
      return f1;
    } else {
      return fn(a);
    }   
  };
};
```
Why not:
```js
var _curry1 = function _curry1(fn) {
  return function f1(a) {
    if (arguments.length === 0 || a === __) { // I mean this.
      return f1;
    } else {
      return fn(a);
    }   
  };
};
```

**Comment by davidchambers** [comment]
Your version would work equally well. There's no particular reason to favour one or the other. I imagine the current form was chosen because `_curry2` and `_curry3` have many branches, and in those cases it's clearer not to combine the various branches in which the function's return value is the function itself.

**Comment by benjycui** [comment]
THX!
