### ISSUE TITLE
off-by-one error in R.invoker

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1148]
`R.invoker(n, methodName)` returns a function with length _n_ + 1. This seems odd to me: I expect the function to have length _n_.

**Comment by CrossEye** [comment]
It's an interesting point.  If you turn a _method_ of arity `n` into a _function_ of arity `n + 1`, which value is the better expected value for the parameter?  The real point, of course, is to deal with possible optional arguments.

    var index = R.invoker(2, 'indexOf');  // include the `fromIndex`
    index('a', 5, 'a22: some value'); //=> 'a22: some value'.indexOf('a', 5) = 11

I don't see a strong reason to change this.  Do you think it would be significantly improved if the parameter reported the output function length rather than the length of the method you're trying to invoke?

**Comment by davidchambers** [comment]
> Do you think it would be significantly improved if the parameter reported the output function length rather than the length of the method you're trying to invoke?

No. I now see that `n` relates to the method in question rather than the function we're creating. This seems reasonable.
