### ISSUE TITLE
compare

### ISSUE THREAD

**Issue by TGOlson** [ramda/ramda#1151]
Any thoughts on a `compare` function?

```
compare :: (a -> Number) -> a -> a -> Number
```

```js
var compare = R.curry(function(f, x, y) {
  return f(x) - f(y);
});
```

Basically, shorthand for converting `(a -> Number)` functions into comparators. I've found it helpful for things like this:

```js
var compareLength = compare(R.length);

R.sort(compareLength, ['hey', 'hi', 'hello', 'cya']);
// => ["hi", "hey", "cya", "hello"]
```

It could also be accompanied by a `sortByComparing` function.

```js
var sortByComparing = R.curry(function(f, xs) {
  return R.sort(compare(f), xs);
});

R.sortByComparing(R.length, ['hey', 'hi', 'hello', 'cya']);
// => ["hi", "hey", "cya", "hello"]
```

**Comment by CrossEye** [comment]
`R.sortBy` does this in a more generic fashion:

```js
R.sortBy(R.length, ['hey', 'hi', 'hello', 'cya']);
// => ["hi", "hey", "cya", "hello"]
```

The function passed to it could generate String or numeric keys; either would work fine, as would Dates.  Basically, anything that you could compare with `a < b` would work.

**Comment by TGOlson** [comment]
:+1: 

Awesome, I guess I would confused by the `(a -> String)` part of the type signature in `sortBy` - should have given it a poke first though. Thanks for the reply.

**Comment by CrossEye** [comment]
Most of our type signatures were created in a heroic effort by @buzzdecafe.  He did this over the course of only a day or two.  He got a surprisingly high percentage of them right, but we really need to look through them more carefully and decide where some polishing is due.

This one is slightly more odd.  I'm pretty sure that function was mine (else it's very similar to one I'd written earlier.)  And I honestly expected it to be used with Strings.  I never really thought about Numbers (or Dates) until this issue was raised.  So it was documented for how we expected the function to be used.  I think this one should be redocumented, because the implementation is clearly right: as long as the keys your function generates are sortable by `<`, it should just work.  Often things like this that fall out of the implementation are intentionally not documented, since we want to feel free to change the implementation, but this feels more like a case of learning from the implementation.
