### ISSUE TITLE
R.init works on strings, R.tail doesn't

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1199]
This is very surprising.

http://bit.ly/1BpkpEk

**Comment by davidchambers** [comment]
`R.tail` should be equivalent to `R.drop(1)`, so this is a bug as far as I'm concerned.

**Comment by CrossEye** [comment]
So @davidchambers are you suggesting that `drop` be changed so that `drop(1, 'foo');`//=> ['o', 'o']` or that `tail` be changed so that `tail('foo'); //=> 'oo'`?

I agree that it seems logical that they be equivalent.  But I really don't like special-casing what should be list code to also deal with Strings, and I'm not sure we should be changing core functions like `tail` to match some implementation fall-out of a different function.  Neither of these is documented to work on Strings.  Should we spend much time worrying how they work if users pass Strings?

**Comment by davidchambers** [comment]
I'm suggesting that the default implementation of `tail` should be `drop(1)`.

I find it helpful when writing—and particularly when refactoring code—to think in terms of equivalences. Functional programming increases our ability to do so (by avoiding side effects). I like knowing that two expressions are equivalent. I'm then free to use whichever expression better conveys my intent, or whichever is preferred by the maintainers of a given project.

`R.tail` and `R.drop(1)` could form such an equivalence. Unfortunately as its stands they are equivalent when applied to values of one type but *not* equivalent when applied to values of another type. I can imagine leaving comments on pull requests along the lines of _`R.drop(1)` is better written as `R.tail`_ only to have the pull request's author respond to say that she made the change but that tests failed as a result. She or I would then spend a few minutes in the REPL determining the actual behaviour of these functions, would discover the discrepancy, and possibly then raise the issue here.

One option is to provide String-specific versions of the various slice functions:

```haskell
strTail :: String -> String
strInit :: String -> String
strTake :: Number -> String -> String
strDrop :: Number -> String -> String
strTakeLast :: Number -> String -> String
strDropLast :: Number -> String -> String
```

All these functions can be derived from `slice` for both Array and String. I'd far prefer to do this than to have the String-specific functions above.

**Comment by CrossEye** [comment]
> I'm suggesting that the default implementation of `tail` should be `drop(1)`.

While I could easily live with that solution, there are two issues to consider:

  - This solution depends on our public `slice`, and the fact that it dispatches to to `String.prototype.slice` for any of this to work.  There is [a serious discussion][sf] about removing all dispatching except for FantasyLand compatibility.  Both @paldepind and @buzzdecafe have expressed support for this idea.  I disagree, but have lost plenty of similar battles in the past.  If we go down that route, this becomes a more significant maintenance effort.  Obviously we can still implement `tail` in terms of `drop(1)`, but getting `drop` to work properly on Strings and lists will be trickier.

  - We need to be careful about binding ourselves too closely to arrays.  That's all we have, to be sure.  But thinking of our lists as vector-like collections strikes me as the wrong way to go.  I would much rather think of them more like streams.  The best analogies is lists, in the LISP/Scheme or ML/Haskell style of the empty list or a pair consisting of a head and another list for a tail.  So `tail` seems a fundamental construct, and it really feels more natural to define `drop` in terms of it.  I know we probably can't do so in the absence of efficient recursion, but I always want us to be suspicious of such inversions.



  [sf]: https://github.com/ramda/ramda/pull/1173

**Comment by buzzdecafe** [comment]
> So `tail` seems a fundamental construct, and it really feels more natural to define `drop` in terms of it.

100% agree with that
