### ISSUE TITLE
R.uniq and R.union are broken at 0.15.0 in IE11 - Set size validation

### ISSUE THREAD

**Issue by celdrake** [ramda/ramda#1201]
In IE11 (11.096) the Set implementation is incorrect for Set.add.
It does not have a return, so checking the size on the return is broken.

I could not find the source code for the change, but at version 0.15.0 at ramda.js:

Would change line 7399 : 
                     
                    // Original
                    if (set.size !== set.add(item).size) {
                        uniqs.push(item);
                    }

                    // BugFix
                    var oldSize = set.size;
                    set.add(item);
                    if (oldSize !== set.size) {
                        uniqs.push(item);
                    }

I updated my project to use R.uniqWith and R.unionWith instead of the now broken functions, but would prefer the fix to be included.

**Comment by buzzdecafe** [comment]
LGTM. Did you want to do a PR?

**Comment by scott-christopher** [comment]
The `Set` implementation of `uniq` has already been rolled back (#1189) due to incompatibility with comparing arrays:
```
R.uniq([[1], [1]]); // [[1], [1]]
R.contains([1], [[1]]); // true
```

**Comment by celdrake** [comment]
I was confused because on master branch I could still see the bug in the "dist/ramda.js" file. I understand that's because it is not updated until a new version is created.

Will wait until next version to revert my code (move back to R.uniq instead of R.uniqWith, etc), and close the issue.

Thanks.
Celia.

**Comment by CrossEye** [comment]
> I was confused because on master branch I could still see the bug in the "dist/ramda.js" file. I understand that's because it is not updated until a new version is created.

We really need to do something about that.

So many things to do.

**Comment by davidchambers** [comment]
> We really need to do something about that.

I continue to disagree with you on this. :stuck_out_tongue_winking_eye:

__dist/ramda.js__ should reflect the most recently published version. __dist__, after all, is presumably an abbreviation for _distribution_.

**Comment by buzzdecafe** [comment]
i'm with @davidchambers again, especially now that it is no longer an impediment to testing.

**Comment by paldepind** [comment]
I agree. I expect a file that that to represent the latest release. Most recent sources can be found elsewhere in the repository.

**Comment by CrossEye** [comment]
When I clone a repository, I assume that the code I'm getting is the code for the given commit, usually HEAD.  When I get a combination of the code from HEAD, plus an artifact built from some earlier tag, what I've gotten is a jumble.

I know the user can rebuild it, if she has `make` and `npm` installed on her machine.  But if she doesn't she is stuck with a built artifact that does not match the source she downloaded.

While I would still rather figure out how to build and check this in from Travis on every successful build, since I haven't done anything about that, I would prefer to remove it from our distribution altogether.  I know it has to go in NPM; that's our main channel.  But I really don't like the mismatch.

An alternative I could live with, since we don't have that many tags, would be:

```
    dist:
        HEAD
            ramda.js
            ramda.min.js
        0.15.1
            ramda.js
            ramda.min.js
        0.15.0
            ramda.js
            ramda.min.js
        0.14.0
            ramda.js
            ramda.min.js
       // ...
``` 

But that would still involve having Travis check something back in.  I suppose at that point, though, I could live without the HEAD directory, though.
