### ISSUE TITLE
R.evolve turns arrays into objects

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1207]
Look here: http://bit.ly/1GqXFQu

Now I know this is also a known characteristic of R.assoc, which was addressed by the addition of update and adjust, but personally I find both quirks very surprising.

**Comment by paldepind** [comment]
Handling arrays closer to what one would expect in the concrete example could be done. But I'm a bit wary about using `evolve` to recurse into arrays. I think doing something like this would be much better:

```javascript
var o = { a: [{ f: 0, g: 3 }] };
R.evolve({ a: R.adjust(R.always(1), 1) }, o)
```

**Comment by CrossEye** [comment]
Please, if it's not too long, include the source code with the issue.  It makes for an easier discussion. 

This was the example:

> ```js
> var o = { a: [{ f: 0, g: 3 }] };
> R.evolve({ a: [{ f: R.always(1) }] }, o)
> //=> {"a": {"0": {"f": 1, "g": 3}}}
> ```

I agree that this is not something to be loved.  But I agree with @paldepind (how's that for a change?!) that recursing into arrays may not be a great idea.

I just don't see any great alternative to @paldepind's not-so-pretty solution.

**Comment by asaf-romano** [comment]
For the record, to get the same effect as in my example using @paldepind's approach, you need to call evolve within adjust as well as on the outside, like this:
```
var o = { a: [{ f: 0, g: 3 }] };
R.evolve({ a: R.adjust(R.evolve({ f: 1 }), 0) }, o);
```
I agree that generally speaking, evolving arrays isn't a great idea, but consider 1-element arrays or even manipulating the output of toPairs. Here's something I've to do quite often:
```
var a = [[new Date(), 1], [new Date(), 1]];
R.map(([date, data]) => [date.toISOString(), data], a);
```
Getting the same effect with adjust:
```
var a = [[new Date(), 1], [new Date(), 5]];
R.map(R.adjust(R.invoker(0, "toISOString"), 0), a);
```
If evolved worked:
```
R.map(R.evolve([R.invoker(0, "toISOString")]), a);
```
Note that evolve already recurses into arrays, in the sense that apart the object class (in ecmascript terms), everything works as expected:
```
[{"0": "2015-06-21T04:04:27.963Z", "1": 1}, {"0": "2015-06-21T04:04:27.963Z", "1": 5}]
```

**Comment by CrossEye** [comment]
Good points all.  I'd welcome a PR on this.  I think there would be some serious discussion on this, as we've found that diving into arrays is not a pleasant experience.  But this clearly shows that the existing function has significant room for improvement.

**Comment by paldepind** [comment]
I think the examples given here are a bit deceiving. If you only want to modify from the beginning of an array then yes, this looks desirable. But as soon as that is no longer true then you have to fall back on another approach anyway.

What if instead of this:

```javascript
R.map(R.evolve([R.invoker(0, "toISOString"), R.inc]), a);
```

We only wanted to increment the last value of the array _and_ the array had four items instead of two. Then the solution would grow into this:

```javascript
R.map(R.evolve([R.identity, R.identity, R.identity, R.inc]), a);
```

Which looks quite horribly. Which to me shows that using `evolve` on arrays was an inadequate solution to begin with.

I think what we might want instead is a function like this that is more general and can handle more than just a small subset of the problem:

```js
R.map(R.adjustMany({0: R.invoker(0, "toISOString"), 3: R.inc}), a);
```

Here `adjustMany` is a mix between `adjust` and `evolve`. This has the advantage that both functions are kept simple and small in scope (`evolve` is only for object and `adjustMany` is only for lists). Compared to the proposed solution this one is more powerful and IMO is more explicit and thus easier to understand.

**Comment by davidchambers** [comment]
All of these examples can be expressed in terms of [lenses][1]:

```javascript
var o = {a: [{f: 0, g: 3}]};

R.set(R.compose(R.lensProp('a'), R.lensIndex(0), R.lensProp('f')), 1, o);
// => {a: [{f: 1, g: 3}]}
```

```javascript
var a = [[new Date(), 1], [new Date(), 5]];

R.map(R.over(R.lensIndex(0), R.invoker(0, 'toISOString')), a);
// => [['2015-06-21T16:10:31.385Z', 1], ['2015-06-21T16:10:31.385Z', 5]]
```

```javascript
var update = R.compose(R.over(R.lensIndex(0), R.invoker(0, 'toISOString')),
                       R.over(R.lensIndex(1), R.inc));

R.map(update, a);
// => [['2015-06-21T16:10:31.385Z', 2], ['2015-06-21T16:10:31.385Z', 6]]
```

> I think what we might want instead is a function like this that is more general and can handle more than just a small subset of the problem

It seems lenses already satisfy these needs, and have the advantage of being composable.


[1]: https://github.com/ramda/ramda/pull/1205

**Comment by CrossEye** [comment]
I'm not sure lenses can easily take the place of the general idea of `evolve`, especially for the simpler cases it handles.  But it does seem a good fit for this examples.  @asaf-romano: I'm assuming these were simplifications?  Would the new suggested formulation of `lenses` fit your real-world scenarios too?

**Comment by asaf-romano** [comment]
Honestly I'm not too familiar with lenses, esp. not with the upcoming API changes for them*, but at a glance this does seem to address my general use case. However:
  (1) for simple stuff like address pairs, I do find the evolve syntax much more straight forward, esp. when the operation isn't reusable and should rather be inlined.
  (2) Regardless of whether or not it's a good practice to use assoc, assocPath or evolve this way, the current behavior is very surprising, to the point that I'd rather prefer an exception thrown. Since the returned object still behaves like an array to some extent, it's easy to pass over the broken array deeper in your application, not realizing what you did until someone tries to iterate it.

_____
* On a side note, the reason I didn't want to get into them so far was their current awkward syntax. The new stuff looks promising.

**Comment by CrossEye** [comment]
I have one more concern with uses `lenses` in place of `evolve` here:

This show the shape of the relevant input data with `^^` representing the structure and `--` representing the values:

```js
var o = { a: [{ f: 0, g: 3 }] };
//      ^^^  ^^ ^ ---
```

Here's how the (unfortunately broken) code looks as it tries to create an updated object, altering that part of the structure:

```js
R.evolve({ a: [{ f: R.always(1) }] }, o)
//       ^^^  ^^ ^  -----------
```

Here's how it looks with lenses:

```js
R.set(R.compose(R.lensProp('a'), R.lensIndex(0), R.lensProp('f')), 1, o);
//                    ^^^^^^^^^        ^^^^^^^^        ^^^^^^^^^  ---
```

This doesn't show that there's something wrong with `lenses`, but the isomorphism between the input structure and the change shows there's something really right with `evolve`.

**Comment by davidchambers** [comment]
Lenses provide a general purpose, composable solution to many problems. It's not surprising that a specialized function such as `R.evolve` provides a more convenient API in contexts where it's applicable.

One could, though, write a helper function to create lens compositions. One could then write:

```javascript
R.set(lensFromPath('a[0].f'), 1, o);
```

Lenses provide a sound foundation for many transformations. I'd rather provide a handful of supporting functions than a handful of one-off functions which provide similar or identical functionality to one of the new lens functions (`R.view`, `R.set`, and `R.over`).

**Comment by CrossEye** [comment]
I'm still not totally sold on the `lenses` API.  I'm still mulling it over.  Part of it is that reading the Haskell Lens stuff is awful.  There are so many variants of so many functions.  And abstractions that have so many properties simply scare me.  I absolutely understand how strange our current lens implementation is in the context of our other functions.  It hasn't bothered me that much because I also haven't found that much need for lenses.

Obviously, you're the one finding that need at he moment, and I'm likely to defer to you.  But I really want to understand this better first.  I've been off reading Haskell Lens and Prism tutorials, which make my brain bleed.  I don't feel I've gotten the basics completely down yet.  And I'm especially concerned with how well all this translates to JS, where nested property access is not, in fact, a challenge.

Part of the problem is that Ramda has really not tried before to introduce types to our users.  We simply operate on a few built-in types such as Lists (via arrays), Objects, Strings, and Numbers.  For anything else, we simply dispatch to user implementations.  So introducing not only a new type but a complicated one at that is a scary prospect.

I do agree that we should build general-purpose, composable solutions.  But we have to make sure that our building blocks are solid, and that those who will use them really can understand how to put them together.

**Comment by davidchambers** [comment]
The nature of the value returned by `R.lens` is not important to a user of the API. It would be fine to say the return type is `Thing`, and that `R.view :: Thing -> Object -> *`.

**Comment by CrossEye** [comment]
> The nature of the value returned by `R.lens` is not important to a user of the API. It would be fine to say the return type is `Thing`, and that `R.view :: Thing -> Object -> *`.

Not to me.  I don't want magic in our codebase.  I don't want to say that to use `R.over` or `R.view`, you need to pass it the output of `R.lens` or one of the helper functions.  That's why I'm hesitating.  Although the simplification proposed by @scott-christopher would make it more palatable, it's (a) still complex and (b) a bit of a lie, as the true types are substantially more complex still.

I really believe each Ramda function should stand on its own.  If `view` and `over` and `get` mean nothing without `lens`, then we are fundamentally changing the nature of Ramda.

**Comment by scott-christopher** [comment]
>  If view and over and get mean nothing without lens, then we are fundamentally changing the nature of Ramda.

To be fair, the same could be argued about transducers with `transduce` and friends.

Personally, I really look forward to the new lens API, as it greatly simplifies (in my mind) interacting and updating deeply nested structures – the updating part being a major part of what lenses offer over plain old Object property accessors for immutable objects, not to mention the possibility for other non-linear paths.

Having said that, I do wonder whether they would have more freedom to grow in their own `ramda-lens`-like repo.

And just for giggles, `evolve` could be implemented using lenses:

```js
var evolve = R.curry(function (updates, obj) {
  function _evolve(_updates) {
    if (R.is(Function, _updates)) return _updates;

    if (R.isArrayLike(_updates)) {
      return R.reduce(R.pipe, R.identity, R.zipWith(function (k, v) {
        return R.over(R.lensIndex(k), _evolve(v));
      }, R.range(0, _updates.length), R.values(_updates)));
    }

    if (R.is(Object, _updates)) {
      return R.reduce(R.pipe, R.identity, R.zipWith(function (k, v) {
        return R.over(R.lensProp(k), _evolve(v));
      }, R.keys(_updates), R.values(_updates)));
    }

    return R.always(_updates);
  }
  return _evolve(updates)(obj);
});

var o = { a: [{ f: 0, g: 3 }] };
var a = [[new Date(), 1], [new Date(), 5]];

evolve({ a: [{ f: 1 }] }, o);
// { a: [ { f: 1, g: 3 } ] }

R.map(evolve([R.invoker(0, 'toISOString')]), a);
// [ [ '2015-06-22T03:17:59.965Z', 1 ],
//   [ '2015-06-22T03:17:59.965Z', 5 ] ]

R.map(evolve([R.invoker(0, 'toISOString'), R.inc]), a);
// [ [ '2015-06-22T03:17:59.965Z', 2 ],
//   [ '2015-06-22T03:17:59.965Z', 6 ] ]
```

**Comment by davidchambers** [comment]
> Having said that, I do wonder whether they would have more freedom to grow in their own `ramda-lens`-like repo.

This is certainly an option, though our efforts might be better spent contributing to an existing lens library.

To me Ramda feels a bit like Python in that it comes with "batteries included". I like this. I see the appeal of single-purpose packages and have written several myself, but use of any given Ramda function would drop significantly were it moved to a separate package. Ramda has a fairly large audience, but I imagine a spin-off lens library would not. It would be a shame to move the lens functions to a separate package if the result is fewer JavaScript programmers discovering lenses.

**Comment by kedashoe** [comment]
> It would be a shame to move the lens functions to a separate package if the result is fewer JavaScript programmers discovering lenses.

I like the sentiment, but I don't know if I would be too worried about that, once you start learning functional programming, you're going to run into lenses sooner or later.

I like the idea of a lens library (not surprising I'm sure, having argued for separating out dispatching).

There could even be a ramda-batteries-included library that ties ramda, dispatching, lenses, etc (sanctuary? not sure if that makes sense of if you like the separate S namespace). If I'm just getting started with functional programming (which I am!) and I `import R from 'ramda';` and then I really start to understand all this stuff (which I don't yet!), I could then simply `import R from 'ramda-batteries';` and all my code still works (unless of course I have a `Cartographer` who likes to `map`, but that can be documented) and now I can use lenses etc.

I'm planning to start using Sanctuary soon and it doesn't bother me at all that it is not part of ramda. For one thing, I've browsed your docs and I really love them, and I don't think there would be such a nice place to read about that stuff if it were all part of ramda. I can see the same thing happening with lenses. Along these lines, there's been quite a bit of time now spent discussing dispatching (and now lenses) but a lot of the talk is focused on grafting and comparison to other ramda functions and the like.. instead of how to actually make awesome dispatching and lenses.

**Comment by davidchambers** [comment]
Perhaps my concern is unwarranted. Having a family of compatible packages could work well. We'd need to restructure the Ramda website to be more like this:

![Ramda and related packages](https://s-media-cache-ak0.pinimg.com/originals/62/97/5e/62975eb103bb5be1b1eaa2adc94fe927.jpg)

_Ramda at the centre with related packages orbiting it. `ramda-lenses` could be one such electron._

**Comment by paldepind** [comment]
> Having said that, I do wonder whether they would have more freedom to grow in their own ramda-lens-like repo.

In their current latest form I think having lenses in Ramda is just fine. But if there is a desire for them to grow further then a separate repository might be adequate. I also think @CrossEye's reasonings [here](https://github.com/ramda/ramda/issues/1207#issuecomment-113979442) are great arguments for a separate repository.

**Comment by buzzdecafe** [comment]
_https://speakerdeck.com/garann/code-is-a-job?slide=31

**Comment by buzzdecafe** [comment]
i say keep 'em in. @CrossEye 's point about functions that only consume lenses is a good one, though.

**Comment by davidchambers** [comment]
This discussion went off on an interesting tangent. What's your position on the original issue, @paldepind?

**Comment by paldepind** [comment]
I think `R.evolve` and `R.adjust` or lenses are nice solutions to the problem.

I think an `R.evolve` that handled both arrays and objects would be neat. But I also think it would be too implicit and hard to tell what was going on. I like how the other solutions makes it explicit what kind of structure one is working with.

**Comment by GingerPlusPlus** [comment]
```js
const evolveArray = R.zipWith(R.call)
```

**Comment by zhtbcgtw** [comment]
@GingerPlusPlus, it is very good, but for my case i was needed something more complicated, so i wrote this:

`
// Takes list if arrays and returns array that consists of equally-positioned pairs
// Note: The returned list is truncated to the length of the longest of the input arrays
// Examples:
// zipLongest([1,2], [10,20,30]) -> [[1,10],[2,20],[undefined,30]]
const zipLongest = R.pipe(
  R.unapply(R.identity),
  R.juxt([
    R.curryN(1)(R.flip(R.pluck)),
    R.pipe(R.map(R.length), R.apply(Math.max), R.range(0))
  ]),
  R.apply(R.map)
);

// Takes default value and predicate function and returns function that returns default value
// when predicate function returns true
// Examples:
// defaultToWhen(R.identity, R.complement(R.is(Function)))(null) -> R.identity
// defaultToWhen(R.identity, R.complement(R.is(Function)))(R.inc) -> R.inc
const defaultToWhen = R.curry((defaultValue, predicate) =>
  R.when(predicate, R.always(defaultValue))
);

// Takes array of functions and array of values and returns array where corresponding
// functions were applied to corresponding values
// Examples:
// evolveArray([,R.inc,,R.always(50)], [1,1,1]) -> [1,2,1,undefined,50]
const evolveArray = R.curryN(2)(
  R.pipe(
    zipLongest,
    R.map(
      R.pipe(
        R.adjust(defaultToWhen(R.identity, R.complement(R.is(Function))), 0),
        R.apply(R.call)
      )
    )
  )
);
`

This is very handy with this function:

`
// Takes mapper function and function and returns new function that pass its arguments
// to mapper and call the second one with transformed arguments
// Examples:
// mapArgs(evolveArray([,R.inc]), (a, b) => `${a}_${b}`)(1, 1) -> '1_2'
const mapArgs = R.curry((mapper, fn) => R.pipe(R.unapply(mapper), R.apply(fn)));
`

**Comment by GingerPlusPlus** [comment]
@zhtbcgtw off topic, but `mapArgs` with `evolveArray` sounds like [`R.useWith`](http://ramdajs.com/docs/#useWith).

**Comment by zhtbcgtw** [comment]
@GingerPlusPlus, sorry for offtop. Yes, it sounds very close in this case. Except R.useWith is curried to transformers length, so this example will not work:
```javascript
R.useWith((a, b, c) => `${a}_${b}_${c}`, [R.identity, R.inc, R.defaultTo(42)])(1, 1) // -> function (t){return n.apply(this,arguments)}
```

mapArgs generally don't limits you with the way you want to transform args (you can change order, or sum them, or convert to object). Using evolveArray here is one of the ways, but in some cases R.useWith is very similar.
