### ISSUE TITLE
Getting started with transducers in Ramda

### ISSUE THREAD

**Issue by Chris-Andrews** [ramda/ramda#1269]
I'm trying to get started learning Ramda, and one thing I find very interesting is Ramda's support for transducers. Unfortunately, I'm having a bit of trouble figuring out when Ramda functions are returning normal functions, when they return normal functions, when they expect transducers, when they don't, etc. I read the article from issue #950, and that was a nice explanation about transducers, but between that and the docs I'm still a little stuck.

As explained in the article, some functions (but not all) can act as transducers if executed in the right context. Reading through the docs, it looks like all the functions that fall in this category seem to be annotated "Acts as a transducer if a transformer is given in list position." So that is informative, but I have a couple questions related to the use and composition of these functions:

1) Using ```R.map``` as an example which can act as a transducer, I believe that ```R.map(x => x+1)``` will return a function that can take a list and perform my map operation. However, is the return of ```R.map``` also a transducer, such that if I pass it to another library expecting a transducer, it will be recognized as such?

2) As the article above (and several other resources that explain transducers) points out, transducers and normal functions have different behaviors regarding their order of execution when composed. So, when I use ```R.compose``` with functions, my understanding is they execute right-to-left, however, transducers execute left-to-right. So, if I compose ```R.compose(R.map(x => x+1), R.filter(x => x%2===0))```, have I composed functions or transducers? If I call ```R.compose``` on a mixture of transducers and functions, what is the behavior?

Many thanks if anyone can point me in the right direction.

**Comment by kedashoe** [comment]
Hi @Chris-Andrews! First of all, great questions! There is quite a lot going on with Ramda's implementation of transducers, but I'll do my best to shed some light.

Let's start with this

> Unfortunately, I'm having a bit of trouble figuring out when Ramda functions are returning normal functions, when they return normal functions, when they expect transducers, when they don't, etc.

For each function that has your quote, "Acts as a transducer if a transformer is given in list position.", you'll notice the function definition is being wrapped by `_dispatchable`, eg https://github.com/ramda/ramda/blob/master/src/map.js#L33. Very briefly:

[Case 1](https://github.com/ramda/ramda/blob/master/src/internal/_dispatchable.js#L29) checks if the last argument defines the function being called and defers to it, which allows ramda to work nicely with other libraries. We won't be dealing with this case here.

[Case 2](https://github.com/ramda/ramda/blob/master/src/internal/_dispatchable.js#L32) checks if we have a transformer (we'll see this again, unsurprisingly).

[Case 3](https://github.com/ramda/ramda/blob/master/src/internal/_dispatchable.js#L37) calls the function as you would normally expect it to be called.

So if you write `R.map(x => x+1)`, what you have is dispatch waiting for its final argument so it can figure out what to do.

> However, is the return of R.map also a transducer, such that if I pass it to another library expecting a transducer, it will be recognized as such?

Yes! Let's use https://github.com/cognitect-labs/transducers-js and write a simple script:

    var t = require('transducers-js');
    var R = require('R');

    var listxf = {
        '@@transducer/step': function(acc, x) { return acc.concat([x]); },
        '@@transducer/init': function() { return []; },
        '@@transducer/result': function(x) { return x; }
    };
    var inc = function(n) { return n + 1; };
    var incMap = R.map(inc);
    console.log(incMap([2, 3])); //=> [3, 4] (no tranducing)
    console.log(t.transduce(incMap, listxf, [], [2, 3])); //=> [3, 4] (using 3rd party lib)

In the 2nd to last line, dispatch will simply see an array and fall through to Case 3 above.

In our last line, when we use `t.transduce`, `incMap` is called here: https://github.com/cognitect-labs/transducers-js/blob/master/src/com/cognitect/transducers.js#L1010. `incMap` of course is wrapped in dispatch, which will see our `listxf` transformer (the `fn` argument to `transduce`), hit Case 2, [and call xf](https://github.com/ramda/ramda/blob/master/src/internal/_dispatchable.js#L33), in this example `_xmap`.

> So, if I compose R.compose(R.map(x => x+1), R.filter(x => x%2===0)), have I composed functions or transducers?

`R.compose` doesn't actually know anything about transducers, so at this point you basically just have dispatch waiting to see what it will do (since the two functions you composed are both wrapped in dispatch).

> If I call R.compose on a mixture of transducers and functions, what is the behavior?

It depends how you call it :) If you call it with `into` or `transduce`, it will blow up on your non-transducer function. If you simply pass in an array to you composition, it'll run just like normal.

Hope that helps!

**Comment by Chris-Andrews** [comment]
Thanks @kedashoe for the awesome explanation! That was extremely helpful, and that's a very cool API for working with functions and transducers. This basically answers all the questions I had about how the transducer functionality of this library works.

This issue could be closed from that perspective, but adding an example/description like you described above to the documentation somewhere could be helpful to other people who may have similar questions about how to use Ramda transducers. Although, the only places that it would seem to fit right now would be under the transduce function documentation (though it really goes beyond the scope of that function), or as an additional link under the Introductions section of the home page.

**Comment by CrossEye** [comment]
What we really need is a tutorial section in the documentation, or perhaps in the GitHub wiki, something that explains in more depth than source code examples or unit tests, _how do I do xyz_, but is perhaps not meaty enough to be it's own blog post somewhere.  The answer from @kedashoe is a great example of something that should be promoted to such a page.

**Comment by Chris-Andrews** [comment]
@CrossEye I think something along the lines of a tutorial section in the documentation or wiki would be great. Actually, I think even some things that *are* meaty enough to be their own blog post are nice to have in the wiki as well. Specifically, I think it could be useful to have one introduction to Ramda written in the wiki. A nice advantage of having this in the wiki is that it could be updated in response to user feedback about the content, and could be updated if there are ever any breaking changes to the API.

For things like @kedashoe's explanation about transducers, these could go in a wiki section called __Using Ramda__ that can cover things like transducers, where a bit more explanation is helpful.

In addition to the transducers explanation, I think it could be nice to add a brief introduction to lenses (they look interesting, but are probably unfamiliar to a lot of people, me included). I'll happily help with any documentation you'd like to add if you want to go that direction.

**Comment by CrossEye** [comment]
See the discussion in @1282.
