### ISSUE TITLE
Rename isSet

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1278]
isSet naming is too confusing, imo. My first guess would be that it is either ```has``` or ```is(Set)```.

**Comment by buzzdecafe** [comment]
`allUniq`

**Comment by CrossEye** [comment]
:+1:

**Comment by davidchambers** [comment]
Renaming the function `R.allUniq` would be a huge improvement. The other option is to deprecate the function, since its functionality can (less efficiently) be achieved via `R.uniq(xs).length === xs.length`. I'm fine with keeping this function even though I've never used it, as it is [well specified][1].


[1]: https://github.com/ramda/ramda/pull/1264#issuecomment-120645134

**Comment by asaf-romano** [comment]
I like it too,
