### ISSUE TITLE
Revert change of propEq

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda#1279]
I consider the changing of argument order in `propEq` to be a mistake. And it feels like an outcome of a misunderstanding of a [comment](https://github.com/ramda/ramda/pull/1243#issuecomment-119541173) I made. 

I noticed that there were some functions beginning with "prop" that took the prop name first and others that didn't. I didn't say this was a bad thing. I just wanted to highlight that it could be both and in the case of #1243 I thought it should be changed.

I do *not* feel that `propEq` should have the argument order changed. We use that function heavily and we sometimes only apply the first or just the first two arguments but we have *never* done `propEq(R.__, someValue)`. Now we would have to `propEq(R.__, 'someProp')` all over our code.

I vote to revert that change.

I also have some issues with how this was done, regardless of whether the change itself was good or not:
  * This change was merged in a PR unrelated to `propEq`
  * The change was not discussed
  * The PR was merged by the author

IMHO this is bad practice and I don't know if ramda has any guidelines for how to handle PRs but each of the items goes against what I find to be the purpose of PRs.

**Comment by davidchambers** [comment]
> This change was merged in a PR unrelated to `propEq`

I disagree. The pull request defined a sister function, `propIs`. Introducing a sister function without considering how it relates to its siblings can lead to API inconsistencies. The pull request also defined a parent function, `propSatisfies`. Since `propEq` and `propIs` are specializations of `propSatisfies`, they should take their common arguments in the same positions as their parent function.

> The change was not discussed

It was not discussed explicitly. I was operating under the assumption that this family of functions should take their common arguments in the same positions. This assumption may or may not have been correct. After you pointed out the inconsistency, @scott-christopher suggested property name second (for `propIs`). @CrossEye agreed. I assumed this meant `propEq` (and `propSatisfies`) should be updated to match. I did so, updated the pull request description to mention the breaking change to `propEq`, and left a comment so that anyone interested could provide further feedback. Two days later, after no further activity, I merged the pull request.

The question is whether my interpretation of the discussion was based on a false assumption. Did others assume that we were discussing the order in which `propEq` should take its arguments by extension?

> The PR was merged by the author

We have no formal policy. For a trivial change such as a typo fix the author is free to merge immediately. For non-trivial changes we want at least one member of the Ramda team to give a "LGTM" (or emoji equivalent). For major changes we like to reach consensus. Once a pull request has been reviewed and approved, it's not important which one of us actually merges it.

---

As for the issue in question, what's your position, @TheLudd, on whether `propSatisfies`, `propIs`, and `propEq` should take the property name in the same position?

**Comment by TheLudd** [comment]
I think `propEq` should be reverted and everything else should stay the way it is. 

By far, the most common use of `propEq` in our app is to compare the `_id` prop of an entity. This works on multiple types of data since almost all our entities has such a property. We have thus defined `var hasId = propEq('_id')`. Consider the next argument to this function, the id value. This is unique across all entities in our system. It can really never be partially applied in a way that makes it reusable. 

The cases where you could partially apply the value argument is when it is a part of an enum set or when it is a boolean. We do this sometimes in our code but in all those cases we also supply the prop as well. An example could be: `var isSingle = propEq('relationshipStatus', 'single')`. All uses of `propEq` that I have says that this is the correct order of arguments. If any one has a different experience I am interested to hear about it. 

Then we have `propOr`. This takes default value first, then prop name. That order makes sense for this function. Because the number of possible default values seems pretty small in comparison to prop names. The default values are probably one of these: `''`, `[]`, `{}` or `0` while the prop name could really be anything. And thus you can create
```
var propOrEmptyList = propOr([]);
var tagsOrEmpty = propOrEmptyList('tags');
var friendsOrEmpty = propOrEmptyList('friends');

var propOrZero = propOr(0);
var ageOrZero = propOrZero('age');
var loginsOrZero = propOrZero('logins');
```

For `propIs` and `propSatisfies` the case is more similar to `propOr` than to `propEq` as argumented [here](https://github.com/ramda/ramda/pull/1243#issuecomment-119551230). Perhaps it is not 100% consistent but it will make much more sense for each individual function.

**Comment by CrossEye** [comment]
>> This change was merged in a PR unrelated to `propEq`

> I disagree. The pull request defined a sister function, `propIs`. Introducing a sister function without considering how it relates to its siblings can lead to API inconsistencies. 

While that's true, it seems also a little circular.  It's a sister function for a few reasons:

  1. because it deals with properties of an object
  2. because it has a similar name
  3. because it has a related signature

The first is too generic to be useful.  The second one is too trivial to be meaningful.  And the third one, in this argument, is circular.


>> The pull request also defined a parent function, `propSatisfies`. Since `propEq` and `propIs` are specializations of `propSatisfies`, they should take their common arguments in the same positions as their parent function.

That cart will have a difficult time pulling your horse.

Only once we've determined the API we want should the implementation be a concern.  The fact that we can implement `propEq` simply in terms of `propSatisfies` doesn't matter at all if this doesn't supply the API we would like the function to have.

Although, as I said before, I didn't have any strong reason for the original parameter order when I picked it, I believe that @TheLudd is right that I did choose correctly for this function.  My feeling is that the placeholder is unloveable, and to say that the function can be used with it misses the point that if we have to use the placeholder more often than we have to curry the function then we've gotten things wrong.  And I'm pretty sure that be inverting these two parameters, we've just caused this.

:+1 for reverting this.

**Comment by davidchambers** [comment]
First, I absolutely agree that `String -> a -> Object -> Boolean` is the most useful type for `R.propEq`.

> Only once we've determined the API we want should the implementation be a concern.

My argument focused solely on the API. I should have been clearer. As a user of an API, internal consistency helps me to see relationships between functions and remember their types.

> ```
> R.propSatisfies :: (a -> Boolean) -> String -> Object -> Boolean
> ```

_So this function takes an arbitrary predicate and tells me whether the specified property of the given object satisfies that predicate._

> ```
> R.propIs :: Type -> String -> Object -> Boolean
> ```

_Ah, this function is convenient shorthand for a common use of `R.propSatisfies`: determining whether the value of a given object property is of a particular type._

> ```
> R.propEq :: a -> String -> Object -> Boolean
> ```

_Another `R.propSatisfies` shorthand; similar to `R.propIs`. This predicate is more exacting: it returns true only if the given object property has a specific value._

I see the first argument to `R.propIs` as shorthand for partial application of `R.is`. The same is true for `R.propEq` and `R.equals`.

If we revert the change to `propEq`, I'd like to revert #1243 in its entirety. I'd prefer not to have three closely related functions whose types don't quite match. (Others seem happy to consider each function's type in isolation, so perhaps my family-oriented view is unusual.)

**Comment by TheLudd** [comment]
@davidchambers 

> As a user of an API, internal consistency helps me to see relationships between functions and remember their types.

That is true but I remember the order of the `propEq` function to come quite naturally. That feeling trumps memorized consistency for me. 

> Others seem happy to consider each function's type in isolation, so perhaps my family-oriented view is unusual

Keeping consistency is nice. But I think it is an impossible mission to keep these kind of consistencies across the entire lib. Functions will naturally require different orders. E.g. compare `adjust` taking index as a second parameter and `update` as the first. Both those functions make sense the way they are.

**Comment by TheLudd** [comment]
I thought of consistency a bit more and realized that maybe consistency is not "prop is always last argument before the object" but perhaps there is an argument hierarchy that is consistent through all functions. If so, it would look something like this:
 
  1 callback function or default value
  2 prop name or index
  3 comparison or update value
  4 data

Meaning that if there is a function where the argument contains a callback and a prop name, the callback will always be before the prop name. Prop name will always be before update value etc. This to me would form a much more natural and meaningful consistency.

I have only done a quick check but I do believe that all current functions hold up to this as it is.

**Comment by buzzdecafe** [comment]
i haven't had a dog in this fight, but this convinced me to get on "team revert":

> First, I absolutely agree that `String -> a -> Object -> Boolean` is the most useful type for `R.propEq`.

we should favor utility over some notion of consistency. so put me down as :+1: for revert, since pretty much *everybody agrees* the original API is better.

**Comment by CrossEye** [comment]
> I thought of consistency a bit more and realized that maybe consistency is not "prop is always last argument before the object" but perhaps there is an argument hierarchy that is consistent through all functions.

I've always simply thought of it as ordered from least likely to most likely change between invocations.  Thus for `map`, we're much more likely to want to map the same function to different lists than to map a number of functions against a fixed list.  So `(fn, list)` makes clear sense.

It's only been on rare occasions that this ordering has not been fairly obvious from the start.  This, though, was one of those cases.  I _thought_ that `(name, value, obj)` made more sense for `propEq` than `(value, name, obj)` but I felt that there was at least some case to be made for flipping the first two.  I've seen several cases that supported the choice I made and none that contradicted it, so I think it was a good decision.  But it was not a clear call at first.

I wouldn't mind settling on some such hierarchy if it really supports the notion of ordering by increasing volatility, but that's the underlying principle to my mind.  It's what makes currying generally useful.
