### ISSUE TITLE
reduceObj

### ISSUE THREAD

**Issue by gyzerok** [ramda/ramda#1327]
How can I achieve something like reduce for objects in ramda?

**Comment by paldepind** [comment]
This question seems ambiguous to me. How would you like to reduce objects? Reduce an array of objects? Reduce the keys of an object? The values? You can use `R.toPairs` or `R.values` and use `R.reduce` on the result?

**Comment by gyzerok** [comment]
AFAIK array is an object with decimal keys. I'm talking about reducing object in the same way that arrays. Check https://lodash.com/docs#reduce.

**Comment by svozza** [comment]
There's an example of getting the same functionality with `useWith` here:

https://github.com/ramda/ramda/issues/1067

**Comment by paldepind** [comment]
> AFAIK array is an object with decimal keys.

True. But that is more like an implementation detail in JavaScript. Reduce as a concept works on lists where a list is an ordered collection of values.

But something like this
```js
_.reduce({ 'a': 1, 'b': 2 }, function(result, n, key) {
  result[key] = n * 3;
  return result;
}, {});
```

Could be done like
```js
R.reduce((acc, [val, key]) => R.assoc(val, key, acc), {}, R.toPairs({'a': 1, 'b': 2}), 
```

And that is, IMO, as much saner way to do it.

Note that the above example from the Lodash documentation is actually a really poor example of `_.reduce`. We could achieve the same thing with Ramda like this:

```js
R.mapObj(R.multiply(3), {'a': 1, 'b': 2})
```

**Comment by gyzerok** [comment]
@paldepind, @svozza Ok, thank you for an implementation example. It feels like I'm not the only person who is challenged with this. Mb you can provide docs for such cases?

**Comment by svozza** [comment]
Could go in the [cookbook](https://github.com/ramda/ramda/wiki/Cookbook) I guess.

**Comment by anton-rudeshko** [comment]
Second ago I came here to post exact same issue, so strongly voting up!
Proposed solution is great... but in ES5 looks way much uglier.

**Comment by anton-rudeshko** [comment]
BTW, what do you thing about implementing [`_.transform`](https://lodash.com/docs#transform)?

**Comment by megawac** [comment]
`_.transform` isn't a good canidate for ramda. It was discussed in  <insert issue here>

**Comment by anton-rudeshko** [comment]
The only difference between them is that `return` is automatic in transform.

**Comment by megawac** [comment]
It also detects and choses the return type implicitly

**Comment by buzzdecafe** [comment]
https://github.com/ramda/ramda/issues/1067

**Comment by buzzdecafe** [comment]
> `_.transform` isn't a good candidate for ramda. It was discussed in ...

https://github.com/ramda/ramda/issues/546

**Comment by anton-rudeshko** [comment]
:sob:

**Comment by jdalton** [comment]
I think this reply is relevant https://github.com/ramda/ramda/pull/1335#issuecomment-132694682.

**Comment by kedashoe** [comment]
As an alternative/temporary solution, we could provide an easy way for the user to reduce objects with something like

```js
var iterSymbol = (typeof Symbol !== 'undefined') ? Symbol.iterator : '@@iterator';

R.valIterator = function valIterator(x) {
    var iterWrapper = {};
    iterWrapper[iterSymbol] = function() {
        var keys = R.keys(x);
        var idx = -1;
        var key;
        return {
            next: function() {
                idx++;
                if (idx == keys.length) {
                    return { done: true };
                }
                else {
                    return { value: x[keys[idx]], done: false };
                }
            }
        };
    };
    return iterWrapper;
}
var obj = { a: 1, b: 2, c: 3};
R.reduce(R.add, 0, R.valIterator(obj)); //=> 6
```
http://bit.ly/1J8XU78
(similar to [this idea](https://github.com/ramda/ramda/issues/452#issuecomment-60602467), except with iterators)

It is also very easy from there provide `R.valKeyIterator` to also give the user the key in their callback. (Aside, [the generator version](http://bit.ly/1J8ZJBa) of these are very nice as you don't need to create the intermediate `keys` collection (and the impl is dead simple)).

For what it's worth, I like the idea of providing support for reducing objects without needing something like this. I think of `reduce` as a way to change the shape of something (have a list of numbers, want a sum; have an object, want a list; have a list, want a smaller list; etc), and only occasionally as something where order matters. Also there is already support for [reducing a list `R.into` an object](https://github.com/ramda/ramda/blob/master/src/internal/_stepCat.js#L20), but not currently the other way around.

**Comment by CrossEye** [comment]
@kedashoe:

That doesn't address my fundamental objection to iterating objects, which is that it's a generally senseless thing to be doing, and even though the language defines a fixed iteration order, it's not one that is defensible from an FP perspective.

```js
  R.reduce((a, b) => b - a, 0, R.valIterator({a: 1, b: 2, c: 3})), //=> 2
  R.reduce((a, b) => b - a, 0, R.valIterator({b: 2, a: 1, c: 3})), //=> 4
```

I will write more details about this soon, but all the recent discussions have made me want to revive discussions about fixing a key order for things that escape from Ramda internals.

**Comment by kedashoe** [comment]
True, it does not, and I don't think it should. Probably it is good the engines seem to be heading towards a defined order, but does anyone here plan on relying on that? In other words, I think plain javascript objects are a tool to be used as unordered key-value pairs. Imposing a law that
```js
R.reduce((a, b) => b - a, 0, R.valIterator({a: 1, b: 2, c: 3})), //=> 2
R.reduce((a, b) => b - a, 0, R.valIterator({b: 2, a: 1, c: 3})), //=> 4
```
must be equal simply adds unexpected overhead to a data structure that I would never expect to have such a property; it doesn't bother me at all that the result is inconsistent, because the operation itself is not consistent with the data structure. And because engines are moving towards insertion order, as a user I would expect the results to be different and actually be quite surprised that they are equal (although, again, I can't see ever actually doing this operation on an object).

Certainly there are times where my data was best modelled as an object and then at some later point in my program I want that data to be ordered in some way, and in this case it seems fine to me to explicitly write `compose(sort, toPairs)`. Here I think we see again the problem with enforcing ordered keys: if I want an order other than by key, `R.toPairs` will first needlessly sort all my values by the key and then I'll sort them a second time how I want.

**Comment by paldepind** [comment]
The reality of JS is this:

1/ JS objects are multi-purpose. JS developers use them both for OOP-objects, records/structs and _maps_.
2/ When they use objects as maps the content in the map will sometimes be monoids.
3/ When the type in a JS developers set-as-obj is a monoid `R.reduceObj` makes a lot of sense and is very useful.

It seems to me like a functional JavaScript library for JavaScript developers should realize that.

> That doesn't address my fundamental objection to iterating objects, which is that it's a generally senseless thing to be doing, and even though the language defines a fixed iteration order, it's not one that is defensible from an FP perspective.

Do you know what is a generally senseless thing indefensible from an FP perspective? That a number can be used to represent the truth value of a statement. Or in general: the concepts of truthy and falsey.

I have no idea why in one case a PR that improves simplicity, our FP semantics and our expressiveness without removing _any_ practicality is being shot down when in another case an idea of great practical benefit is being shot down because it has potential danger (what happened to the "then don't do that"-mantra?).

Based on these two cases it seems to me like the goal is to keep bad stuff from JS with the argument "that is how JS does it" and to remove the practical stuff with the argument "that is not how FP does it".

In one case it doesn't matter that we're not respecting FP semantics even though theres is no reason not to. In another case FP semantics are suddenly way more important that practical value. In one cases are users are very clever and we can say "then don't do that" and in another case they are too stupid to have a tool that could be used in to great benefit.

It leaves me completely baffled and quite frankly also very unmotivated about contributing to Ramda. I can't justify spending time on long wordy discussions going nowhere when I have enjoyable and fruitful things to spend my time on.

**Comment by paldepind** [comment]
@kedashoe wrote his answer while I was writing mine. I very much agree. Especially this point:

> it doesn't bother me at all that the result is inconsistent, because the operation itself is not consistent with the data structure.

Which I think relates to my point about using objects as sets. When you have a set then folding it with a commutative operation makes sense whereas folding with a non-commutative operation does not make sense. I think users can tell the difference.

**Comment by CrossEye** [comment]
@kedashoe:

> it doesn't bother me at all that the result is inconsistent, because the operation itself is not consistent with the data structure.

That's why I don't want to offer the operation on the data structure!  :smile:

Note that it's not just a matter of data structure; it introduces a notion of _sequence_ into code that functional programming works hard to avoid:

```js
var obj = {};
obj.a = 1; // line 2
obj.b = 2; // line 3
obj.c = 3;
R.reduce((a, b) => b - a, 0, R.valIterator(obj)), //=> 2
```

If we invert the order of lines 2 and 3, we get a different value out at the end.  This is pretty horrible in my eyes.

If we were to introduce this, I'd want to do at least one of several things: change `equals` to represent the notion that such values are actually not equal.  Assert our own enforceable key order for `keys`, `toPairs`, `foldObj`, etc.

**Comment by paldepind** [comment]
> If we invert the order of lines 2 and 3, we get a different value out at the end. This is pretty horrible in my eyes.

That example is completely irrelevant. Yes, it's horrible. That's because you're writing imperative code with mutations. Of course sequence matters. But it has nothing to do with Ramda.

Case in point:

```js
var arr = []
arr.push(1)
arr.push(2)
obj.push(3)
R.reduce((a, b) => b - a, 0, arr), //=> 2
```

Here order also matters. But it has nothing to do with `R.reduce`.

**Comment by CrossEye** [comment]
@paldepind:  You have made a lot of very good points (as has @jdalton.)  I want to respond to them all in a thoughtful manner and stop the rounds of back-and-forth I've been engaged in with both of you.  As you obviously know, I'm not particularly brief in my responses.  I'd like to take a short break to settle my mind and think these things through, and to compose a hopefully more-reasoned response.

  -- Scott

**Comment by paldepind** [comment]
@CrossEye No problem at all. I can wait :)

Let me point out that both Data.Map and Data.HashMap in Haskell are Foldables and have `fold` methods available. In Data.Map values are ordered by their keys and in Data.HashMap values are in arbitrary order.

**Comment by CrossEye** [comment]
@paldepind: Sorry, my latest was not in response to _your_ latest but to other previous messages in two threads.

> That example is completely irrelevant. 

I was going to do it with WebWorkers, but I was too lazy to set up the infrastructure.  The point is that for general use of objects, _order is irrelevant_.  @jdalton is right to call us out on all the other places where Ramda gets this wrong.  I've always been willing to gloss it over because I always think of the lists coming out as sets, and the order doesn't matter to me.  But I shouldn't have been so naive.

I'm willing to bet that in the Haskell package, no matter how you define the values, you get them back in a _consistent_ order.  And when I do have a more detailed response, it will probably include resurrecting that proposal.

**Comment by paldepind** [comment]
> I was going to do it with WebWorkers, but I was too lazy to set up the infrastructure.

And that example would not have relied on mutations?

> I'm willing to bet that in the Haskell package, no matter how you define the values, you get them back in a consistent order

No. As I wrote: In Data.HashMap values are in arbitrary order.

**Comment by CrossEye** [comment]
>> I was going to do it with WebWorkers, but I was too lazy to set up the infrastructure.

> And that example would not have relied on mutations?

I was going to build one that didn't rely on mutation.  It can be done, although it's not pretty.  But it wasn't worth it for a simple argument.


> As I wrote: In Data.HashMap values are in arbitrary order.

'arbitrary' and 'consistent' are not antonyms.  Using a standardized string hashing algorithm with a particular seed is arbitrary, but it will consistently hash a string to the same value.


----

And here I go again.  Signing off now!  :smile:

**Comment by paldepind** [comment]
> @jdalton is right to call us out on all the other places where Ramda gets this wrong. I've always been willing to gloss it over because I always think of the lists coming out as sets, and the order doesn't matter to me. But I shouldn't have been so naive.

I'm fairly certain that @jdalton's point is the opposite. That Ramda is doing it a lot already _without any practical problems_. And I don't understand what has suddenly changed your mind into thinking of it as naive. Especially since it seems like our users wants more it not less.

**Comment by jdalton** [comment]
> I'm fairly certain that @jdalton's point is the opposite. 

Yah it was.

**Comment by jdalton** [comment]
Where did you all land on key order?

**Comment by CrossEye** [comment]
@jdalton:
Because it raised a fair bit of controversial discussion, I've backed off to let settle the ideas I proposed in https://github.com/ramda/ramda/issues/1067#issuecomment-135923353.  But I'm still hoping that's the direction we'll take.

**Comment by jdalton** [comment]
Cool. So no sorting of keys or guaranteed iteration order for objects at this time.

**Comment by CrossEye** [comment]
Well, I'm hoping to do that within a few weeks, but we'll see if there is still stiff opposition.

**Comment by jdalton** [comment]
> Well, I'm hoping to do that within a few weeks, but we'll see if there is still stiff opposition.

Not sure what waiting a few weeks will do.
If you're dead set on it I'm sure @davidchambers can fire off a PR.

**Comment by CrossEye** [comment]
> Not sure what waiting a few weeks will do.

As you're probably aware, some of the discussion on these issues got rather heated.  One core contributor had very strong opposition, two expressed no clear opinions, and four expressed various strengths of approval.  I'm hoping that a little perspective will be enough for us to reach a happier consensus than "Hey, it's four to one; you lose."

That's why I backed off the issue for the moment, along with two other reasons: I'm hot on another side project which has taken more of my time for several weeks.  And my highest priority for Ramda at the moment is not this, but figuring out what we're going to do with `compose`/`pipe`: #1318.  I do expect to revisit this one, though, before too long.

**Comment by jdalton** [comment]
Cool.

**Comment by jdalton** [comment]
Ping @CrossEye.

**Comment by CrossEye** [comment]
@jdalton: When I do follow up, I will be in #1067.
