### ISSUE TITLE
maxList, maxListbBy, minList, minListBy

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1334]
I was somewhat surprised to see that max[By] and min[By] are binary functions. I think unary-list variants would be much more useful, or maybe both options can be provided.

**Comment by davidchambers** [comment]
The problem is that `R.maxList` would be a partial function, since `R.maxList([])` is undefined. Folding forces one to handle the empty list:

```javascript
> R.reduce(R.max, -Infinity, [])
-Infinity
> R.reduce(R.max, -Infinity, [1, -2, 3, -4])
3
```

The function's curried nature is sometimes useful, too:

```javascript
> R.map(R.max(0), [1, -2, 3, -4])
[ 1, 0, 3, 0 ]
```

**Comment by asaf-romano** [comment]
The empty-list case is interesting in the context of ramda, because throwing isn't nice but returning a ``Maybe`` or an ``Either`` isn't an option.

The ``reduce`` implementation is nice, but I'm afraid it cannot be applied easily for implementing maxListBy, since you don't have ``-Infinity`` handy. For example, let's say you have a list of objects representing some sort of activities, each having a timestamp property, which an ISO-Date string. Now you wish to find the most recent activity. The ``by`` version would then be something like this
```js
var toEpoch = pipe(moment, invoker("valueOf"));
pipe(prop("timestamp"), toEpoch);
```
But now what's you initial value for the reduce function? It cannot be ``-Infinity`` because if you pass that to maxBy, your ``by`` function ought to be branched to support that.

**Comment by davidchambers** [comment]
The problem remains that if these functions did not require an initial value, users would in many cases need guards to handle the empty list. For example:

```javascript
R.isEmpty(xs) ? 0 : R.maxListBy(Math.abs, xs)
```

Instead we could have written:

```javascript
R.reduce(R.maxBy(Math.abs), 0, xs)
```

The advantage of the latter is that we're using a total function rather than a partial function with a guard. The problem with guards is that it's easy to forget to include them, which can result in crashes at run time.

If one is able to determine that `xs` will never be `[]`, one can use `xs[0]` as the initial value.

**Comment by asaf-romano** [comment]
I acknowledge that. This is why I was referring to Maybe (which isn't not an option, unfortunately).

maxListBy doesn't have to be partial; it could take the fallback value (not that initial value - just the final fallback; this is similar to ```propOr``` which guards against null value, unlike ```prop```).

Again, the problem with ```R.reduce(R.maxBy(Math.abs), 0, xs)``` is that the initial value isn't always in par with the fallback value, or it could be hard to provide. If i want the fallback to be ```null``` in the case of an object, i need to call reduce with an initial value for which the reducing function returns null.

**Comment by davidchambers** [comment]
The `reduce` approach certainly isn't perfect. I don't yet see a way to have our :cake: and eat it too. :)

> If i want the fallback to be `null` in the case of an object, i need to call reduce with an initial value for which the reducing function returns null.

I don't quite follow (perhaps because I've stayed up very late writing code the past two nights). Could you provide an example?

By the way, for in-line code in Markdown single backticks are sufficient. ;)

**Comment by asaf-romano** [comment]
I sometimes forget :) How did you notice?

So, let's go to my first example.

Here's a list:
```js
var list = [
  { value: "foo", timestamp: "2015-08-13T06:22:39.501Z" },
  { value: "bar", timestamp: "2014-08-13T06:22:39.501Z" },
  ...
];
```
and now you want to find the most-recent entry in such list. If you know the list isn't empty, you could, indeed, do something like this:

```js
var isoToEpoch = pipe(moment, invoker("valueOf"));
reduce(maxBy(pipe(prop("timestamp", isoToEpoch), list[0], list);
```
But if you don't know that the list isn't empty. You have to do it this way (assuming you want to return null in that case):

```js
isEmpty ? reduce(...list[0]...) : null;
```

and that's because the initial value also goes through the function you pass to `maxBy`

**Comment by davidchambers** [comment]
Maybe is the answer, I believe:

```javascript
> R.converge(R.lift(R.reduce(R.maxBy(x => moment(x.timestamp).valueOf()))), S.head, S.tail)(list)
Just({timestamp: "2015-08-13T06:22:39.501Z", value: "foo"})
> R.converge(R.lift(R.reduce(R.maxBy(x => moment(x.timestamp).valueOf()))), S.head, S.tail)([])
Nothing()
```

In the case of vanilla Ramda, I think we're stuck with `<guard> ? ... : null`.

**Comment by asaf-romano** [comment]
I still need to catch up on `lift` :)

I think vanilla-ramda could just return `undefined` in this case (if such a function is provided). After all, it's probably the most appropriate use of `undefined. After all, the maximum value of an empty list is logically /undefined/.

**Comment by paldepind** [comment]
> I still need to catch up on lift :)

Conceptually `lift` and `map` are almost the same thing. `R.map(fn)` _lifts_ a unary function to work on any functor (lists for instance).

```js
R.equals(R.map(R.add(2))([1,2,3,4]),
         R.lift(R.add(2))([1,2,3,4])); //=> true
```

`R.map` takes a unary function. But you could also imagine a `R.map2` that takes a binary function, an `R.map3` that takes a ternary function and so on. If you make that into `R.mapN` you have the same as `R.liftN`. And `R.lift` just looks at the arity of the function you pass it and "selects" the correct `map` variant to use.

**Comment by raine** [comment]
Probably not the best implementations, but this has worked for me:

```js
import { pipe, split, toString, product, curry, maxBy, reduce, useWith, identity, head, tail } from 'ramda';

const NUMS = [415, 519, 145, 189];

const reduce1 = curry((fn, arr) =>
  reduce(fn, head(arr), tail(arr)));

// after http://hackage.haskell.org/package/base-4.8.1.0/docs/Data-List.html#v:maximumBy
// returns undefined for an empty list
const maximumBy = useWith(reduce1, maxBy, identity);

const numberProduct = pipe(
  toString, split(''), product);

maximumBy(numberProduct, NUMS);
// => 189
```

**Comment by asaf-romano** [comment]
In our code base, I also chose the ``undefined`` behavior. I still think it's worth inclusion in the core lib. David's library can of course return ``Nothing`` in that case :)

**Comment by davidchambers** [comment]
What are your thoughts on this proposal, @CrossEye?

**Comment by CrossEye** [comment]
Trying to catch up on very old messages.

> What are your thoughts on this proposal, @CrossEye?

I'm not quite sure what constitutes a proposal here.  The code from @raine?  That's almost exactly what I do when I want this sort of behavior.  I don't know that we'd want to reintroduce `reduce1` (see #20) on the public API, but obviously we could do it internally if desired.

I'd be happy to have the `*List[By?]` functions.  I wasn't thrilled with the change from variadic (or list?) based max/min to binary ones, even if I saw the reasons for it.  It would be nice to have these back.  But I think I would prefer to insist that the user supply a reasonable initial value than try to infer it.  Thus:

```js
var list = [
  { value: "foo", timestamp: "2015-08-13T06:22:39.501Z" },
  { value: "bar", timestamp: "2014-08-13T06:22:39.501Z" },
  ...
];

var isoToEpoch = pipe(moment, invoker("valueOf"));
reduce(maxBy(pipe(prop("timestamp"), isoToEpoch), 
       {timestamp: "0000-00-00T00:00:00.0Z"}, list
);
```

But. then again, it has been a long time since #20, and @buzzdecafe and I were working blind, as the only ones working at all with the code-base, so perhaps it's time to reconsider `reduce1`.

**Comment by buzzdecafe** [comment]
the bigger question is whether we should integrate algebraic types, which i am starting to think might be worth doing. ramda-sanctuary merge?

**Comment by buzzdecafe** [comment]
closed for inactivity
