### ISSUE TITLE
R.all condition is returning an unexpected positive

### ISSUE THREAD

**Issue by miwillhite** [ramda/ramda#1338]
Basically `R.all` is returning truthy where it's condition (when isolated) is returning falsey against the same argument.

```javascript
R.all(R.propEq('foo', true), [{ foo: true }]);
//=> true (Expected)

R.all(R.propEq('foo', true), []);
//=> true (Unexpected)

R.propEq('foo', true)([]);
//=> false (Expected)
```

See this example: http://bit.ly/1hbhXJ2

**Comment by buzzdecafe** [comment]
you are confusing the types:

The first example is passing the *elements* of the list to `propEq`, and the list itself to `all`. Since all of the elements in the list pass the predicate, it evaluates to `true`. 

In the second example, once again, all of the elements of the list satisfy the predicate -- this time because there are no elements in the list.

In the third example, you are passing a list where an object is expected. JS treats this as an object anyways; and that empty list does not have a `foo` property on it.

Seems fine to me,

**Comment by miwillhite** [comment]
Ah good catch on the third example, changing it to an object has the same result.

Thanks for clarifying on the rest!
