### ISSUE TITLE
Drop placeholder support in curry, add placeholder support in `partial`

### ISSUE THREAD

**Issue by paldepind** [ramda/ramda#1363]
Quotes (from #1178):

@buzzdecafe 

> i am not thrilled with generalized placeholders, because of the amount of complexity they are baking into fundamental operations of the lib. to my mind they don't give you much you can't get with flip. the cost exceeds the benefit.

@CrossEye 

> I'm starting to join @buzzdecafe's distaste for these things.

Back then I didn't want to remove support for placeholders (I like them). But it just occurred to me that we could drop placeholder support from curry but still have it available by adding support for it to `R.partial` and `R.partialRight`.

Having placeholder support in curry adds an invocation overhead to every single function in Ramda and functions created with `R.curry` and `R.curryN`.

Placeholder syntax is nice but I don't think it's used often enough that having it in curry is warranted.

I suggest dropping placeholder support from all our curry functions and instead adding placeholder support to `R.partial`. Thus people can still get the benefits of placeholders when it's really needed.

I don't have any benchmarks about the actual cost of placeholder support. But I think the simplifications we can get to `_curryN`, `_curry1`, `_curry2` and `_curry3` would be enough in itself.

As far as I'm away our binary math functions are the primary use case for placeholders. But users can `R.flip` them or maybe we could provide flipped versions of them.

Doing this would close #1178 and #1027.

**Comment by davidchambers** [comment]
Interesting idea. I could get behind this.

**Comment by TheLudd** [comment]
If `partial` supports the placeholder, is `partialRight` needed?

**Comment by paldepind** [comment]
> Interesting idea. I could get behind this.

:smile:

> If partial supports the placeholder, is partialRight needed?

Good question. I've never used `partialRight` so I wouldn't know.

**Comment by davidchambers** [comment]
I would keep `R.partialRight`. It would still be more convenient, in some cases:

```javascript
R.partialRight(f, x)
```

```javascript
R.partial(f, R.__, R.__, x)
```

**Comment by buzzdecafe** [comment]
> As far as I'm away our binary math functions are the primary use case for placeholders. 

not exactly. the placeholder arose from trying to find a way to convert infix operators into prefix functions. the problem is the infix operators that don't commute (`>, <, concat`, etc.) are better converted flipped. But you can't just flip 'em, that leads to some weird, surprising behavior. So it wound up a big f*cking mess. The original placeholder was just for those non-commutative infox operators, so you could: 

```js
gt10 = R.gt(R.__, 10);
```

instead of 

```js
gt10 = R.flip(R.gt)(10);
```

or even worse

```js
gt10 = R.lte(10);
```

anyways, it was worth exploring whether generalized placeholders were worth doing.

**Comment by CrossEye** [comment]
I could definitely support this.

I have two concerns.  First is that we didn't ever solve the original puzzle (#175) that led us down the path that started with an attempt at operator support and ended with the placeholders.  That was the question about what to name flipped versions of `lt`, 'gt', et. al.  Things like `divideBy` and `subtractN` were ok, and I'm sure we could find useful names for `modulo` and some others, but there just seem to be no good versions for these binary comparisons.  And I think good names are important.

Second, this leaves only `flip`.  While I'm often the one trying to explain to people that points-free should not be a major goal of its own, it _is_ often useful, and I'd hate to lose support for it.  We could maintain it by adding some `cycle` style function  that rotates the args in order, or we could implement something like lodash' `rearg`,  @paldepind: you worked on something like this some months ago.  Were you happy with the results?

I'd like to solve these issues, because I think this is worth doing.

**Comment by paldepind** [comment]
> I have two concerns.  First is that we didn't ever solve the original puzzle (#175) that led us down the path that started with an attempt at operator support and ended with the placeholders.  That was the question about what to name flipped versions of `lt`, `gt`, et. al.  Things like `divideBy` and `subtractN` were ok, and I'm sure we could find useful names for `modulo` and some others, but there just seem to be no good versions for these binary comparisons.  And I think good names are important.

I agree. I think our binary functions are quite problematic as is. `R.gt(5)` sounds like a function that returns true if you pass it something greater than 5, but it is the opposite. `R.subtract(5)` sounds like a function that subtracts five from it's argument but instead it subtracts it argument from 5. Maybe those functions should actually be flipped so that partially applying them with one argument is natural.

> Second, this leaves only `flip`.  While I'm often the one trying to explain to people that points-free should not be a major goal of its own, it _is_ often useful, and I'd hate to lose support for it.  We could maintain it by adding some `cycle` style function  that rotates the args in order, or we could implement something like lodash' `rearg`,  @paldepind: you worked on something like this some months ago.  Were you happy with the results?

I'm not sure what you mean that this leaves only `flip`? This adds placeholder support in `R.partial`? I created `rearg` for [functionize](https://github.com/paldepind/functionize) as a way to convert libraries with arguments in the wrong order for currying. For such conversions it is splendid. In most code I probably would not want to use `rearg`.

**Comment by CrossEye** [comment]
> I think our binary functions are quite problematic as is. `R.gt(5)` sounds like a function that returns true if you pass it something greater than 5, but it is the opposite. `R.subtract(5)` sounds like a function that subtracts five from it's argument but instead it subtracts it argument from 5. Maybe those functions should actually be flipped so that partially applying them with one argument is natural.

The trouble is that then they don't work correctly in their full form:

```js
R.subtract(12, 7); //=> -5  // WTF?
```

It was this tension that led to the discussion in #175, and the very short-lived changes in #368 -- removed again in #388 because of some very important objections from @davidchambers.


> I'm not sure what you mean that this leaves only `flip`? This adds placeholder support in `R.partial`? 

Sorry, that was rather terse.  The point was that `flip` allows us to partially apply the second instead of the first parameter to a curried function.  But with the placeholder, we can partially apply whatever parameter we choose.  If we move to just doing these on `flip` and `partial`/`partialRight` first of all, we might not be able to partially apply the third of four parameters, but generally working with curried functions altogether would become more difficult:

```js
var f = R.curry((a, b, c, d) =>[a, b, c, d]);
var g = R.partialRight(f, 4);

g(1, 2, 3); //=> [1, 2, 3, 4]
g(1, 2)(3); //=> [1, 2, 4, 3]  // ???
```

While this looks like bad behavior, it really is the logical thing when you think about it.  But it makes partially applying any parameter more tricky than desired, if you still want Ramda's standard curried behavior.  You would need to curry again after the `partial` call:

```js
var h = R.curry(g);

h(1, 2, 3); //=> [1, 2, 3, 4]
h(1, 2)(3); //=> [1, 2, 3, 4]
```

So `flip` is the only thing that would retain the curried semantics and still allow you to alter what values are partially applied.  That is much more limited than our current capabilities.  I'm not sure how critical that is.  I asked about your `rearg` because I'm curious, but I don't know that we'd want to go that way.  We do have to think pretty carefully, though, when deciding to reduce functionality.
