### ISSUE TITLE
include "added in vX.Y.Z" for each function

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1381]
When working on a project which specifies a Ramda version other than the most recent, one should be able to determine from the documentation whether a particular function is available. This need would be satisfied by ramda/ramda.github.io#10, but I'm interested in seeing each function's "age" regardless.

**Comment by raine** [comment]
For the most part you can use git to find out in which tag `src/<function>.js` was added, but not so easy for ones added before 3a3285b.

**Comment by CrossEye** [comment]
I've wanted the same thing at times.  While this is probably worth doing, I hate adding still another JSDoc tag, and reducing further the signal/noise ratio of our source files.

**Comment by raine** [comment]
It should be doable without a JSDoc tag if the git method is acceptable and figuring out the git tags when docs are built isn't too time consuming.

**Comment by CrossEye** [comment]
We could, but that might get tricky for renames, etc.  I'm really tempted to have one or several separate metadata files for such information, ones that would be required by the build to have an entry for every public function, but which don't end up in the source code file.

But perhaps it's just me that doesn't like all that stuff cluttering up my source code.

**Comment by davidchambers** [comment]
I don't think this needs special treatment: it could simply be a paragraph in the description. For example:

> __`objOf :: String -> a -> StrMap a`__
>
> Creates an object containing a single key:value pair.
>
> Added in v0.7.0 as `createMapEntry`. Renamed `objOf` in v0.18.0.

**Comment by CrossEye** [comment]
If we do have it in the source file, I would rather a tag (or even two if necessary [`@formerly` or some such]), which we can more easily treat as standardized metadata, format independently, etc.

I just having a longing for cleaner source files.

**Comment by branneman** [comment]
I vote for adding the `@since` tag, which is official JSDoc: http://usejsdoc.org/tags-since.html

**Comment by davidchambers** [comment]
Nice find, @branneman! That's clearly the way to go. Now we just need someone with good Git skills to add this for each function. :)

**Comment by branneman** [comment]
I'll look into it!

**Comment by branneman** [comment]
I've got an initial try here: https://gist.github.com/branneman/f63a7ea4d867d539599d

I did not implement searching for the exact function versions from before ramda 3a3285b (is that ≤0.8 or ≤0.9?), that requires a different implementation. Do we actually want this? Or might a `@since` tag such as *≤ 0.8.0* be enough? I can put the `@since` tags in a PR right now, or I can implement the harder version, which will take me some more time.

I can look into the more precise older version tags as well, but if we don't really want it, that'll save me the effort.

When will the next version of ramda be there? It would be nice if this makes it in. Is there a deadline?

----
Aside:
I was playing around with ramda-fantasy for the first time, so forgive me if i screwed up with using IO correctly ;) To me, it seems that the implementation of `getCommit()` and `getVersion()` is too bloated. If I'm using IO/chain/map wrong, pointers would be appreciated.

The non-functional shorter version of the same code is available as well, [here](https://gist.github.com/branneman/f63a7ea4d867d539599d/e025d8c5ba174cdb5e2e7e22384d018cbe781499).

**Comment by davidchambers** [comment]
> I can look into the more precise older version tags as well, but if we don't really want it, that'll save me the effort.

I would very much like to provide `@since` tags going all the way back to v0.1.0 or whatever the first release was. There's a straightforward manual approach for determining when early functions were added:

1.  Open _n_ tabs in a browser window, each displaying __ramda.js__ as it existed at a particular tag (here's [0.2.0][1], for example).

2.  For each function added before 3a3285b817ea1780e5e9a5fbc72f8cde0da90f78, determine the version in which it was added by searching for `R.<name> =` in each tab from left to right until a match is found.

> When will the next version of ramda be there? It would be nice if this makes it in. Is there a deadline?

There's no deadline. I would love to release v0.18.0 this weekend, but I'm happy to wait for you pull request.

One thing I noticed when viewing your gist is that patch releases are incorrectly given credit for additions. Functions added in X.Y.0 are shown to have been added in X.Y.1 instead.


[1]: https://github.com/ramda/ramda/blob/0.2.0/ramda.js

**Comment by kedashoe** [comment]
An approach that may work for all versions:

1. run `git show-ref --tags` to get our list of tags and sha's
2. order tags, start with earliest
3. run `git show ${sha}:package.json > ${os_tmp_dir}/package.json`
4. require the file from step 3
5. read the `main` key to get path to ramda
6. run `git show ${sha}:${path_from_step_5} > ${os_tmp_dir}/ramda.js`
7. require our ramda file from step 6, loop over module keys, every function that we have not seen yet we can add our since tag

Could also just `require` those temp files from memory. Sorry for the pseudo code if I've messed anything up/left anything out, played around a bit and this seems to work. I also like personally like @CrossEye's suggestion [above](https://github.com/ramda/ramda/issues/1381#issuecomment-139823106) of a separate meta data file that is included with the distribution, so that the doc builder repo can use it. Seems easier to maintain going forward and can potentially include other stuff for docs as needed.

**Comment by davidchambers** [comment]
I'm keen to release v0.18.0 this weekend, so I've put together a shell script based on @kedashoe's excellent suggestion. I've also pushed missing tags and addressed inconsistencies in the tag names from the pre-xyz days.

Do you mind if I take this over, @branneman? If you've done further work on your script we could collaborate. :)

**Comment by branneman** [comment]
Not at all @davidchambers! I haven't done any additional work yet.

I'd love to see your solution. If you don't mind me asking, why not a ramda/ramda-fantasy script? ^^

**Comment by davidchambers** [comment]
> Not at all @davidchambers! I haven't done any additional work yet.

I'm pleased to determine that we haven't been duplicating our efforts.

> I'd love to see your solution. If you don't mind me asking, why not a ramda/ramda-fantasy script?

I prefer Bash for scripts which need to interact with other Unix tools because synchronous code is simpler than asynchronous code (even if good abstractions are available). I'll include the script in the description of the pull request I'll open shortly. :)
