### ISSUE TITLE
Memoize should probably use some internal hashing function rather than toString

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1384]
See #1383 comment 3. I think that using toString limits the flexibility here, as it requires an `eval` representation of an object, which may not always contain everything necessary to base an equality check on.

Powerful enough, such a function could be used for implementing a much more efficient version of `uniq`, `union` and other functions currently relying on `equals`.

**Comment by CrossEye** [comment]
I'm all ears.

I believe that part of the design of `R.toString` (please correct me if I'm wrong, @davidchambers) was that it was supposed to be good enough for this task, that two equal  values would return the same `toString` value, and no two that were not equal would do so.  I would think that if we were to go down the path of #1383, then we would also update `toString`.

If we did do a hash, what's your proposal for dealing with potential hash collisions?

**Comment by asaf-romano** [comment]
I actually didn't suggest a proper hashcode function, and considered toString as some sort of pseudo hashing. The problem with toString here isn't that it returns a string rather than a number, but rather that because it's a public API, you have to be "nice";  that's how we got ``R.toString([...]) == R.toString(/.../.exec("...")``. A proper hashcode is the more robust option anyway though, and collisions could be handles the same way they are handled in Java for example, i.e. utilize ``equals``.

Regarding toString limitations I know of:
* "Overriding" ``equals`` but not ``toString`` is a problem (btw, the same way overriding ``equals`` but not ``hashcode`` in Java is a problem; except here the contract is an implementation detail that is easy to overlook).
* the Object prototype is ignored (see david's comment in the other bug).
* If we do address Symbols in ``equals``, I don't think there's a way ``toString`` them nicely, needless to say in an ``eval``-able way.

```js
var _a = Symbol(), _b = Symbol();
R.toString({ [_a]: 1, [_b]: 2 }); // Currently throws "TypeError: can't convert symbol to string", but would probably be {} to keep eval happy.
```

**Comment by CrossEye** [comment]
> I actually didn't suggest a proper hashcode function

Sorry, I just assumed from the title.

> * "Overriding" ``equals`` but not ``toString`` is a problem (btw, the same way overriding ``equals`` but not ``hashcode`` in Java is a problem; except here the contract is an implementation detail that is easy to overlook).

This is an interesting point, but it's really odd with our dispatching to think of _overriding_ anything, but only of allowing the user to choose her own function rather than our own if she knows better than us how to handle her data.


> * the Object prototype is ignored (see david's comment in the other bug).

I don't know a good solution to this.  I wish I did, but I suspect it's close to insoluble.


> * If we do address Symbols in ``equals``, I don't think there's a way ``toString`` them nicely, needless to say in an ``eval``-able way.

You may well be right.  This makes me a bit suspicious of the whole program of this style of `toString`.

**Comment by asaf-romano** [comment]
Regarding the object prototype issue, I think that's easily solvable in ``equals`` (with ''getPrototypeOf''/''constructor.name''/whatever, let's discuss that elsewhere if necessary). It'd also be solvable in a black-box version of ''toString'' (what I sort-of suggested here). Indeed, I don't think it can be solved in the current version of ''toString''.

**Comment by andrewbranch** [comment]
+1.

I have a serious performance issue due to memoize using toString. I was trying to memoize some functions that I was passing Immutable.js objects to, and was surprised to find that the memoization actually slowed my program by 5 or 6. After realizing that `toString` is called on the arguments each time, I checked out the performance of `.toString()` on my Immutable.js structures, and it was absolutely awful. They override that method purely for debugging purposes, and it recursively pretty-prints the entire structure.

Ironically, I went a little out of my way to pass immutable objects to these functions, because I at first assumed that Ramda was using some sort of Map implementation (object equality) as its cache.

**Comment by CrossEye** [comment]
I do think we need to find some reasonably efficient way to hash objects, for use in a more complete HashMap structure.  I'm definitely not looking forward to it.  But I think we need it for this, for `uniq` and probably for other things as well.

If anyone has good ideas, I'd love to hear them.

**Comment by louisremi** [comment]
Hi guys,

I've just released [memoize-immutable](https://github.com/louisremi/memoize-immutable) because Ramda's memoizer was taking too long to build cache keys. You should read the [accompanying blog post](https://github.com/louisremi/memoize-immutable) and the code, as I believe you could reuse the base idea in your memoizer: using a WeakMap and auto-incrementing id to materialize/serialize non-primitive parameters.

I'm here to help!

**Comment by CrossEye** [comment]
Thanks, Louis-Rémi!  I'll try to take a look this weekend.

**Comment by CrossEye** [comment]
@louisremi: This is interesting stuff.  Ramda is currently built with no external dependencies, which means that so long as we're trying to support older environments without polyfills, we can't depend on things like `WeakMap` and `Map`.  There is talk now about changing this, and about publishing version 1.0 with something like the current API and then starting v.2 with a hard dependency on an ES6 (or shimmed) environment.  That might allow us to consider changes like this.  Because I do like the approach.

**Comment by louisremi** [comment]
@CrossEye: As far as I can see, Ramda doesn't specify which browsers and environments it supports (or does it?). This should be the only criteria to adopt this approach or not, as the polyfills for WeakMap actually defeat the purpose of my approach: they rely more or less to good ol' serialization to index a map that isn't Weak at all.
So if you're ok with having Ramda v1 or v2 support only [browsers that support WeakMap](http://kangax.github.io/compat-table/es6/#test-WeakMap), then you can adopt this approach :-)

**Comment by buzzdecafe** [comment]
> So if you're ok with having Ramda v1 or v2 support only browsers that support WeakMap, then you can adopt this approach :-)

i like this, because memoization is so critical for this style. unfortunately, [IE < 11 has no support at all for WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#Browser_compatibility). 

Personally, I'd be happy to fallback to existing implementation for IE < 11 rather than sacrifice the good citizens for the sins of the bad ones.

**Comment by louisremi** [comment]
You could fallback to the current implementation of Memoize instead of using a WeakMap polyfill.

In any case, it would be good to define and document the browser support of Ramda.

**Comment by joshburgess** [comment]
Just randomly stumbled on this issue... Is `memoize` still using .toString? Still any plans to switch to a hashing implementation?

**Comment by kedashoe** [comment]
> Just randomly stumbled on this issue... Is memoize still using .toString? Still any plans to switch to a hashing implementation?

It is, but we've added `memoizeWith`. I would recommend using `memoizeWith` over `memoize` for pretty much all cases.

**Comment by jvorcak** [comment]
@kedashoe wouldn't it then make sense to mark `memoize` as deprecated? People could still create it using `memoizeWith`, but they will need to do it explicitly ~> they would have to realize what it does and that it can cause serious performance issues.

**Comment by joshburgess** [comment]
@jvorcak @kedashoe Yeah, I think it would make sense to provide some further detail... some examples of different ways to use `memoizeWith`, either a deprecation or a warning about `memoize`, etc....

**Comment by kedashoe** [comment]
Agreed the current situation is not ideal. Personally yes, I would like to deprecate `memoize`. Anyone else thoughts on it?

**Comment by buzzdecafe** [comment]
👍 for deprecating `memoize`

**Comment by CrossEye** [comment]
:+1: on deprecating

**Comment by MadDeveloper** [comment]
Why deprecate `memoize`? Why not give it `memoizeWith` function signature, and if the first parameter is the function to memoize, use the default hash algorithm?
We have the choice between a lot of fast hash algorithm: https://github.com/joliss/fast-js-hash-benchmark
- `iMurmurHash`
- `SparkMD5`,
- `xxhash`

And if Ramda does no want dependency, the hash can be imported in Ramda core.
Or, Ramda can use the [memoize-one](https://github.com/alexreardon/memoize-one) library, presented on the [React doc](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization).

**Comment by CrossEye** [comment]
I'm not quite sure what you're recommending.  Is there a "**not**" missing?  ("and if the first parameter is **not** the function to memoize...")?

But regardless, Ramda avoids optional parameters and shifting signatures.  While we might rename `memoizeWith` to `memoize` later, we would want to give users a chance to fix code and not have surprising non-obvious breaks.  If a user skipped the release notes noting that `memoize` doesn't exist, the problem will be immediately obvious.  If instead, `memoize` simply changed behavior, it might take some time before there is a noticeable problem.

Also note that a standard hash function won't really do here, not without writing a HashMap algorithm to handle it: how else would we deal with collisions?  We could write an internal `_Map` function parallel to the [current `_Set`][se] one; that might be useful, but a plain `hash` function by itself is not much help.

----------

While memoization is a very useful feature for dealing with expensive computations, I'm not particularly convinced it really belongs in Ramda at all.

  [se]: https://github.com/ramda/ramda/blob/master/source/internal/_Set.js

**Comment by MadDeveloper** [comment]
`But regardless, Ramda avoids optional parameters and shifting signatures.`
Right, so my proposition is not faithful to Ramda's standards. I hope that later `memoize` will be undeprecated 😄
