### ISSUE TITLE
R.both and R.either should be ternary functions

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1395]
Current type:

```haskell
:: (** -> Boolean) -> (** -> Boolean) -> (** -> Boolean)
```

Proposed type:

```haskell
:: (a -> Boolean) -> (a -> Boolean) -> a -> Boolean
```

If we're happy to restrict these to unary predicates, I'll submit a pull request. If not, I'll open a Sanctuary issue. :)

**Comment by CrossEye** [comment]
So, what's the gain?

Obviously we would lose the ability to say, for instance,

var somewhatLarger = ɛ => R.both(R.gt, (a, b) => a < b * (1 + ɛ));

withinTenPercentLarger = somewhatLarger(0.1);
withinOnePercentLarger = somewhatLarger(0.01);

[
  withinTenPercentLarger(125, 140),
  withinTenPercentLarger(125, 120),
  withinOnePercentLarger(125, 140),
]

**Comment by davidchambers** [comment]
> So, what's the gain?

A simpler type, and the ability to provide the value along with the predicates. I lean towards defining simple functions which handle 80% of cases (and falling back to lambdas when necessary) rather than defining slightly more complex functions which handle 100% of cases. I agree that the current behaviour is more in keeping with the Ramda philosophy.

**Comment by CrossEye** [comment]
> ... and the ability to provide the value along with the predicates.

Every time I think that sounds like a good idea and build a function that way, when it started out as the reverse, I never use it that way.  I don't know if it's simply because I've already gotten it settled in my head, or if there are some functions that simply seem more about decorating other functions than about themselves transforming data, but I've discussed this from the other side several times with @buzzdecafe.  I'd argue for adding the data as an additional argument, mostly for consistency, and he would never see the point.  I'm starting to see why.  I find I simply don't use it.

That's not to say that I find it wrong-headed to want to do so, but it turns out not to be much motivation to me.

> I lean towards defining simple functions which handle 80% of cases (and falling back to lambdas when necessary) rather than defining slightly more complex functions which handle 100% of cases.

The word "slightly" in there is important, though.  Although the type signature is clearly harder to write, that's an artifact of the Hindley-Milner syntax.  There is not a tremendous amount of difference if you set aside the notion of supplying the value along with the predicates.  And if the difference really is slight, then I would tend toward the 100%.

So, while I have been convinced that we should be removing all vestiges of variadic functions from Ramda (although I'm pretty sure @buzzdecafe, @paldepind, and @TheLudd don't agree), I don't feel that we should avoid generating polyadic functions, and I certainly don't feel we should only accept unary ones.
