### ISSUE TITLE
Converge with curried/partial functions

### ISSUE THREAD

**Issue by jacobp100** [ramda/ramda#1404]
Running the following does nothing. Is this a bug, or am I doing something wrong?

``` js
const checkTest = (value, item) => value + item;
const test = converge(map, partial(checkTest), prop('test'));
test({ test: [1, 2, 3], value: 2 });
```

**Comment by davidchambers** [comment]
Could you try `curry(checkTest)` in place of `partial(checkTest)`?

**Comment by buzzdecafe** [comment]
in the `converge` `checkTest

**Comment by jacobp100** [comment]
Nope. Is this more a case of me going wrong with the Ramda concepts?

```js
function checkTest(value, item) { return value + item; }
var test = R.converge(R.map, R.curry(checkTest), R.prop('test'));
test({ test: [1, 2, 3], value: 2 });
```

**Comment by davidchambers** [comment]
Let's look at the types:

```haskell
map      :: (x -> y) -> [x] -> [y]
converge :: (b -> c -> d) -> (a -> b) -> (a -> c) -> (a -> d)
```

Let's specialize the type of `converge`. First, replace `b` with `x -> y`:

```haskell
converge :: ((x -> y) -> c -> d) -> (a -> (x -> y)) -> (a -> c) -> (a -> d)
```

Next, replace `c` with `[x]`:

```haskell
converge :: ((x -> y) -> [x] -> d) -> (a -> (x -> y)) -> (a -> [x]) -> (a -> d)
```

Finally, replace `d` with `[y]`:

```haskell
converge :: ((x -> y) -> [x] -> [y]) -> (a -> (x -> y)) -> (a -> [x]) -> (a -> [y])
```

So, the type of `converge(map)` is as follows:

```haskell
converge(map) :: (a -> (x -> y)) -> (a -> [x]) -> (a -> [y])
```

That's a weird type. Probably not what you want.

What are you actually trying to do? Do you want to get `[1 + 2, 2 + 2, 3 + 2]` given `{ test: [1, 2, 3], value: 2 }` as an argument? If so, let's first express the transformation as a lambda:

```javascript
const test = o => R.map(R.add(o.value), o.test);
```

This is short and clear, and I'd be inclined to leave it at that. As an exercise, though, we could make it point-free. We'll need to converge, since we reference `o` in two places:

```javascript
const test = R.converge(..., ..., ...);
```

`o` appears in both arguments to `R.map`, so we'll use `R.map` as the combining function:

```javascript
const test = R.converge(R.map, ..., ...);
```

The right-hand branch is simply `R.prop('test')`:

```javascript
const test = R.converge(R.map, ..., R.prop('test'));
```

The left-hand branch requires composition:

```javascript
const test = R.converge(R.map, R.compose(R.add, R.prop('value')), R.prop('test'));
```

**Comment by jacobp100** [comment]
My exact code (workaround) is,
```js
(context) => (
      map(processTag(context), context.tags)
),
```
Where `processTag` is a curried function (which can’t be substituted by anything like R.add). I attempted to write this as,
```js
converge(map, processTag, prop('tags'));
```
Which you would then call with the `context` object.

**Comment by CrossEye** [comment]
I'm betting that the issue you're facing is that `processTag` is a 2-argument function, and so `converge` thinks that the output function is binary.

That's the only difference between [this failing example][fa] 

```js
var processTag = R.curry((context, value) => context.handle(value))
```

and this [working one][wo]

```js
var processTag = context => value => context.handle(value);
```

(Obviously I have no idea what the real `processTag` function looks like.)

There are [several][a1] [different][a2] ways you could adjust your `converge` statement and still keep `processTag` as a curried function.  Either of these would work:

```js
R.converge(R.map, R.unary(processTag), R.prop('tags'));
```

or

```js
R.converge(R.map, context => processTag(context), R.prop('tags'));
```

I'm not sure there is any real way for Ramda to help with this directly.  The only alternative to using the transformer functions' arities in order to derive the output function's arity is to ask the user to supply it.  And in the vast majority of cases, this derivation is helpful, so adding a parameter for it is uncomfortable.

If that is not the issue, please let me know.  I'm quite curious.

  [a1]: http://bit.ly/1KTj3Vb
  [a2]: http://bit.ly/1KTj3Vd
  [fa]: http://bit.ly/1KTj3V3
  [wo]: http://bit.ly/1KTj3V9

**Comment by ShaunEgan** [comment]
Thank you @CrossEye! That was really useful.

**Comment by ShaunEgan** [comment]
Was this ever fixed?
