### ISSUE TITLE
R.map docstring should mention Fantasy Land

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1417]
Currently there's no indication that [`R.map`][1] is compatible with functors other than List.

[1]: http://ramdajs.com/docs/#map

**Comment by branneman** [comment]
Isn't the same true for more functions that dispatch? Like `R.ap()`? If I understand correctly, only `R.chain()` is mentioning Fantasy Land?

**Comment by CrossEye** [comment]
Our mechanism does not imply anything about conformance to the FantasyLand specification.  I believe we really need to document how functions are delegated.  And I think our documentation should somehow mention that there is some special place in our hearts for the FantasyLand spec, but I'm not sure that we should specifically document individual functions as delegating specifically to FL.

**Comment by benperez** [comment]
I actually think that individual functions should indicate that they delegate to FL-compatible methods. What's the point of dispatching if nobody knows about it? Also, given the way a lot of people interact with the docs (go to the ramdajs.com/docs, search for map/ap/chain/etc., read description of an individual function) I think that documenting individual functions is the appropriate place to do it.

**Comment by CrossEye** [comment]
Sorry if I wasn't clear.  I agree that individual functions should be documented as delegating to a named method.  I just don't think they should be specifically documented as delegating to the Fantasy-land specification.  I feel that's too limiting.  I would rather simply tag it

```js
// @dispatchesTo map
```

And then have the documentation include

```html
<p><a href='path/to/dispatch/docs'>Dispatches</a> to the `map` method of the
object in the final parameter, if a list is not supplied.</p>
```

My feeling is that, while Fantasy-land is a good spec, it's far from an ideal one, and I would like to be open for possible [advancement to it][fl] or alternatives to it.  I'd also like our documentation to be flexible enough to cover [possible enhancements][pe] to our own dispatching mechanism.

  [fl]: https://github.com/fantasyland/fantasy-land/issues/92
  [pe]: https://github.com/ramda/ramda/issues/1367

**Comment by branneman** [comment]
> I agree that individual functions should be documented as delegating to a named method.
> I just don't think they should be specifically documented as delegating to the Fantasy-land specification.

Well said good sir.

However, I think it's also a good idea to mention **Ramda currently is fully compatible with Fantasy Land** on the homepage/readme, I think this is definitely a selling point. There could be more of those 'compatible with'-statements in the future if necessary.

**Comment by buzzdecafe** [comment]
>  I just don't think they should be specifically documented as delegating to the Fantasy-land specification. I feel that's too limiting.

iOn the contrary: dispatching promiscuously to any function is *way* too broad. i'd favor FL and not arbitrary functions that happen to have the correct name. that's why i'd like to see FL namespace their methods, so that we can dispatch with confidence that the supplied object is going to behave in a well-defined way.

**Comment by CrossEye** [comment]
> I think it's also a good idea to mention **Ramda currently is fully compatible with Fantasy Land** on the homepage/readme, I think this is definitely a selling point. 

This is a good idea, but it'll be interesting to see how to phrase it, since Ramda itself (ignoring Ramda-fantasy) does not precisely implement _any_ of the Fantasy-land data types, so it came claim compatibility in the usual manner.<sup>1</sup>  What it really does is offer a functional programming gloss on the OO APIs specified by Fantasy-land.

I think this is a _good_ thing, and I don't want to change it.  But it's difficult to capture succinctly and not make it sound like either a narrow technicality or an attempt to one-up Fantasy-land, both of which I'd like to avoid.

----------
<sup>1</sup>In some sense we do implement a set of functions that operate on lists in a manner very close to compatible with Fantasy-land, but since we're providing pure _functions_ and not the specified _methods_, we cannot claim conformance in any literal sense.

**Comment by CrossEye** [comment]
>>  I just don't think they should be specifically documented as delegating to the Fantasy-land specification. I feel that's too limiting.

> On the contrary: dispatching promiscuously to any function is *way* too broad. i'd favor FL and not arbitrary functions that happen to have the correct name

While I have some sympathy for this view, I'd rather stick with the idea that this is a library for grown-ups.  If you don't know what you're doing, we're not going to try to hold your hand.  If you supply us with an object with a `map` method, we'll call it.

I'd rather not be doing this only on Fantasy-land methods of `equals`, `concat`, `empty`, `map`, `ap`, `of``, `reduce`, `sequence`, `chain`, `extend, and `extract`.  I think it's quite reasonable that a user would want our `toString` to delegate to her object's `toString` method, that her data structure would have its own version of `filter` for us to call, or that she would override `equals` for reasons entirely unrelated to Fantasy-land.

I agree that there is a special place for Fantasy-land.  I would love it if [issue #92][i9] were accepted, especially with a more generic set of names such as `@@alg-types/map`.  I would love to be able to implement those unambiguously.  But that wouldn't satisfy my hunger for integration.

  [i9]: https://github.com/fantasyland/fantasy-land/issues/92

**Comment by buzzdecafe** [comment]
i totally disagree. if you want to execute arbitrary, ill-defined functions on your objects that's fine, but we shouldn't be in the business of supporting that inside the lib. We have `invoker` for that.  I would *much* rather restrict the scope of dispatch.

**Comment by raine** [comment]
If it's possible to do things like below because `R.filter` dispatches, then I feel the mechanic should be *in some way* communicated in its documentation.

```js
> R.filter(R.equals(1), S.Maybe.of(0))
Nothing {}
> R.filter(R.equals(0), S.Maybe.of(0))
Just { value: 0 }
```

**Comment by CrossEye** [comment]
> If it's possible to do things like below because R.filter dispatches, then I feel the mechanic should be in some way communicated in its documentation. [... code elided ... ]

Agreed.  We need to document this.

But I think there's now a much larger point about whether we should be delegating such things as `filter` at all.  This has definitely come up before.  Perhaps now's the time to settle it.

**Comment by paldepind** [comment]
> i totally disagree. if you want to execute arbitrary, ill-defined functions on your objects that's fine, but we shouldn't be in the business of supporting that inside the lib. We have invoker for that. I would much rather restrict the scope of dispatch. 

I very much agree with this. We have touched this subject several times before. IMO we should remove dispatching in all cases except for to fantasy land (and hopefully future versions of fantasy land will make this dispatching safer). Adding ad hoc arbitrary dispatching, crossing ones fingers and hoping it turns out to be something useful is not going to work. That is not how you recognize or implement useful abstractions.

Our current dispatching functions could do anything. For instance delegate to impure methods. A call to `R.filter` could fire the missiles. All bets are of. We have no guarantees. Horrible code that is impossible to understand can be written.

This implicit duck typing is trying to emulate something like Java's interfaces or Haskell's type classes. I think it has valid use cases. But even in Haskell where type classes offers much stronger guarantees it is recognised that overusing type classes results in hard to understand code. I read [a quite nice comment on Reddit](https://www.reddit.com/r/haskell/comments/3mhbuq/so_i_was_working_on_putting_some_math_im_learning/cvezu3w) about this a few days ago:

> Typeclasses ended up turning out to be a bad idea in most cases because they made code a lot less maintainable and harder to reason about [...] It turns out that there are actually only a couple uses of typeclasses where people have agreed that the benefit outweighs the massive, massive headache and loss in maintainability...the main one is when your typeclass has laws that lets you reason about code in a polymorphic way that lets you write safer code.

I think the above observation translates quite nicely to our dispatching system.

**Comment by CrossEye** [comment]
>  IMO we should remove dispatching in all cases except for to fantasy land.

I don't see any particular reason to give a privileged place to Fantasy-land.  I think it's a reasonable spec, but far from an ideal one.  And it is certainly not the last word in useful abstractions.  We have chosen some of our functions names in order to match this spec, and that seems reasonable to me, but I wouldn't let that specification drive us much further.

> Adding ad hoc arbitrary dispatching, crossing ones fingers and hoping it turns out to be something useful is not going to work. That is not how you recognize or implement useful abstractions.

Why do you think it's Ramda's job to recognize these abstractions?  Our users know infinitely more about their data than we do.  They know the proper abstractions and when those abstractions harmonize well with one of our function names.  I really think `filter` is a great example.  It's not specified by FL, but it has a clear and obvious meaning, and there is an obvious way to extend the notion to various other structures.

As @buzzdecafe points out, there is an alternative in `invoker`.  But I simply find this API a better user experience:

```js
const oddTree = filter(odd, tree);
```

than either of these:

```js
const oddTree = invoker(2, 'filter')(odd, tree);
```

or

```js
const filterTree = invoker(2, 'filter');
// ...
var oddTree = filterTree(odd, tree);
```

**But**, if we decide that Ramda should insist that users do the latter, and forgo the delegation, why in the world would we make exceptions for these eleven functions: `equals`, `concat`, `empty`, `map`, `ap`, `of`, `reduce`, `sequence`, `chain`, `extend` , and `extract`?

If Fantasy-land adds `bimap` and `fork` next week, do we scramble to add them?  If they add `filter` in a way that doesn't match our list filter, do we simply drop our long-standing function?  If [issue #92][i92] is accepted, do we drop all these functions and delegate only to `@@alg-types/map` _et. al._?  What if TC39 finally recognizes FP and creates its own algebraic data types spec but it doesn't align precisely with Fantasy-land?  Are we expecting to have to choose?  I would rather do our best to integrate with as many useful libraries as we can.

I don't have a particular antipathy towards Fantasy-land, but for me our dispatching started elsewhere (our now-gone lazy list extension), and was aimed elsewhere.  (My first thought was that we could handle streams much the same way we do lists, something similar to what Highland eventually did; but even then I thought it had broader implications.)  Fantasy-land was to me simply the most obvious demonstration of the possibilities of delegation.


> Our current dispatching functions could do anything. For instance delegate to impure methods. A call to `R.filter` could fire the missiles. All bets are of. We have no guarantees. Horrible code that is impossible to understand can be written.

If that's our concern, then we'd better stop calling user functions.  No more `map`, `filter`, `reduce`.  Honestly, no more reason for Ramda, as far as I'm concerned.  Our goal should never be to make it impossible to do bad things.  Our goal should be to make it simple to do good things.  Along with that might come the possibility of doing bad things, but we can't prevent that, and we shouldn't worry about it.

```js
// Ooh, this is dangerous! Better deprecate `map`
R.map(R.pipe(fs.readFileSync, 
             R.take(8), 
             R.when(R.eq(window.secretCode), launchMissiles)), 
      files); 
```



  [i92]: https://github.com/fantasyland/fantasy-land/issues/92

**Comment by paldepind** [comment]
> I don't see any particular reason to give a privileged place to Fantasy-land.

I'm not suggesting we give it a privileged place. We can support it along with all other well defined interfaces with laws about how they should behave. But to my knowledge there are no other such specifications for JS.

> Why do you think it's Ramda's job to recognize these abstractions?

I'm not saying that's Ramda's job.

> If that's our concern, then we'd better stop calling user functions. No more map, filter, reduce. 

I don't think you can compare dispatching with higher order functions.

**Comment by CrossEye** [comment]
> I'm not suggesting we give [Fantasy-land] a privileged place. We can support it along with all other well defined interfaces with laws about how they should behave. But to my knowledge there are no other such specifications for JS.

----------

> ### Countable
> 
> 1. `c.inc().dec()` is equivalent to `c` (redecrementability)
> 2. `c.dec().inc()` is equivalent to `c` (reincrementatbility)
> 
> #### `inc` method
> 
> A value which has a Countable must provide an `inc` method. The `inc`
> method takes no arguments:
> 
>     c.inc()
> 
> 1. `inc` must return a value of the same Countable.
> 
> #### `dec` method
> 
> A value which has a Countable must provide a `dec` method. The `dec`
method takes no arguments:
> 
>     c.dec()
> 
> 1. `dec` must return a value of the same Countable.

----------

Ok, I've fixed that for you.  There's a new spec in town, the Countable specification, It's been published, albeit in a minor issues list on a somewhat obscure project.  But it _has_ been published.  Its laws are clean and simple.  It's quite easy to see that this type-class is well-defined.

So should Ramda dispatch its `inc` / `dec` methods now?  What if I start a new project on GitHub for this spec, and that project gets 1000 stars?  Is that when we decide to dispatch on `inc` / `dec`?

>> Our current dispatching functions could do anything

**Comment by scott-christopher** [comment]
I agree that we shouldn't restrict dispatching solely to FL approved methods and it should either be open to discussion as to whether a function can apply generically to other data types, or remove dispatching altogether.

If we go down the path of the latter, it would be nice to offer a public `dispatch` (or other creatively named) function where the dispatching can be moved to a user-land decision.

**Comment by CrossEye** [comment]
> If we [remove dispatching altogether], it would be nice to offer a public dispatch (or other creatively named) function where the dispatching can be moved to a user-land decision.

There have been some discussions about how to do that, either in addition to or as a replacement for our current dispatch, in #1037 and #1367.  This is more palatable to me than restricting dispatch to Fantasy-land's small set of functions, but I think it would still be a disappointing retreat for Ramda.

**Comment by paldepind** [comment]
> And why would that be a bad thing? It's much of what I want to promote!

When users pass a function to `map` they've most often created the function specifically for that purpose. When users use Ramda's dispatching on third party libraries the library method was not created for that purpose. The third party library creator maybe didn't have a problem with a mutating `filter` method. But now a Ramda user has lot's of mutating `R.filter` invocations in his code and he finds it very hard to know for certain which is which.

That also answers this question:

> How in the world does the former make it any less likely that the function supplied will launch the missiles?

But prefixing the method names in Fantasy Fand and the Countable specification would make it much safer.

> If we go down the path of the latter, it would be nice to offer a public dispatch (or other creatively named) function where the dispatching can be moved to a user-land decision.

I think that is a great idea.

**Comment by CrossEye** [comment]
@paldepind:

I'm clearly misunderstanding something here.  I don't make much sense out of this:

> When users pass a function to `map` they've most often created the function specifically for that purpose. When users use Ramda's dispatching on third party libraries the library method was not created for that purpose. 

I would expect the user to use exactly the same care on the functions passed in to these two.  The dispatching takes place on the data structure, not the function.  That data structure might be managed by the user or by a third-party, but the only difference I see between using `map` and `filter` is that we think `map` implies that the implementation of the data structure is attempting to follow the Fantasy-land laws -- laws which, by the way, do _not_ specify a lack of side effects -- and we don't think `filter` implies the same.  Of course unless and until Fantasy-land changes to more specific names, we can't even really know that; we have to count on our user to avoid using Ramda's `map` with a geographic `map` function.

I simply don't see that there is a significant distinction here.  In either case, it's up to the user to pass a reasonable function to filter, and a compliant data type.  If she's using a third-party data type, she will have to confirm for herself that its `map`/`filter` does the sort of thing she wants it to.  If it's her own data type, she has to build it that way.  And of course if it's a list, we handle that for her.

**Comment by branneman** [comment]
While I love the philosophical discussion, It's a fact that right now it is undocumented behaviour for some functions. I hope everyone can agree that it should be documented for the current version, whatever big change will be decided upon for future versions.

It's easy to update the documentation right now to at least mention the dispatching, as some other functions already do.

My proposal for a sentence that hopefully anyone can agree upon:
**Dispatches to an `X` method if present.**

Right now, this is what the description for the [`equals`](http://ramdajs.com/docs/#equals), [`and`](http://ramdajs.com/docs/#and) and [`or`](http://ramdajs.com/docs/#or) function say.

I could make a PR for this if that's preferable.

After this is done, I think the original discussion should continue! And whatever the outcome, I think that it should be explained under the *Philosophy* section on the homepage.

**Comment by raine** [comment]
Should it also mention the argument, like it currently does for `and`?

> Dispatches to the `and` method of the first argument if applicable.

**Comment by branneman** [comment]
> > Dispatches to the and method of the first argument if applicable.

> Should it also mention the argument, like it currently does for and?

Sure, more clarity!

**Comment by CrossEye** [comment]
Absolutely, and a PR would be welcome, although if you don't someone will get around to it eventually.  :smile:

**Comment by buzzdecafe** [comment]
superceded by #1428
