### ISSUE TITLE
add tests to assert that functions are compared by identity in R.indexOf

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1430]
See https://github.com/ramda/ramda/issues/1362#issuecomment-136008766

At the very least we should include assertions for the following:

```javascript
var f = function() {};
var g = function() {};

R.indexOf(f, [f]);  // => 0
R.indexOf(g, [f]);  // => -1
```

Would you like to work on this, @syves?

**Comment by syves** [comment]
Sure!

**Comment by syves** [comment]
Perhaps the docs could add ->  When target is a function `R.identical` is used to determine if the
 target is equal to an element in the array.

**Comment by davidchambers** [comment]
Good idea! Ideally we would have a section on the website explaining is meant by "value-based equality", and we could link to it wherever we use the phrase.

**Comment by syves** [comment]
is there testing for this on _indexOf ?

**Comment by davidchambers** [comment]
> is there testing for this on _indexOf ?

I'm not sure what you're asking, exactly. `_indexOf` uses [`R.equals`][1] internally, so the decision as to whether two values are equal is made by `R.equals`.

If you're asking whether we test `_indexOf` directly, the answer is no. We do test it indirectly, though, by testing `R.indexOf`.


[1]: http://ramdajs.com/docs/#equals

**Comment by syves** [comment]
you have answered my question. Do you generally test on both levels internal and API?

**Comment by CrossEye** [comment]
> Do you generally test on both levels internal and API?

I come down quite strongly on the only-test-the-API side of this perennial debate.

**Comment by syves** [comment]
@CrossEye why is that?

**Comment by CrossEye** [comment]
@syves: I could be my usual wordy self, but it boils down to the simple fact that the public API is what I'm committing to support.  If I start adding tests for internals, then I am no longer free to simply change my implementation.  I have to also work through questions of which broken tests have to be changed, which ones can be deleted, and which ones are actual issues.  None of that should matter, since if I have thorough tests on my public API, I can trivially verify if everything that I'm _supposed_ to be doing is still being done correctly.  That's what unit tests are for, IMHO.

**Comment by thefourtheye** [comment]
Can this be closed now, as we already have tests like this in `test/indexOf.js`?

**Comment by davidchambers** [comment]
You're quite right, @thefourtheye. :)
