### ISSUE TITLE
"No index in callbacks" - why?

### ISSUE THREAD

**Issue by Andrew-Webb** [ramda/ramda#1478]
So I note in the Manual that "uncommon features in Ramda" are:-
* parameter order
* mutation-free
* no index in callbacks

I totally get the first two. But why no index in callbacks?  Sometimes knowing the index is very useful, especially when you are specifying an array as the list to be operated upon.  Today I went looking for R.mapi - Ramda's equivalent of the F# standard library's List.mapi function, but didn't find it.  And since no index in callbacks is touted as a feature, it seems unlikely that R.mapi will ever be added.

But what is the thinking behind this?

**Comment by raine** [comment]
There's [`R.addIndex`](http://ramdajs.com/docs/#addIndex) for that.

**Comment by Andrew-Webb** [comment]
Thanks for that pointer!  Now I know.

**Comment by CrossEye** [comment]
And as to _why_, we think of many of these functions operating on more generic types than just the standard lists.

`map` is meant to work not only with lists, but also with anything adhering to the [FantasyLand Functor specification][fl] and to various other types, such as streams:

```js
map(square, [1, 2, 3, 4]); //=> [1, 4, 9, 16]
map(square, Just(7)); //=> Just(49)
map(square, Nothing); //=> Nothing
map(square, <stream: ...3...1.......2.....2....3............1...5...>)
//=> <stream: ...9...1.......4.....4....9............1...25...>)
```

For many such types, an _index_ parameter makes no sense.

Of less concern, but also important, is the recognition that it can leave to undesirable behavior:

```js
_.map(['1', '2', '3'], parseFloat); //=> [1, 2, 3]
_.map(['1', '2', '3'], parseInt); //=> [1, NaN, NaN] // WTF?
```

Because `parseInt` deals with a `radix` parameter as well as the value to convert, when a map function such as Underscore's or the native `Array.prototype` one, calls this, it causes this sort of problem.

```js
R.map(parseInt, ['1', '2', '3'], parseInt); //=> [1, 2, 3]
```

If you want to see an involved (and fairly argumentative) discussion about this, please see #452.

  [fl]: https://github.com/fantasyland/fantasy-land#functor

**Comment by Andrew-Webb** [comment]
Thanks Scott.

Yes indeed: `map` is meant to work not only with lists.  And this is the case with other `map`, `reduce`, etc. implementations (e.g. in .NET) where what you're iterating over may or may not be indexed.  Other libraries deal with this by having overloaded functions or separate functions (F#'s Seq.map vs Seq.mapi), but I do like your decision to have `R.addIndex`.  This seems cleaner and simpler - less to have to think about; fewer library functions and fewer parameters to document.  Now I just have to remember that it exists for the next time I need an index (which may be months away).

**Comment by Andrew-Webb** [comment]
Maybe a small documentation note for `R.map` might help steer newcomers to this feature?

"See `R.addIndex` for how to add an index (+ the whole list) to the callback function."

**Comment by CrossEye** [comment]
I'm not sure we want that much on each likely candidate.  But we could certainly add a `@see` tag to them.  That makes sense.  Feel like opening a PR?

**Comment by Andrew-Webb** [comment]
Ok, I'll identify the functions in question, and then work on a PR.

**Comment by CrossEye** [comment]
> Ok, I'll identify the functions in question, and then work on a PR.

Thanks!!
