### ISSUE TITLE
pipeP fails when first argument is function that does not return promise

### ISSUE THREAD

**Issue by bwestergard** [ramda/ramda#1528]
This seems like obviously pathological behavior. Tested on version 0.18.0.

```javascript
var R = require("ramda")
var Promise = require("bluebird")

var mulslow = R.curry(function (x, y) {
    return new Promise(function (resolve, reject) {
        resolve(x * y)
    })
})

R.pipeP(mulslow(3))(3).then(console.log) // works
R.pipeP(mulslow(3),R.multiply(3))(3).then(console.log) // works
R.pipeP(mulslow(3),R.multiply(3),mulslow(3))(3).then(console.log) // works
R.pipeP(R.multiply(3), mulslow(3))(3).then(console.log).catch(console.log) // does not work.
R.pipeP(R.multiply(3))(3).then(console.log).catch(console.log) // does not work.
```

**Comment by CrossEye** [comment]
I don't have time to look right now, but this might have got lost in the #1260, #1391 shuffle.

**Comment by bwestergard** [comment]
#1314 as well. I'm very worried about this.

**Comment by asaf-romano** [comment]
Yup, this is the same issue I reported in #1314. At the end, we introduced our own version of pipe to workaround this. Here's it:
```js
export function pipeP(first, ...rest)
{
    return R.pipeP(nAry(first.length,
                        (...args) => {
                            try
                            {
                                return Promise.resolve(first(...args));
                            }
                            catch(ex)
                            {
                                return Promise.reject(ex);
                            }
                        }),
                   ...rest);
}
```

**Comment by scott-christopher** [comment]
There are a few issues here:
* If we don't require the first function to return a valid Promise, there is a possibility that none of the functions given to `pipeP` will return a Promise, meaning that `pipeP` as a whole won't return a Promise which makes for inconsistent return types.
* We can avoid this by calling `Promise.resolve` on the output of the first function if it is missing a `then` method, however this then adds a dependency on a Promise implementation.
* We can work around this by hand-rolling our own minimal Promise implementation, but we're then hand-rolling our own Promise implementation.

This can however be avoided currently by users starting the `pipeP` composition with the appropriate function from the Promise implementation that lifts plain values into a Promise instance. This is only necessary if the first function would otherwise not return a Promise.

e.g. for ES6 Promises:
```js
R.pipeP(Promise.resolve, R.add(42), someOtherAsyncFn);
// or if the pipeline needs to accept multiple arguments
R.pipeP(R.compose(Promise.resolve, R.add), someOtherAsyncFn);
```

**Comment by bwestergard** [comment]
Agreed @scott-christopher.

Am I correct in thinking all of the examples in my original post once worked? If so, which of the options laid out by Scott did the implementers go with at that time?

**Comment by asaf-romano** [comment]
@scott-christopher  It's worse than that, in practice, because the stupid spec doesn't require ``Promise.resolve`` to be "static", i.e. only ``Promise.resolve.bind(Promise)`` is guaranteed to work (this is an issue at least in Node v4, try ``var f = Promise.resolve; f(3)``). So one needs a lamda, or an invoker, and if this turns out to be a common pattern in your code as it's for me, you end up with your own pipeP wrapper.

**Comment by bwestergard** [comment]
@asaf-romano Yikes. I think I may package a version of your solution above that exports this function with Bluebird as a dependency. Unless, of course, you're so kind as to beat me to the punch.

I'm undecided as to the best way forward for Ramda itself. If we're comitted to the promise aware functions - as I think we should be, as it's one of the major attractions of the library - it seems that either a Promise implementation has to become a dependency of the library or it has to take such an implementation as an optional parameter. Something like:

```
var Promise = require('bluebird');
var R = require('ramda')({'promise':Promise});
// composeP, promiseP now work with non-promise-returning functions in any position
```

More radically, those functions could be factored out into a distinct library that depends on Ramda, to isolate the Promise concerns.

**Comment by CrossEye** [comment]
@bwestergard:
> Am I correct in thinking all of the examples in my original post once worked? If so, which of the options laid out by Scott did the implementers go with at that time?

The inconsistent return type.  I'm not sure this was thought through as such.  The assumption was certainly that people would use it with _some_ promises in the list.

I do think, though, that this might be the best choice.  We should not be in the business of supplying (or even conforming with) particular Promise implementations.  I for one have stopped using Promises altogether in my personal work, replacing them entirely with `Future` / `Task` implementations.  And I really don't think Ramda should be getting into that business.

**Comment by bwestergard** [comment]
@CrossEye That does seem like the best option. Could we just revert to the previous implementation?

**Comment by CrossEye** [comment]
While it won't be hard to revert, that commit changed a number of different `compose`-like functions.  Some other of the changes have already been either reverted or rewritten in a manner similar to the original, and there had originally been some shared infrastructure for them.  Perhaps that needs to be reinstated, or perhaps this can be rewritten without the internal `_createComposer` function.

Do you feel like taking a stab at it?

**Comment by bwestergard** [comment]
Yes, but I won't have much time until next weekend. Could you point me to the last known version with which the above would work?

**Comment by scott-christopher** [comment]
@bwestergard I believe v0.15.1 was one of the last that worked that way. You can look at https://github.com/ramda/ramda/blob/v0.15.1/src/internal/_composeP.js for how it was implemented. In earlier versions, `pipeP` just reversed the arguments before deferring to `composeP`.

**Comment by bwestergard** [comment]
:+1:

**Comment by CrossEye** [comment]
And you can specifically see #1260 for the commit that changed this.

**Comment by davidchambers** [comment]
Having spent considerable time pondering JavaScript's [async problem][1], I can no longer recommend promises. Reasons:

  - creating a Promise for an effectful operation *triggers* the effectful operation;
  - promises promote the use of exceptions;
  - like jQuery's `map` function, `Promise#then` complects `map` and `chain`; and
  - because implementors are not guided by laws, implementations are not necessarily interoperable.

> More radically, those functions could be factored out into a distinct library that depends on Ramda, to isolate the Promise concerns.

This is a wonderful idea. I'd love to see the Promise-related functions removed from Ramda.


[1]: https://github.com/plaid/async-problem

**Comment by CrossEye** [comment]
> * because implementors are not guided by laws, implementations are not necessarily interoperable.

And more than that, because they're not guided by laws, one cannot use law-abiding tools to work with them.  That's my main reason for moving away from them.

However, I don't see the two public functions in Ramda `composeP` / `pipeP` as painful.  I would like to this issue fixed.  But I would be very, very cautious about creating additional Ramda functions that worked with Promises.

**Comment by Zerim** [comment]
Hey guys, just came across this thread and wanted to see if there were any updates on this issue. Looking for a good solution for composing functions that may (optionally) return a Promise. Does Ramda's implementation still break if the first function does not not return a Promise?

I came across [this implementation](https://github.com/rikukissa/compose-async/blob/master/index.js) on npm that seemed simple and elegant, but has almost no stars/ downloads. Could someone comment on the validity of this approach and whether it would work for Ramda's composeP? Thanks!

**Comment by davidchambers** [comment]
That function seems reasonable to me, @Zerim.

I think I've almost convinced @CrossEye that we should deprecate our Promise-specific functions, so I don't expect `R.composeP` to be "fixed".

**Comment by Zerim** [comment]
I see, good to know. Thanks for the quick reply and input on the other approach @davidchambers

**Comment by CrossEye** [comment]
> I think I've almost convinced @CrossEye that we should deprecate our Promise-specific functions, so I don't expect `R.composeP` to be "fixed".

Was I ever hard to sell on that idea?  I'm really not a fan of Promises, although I do use them all the time in my day job.
