### ISSUE TITLE
juxt reports wrong arity

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1569]
```js
R.juxt([R.prop("a"), R.path(["a", "b"])]).length; // => 0
```

**Comment by CrossEye** [comment]
What's the suggested value?  `max(pluck('length', fns)` ?  `min(pluck('length', fns)`?

**Comment by asaf-romano** [comment]
``converge`` does max and I'm very happy with that (In fact, this bug was quite a bummer for us as we got used to ``juxt`` practically overnight, so we we went ahead and re-implemented it as ``converge(Array.of)``.

**Comment by CrossEye** [comment]
Yes, I think `max` makes sense here.  I'm less certain about `cond` though.

**Comment by asaf-romano** [comment]
Btw, I think a good fix here would be to implement ``juxt`` in terms of ``coverge``. Since we cannot rely on ``Array.of`` I guess this will do:

```js
var juxt = R.converge(function() { return Array.prototype.slice.call(arguments); })
```
Assuming arrays were implemented in ES3 ;)

One question though: Is it intended that the function returned by ``juxt`` isn't curried? Because ``converge`` does curry, and the suggested implementation would do so as well.

**Comment by asaf-romano** [comment]
@samueller 

Hey Scott, I'm working on a fix for this issue. My initial fix was a re-imlementation of just as (roughly, see above) ``converge(Array.of)``. This works fine except for juxt([]), which breaks two tests you've added:
1) juxt works with no functions and no values
2) juxt works with no functions and some values

@CrossEye and I were wondering if there's some reason in particular for supporting this use case.

**Comment by samueller** [comment]
@asaf-romano `converge(Array.of)` sounds perfect. I guess you can't use `Array.of` because it's too new of a function, that's unfortunate. Your `Array.prototype.slice.call(arguments)` workaround seems good though.

I didn't have a specific reason in mind for supporting the situation where `juxt` is passed an empty array of functions. It was a corner case I just wanted to make sure was handled in some reasonable fashion. `converge(Array.of)` gives an unintuitive error when passed an empty array.

**Comment by CrossEye** [comment]
Thanks, everyone.  This was already a nice little function, and it just got better!

**Comment by asaf-romano** [comment]
@samueller Thanks for the reply. Regarding the empty-case exception: It's a bug in ``converge``, and I fixed it in my PR.
