### ISSUE TITLE
cond reports wrong arity

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1570]
```js
R.cond([[R.propEq("a", "b")]]).length; // 0
```

**Comment by CrossEye** [comment]
I'm not sure there's a good fix for this.  Commonly, even in the documentation for this, one of the functions passed is the 0-arity `R.T`.  Would we report the arity as the maximum arity of the predicates supplied?  While I suppose that's possible, it's not at all clear to me that it's desirable.

**Comment by asaf-romano** [comment]
As I said in the other issue, ``converge`` does Math.max and I think that works quite well. The problem with returning 0-arity functions is that it breaks composition in very unexpected ways (It's only because I fixed ``memoize`` to retain arity in 0.18 that I could figure those two bugs in less than an hour yesterday...).

**Comment by CrossEye** [comment]
As I said, it may be the best we can do, but while if feels right for `juxt`, it feels somehow off for `cond`, in part because the main usage will often include `R.T`.  I suppose that's not a problem, but it still feels slightly odd.  Still I'd be happy to see PRs for each of these along this line.  We can discuss them as a group.  They shouldn't be hard to write.

**Comment by asaf-romano** [comment]
Yes, I see your point, but I think it's by far the lesser of two evils.

**Comment by asaf-romano** [comment]
I'll post a PR (for both issues) this weekend.
