### ISSUE TITLE
Inconsistency between assoc and merge

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#1582]
Starting with usecase... I need to remove trailing hash from URL (for scraping). 
Node `url` module is able to parse and format urls but gives no way to immutably nullify hash. 
Let's assume I need parsed URL down the code so I won't use regexes.

---

Let's try `R.assoc`

``` js
import Url from "url";

let url = "https://github.com/somepage#trash"
R.assoc("url", null, Url.parse(url)).format();
// => https://github.com/somepage
```

**It works** because `assoc` copies all props including functions.
`.format` method was copied to new object.

``` js
// === assoc source code ===
for (var p in obj) {
  result[p] = obj[p];
}
// === === === === === ===
```

---

Let's try `R.merge`

``` js
import Url from "url";

let url = "http://github.com/somepage#trash";
R.merge(Url.parse(url), {url: null}).format();
// => **format is not a function**
```

**It does not work** because `merge` copies only `enumerable` props omitting functions.
`.format` method was not copied to new object.

``` js
// === merge source code ===
var result = {};
var ks = keys(a); // a is original obj
// === === === === === ===
```

---

I think we should apply same politics to both functions and they should give equal results in this case.
Other Ramda functions may also be affected.

But I'm not sure which behavior is "correct" and which one should be "fixed". 
In this case `assoc` turned out to be more useful as `merge` failed to patch Object-Oriented code. 
But we surely need to account more use cases.

**Comment by CrossEye** [comment]
> I think we should apply same politics to both functions and they should give equal results in this case.
Other Ramda functions may also be affected.

Why do you think these should act the same?  I see no strong arguments either for or against this.  If I were to choose, I'd rather stick with the properties delineated by `keys`, although that would not work for your case.  But I'm not sure I see any great reason yet to make the choice.

**Comment by asaf-romano** [comment]
Note that in your case the reason ``format`` is not copied over isn't because it's set as non-enumerable, but rather because it's part of the object prototype, rather than the object itself:

```js
Object.keys(Object.getPrototypeOf(require("url").parse("http://a.tld"))); // [ 'parse', 'format', 'resolve', 'resolveObject', 'parseHost' ]
```

node's ``url`` is a "class-like" object, and it's probably OK for Ramda not to define the behavior for such objects at all. However, in prototypical inheritance model, it's somewhat valid to have "records" which inherit from some prototype. While there's no reasonable way for ramda to distinguish between the two models, since we're in JS land, it'd be nice to support prototypical inheritance when it makes sense; sometimes it'll also "just work" in for class-like objects, but they should be treated the same way sparse arrays are, imho.

``merge`` is a good example. Today it simply ignores the prototype chain of its input - both for the lookup (by looking just at the first-level properties) and for the object construction (by simply constructing ``{}``).  What it could do, instead, is to create the new object from the prototype of the first ("left") object (that's doable with ``Object.create`` and ``Object.getPrototypeOf``). For pure FP programmers this won't matter at all, because their object always inherit from ``Object.prototype`` (or from ``null``). For other JS programmers, it's a nice touch.

**Comment by CrossEye** [comment]
@asaf-romano:

How would you deal with non-enumerable properties on the prototype chain?

**Comment by asaf-romano** [comment]
In my proposal one doesn't deal with the proptotype chain, as the new object simply just inherits the same prototype. As for non-enumerable properties of the "leaf" (i.e. non-enumerable own-keys), I'd leave them out.

**Comment by CrossEye** [comment]
The new object inherits the prototype of _which_ object?  `merge` takes two objects.

**Comment by CrossEye** [comment]
Sorry, rereading, I see you would use the first one.  But then you lose any prototype properties of the second one if they have different prototypes.

I think this just gets nasty.  It certainly is possible, but definitely ugly.

**Comment by asaf-romano** [comment]
It isn't pretty indeed, but it's the decent thing to do ;) Although not officially supported, it'll make functions like ``clone`` and ``merge`` useful in many case they're not today.

**Comment by CrossEye** [comment]
I'm certainly willing to entertain a PR on this.  Do you have ideas for the situation when the two objects have different prototypes, especially if the prototype of the second has the prototype of the first in as its own prototype, which seems reasonably possible...

**Comment by ivan-kleshnin** [comment]
> Note that in your case the reason format is not copied over isn't because it's set as non-enumerable, but rather because it's part of the object prototype, rather than the object itself

Right, thank you for correction. 

> For pure FP programmers this won't matter at all, because their object always inherit from 
> Object.prototype (or from null). For other JS programmers, it's a nice touch.

I'm afraid all JS programmers have to deal with non-pure, non-FP APIs alot.
Ability to modify objects with prototypes in immutable ways would be superb.

**Comment by asaf-romano** [comment]
I think the left (first) should always dictate the prototype. The second argument should always be treated as a dictionary. In other words, this is an immutable version of Object.assign. This will make sense esp. if assoc, assocPath, dissoc, etc. are changed to work this way too.

**Comment by asaf-romano** [comment]
I'll try to do some sort of PR on this in the near future, if no one else jumps in.
