### ISSUE TITLE
Optimize R.interesction to lookup the smaller list

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1595]
http://bit.ly/1RJVPp4

**Comment by buzzdecafe** [comment]
looks like a good idea

**Comment by asaf-romano** [comment]
One problem I see is callers relying on the order.

**Comment by buzzdecafe** [comment]
`intersection` seems to me to be a set operation, so ordering should not matter. let 'em sort if order is important. I don't think we should pick an order.

**Comment by jdalton** [comment]
I think it's less picking an ordering more preserving it. See this [haskell example](http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-List.html#v:intersect).
```
[1,2,2,3,4] `intersect` [6,4,4,2] == [2,2,4]
```
The results are `[2,2,4]` because that's the order they appear in the first array.
If it was using the shortest array first internally it would produce `[4,4,2]`

**Comment by jdalton** [comment]
It bleeds into other things like `R.union`:
```js
R.union([1,2,3], [4,5]); // [1,2,3,4,5]
R.union([4,5], [1,2,3]); // [4, 5, 1, 2, 3]
```
and `R.uniq`
```js
R.uniq([1,3,1,2,3,2]) // [1, 3, 2]
```

**Comment by jdalton** [comment]
First list priority is established with `R.difference` and `R.symmetricDifference` too
```js
R.symmetricDifference([1,2,3,4], [7,6,5,4,3]); //=> [1,2,7,6,5]
R.symmetricDifference([7,6,5,4,3], [1,2,3,4]); //=> [7,6,5,1,2]
```

**Comment by CrossEye** [comment]
I think #1638 may remove many of these issues.

**Comment by buzzdecafe** [comment]
> I think #1638 may remove many of these issues.

I don't think so. At present, we treat `intersection` etc. as Set operations (i.e. no dupes). But it's not clear to me if that should still be the case for lists if we have a Set type. If we treat lists like bags, then we'll need to define consistent behaviors, as suggested by @jdalton above. That's beyond the scope of #1638 IMO.

**Comment by jdalton** [comment]
FWIW we tried this kind of optimization in Lodash but reverted it because folks complained. The bang wasn't worth the cost as it only really mattered for arrays of significant size difference which was something we couldn't predict and the inconsistency wasn't worth it. Instead we went for optimizations that didn't effect expected or behavior consistent with the rest of the methods.

**Comment by CrossEye** [comment]
@buzzdecafe: I'd forgotten that we already had done that.  I'm quite happy with the Set-like interface for lists for these operations.  I don't see any real advantage in pursuing Bags for these.

@jdalton: What inconsistency did you introduce?  Ramda already is different from the Haskell example above:

    intersection([1,2,2,3,4], [6,4,4,2]); //=> [4, 2]

I don't right now have a significant concern about whether that should be `[2, 4]` instead.  Do you think I should?

**Comment by jdalton** [comment]
> Ramda already is different from the Haskell example above:

Uniqing the results aside it shows order of first array is preserved. 

> What inconsistency did you introduce? ... Do you think I should?

The same same issue I outlined above for Ramdas other APIs. It made `_.intersection` the only one to not use the order of the first array or subsequent arrays (as methods like union). Added that it only kicked in when the second array was shorter was a point of confusion and a gotcha for users.

**Comment by jdalton** [comment]
Which is why it was reverted.

**Comment by asaf-romano** [comment]
We're in a problematic situation here because it's hard to keep value-equality semantics without introducing such optimizations. When the difference between the list is large enough, the performance improvement is quite impressive.

Having said that, my intuition that this should not be a problem for consumers may be very wrong, and if many lodash users complained we should consider reverting the optimization.

**Comment by CrossEye** [comment]
@jdalton: Do you have lodash discussion thread numbers?

**Comment by jdalton** [comment]
I'll see if I can find them. The gist is that though the win is big when the size difference is significant its not otherwise. The root issue is large lists are slow, so that's where we focused our attn to get more generic wins without introducing inconsistencies.

**Comment by jdalton** [comment]
Here's @davidchambers thoughts on a similar change in Underscore https://github.com/jashkenas/underscore/pull/1511#issuecomment-37154114.

**Comment by CrossEye** [comment]
@jdalton, Thanks.  I read through  the  issues.  I'll take a look at the code in question when I'm in front of a computer again.  It's still unclear to me whether this is of interest to Ramda or not, but thanks for bringing it to our attention.

**Comment by jdalton** [comment]
It's as if Dave's replying to @buzzdecafe.
> > order of elements in a set is not important and we must not relay on order of elements
>
You're absolutely correct that the order of elements in a set is not important. Unfortunately, we're not returning a set, we're returning an ordered list. If _.intersection is called twice with the same arguments, it should return the same value in both cases. Thus, there must be rule for determining the order of elements. The current rule is relatively straightforward:
>
    Elements in the resulting list appear in the same order
    as they (first) appear in the first of the given lists.
>
If this pull request is accepted, the rule will be more complex:
>
    Elements in the resulting list appear in the same order
    as they (first) appear in (the first of) the shortest of
    the given lists.
>
The problem is that changing the ordering rule is a breaking change. One can argue — perhaps rightly — that code should never have relied on the current ordering rule, but there must surely be code in the wild which does (in much the same way that many JavaScript projects rely on for–in enumeration order).
