### ISSUE TITLE
converge with curried fns

### ISSUE THREAD

**Issue by miwillhite** [ramda/ramda#1613]
This may be expected behavior, but I want to bring it up anyway. Given the following:

```javascript
var list = [
  { id: 1, val: 'a' },
  { id: 2, val: 'b' },
  { id: 3, val: 'a' } // NOTE: The same 'val' as the first entry
]

// Suppose we want to find something in the list by referencing its id
var getA = R.curry((id, list) => {
  return R.compose(
    R.prop('val'),
    R.find(R.pipe(R.prop('id'), R.equals(id)))
  )(list);
});

// Then later we want to look at that same list and get all occurrences
// of entries with the same value that we found with getA (get B of A)
var getBA = R.curry((list, rA) => {
  return R.filter(R.pipe(R.prop('val')), R.equals(rA))(list);
});

// We load up getA with the term to search on
// And getBA gets loaded up with the list
//
// getBA(list, getA(1, list))
R.converge(R.call, [getBA, getA(1)])(list);

```

I had expected (before looking at the source) that this would return:
```
[{"id": 1, "val": "a"}, {"id": 3, "val": "a"}]
```

But instead I get:

```javascript
function (a0) {
  return fn.apply(this, arguments);
}
```

I understand now that `converge` gets the arity of the "largest" function and uses that to determine its own arity.

_**Is this expected/desired behavior?**_

See this Ramda REPL with the flawed code, and the commented out solution (uncurried): http://goo.gl/GaeIi9

**Comment by benperez** [comment]
**I think the case where you pass unary functions as transformers to converge is the easiest to understand.**
The function you get back from converge will take 1 argument, pass it to each of the transforming functions, and then pass the results of each transformation to the final function.

The original formulation is redundant, since the whole point of `R.converge` is to call the final function at the end of the day:
```javascript
R.converge(R.call, [getBA, getA(1)])(list)
```
If your goal is this:
```javascript
getBA(list, getA(1, list))
```
 then it can be expressed a little more simply as:
```javascript
R.converge(getBA, [R.identity, getA(1)])(list)
```

P.S. your example has a typo, I think you meant close the pipe in `getBA`after `R.eqauls(rA)`.

**Comment by miwillhite** [comment]
@benperez Thanks for your insight. And you are right…I did have a typo!!

As a side note, regarding issue #1447…this new form lends itself to `lift`, so `converge` is not necessary.
