### ISSUE TITLE
allUniq O(n^2) running time

### ISSUE THREAD

**Issue by Bpless** [ramda/ramda#1622]
As currently implemented, allUniq appears to run in O(n^2) time.  For each element in the list, we look ahead to all "next" elements and call _indexOf (which is a linear operation).

Here is an alternative implementation that runs in linear time by building up a hash.  Not entirely sure if the semantics here match the current implementation.  Would prefer to use a set type, rather than a hash.

```javascript 
function allUnique(list) {
  hash = {};
  for (var idx=0; idx < list.length; idx++) {
  	var el = list[idx];
    if (hash[el] != null) {
    	return false;
    } else {
    	hash[el] = true;
    }
  }
  return true;
}
```

**Comment by davidchambers** [comment]
We can use `R.toString` for many values, but not for functions (and a few other types). We could fall back to identity comparison in such cases.

**Comment by albrow** [comment]
There's at least one issue with this approach. `R.allUniq` uses `R.equals`, which considers `undefined` and `"undefined"` to be different values, which seems like the correct behavior to me. However, if you store these values in a hash that is not the case and `undefined` is considered the same as the key `"undefined"`. I believe the same is true for `null` and `"null"`.

See http://goo.gl/1PznQI.

**Comment by davidchambers** [comment]
I believe @Bpless is suggesting applying `R.toString` (or a similar hashing function) to each value (though he neglected to mention it).

**Comment by Bpless** [comment]
@albrow.  This doesn't seem to be a problem with the Set type (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).  

Fortunately, uniqBy appears to implement a set based solution, similar to what I proposed, in the event that Set is defined.  We can probably just invoke that function and compare the length of the original collection to the unique set.

**Comment by davidchambers** [comment]
> We can probably just invoke [`R.uniqBy`] and compare the length of the original collection against that resulting unique set.

:thumbsup:

**Comment by Bpless** [comment]
Upon further inspection, it appears as though R.uniqBy is similarly to be O(n^2) in the number of objects in the collection.  The set optimizations largely apply to scalar types.

**Comment by benperez** [comment]
Haskell's `List` and `Set` API's use comparisons (`Ord`) instead of hashing to implement this kind of functionality. I wonder if that would be an option here.

**Comment by CrossEye** [comment]
> Haskell's `List` and `Set` API's use comparisons (`Ord`) instead of hashing to implement this kind of functionality. I wonder if that would be an option here.

I'd be curious to hear more.  I have no clue how we'd try to apply `Ord` to the wild west of arbitrary JS types.  Do you have any ideas?

**Comment by benperez** [comment]
I did a little more research last night about the state of these functions in Haskell. The equivalent function to `uniq` in Haskell is [`nub`][^1], which only has the `Eq` class constraint. Since it only relies on an equality comparison, it is necessarily O(n^2).

For ramda's `allUniq` function, I think the current interface and implementation makes sense, since it's reasonable to *only* require a type that can be compared using `equals` when determining uniqueness.

To achieve something more performant, you're going to have to place additional requirements on the data that are passed into these functions. To me, that's the key issue that needs to be addressed. Whether it's some concept of `hashable` or `Ord` is secondary.

Having said that, I went ahead and had a look at Haskell's [`Data.Set`][^2]. Since hash-maps require mutable arrays to be efficient, they aren't a good fit for [Haskell][^3]. `Data.Set` instead uses balanced binary trees and has O(nlogn) complexity for insert and membership operations. `Ord` is required of your datatype to use `Data.Set`.

In JS we can use mutable state and hash-maps so it probably doesn't make sense to try and build something using `Ord`. 

[^1]: http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-List.html#v:nub
[^2]: http://hackage.haskell.org/package/containers-0.5.3.1/docs/Data-Set.html
[^3]: http://stackoverflow.com/a/18908851

**Comment by CrossEye** [comment]
@benperez: That all makes sense.  I don't think we could reasonably use `Ord`.

But using `R.toString` as a hash key might be worth the obvious cost for large enough data sets.  I haven't done the comparison to see where the lines would cross in the various implementations, though, and it might be pretty high, as there's a lot going on in `toString`.  And clearly it would not cover 100% of JS types, but I think we might be able to live with the caveats.  Most of the exceptions are ones we really can't deal with reasonably in any technique.

**Comment by benperez** [comment]
It really seems like they should be 2 separate functions.

What currently exists relies solely on `R.equals`:
```haskell
allUniq :: (Eq a) -> [a] -> Boolean
```

What's proposed using a hash-table (Show here means "has a toString"):
```haskell
allUniq' :: (Show a) -> [a] -> Boolean
```

The more I think about it, the more this function seems like it might better off being cookbook material. `R.uniq` and `R.uniqBy` already correctly do the heavy lifting for this function.

If one really wanted to get the hash-table time complexity for uniqueness, they could just use `uniqueBy` with a function that returned [a type that can be inserted into a set](https://github.com/ramda/ramda/blob/dcd0390833c90db3e8acb46650456df3473ecb86/src/uniqBy.js#L52-L73) and compare the length of the resulting list with the length of the original list as @Bpless suggested.

**Comment by davidchambers** [comment]
> The more I think about it, the more this function seems like […] cookbook material.

I agree!

**Comment by buzzdecafe** [comment]
> >    The more I think about it, the more this function seems like […] cookbook material.

> I agree!

me too
:cookie: :book:
