### ISSUE TITLE
introduce R.Set

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1638]
The view I'm about to express will come as no surprise to those familiar with a certain other open-source project to which I contribute. __We are doing our users a disservice by restricting ourselves to JavaScript's built-in data types.__

I believe it's a mistake for Ramda to be divided into two libraries: `ramda` and `ramda-fantasy`. Ramda cannot define—or cannot "correctly" define—certain functions because it doesn't have access to the appropriate data type. The type of [`R.head`][1], for example, is `[a] -> a` rather than `[a] -> Maybe a`, making it unsafe (since `R.head([])` evaluates to `undefined`). Even if one depends on both `ramda` and `ramda-fantasy` one must still define one's own `head` function if type safety is a concern. This has been discussed elsewhere, but it's worth mentioning.

Another group of functions is negatively impacted by our reliance on built-in data types: set functions. There are two problems with using arrays to represent sets:

  - __Ordering.__ Sets are unordered, but using an array forces us to consider ordering. How should `R.intersection([1, 2, 3], [3, 2, 1])` evaluate, for example? Should we preserve the order of the first argument? If so, we break commutativity. Should we randomize the order (as Go does when enumerating unordered collections)? This would break referential transparency. The only reasonable option is to return a *sorted* array. We must then decide on a sort function. Incidental complexity results from the use of an unsuitable data type.

  - __Duplicates.__ If we use arrays to represent sets, what does `[1, 2, 2, 3]` represent? `{1, 2, 3}`, presumably. It's not clear to me whether `R.intersection([1, 2, 2, 3], [2, 2, 2])` should evaluate to `[2]` or `[2, 2]`. On the face of it, `[2, 2]` is the correct answer. Only by reading the documentation would one learn to see the expression through a lens, giving `R.intersection({1, 2, 3}, {2})` which is of course `{2}` (or `[2]` once transformed by the lens). We're forced to communicate *out of band* because we can't encode the uniqueness constraint in the data type.

If I've made a compelling case against the use of array as sets, the next thing to consider is whether JavaScript's [Set][2] is appropriate. Unfortunately, the answer is no. Ramda and Set disagree on what it means for two values to be equal. Ramda considers `{x: 1, y: 1}` and `{x: 1, y: 1}` equal; Set does not (unless identical). Set considers `0` and `-0` equal; Ramda does not.

We should define our own Set type. Several existing functions could be updated to take and/or return values of this type, and we'd provide functions for converting Array values to Set values and vice versa.

```haskell
Set          :: [Any] -> Set Any
fromSet      :: Set Any -> [Any]

intersection :: Set Any -> Set Any -> Set Any
union        :: Set Any -> Set Any -> Set Any

keys         :: Object -> Set String
toPairs      :: Object -> Set (Pair String Any)
```

I imagine this will be controversial. I look forward to the discussion. :)

[1]: http://ramdajs.com/docs/#head
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by buzzdecafe** [comment]
> using an array forces us to consider ordering. 

On the contrary; since this is a "set" operation, order is immaterial. I grant you that we can then pass that `Set` as a `List` to some other function where iteration order matters (e.g. `reduce`). That does seem problematic.

Your `intersection` example is interesting. Under this proposal would you not also need a `Bag` or `Multiset` type to support your example? A set `{2, 2, 2}` is impossible. Then you would have to have functions `Set -> Set -> Set`, `Bag -> Bag -> Bag`, and maybe `Set -> Bag -> Bag`, `Bag -> Bag -> Set`, etc.

This would also necessitate helpers for `Set -> List` anyways, since that is likely to be a very common use case. If that is so, then we need to decide upon an iteration order *anyways* and all we've done is add a layer of complexity, but for what?

I'm not certain where I stand on this proposal. I need more time to dwell on it, and see how others respond.

**Comment by CrossEye** [comment]
> I imagine this will be controversial. I look forward to the discussion. :)

Perhaps it's not as controversial as you expect.

I'm not sure that we would remove the implementation for lists, as, whether or not `union` and `difference` make a great deal of sense, something like `without` / `difference` is useful.

But the points @buzzdecafe makes are important.  I have an incomplete PR laying around I really need to get back to for this, though.  If we add a library-wide consistency about iteration order, then this would just fall out.

However, about this:

> I believe it's a mistake for Ramda to be divided into two libraries: `ramda` and `ramda-fantasy`.

I'm afraid I still don't agree.  I understand entirely that unsafe operations can be a problem.  But forcing users to `map`/`chain` over the result of every call just to avoid any unsafe operation is pushing too many people too far.  I feel that Ramda should be offering tools.  It should be opinionated, but it should not be opinionated to the point that it's unusable for people not accustomed to FP.  In other words, it should offer a gradual path in.  The first hit's free, kid.

**Comment by davidchambers** [comment]
> Under this proposal would you not also need a `Bag` or `Multiset` type to support your example? A set `{2, 2, 2}` is impossible.

I assume you're referring to `R.intersection([1, 2, 2, 3], [2, 2, 2])`. This would become `R.intersection(R.Set([1, 2, 2, 3]), R.Set([2, 2, 2]))` which gives `{2}`. I'm not suggesting we provide a function for determining the intersection of two multisets. An existing function that would benefit from a Multiset type, though, is [`R.values`][1].

> This would also necessitate helpers for `Set -> List` anyways, since that is likely to be a very common use case. If that is so, then we need to decide upon an iteration order *anyways* and all we've done is add a layer of complexity, but for what?

There are several gains:

  - More descriptive type signatures.

  - Ordering would not be erroneously encoded in values such as those returned by `R.keys`.

  - The uniqueness constraint would be encoded in the arguments to `R.intersection` (for example). This function needn't rely on out of band communication (i.e. documentation) to convey the fact that duplicates in the "sets" are ignored: there could be no duplicates.

  - We would centralize the code (and documentation) for getting from `Set Any` to `[Any]`. We'd still need to decide how this function should behave, but we'd only need to document this behaviour in one place. This would simplify the descriptions of several functions as we'd no longer need to include notes about ordering and uniqueness.

> > I believe it's a mistake for Ramda to be divided into two libraries: `ramda` and `ramda-fantasy`.
>
> I'm afraid I still don't agree. I understand entirely that unsafe operations can be a problem. But forcing users to `map`/`chain` over the result of every call just to avoid any unsafe operation is pushing too many people too far.

We could provide, as PureScript does, `unsafeHead :: [a] -> a` in addition to `head :: Maybe a`.


[1]: http://ramdajs.com/docs/#values

**Comment by buzzdecafe** [comment]
> We could provide, as PureScript does, `unsafeHead :: [a] -> a` in addition to `head :: Maybe a`.

should we go down this road, it may make more sense for us to favor the unsafe js-style function as the default and add `safeHead : [a] -> Maybe a` instead of redefining `head`.

**Comment by CrossEye** [comment]
>> We could provide, as PureScript does, `unsafeHead :: [a] -> a` in addition to `head :: Maybe a`.

> should we go down this road, it may make more sense for us to favor the unsafe js-style function as the default and add `safeHead : [a] -> Maybe a` instead of redefining `head`. 

Agreed.  It's not that I object to including a `Maybe`.  It's that making it the default is moving to far from being "a library for Javascript developers".

**Comment by arcseldon** [comment]
> since R.head([]) evaluates to `undefined`

Vaguely remember conversations here a while ago, but can anyone offer why this wasn't implemented to return error condition when accessing an empty collection?

> I believe it's a mistake for Ramda to be divided into two libraries: `ramda` and `ramda-fantasy`.

Not in a position to make a recommendation here, that is definitely one for the core-team, but I would like to offer some thoughts as an avid long-time user of `ramda` and family of projects. 

From what I understand `ramda` was borne out of `eweda` where:

> Our basic data structures will be normal Javascript objects, and our usual collections will be Javascript arrays.

`ramda` was conceived as a **practical** (re-)implementation which initially at least, wished to retain a simple API (basic data structures being one).  Please correct me if this is incorrect. To that end, `ramda` has been a phenomenal success imho.  And bear in mind this all started at least a couple of years ago now (a long time in FP adoption around the world). We have seen some relatively fast-followers to Ramda as it was originally intended, such as `lodash/fp`. 

In the meantime, the rest of the JS developer world has matured with regards to FP concepts - would argue most JS developers today (perhaps other than out and out newbies) actively use one of `underscore`, `lodash`, `es5 / es6 array functions such as map, reduce, filter`, or their favourite fp library such as `ramda`.  In fact, I recently did a pull request to this project: [you might not need underscore](https://github.com/reindexio/youmightnotneedunderscore) and agree with where it is going too - the core language is gradually pushing out the need for many of the original toolbelt FP functions supplied by third party libs - albeit not in a point-free / curried way.

In fact, it is fair to say that FP is pervading most modern languages whether people like it or not. Take a look at even... Java 8 - exotic concepts like reactive functional programming, streams etc are now everyday constructs or else regularly included as third party libs. It is only a question of time imho, before more constructs such as `maybe`, `either` et al also become mainstream, perhaps supported as core language syntax.

> It's not that I object to including a `Maybe`. It's that making it the default is moving to far from being "a library for Javascript developers".

Today, I would agree with this. The problem with `Maybe` is that you really have to opt in all the way to use it, and so do all the functions in which it is composed.

Perhaps misguided in asking this but.. - is it that what is really needed is either a new **version** of `ramda` with breaking changes, and baseline off what has been written to date as the `original` v1. 

Or else, consider a fork of `ramda` as a separate project. In the same way that `ramda` was created as a reboot of `eweda`, perhaps now is the time to consider the future with a project reboot rather than a refactoring of what we know as `ramda` as it stands today?  Please understand I am not suggesting that `ramda` has any shortcomings, just that in order to push the envelope with more FP constructs that are still not mainstream today, it might be best to fork and have greater flexibility to make breaking changes.

My final observation would be this.  Please rename `ramda-fantasy` to something else? The name itself, regardless of whether it is an implementation of a fantasy-spec, is at odds with any developer that likes to be firmly grounded in the real world. Even `ramda-next` or `ramda-fp` (if that isn't an oxymoron of sorts) might work, and encourage adoption. 

Certainly be very interested to hear your thoughts here.

**Comment by buzzdecafe** [comment]
@arcseldon your history is pretty much accurate. I don't have a problem with including a simple `Maybe` or `Option` type in the core lib. For now I think we should include both the low-level, unsafe functions as well. 

I'd be loath to take it too far though. I'm afraid that once you start down the road of strong typing everything else gets pushed out. And I think supporting that would be a very difficult task in JS. I'd rather write in a language that would offer me some help, rather than relying on run-time checking.

As to the name of `ramda-fantasy`, this is the first complaint I've heard. But the audience is very small. I'm sorry to say that I find your alternative suggestions even worse, especially `ramda/fp`. To my mind, the acronym `fp` is so broad as to be almost meaningless. But perhaps something like `ramda-types`. Anyone for `algebramda`?

**Comment by arcseldon** [comment]
@buzzdecafe - thanks for reply.  Re. naming - I did take a quick look at [Sheep breeds](http://www.sheep101.info/breeds.html) for inspiration but came up short :smile:   `algebramda` is an interesting suggestion - like that alot.

@davidchambers - you started this discussion, and know `ramda` as well as anyone - is your point of view here being as a consumer of `ramda` from a user perspective, or for better integration and extension with packages such as [sanctuary](https://github.com/plaid/sanctuary)?  Really like and appreciate what you and the team are doing to keep the momentum of innovation in this space perpetually moving forwards - towards both a safe & useful language (albeit JS) :smile:  Would like to play a (small) part in that too if possible. 

The trouble I get with investing too much time in languages like `haskell` or `purescript` is that although these languages often form the source of inspiration for other languages to adopt what works for them, they are often not much use beyond **petri dishes** (as Simon Peyton Jones likes to put it). Sorry if I offend anyone here, perhaps I should point out this [youtube clip](https://www.youtube.com/watch?v=iSmkqocn0oQ) - where most of the `useful languages` are those that are also `unsafe`. Of course, all this is sucking eggs, and we are all trying to move towards safe and useful right? `ramda` is definitely useful today, can it be made safe too, without losing some of that usefulness? If the answer is **yes** then my personal opinion is then go ahead and make the needed changes. But if it comes at the cost of being practical and relevant (useful) then it would be a mistake.

**Comment by CrossEye** [comment]
@arcseldon:
> Perhaps misguided in asking this but.. - is it that what is really needed is either a new **version** of `ramda` with breaking changes [ ... ] Or else, consider a fork of `ramda` as a separate project.

I've thought a lot about both of these ideas.  I'm not quite ready for either of them, especially a new version before we've managed to reach 1.0!.  But I've been thinking pretty hard about what I would want in a library if I were starting from scratch and it was what eweda/ramda were at first, semi-private playgrounds for @buzzdecafe and me to work out our ideas.  For a new personal project, I would probably want a Maybe, for many of the cases that worry @davidchambers.  But I still would not want to go the route of strong-typing, for much the same reasons @buzzdecafe expressed.

As to the `ramda-fantasy` name, I have no strong feelings, although `algebramda` does have a very nice ring to it.  I did [express my concern][(co) about the name 'fantasy-land', but don't hold out much help for a change.


  [co]: https://github.com/fantasyland/fantasy-land/issues/92#issuecomment-118576261

**Comment by JAForbes** [comment]
algebramda is great!

**Comment by gilligan** [comment]
The discussion is starting to get very broad ...

1. Does a `Set` data type make sense for Ramda ?
1. Is Ramda in the business of providing data types at all or should this happen only in ramda-fantasy ?
1. Moving more towards FP can we omit the introduction of specific data types at all ?
1. Do we actually *want* to go into that direction ? Is Ramda slowly moving towards Ramda-Fantasy or not ?
1. Talking about Ramda-Fatansy is that actually a good name at all ?

I think a lot of it boils down to the question of what the user base should be. If Ramda is supposed to be a library that can be used by Javascript  developers without assuming existing knowledge of Functional Programming then certain things are hard to be had. 

Some time ago @scott-christopher did great work on his profunctor based lens PR for [ramda lens](https://github.com/ramda/ramda-lens/pull/2) and on the one hand I really wish the PR had made it. On the other hand it seemed clear to me that this would not be something I could get my coworkers to get into. One or two days after the PR was closed a colleague at work asked me for help and I figured what he was asking for (without knowing it of course) were prisms. Sigh.

I think introducing data types to Ramda is a tough decision. I really wish Ramda could include `Maybe` and `Either` and adjust existing functions accordingly or provide `safe` variations where it makes sense. On the other hand there already are tickets such as #1578 and the inclusion of such data types would not improve the situation I am afraid.

**Comment by CrossEye** [comment]
@gilligan:
> Is Ramda in the business of providing data types at all or should this happen only in ramda-fantasy ?

I think Ramda overall should not be in the business of providing types.  Ramda's functions should work with a great variety of types, though.

Nevertheless,

> Does a Set data type make sense for Ramda ?

I think there's a good reason to consider this.  This might be an intermediate solution to some serious problems, less radical than what I started doing, then dropped (how did I forget that?) in #1463.  It would fit very nicely with the `uniq` work scott-christopher has done.  It essentially solves the problem that we occasionally run into of trying to illegitimately use a list as a set.

And of course because of the reference equality of built-in Sets, we'd have to roll our own.

I feel the same about `Maybe`, and possibly `Either`, but I would make these opt-in APIs rather than default ones.

**Comment by buzzdecafe** [comment]
i think i am warming up to this idea, subject to the following:

* we should also provide well-defined functions for list intersection,list difference, etc. 
* we should determine what laws the `Set` type should satisfy. Clearly it's a functor; but what else makes sense to support?

**Comment by davidchambers** [comment]
> we should also provide well-defined functions for list intersection,list difference, etc.

Sure. Currently we're forced to decide whether `[1, 2, 2, 3]` represents `[1, 2, 2, 3]` or `{1, 2, 3}`. If we chose the former we can't provide set intersection, set difference, etc. If we chose the latter we can't provide list intersection, list difference, etc. If we consider both sets of functions important, we need—unsurprisingly—two sets of functions. These could, of course, both rely on arrays, but having a Set type would make the set functions simpler.

**Comment by arcseldon** [comment]
Linking here to findings recorded in this [issue](https://github.com/ramda/ramda/issues/1610#issuecomment-187081935)

**Comment by HarryPehkonen** [comment]
Please pardon my lack of understanding, but is this "Set" type different from the native [JavaScript Set](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set)?

**Comment by scott-christopher** [comment]
> @HarryPehkonen: Please pardon my lack of understanding, but is this "Set" type different from the native JavaScript Set?

The main difference would be how membership is determined. The native `Set` effectively uses reference equality, while the Ramda instance would have to use the semantics of `R.equals`.

**Comment by davidchambers** [comment]
Let's play with this in Sanctuary first. If we're happy with the result we can reconsider this proposal.
