### ISSUE TITLE
Why not supply functions to pipe/compose in an array?

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1644]
Sorry to inconvenience you with this question that has probably been answered before:

How come Ramda doesn't use an array for the functions supplied to `compose` and `pipe` so that data might be supplied as the last argument?

My impression was that the developers of Ramda generally frown upon variadic functions.

I guess I'm just trying to understand some of the design decisions of Ramda. (I'm still struggling with understanding why the resulting function from `compose`/`pipe` isn't curried.)

**Comment by CrossEye** [comment]
This has been discussed, most recently in #1213.  While there wasn't serious opposition, it's also a seriously breaking change.  I would guess that the vast majority of codebases using Ramda would have to be rewritten to handle it.

And I'm not so sure about the idea of taking the argument(s) as the final parameter.  That would be a much bigger change, since we allow the first-to-be-called function (first in `pipe`, last in `compose`) to be variadic.  Would `pipe`/`compose` then be variadic again in order to account for this (with shades of the #1260 / #1380 problems), or would the user have to pass a list of arguments every time?  Neither strikes me as very ergonomic.

**Comment by davidchambers** [comment]
[`S.compose`][1] and [`S.pipe`][2] have fixed arity. I'd like `R.compose` and `R.pipe` to have fixed arity too.


[1]: https://github.com/plaid/sanctuary#compose
[2]: https://github.com/plaid/sanctuary#pipe

**Comment by dalgard** [comment]
@CrossEye: I agree with you about the variadic signature.

I think it's alright to simply refer to Sanctuary for people who prefer the other style.
