### ISSUE TITLE
Flipped version of converge

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1646]
The order of arguments in `converge` matches that of `compose`. But since I only ever use `pipe`, it would make my code easier to read if there were a version of `converge` with the arguments flipped.

It would be _even greater_ if `pipe` and `compose` accepted an array for an argument – I've created a separate issue for it here: https://github.com/ramda/ramda/issues/1645

**Comment by CrossEye** [comment]
That's interesting.  I could see it, Since the array that's there came long after the function had been introduced (the same for `useWith`), it would originally have felt awkward to me   Placing a distinguished parameter first is clear.  Placing it last is odd.  But with only the combining parameter and a list, either seems reasonable.

But let's hold off on this one until we decide whether we're even keeping compose.

**Comment by buzzdecafe** [comment]
on that note, `converge

**Comment by CrossEye** [comment]
Well, it's under discussion, anyway: #1447.

That's what I meant to point to with my comment, but was too lazy to look for the link.  Serves me right to be that lazy and end up with an embarrassing mistake!

**Comment by dalgard** [comment]
The way `lift` is used, it appears to me, doesn't read very well in the context of a `pipe` or `compose`.

Overloading `pipe` and `compose` with branching (or introducing a new `flow` function that does that) would make that irrelevant, though.

**Comment by partially-applied** [comment]
@dalgard  

I had the same problem as you ! I liked left to right rather than right to left for compose.

see if you find it useful 

https://github.com/partially-applied/flip

**Comment by buzzdecafe** [comment]
@partially-applied it may ineterst you to know that for left-to-right `compose` we already provide `pipe`

**Comment by partially-applied** [comment]
So the only difference between compose and pipe is the fact that the arguments are flipped ?

**Comment by buzzdecafe** [comment]
yup: `compose(f, g, h) ≡ pipe(h, g, f)`
