### ISSUE TITLE
equals should not be sensitive to Map/Set ordering

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1653]
``` js
equals(new Set([1, 2, 3]), new Set([1, 2, 3])); // => true
equals(new Set([1, 2, 3]), new Set([3, 2, 1])); // => false
```

The same goes for maps. I know there are other issues here that are not trivial at all, but at the very least the iteration order should be ignored.

**Comment by CrossEye** [comment]
Absolutely.  This may get ugly...

**Comment by asaf-romano** [comment]
For the Set case, it shouldn't get too bad if the internal _Set implementation would implement (1) equals; (2) a way to initialize it from a native Set.

As For Maps, well, where is _Map? But it should be easy anyway, if both maps' keys are queried in advance.

**Comment by CrossEye** [comment]
Sets don't scare me here, but Maps look to be an O(n^2) problem unless, and we've discussed this before without a good resolution, we find a good object hashing function.  Even then, we'd have to be willing to not deal with the cases of function properties  since we couldn't distinguish the closures two otherwise identical functions dragged around with them, even if we could tell they were otherwise the same.

It's just a bit daunting.

**Comment by Bradcomp** [comment]
This was fixed in a recent PR... https://goo.gl/3FvVov
