### ISSUE TITLE
note in the docs that insert does not work beyond the lenght of the array

### ISSUE THREAD

**Issue by despairblue** [ramda/ramda#1676]
``` js
> r = require('ramda')
// ...
> a = r.insert(10, 'bar', [])
[ 'bar' ]
> a[10]
undefined
> a[0]
'bar'
>
```

Or could this behaviour be changed?

**Comment by buzzdecafe** [comment]
This strikes me as an *error* and it should probably *throw*. AFAICT the only reason it returns a value at all is that it relies upon the behavior of `splice`. Throwing is not a pleasant prospect, however. hmmm

**Comment by CrossEye** [comment]
As much as I dislike throwing, I agree that here we might have no choice.

And yes, @despairblue, however this works, it should be documented.

**Comment by buzzdecafe** [comment]
wouldn't it be nice if:

```js
// insert :: Number -> a -> [a] -> Maybe [a]
```
?

implying:

```js
idx > list.length ? Nothing : Just(list.concat(elt));
```

**Comment by despairblue** [comment]
My use case is actually that I have a spreadsheet (object of cells) from [js-xlsx](https://github.com/SheetJS/js-xlsx) and I want to reduce it into an object of arrays (rows):

```js
const s = { 'A2': 'ho', 'A1': 'hey' }
r.deepEqual(f(s), { 'A': ['hey', 'ho'] })
```

This would easily be solvable by using `toPairs`, `reduce` and `append`, except that the object keys may be unsorted - as in this example above - and thus `append` does not work here. Having `insert` simply inserting wherever would solve this.

**Comment by buzzdecafe** [comment]
> Having `insert` simply inserting wherever would solve this.

Understood. Unfortunately the cost is dealing with "sparse arrays" which is something we have striven to avoid. 

The problem here seems to be that ramda thinks in terms of `List`, but the easiest way to model a list in JS is to use `Array`. `List` is not the appropriate data structure for the algorithm you are using, and you are not surprisingly expecting `Array` behavior from an `Array`. 

Not sure where to go from here though

**Comment by davidchambers** [comment]
I'd be happy to see this function go.

**Comment by CrossEye** [comment]
@davidchambers:

> I'd be happy to see this function go.

David Chambers, by day, a mild-mannered open-source developer, but by night, the intrepid Lens Man!  :smile:

**Comment by buzzdecafe** [comment]
![LensMan](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fd1466nnw0ex81e.cloudfront.net%2Fn_iv%2F600%2F714969.jpg&f=1)

**Comment by CrossEye** [comment]
I should have known that existed somewhere!

**Comment by buzzdecafe** [comment]
i'm fine with removing `insert` in favor of a lens approach. The problem is the functor-y goodness of the lens impl hides this error:

```js
set(lensIndex(10), 'index ten', []); //=> []
```

While this is "good behavior" from some POV, I can imagine this causing some head-scratching bugs. The lens here is simply saying "You asked me to do something I don't know how to do, so here's your container back"; but unfortunately it's not actually saying *anything*.
