### ISSUE TITLE
R.flip always curries two arguments only

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1714]
``` js
R.flip((a, b, c) => { return `${a} ${b} ${c}`})(1, 2);
// => "2 1 undefined" (should be function)
```

http://goo.gl/dkpLXU

**Comment by davidchambers** [comment]
[`S.flip`][1] behaves the same way, though the behaviour is documented:

> `flip` may also be applied to a Ramda-style curried function with arity greater than two.

Having `R.flip` apply `R.curry` to its first argument before flipping seems reasonable to me.


[1]: http://sanctuary.js.org/#flip

**Comment by asaf-romano** [comment]
I'd expect curryN, with the arity of the original function.

**Comment by buzzdecafe** [comment]
> I'd expect curryN, with the arity of the original function.

me too

**Comment by partially-applied** [comment]
@asaf-romano  

I had situations where I needed to flip more than the first two arguments for ramda 

https://github.com/partially-applied/flip

Its a more general flip for N arguments :)

**Comment by getify** [comment]
Since the underlying function (assumingly) is already curried, I don't see that `flip(..)` only currying for 2 arguments is such a problem, as the currying would sort of cascade from the 2-arg outer flipped function to the inner original (curried) function.

Example:

```js
var f = curry(function(a,b,c,d) { return a + b + c + d; });
var g = flip(f);
g(1)(2)(3)(4);    // 10
```

The `g(..)` only curries `(1)(2)`, but then the underlying `f(..)` is still curried waiting for `(3)(4)`.

If `f(..)` hadn't already been curried, I think it would have been a bit surprising for the `(3)(4)` to have worked. In other words, I don't see that `flip(..)` should necessarily create extra currying where it didn't already exist, but merely preserve whatever currying was present.

However, I do find it surprising that `flip(..)` doesn't use `_arity(..)` to create a function with the "proper" `.length`. I think just adding that in would suffice.

```js
g.length;   // 2  (shouldn't it be 4?)
```

**Comment by CrossEye** [comment]
I agree.  We should fix this.
