### ISSUE TITLE
Documentation on reduced (v0.20.1)

### ISSUE THREAD

**Issue by cscalfani** [ramda/ramda#1766]
Reduced API docs state:

`Note: this optimization is unavailable to functions not explicitly listed above. For instance, it is not currently supported by reduceRight.`

But it doesn't list which functions support this optimization above (or below).

**Comment by CrossEye** [comment]
Yup, definitely needs to be fixed.  Might take a bit of digging, but should be fairly straightforward.

**Comment by morgsmccauley** [comment]
Hey i'd like to pick this up as my first contribution! Can someone please point me in the right direction?

**Comment by CrossEye** [comment]
@morgsmccauley: That's great!  (Sorry for the slow response.  Been busy on other projects.)

I would suggest simply finding which files import `_reduced` and double-checking that it does actually do what it suggests for them.

**Comment by morgsmccauley** [comment]
Cheers @CrossEye! I'll come up with a list of all functions currently supporting `reduced` and then check back in on how to update the documentation.

**Comment by CrossEye** [comment]
Updating the documentation is just a matter of updating the comment sections on the functions.  The docs are extracted from those.

**Comment by morgsmccauley** [comment]
It looks like `_reduce` checks for `@@transducer/reduced` on the accumulator every loop (set by `_reduced`) and short-circuits if present and true.

Because of this, both `reduce` and `reduceWhile` support `reduced` as they both use `_reduce` under the hood. `reduceBy` also uses `_reduce`, but it has a bit more going on so doesn't work as expected (and also doesn't make much sense?).

What confuses me though is when functions are used as transducers, because `@@transducer/reduced` pops up a lot in this context. Is there such a thing as users wanting to use `reduced` when trying to build a transducer, or is this just used internally?

I think `reduce` and `reduceWhile` may be sufficient for a list of supported functions but just wanted to check in first. Is there more that i'm missing? I'm very happy to keep digging but I may need more guidance. Functional concepts are relatively new to me, apologies if these are basic quesitons. All help is very much appreciated!

**Comment by CrossEye** [comment]
I will have to check into this.  Although it gets easier each time to wrap my head around transducers, I don't really remember it between times.  I suppose the question is whether there are other functions that themselves depend on `reduce` or `reduceWhile`.  Many of them *could* be written in terms of these, but there probably are not many which are.

**Comment by morgsmccauley** [comment]
So I ended up going through the 63 files which mention `reduce`. These mentions include `_reduce`, `reduceWhile`, `forceReduced` etc. From this I have concluded that the only functions which truely support `reduced` are:
- `reduce`
- `reduceWhile`
- `transduce`
Note that `pipeWith` also supports `reduced` depending on the application but I think this may be by accident and something like `R.when` would be better suited for the use-case.

Many `_x*` functions/transducer implementations mention `reduce` but this is for internal capability to ensure the function works as expected when used as a transducer. For example, `R.take` will short-circuit the transducer when the specified number of values is met.

I have created a pull request adding the above supporting functions to the documentation of `reduced` and I have also added tests to support this.

As a side note, it may be beneficial if all `reduce*` functions support `reduced`, which is possible. I am happy to raise a PR for this if there is interest.

**Comment by CrossEye** [comment]
> As a side note, it may be beneficial if all `reduce*` functions support `reduced`, which is possible. I am happy to raise a PR for this if there is interest.

I think that would be a very good idea.  If you're willing to take it on, then thank you very much.

**Comment by morgsmccauley** [comment]
Thanks @CrossEye. Ill work towards a PR for that when I get the time :)
