### ISSUE TITLE
propEq() throws Type Error when trying to access an undefined object

### ISSUE THREAD

**Issue by olegzd** [ramda/ramda#1808]
When using R.propEq('propertyName', 'propertyValue')(object)

when an object could be undefined, or null, it throws a Type Error. Would it be worthwhile to add a check and return false if the object is not defined , or have the user deal with error handling?

**Comment by davezuko** [comment]
While I don't speak for the Ramda team, from what I've experienced they appear to be (rightfully) very hesitant to bake this sort of functionality into the functions, instead putting that burden on the user so you can more reliably determine how a function will perform.

You may be interested in the `Maybe` and `Either` functors provided by [ramda-fantasy](https://github.com/ramda/ramda-fantasy). It's a type that essentially encapsulates the logic of "hey, this thing may or may not exist, so only perform the operation when there is actually something to perform it on. Since the logic of whether or not to perform the operation is encapsulated within the type, you don't have to worry about it so much in your functions.

I am still fairly new to this, so it may not be entirely correct, but hopefully this example somewhat demonstrates the idea: http://goo.gl/AN1vpr

```js
const getUser_Either = (user) => {
  return user
    ? Either.Right(user)
    : Either.Left(new Error('User not found'))
}

const isMichael = pipe(
  map(propEq('firstName', 'Michael')),
  Either.either(always(false), identity)
)

console.log(isMichael(getUser_Either({ firstName: 'Michael' })))  // true
console.log(isMichael(getUser_Either({ firstName: 'Mitch' }))) // false
console.log(isMichael(getUser_Either(null))) // false

```

**Comment by olegzd** [comment]
Thanks for the heads up. The example above seems to be right (I'm new to this too), but to use a new library + dependancy to bypass an error catch seems a little overkill for my purposes. I used try-catch around R.map(R.propEq(key, val)). 

Closing this issue -  thanks again for your help :)

**Comment by davezuko** [comment]
@olegzd one other solution w/o need `try/catch` or another lib, just in case you want to purely use Ramda:

```js
const isMichael = ifElse(
  complement(isNil),
  propEq('firstName', 'Michael'),
  always(false)
)

console.log(isMichael({ firstName: 'Michael' })) // true
console.log(isMichael(null)) // false
```

**Comment by olegzd** [comment]
Ah, forgot about the !! trick. That works better than what I have.

**Comment by svozza** [comment]
You could also use `defaultTo`.

**Comment by CrossEye** [comment]
Thank you @davezuko!  That sounds very much like an answer from a core developer!  And it is a very good description of our hesitancy to add run-time type-checking to the library.  I would urge anyone who's interested in that to check out [Sanctuary][sa], which is an excellent companion to Ramda, and becoming a stand-alone library of its own, with a very different take on type-checking.


  [sa]: http://sanctuary.js.org/
