### ISSUE TITLE
List function like R.map and R.filter to accept iterators as arguments

### ISSUE THREAD

**Issue by awto** [ramda/ramda#1809]
I'm not sure if it is feature request or an issue, looking at documentation I would expect this to work already, for example:

``` javascript
console.log(R.filter(R.gt(3),[1,2,3,4]))
console.log(Array.from(R.filter(R.gt(3),g())))

function* g() {
  yield 1
  yield 2
  yield 3
  yield 4
}

```

I would expect first and second lines to output the same, but the program outputs:

```
[ 1, 2 ]
[]
```

This would unlock very nice feature, namely transducers working on producers, not on consumers (like current transducers in Ramda), so following holds `R.comp(R.map(f),R.map(g)) === R.map(R.comp(f,g))` for iterators as arguments, i.e. no intermediate values are created. I think this is simpler than clojure style transducers implemented in Ramda.

**Comment by thurt** [comment]
Sounds like a feature request. i believe generator objects are a class of iterator interface, so `R.filter` would have to be changed internally so that it can run your object with `next` calls. 

I think its a good feature request to consider. 

I don't completely follow your last paragraph. I thought the point of using iterators was to get at intermediate values?

**Comment by awto** [comment]
> R.filter would have to be changed internally so that it can run your object with next calls

yes, run it, but also return generator, it is the point, simplified definition for filter (without other input types) would be just:

```javascript
function* filter(pred, input) {
   for(let i of input)
      if (pred(i)) 
         yield i
}
```

or for map

```javascript
function* map(fun, input) {
   for(let i of input)
      yield fun(i)
}
```

and I don't think it is hard for other List functions too

> I don't completely follow your last paragraph. I thought the point of using iterators was to get at intermediate values?

I mean the whole results of `f` and `g` as intermediate values, in case of arrays these will be the whole array returned after each state. In case of these transducers the execution order of `f` and `g` will be interleaved for each element.

I use this in my utility for ESTree AST traversal, there is a bit of elaboration about this kind of transducers in [estree-transducers](https://github.com/awto/estree-transducers#readme)

**Comment by thurt** [comment]
> and I don't think it is hard for other List functions too

Probably right.

Thanks for the link. I will check it out and get back to you.

**Comment by thurt** [comment]
I really like this idea. Thank you for the post! you describe it well with context to clojure, ramda, and reference links.

I made a simple example because I want to make sure I understand correctly what you intend. 
- producer - changes input into an iterable and returns it
- consumer - pulls iterable values through the composed transforms in order to produce output
```javascript
const R = require('ramda')

function producer() {
  return Array.from(arguments)
}

function map(fn) {
  return function* (iterable) {
    for (let i of iterable) {
      yield fn(i)
    }
  }
}

function consumer(transforms) {
  const list = []
  
  for (let i of transforms) {
    list.push(i)
    console.log(list) // side-effect
  }
}

function main() {
  const pipeline = R.pipe(
    producer,
    map(R.compose(R.inc, R.inc)),
    consumer)
    
  pipeline(1,1,1)
  /*  Logs
      [ 3 ]
      [ 3, 3 ]
      [ 3, 3, 3 ]
  */
}

main()
```
[gist link](https://gist.github.com/thurt/2685c32774bc9f4c03ca35ed8928dee9)

Ramda functions like `map` are dynamically dispatched--see the [switch statement](https://github.com/ramda/ramda/blob/v0.21.0/src/map.js#L43) for all of map's possible behaviors based on the second input value. In node v6 `generatorObj.toString() === "[object Generator]"`, so that could be added to `map` dispatch quite easily.

**Comment by awto** [comment]
probably the switch may look like the one in [interanal/_reduce.js](https://github.com/ramda/ramda/blob/v0.21.0/src/internal/_reduce.js), and default behavior is to return generator. And actually, it is another useful application for the tool, say, we use ES6 Sets instead of generators, and what to apply filter and transform each element:

```javascript
R.compose(R.filter(g), R.map(f))(new Set([1,2,3,4])
```

If implementations of `R.map` and `R.filter` work for Set like for Arrays, namely, returning Set with updated and filtered values, this will create intermediate Set value between `filter` and `map`, we know Set creation is expensive, and it is absolutely useless there, we can get Set back on the final stage, or whenever we need Set:

```javascript
new Set(R.compose(R.filter(g), R.map(f))(new Set([1,2,3,4]))
```

So I think for all Iterables it is good it to return Generator, I would do this for Arrays too, but since a lot of code may already depend on current implementation a special case for it would do the job.

There is probably another stopper, it requires ES6 Generators, but Ramda seems to keep ES5 sources.

**Comment by buzzdecafe** [comment]
looks interesting. i think we should take this up post-1.0.

**Comment by comraq** [comment]
I am actually curious, why not use the internal _reduce for map and filter as the default fallback? instead of a separate _map and _filter for arrays?

just for performance reasons? as _reduce supports reducing over iterables.

since most if not all functions can be implemented through reduce/fold, why not use that instead?
then in _reduce, have any dynamic dispatches for different data structures, if necessary.

**Comment by buzzdecafe** [comment]
@comraq good question. i think the array-specific lines are to optimize the primary path. it is not written in stone, however. i am certainly open to seeing what the tradeoffs are of centralizing these implementations in `reduce`. I expect we'd take a perf hit, but if we can streamline the dispatch logic or get some other benefit in exchange, that may be a trade worth making

**Comment by thurt** [comment]
> why not use the internal _reduce for map and filter as the default fallback? 

internal _reduce takes three arguments: `fn`, `acc` and `list`. So how do you derive `acc` from a map call which only takes two arguments: `fn` and `functor`?

**Comment by thurt** [comment]
[imlazy library](https://github.com/benji6/imlazy) by @benji6 may be of interest

**Comment by buzzdecafe** [comment]
@thurt  `map` for example:

`const map = (fn, ls) => reduce((acc, x) => acc.concat(fn(x)), [], ls)`

if we had something that could reliably get us the type of the container `ls` and an empty instance of it, then we could do something nice like

`const map = (fn, ls) => reduce((acc, x) => acc.concat(fn(x)), empty(ls), ls)`

**Comment by davidchambers** [comment]
> if we had something that could reliably get us the type of the container `ls` and an empty instance of it

Isn't that exactly what [`R.empty`][1] does, @buzzdecafe?


[1]: http://ramdajs.com/docs/#empty

**Comment by buzzdecafe** [comment]
indeed. also gotta have `concat` defined for the relevant type

**Comment by comraq** [comment]
a generic concat and empty (with dynamic dispatches) are pretty crucial, as they are the essence of monoids.

but yeah, if those are present, pretty much everything can resort to a reduce implementation.

though only thing is that reduce, for the most part, is eager and not lazy. what @awto brought up about lazy generators really has potential.

**Comment by yrns** [comment]
I stumbled upon this today, playing with a custom iterator for an object. `R.reduce` works as expected with it, but `R.map` simply maps over the keys and ignores the iterator.

**Comment by CrossEye** [comment]
>> if we had something that could reliably get us the type of the container `ls` and an empty instance of it

> Isn't that exactly what [`R.empty`][1] does, @buzzdecafe?

It would be, but unless I'm missing something, there is no guarantee that every Functor passed to `map` is a Monoid.

[1]: http://ramdajs.com/docs/#empty

**Comment by comraq** [comment]
@CrossEye if not guranteed to be monoid, then there can possibly another switch in map before fallback? check if empty is function or map differently?

though, currently I am more leaning towards the idea of lazy generators, and that it may be a better default/fallback.

**Comment by thurt** [comment]
going back to @awto:

I don't see how it will be easy/simple to change over to a generator-based library at the current time (as @buzzdecafe says the current version is pre 1.0). It wouldn't be good to only change some functions to generator functions, because in certain cases they are not composable with non-generator functions (ie. they introduce backwards compatibility concerns).

I'm not convinced that all list-based functions have an obvious generator version, and there are still other functions which require more careful consideration about how or whether to store state in their generator version.

If you are interested in starting a fork to try changing some functions, I would be happy to provide input! A complete list of all the functions you want to change to generators would be a good start I think.

I definitely like the model expressed by generator composition and I see how it can quickly pay off after implementing just a few functions. The [imlazy library](https://github.com/benji6/imlazy) looks like a really good source of inspiration (source code is very easy to read).

**Comment by awto** [comment]
@thurt many thanks for imlazy library pointer, this is exactly the library I need, I will definitely try to add iterator cases to ramda functions after I have some free time if nobody takes it first

> I'm not convinced that all list-based functions have an obvious generator version, and there are still other functions which require more careful consideration about how or whether to store state in their generator version.

do you have any concrete function in mind as an example? I looked briefly through List functions list and haven't noticed any complicated. 

But anyway, it looks like a core decision for Ramda team to make, now many functions don't support iterators at all, and for me it looks like a top priority requirement for libraries such as Ramda. There are quite a few modern containers: in ES6, Immutable.js worth supporting. The question is: should the functions work eagerly with such containers and each to build same type of container as output, or lazely, like in imlazy librarry, well, or the 2 sets of functions.

**Comment by svozza** [comment]
Wouldn't using `concat` on arrays mean you'd be cloning the accumulator on every pass of the reduce?

**Comment by buzzdecafe** [comment]
@svozza yes, there would definitely be some perf hits with a naive implementation.

**Comment by thurt** [comment]
>> I'm not convinced that all list-based functions have an obvious generator version, and there are still other functions which require more careful consideration about how or whether to store state in their generator version.

> do you have any concrete function in mind as an example? I looked briefly through List functions list and haven't noticed any complicated.

:+1: Yea I'm thinking about this right now. I don't have any specific ones yet, but I am being wary.

My primary concern is that the model of composition introduced by composing generators isn't friendly with non-generator functions.
```javascript
R.pipe(R.map(R.inc), R.apply(R.multiply))([1,1]) // returns 4
// changing R.map to a generator map will break this code (for multiple reasons)
```
This suggests to me that many more functions would have to be changed to generator functions (not just the list-based ones).

Regarding state: for example, I think of `reduce` having two likely implementations
```javascript
const reduce = R.curry(function* (f, acc, iterable) {
  for (let i of iterable) {
    acc = f(acc, i)
    yield acc
  }
})

const reduce2 = R.curry(function (f, acc) {
  let a = acc
  return function* (iterable) {
    for (let i of iterable) {
      a = f(a, i)
      yield a
    }
  }
})
```
With the first, I get the accumulator values across one iterable. With the second, I can continue the accumulator across multiple iterables (which may be separated in time). Which implementation to choose depends on what direction the library wants to go.

**Comment by comraq** [comment]
@thurt hmm, reduce with generators? maybe im missing something here but what is the purpose of yielding the intermediate acc values?

by nature reduce is defined to "fold down" a sequence/list and reduce them to ONE final value. what purpose does outputing the intermediate results serve? (other than seeing how the accumulator is accumulated) 

it is why i think that reduce is eager because reduce should only output 1 result from any arbitrary length list. hence, it can be lazy in the sense that it will not execute until you demand for its value/acc. but, it will/should only have 1 value as its output. (in terms of JS iterators, imo it probably only has 1 "next" value and then its done).

and thus, if reduce is eager and generators are lazy, they cant/shouldnt be mixed together. either you choose to use lazy generators for transformations or you use reduce to eagerly reduced down to ONE final value/result. (if you want to pipe multiple transformations into eager evaluation through reduce without intermediate values, use clojure transducers)

In the end, it seems like reduce vs generators are on two sides of the spectrum, the public api can support both (but may be messy), however, they shouldnt be mixed.

**Comment by thurt** [comment]
@comraq makes sense! thanks for noticing that. I agree with your explanation. I think `scan` is a more appropriate name.

**Comment by awto** [comment]
@thurt I don't see problem with `R.apply`, JS apply doesn't work with arbitrary Iterables too, why should R.apply works, or you mean something else?

**Comment by thurt** [comment]
@comraq 

>  if reduce is eager and generators are lazy, they cant/shouldnt be mixed together

i don't think `reduce` has to be eager. It can be a lazy generator. does this do what you expect:
```javascript
const reduce = R.curry(function* (f, acc, iterable) {
  for (let i of iterable) {
    acc = f(acc, i)
  }
  yield acc
})

const sumIterable = reduce(R.add, 0)
const mySum = sumIterable([1, 2, 3]) // lazy
console.log(...mySum) // 6
```

@awto I just wanted to make it clear to other readers that the generator composition model is not interchangeable with Ramda's function composition model. To do the same computation, I would have to write an `apply` consumer:
```javascript
const apply = R.curry(function (f, transforms) {
  const xs = []
  for (let t of transforms) {
    xs.push(t)
  }
  return f(...xs) 
})

// now this works because I am composing compatible things
R.pipe(map(R.inc), apply(R.multiply))([1,1]) // returns 4 
```

**Comment by comraq** [comment]
@thurt yeah, your example is what i meant by:

> in terms of JS iterators, imo it probably only has 1 "next" value and then its done

**Comment by thurt** [comment]
> yeah, your example is what i meant 

Ok good :+1: 

>  i cant really think of a good situation/usage for that. any thoughts?

it seems like all the generator functions would be implemented so that they only work with iterables. So if reduce returns a primitive value, like a number (as I show above), then it may not be very useful in a generator composition (i think you were getting at this point in your comments). In that case, the only place I would put it is at the end of an `R.pipe`:
```javascript
const sumIterable = reduce(R.add, 0)
const myOperation = R.pipe(map(R.inc), sumIterable)
console.log(...myOperation([1,1])) // 4
```   

Maybe I could use it in the middle of a generator composition, but I have to make sure `reduce` returns an iterable, not a primitive.
```javascript
const of_sumIterable = reduce(R.pipe(R.add, R.of), 0) 
const myOperation2 = R.pipe(map(R.inc), of_sumIterable, map(R.inc))
console.log(...myOperation2([1,1])) // 5
```
I suppose the `reduce` operation could also build up a more complex iterable, but I haven't experimented on that.

**Comment by thurt** [comment]
> I suppose the reduce operation could also build up a more complex iterable, but I haven't experimented on that.

Just following up on this more complicated case.

When `reduce` is used to build up a new iterable structure, I may want to subsequently iterate through that new structure. Unfortunately with composed generators, I'm not able to do that within the same composition.

To iterate the new structure, I have to map another generator function or generator composition over it. 

For simplicity, I will build a new iterable structure with `map(dupl)`, which yields a new iterable for each of the values.

```javascript
const dupl = R.flip(R.repeat)(2) // dupl(1) => [1, 1] 
const nextOp = map(R.inc)
const Op = R.pipe(map(dupl), map(nextOp))

const myOp = Op([1, 2, 3]) // lazy and nested: Generator(Generator)
console.log(...myOp) // {} {} {} (returns 3 instances of the second generator, nextOp)
``` 
I don't get my final values unless I also consume the nextOp generators. In most cases, that will be a burden to have to consume twice. So I will have to write another generator function, maybe `flatMap` is a suitable name?

```javascript
// I expect i to be one of my new iterables (ie. a result of dupl) 
// and f(i) to be iterable (ie. a generator, nextOp)
const flatMap = R.curry(function* (f, iterable) {
  for (let i of iterable) {
    for (let j of f(i)) {
      yield j  // j is a value from new iterable; transformed by nextOp
    }
  }  
})
```
Now I will get my final values with just one consumer
```javascript
const Op = R.pipe(map(dupl), flatMap(nextOp))

const myOp = Op([1, 2, 3])
console.log(...myOp) // 2 2 3 3 4 4
```
The principle would be the same if I had to use `reduce` instead of `map(dupl)`, except that `reduce` would only yield one new iterable from all of the values.

**Comment by xgrommx** [comment]
I also agree that generators will be helpful.
```js
const S = x => y => z => x(z)(y(z));
const K = x => y => x;
const B = x => y => z => x(y(z));

const W = (S(S))(S(K)); // monadic join for function

const take = R.curry(function * (n, stream) {
  for(let x of stream) {
    if(n-- === 0) {
      return
    }
    yield x
  }
});

const iterate = R.curry(function * (f, a) {
  yield a
  for(;;) {
    a = f(a)
    yield a
  }
});

const repeat = function * (value) {
  yield * iterate(K(value), value)
}

const replicate = R.curry(function * (n, value) {
  yield * take(n, repeat(value));
});

console.log([...W(replicate)(3)]); // => [3,3,3]
```

**Comment by CrossEye** [comment]
I think perhaps it's time to write a roadmap document.  As @buzzdecafe suggested above, this might be good post-1.0 work.

A roadmap might make it clear that 1.0 would be the last version to support ES5 (even ES3?)  While that seems to be a general understanding among the core team, I believe, it would be good to document it.

**Comment by CrossEye** [comment]
I didn't say that correctly.  1.0 would support ES5, and work would begin on 2.0, which would not.  There certainly could be intermediate releases which also support ES5.

**Comment by OliverJAsh** [comment]
I would like to see Ramda suppporting the native `Map` and `Set` types. Has this been considered?

**Comment by CrossEye** [comment]
@OliverJAsh:

What sort of support do you envision?  Both have significant philosophical differences with Ramda, which is interested in value equality; they focus on reference equality.  This makes it somewhat difficult to interoperate.

**Comment by OliverJAsh** [comment]
Sorry, to be clear I meant the ES6 native `Map` and `Set` types, which are iterables.

For example, I would like to be able to use Ramda to map over a native ES6 `Set` and get back a mapped `Set`.

**Comment by OliverJAsh** [comment]
I found an alternative project that does exactly this: https://github.com/kevinbarabash/functify

**Comment by CrossEye** [comment]
That sort of support is exactly where I can imagine philosophical differences.  There are several issues.  First, assuming that `map` was extended to `Sets`, there is a very clear, if imprecise, notion that what `map` does is to return a new data structure of the same shape as the original one.  If you map over an `n`-element list, you return an `n`-element list.  If you map over a `Maybe.Just` you get another `Maybe.Just`.  If you map over a binary tree, you get another binary tree with exactly the same branching pattern.  But this would not be able to extend to mapping over native `Sets`:

```js
let s1 = new Set([-2, -1, 0, 1, 2])
map(n => n * n, s1) 
//~~> new Set([4, 1, 0])
```

Our 5-element set mapped into a 3-element one.  This wreaks havoc with our intuition.  But perhaps that's acceptable.  We haven't formulated any precise laws that this would break, so maybe it's OK.

But then look at this example:

```js
let s2 = new Set([{x: -2}, {x: -1}, {x: 0}, {x: 1}, {x: 2}])
map(n => ({x: n.x * n.x}), s2) 
//~~> new Set([{x: 4}, {x: 1}, {x: 0}, {x: 1}, {x: 4}])
```
Now we run into real problems with Ramda.  The native `Set` type distinguishes the first and last elements listed in that return by reference, and so includes them both.  Ramda works with value equality and would consider them identical.  So from Ramda's point of view, we have a Set with duplicated elements.  That's a very substantial problem, quite possibly an insurmountable one.

And of course native `Maps` would run into the same issue with their keys.

I would love to hear of reasonable ways of addressing these issues.  But I haven't come up with any myself.

**Comment by OliverJAsh** [comment]
@CrossEye Interesting points. As for the first, I think that's acceptable. I'm used to this behaviour with Scala's `Set`:

```
scala> Set(1, -1).map(n => n*n)
res1: scala.collection.immutable.Set[Int] = Set(1)
```

**Comment by CrossEye** [comment]
@OliverJAsh:

I think the first one is actually all right.  It doesn't feel that way, because in all other iterable cases we are used to seeing, either the original and the mapped iterables are both infinite or

**Comment by OliverJAsh** [comment]
Why not just let the native `Set` decide how to dedupe elements? E.g. `new Set([1,1]) => Set { 1 }`. Is there a reason Ramda must decide what is and is not equal?

**Comment by CrossEye** [comment]
@OliverJAsh:
> Why not just let the native `Set` decide how to dedupe elements?

To my mind, this is very clear.  Ramda is designed to do one important job: to make it easier to do in JS the sort of functional programming available in a number of other languages.  There are a number of factors involved, including purity, immutability, composability, and this one: value-based semantics.

Functional programming is about *values* not *references*.  When we want to know if `foo` and `bar` are equal, we care about their content, and not their addresses in memory.  We take this for granted with strings and numbers but, often in JS, feel fine ignoring this for other types.  Ramda is interested in sticking closer to the functional programming mainline.

We already have functions that try to think in a `Set`-like fashion, `uniq`, `union`, `intersection`, `difference`, and the like.  These are designed to work with lists, and it would be really nice to have a Set interface for them to work with.  (We do, by the way, internally; perhaps we need to promote that.)  But they are designed for value equality.

What would you see as the integration points with native `Set`/`Map` implementations, and what are the advantages?  Is it any more than adding `map`, `filter, `reduce`, *et. al.*, to them?
