### ISSUE TITLE
R.max and null vs undefined

### ISSUE THREAD

**Issue by reactivize** [ramda/ramda#1812]
Hey guys,

I'm wondering if this is the expected behavior of the max function.
For null I was expecting that -5 would be the largest number.

> 
R.max(-5, undefined)
// -5

>
R.max(-5, NaN)
// -5

>
R.max(-5, null)
// null

**Comment by buzzdecafe** [comment]
i expect @davidchambers would say that should be a type error. And i'm inclined to agree

**Comment by CrossEye** [comment]
This looks like a typical JS case of [garbage in, garbage out][rl].  The signature for `max` is `Ord a => a -> a -> a`.  And `undefined` and `null` are not part of ordered types.  But `null` will be coerced to 0 when coerced in a comparison.  And `NaN` is even more subtle, since it is part of the Number type, but Number is an ordered type only if `NaN` is excluded.

I don't know that there is much to do here.  Sanctuary would presumably throw an exception in any of these calls.  Ramda usually avoids that.


  [rl]: http://goo.gl/Ud4URM

**Comment by davidchambers** [comment]
> Sanctuary would presumably throw an exception in any of these calls.

It does indeed:

```javascript
S.max(-5, null);
// ! TypeError: Type-class constraint violation
//
//   max :: Ord a => a -> a -> a
//          ^^^^^         ^
//                        1
//
//   1)  null :: Null
//
//   ‘max’ requires ‘a’ to satisfy the Ord type-class constraint; the value at position 1 does not.
```

Our garbage in, garbage out philosophy means we spend a small proportion of our time and energy discussing how various functions should respond to various invalid inputs. It's a bearable tax, certainly.
