### ISSUE TITLE
Must list functions work with objects?

### ISSUE THREAD

**Issue by neerone** [ramda/ramda#1817]
For now we using in our project [normalized](https://github.com/paularmstrong/normalizr) format of data store. We have all data in objects like this:
{1: {id:1, name:"test" ...} ...}

For example, it would be awesome if we could use R.last() on objects too (just get the last key value).
Only(?) R.filter works with objects but even R.forEach does not works as expected. 

Ramda is awesome but it needs to be more universal to use only ramda in our project (for now we use lodash+ramda+own helpers).

**Comment by davidchambers** [comment]
> it would be awesome if we could use R.last() on objects too

Objects are unordered. How would we choose the "last" property? Would we sort the property names in some way and choose the last, or would we—:scream:—rely on enumeration order? If the former I think this is better left for others to define in their own projects, since the order we would choose would be arbitrary and therefore inappropriate in many contexts. If the latter we can no longer consider `{x: 0, y: 0}` and `{y: 0, x: 0}` equal – a sacrifice I'm unwilling to make.

**Comment by neerone** [comment]
Thanks for the response. Now i see that the question have no sense. 
But for the more correctness, for example in V8 object key order match it's insertion order with exception that key doesn't parsed as Int32 value.
Again sorry for the dumb question. We previously used Immutable.OrderedMap() to keep objects key order

**Comment by davidchambers** [comment]
> But for the more correctness, for example in V8 object key order match it's insertion order with exception that key doesn't parsed as Int32 value.

We could rely on insertion order, but it would be a shame for `R.equals({x: 0, y: 0}, {y: 0, x: 0})` to be forced to evaluate `false` (to ensure `R.last(a)` ≍ `R.last(b)` if `a` ≍ `b`).

**Comment by CrossEye** [comment]
And if you want to see a painfully long discussion on this matter, see #1067.  :wink:
