### ISSUE TITLE
Having problems with composeK docs example

### ISSUE THREAD

**Issue by wwalser** [ramda/ramda#1826]
The problem could be ignorance on my part. I occasionally use the docs to familiarize myself with new concepts and I was just looking over the docs for composeK and attempted to try out the example in the REPL.

I understand that there are trade offs between succinct examples and providing clarity for users new to FP. I was comfortable filling out the missing `parseJson` and `get` functions and even looking up Sanctuary to understand Maybe. Even after having done that though there are still several things that I don't understand about the example and I'm wondering if it's a lack of understanding on my own part of something wrong with the example, Ramda or Sanctuary. 

Here is my code (http://goo.gl/4aCLE4):
```javascript
//  parseJson :: String -> Maybe *
// this should work :
//var parseJson = S.encase(JSON.parse);
// but does not, it throws a type error.
// instead you have to unwrap the maybe and rewrap it?
var parseJson = str => {
  var result = S.encase(JSON.parse, str)
  return Maybe.of(result.value);
}
//  get :: String -> Object -> Maybe *
var get = str => obj => {
  return Maybe.of(obj[str]);
}

var getStateCode = R.composeK(
  R.compose(Maybe.of, toUpper),
  get('state'),
  get('address'),
  get('user'),
  parseJson
);

getStateCode(Maybe.of('{"user":{"address":{"state":"ny"}}}'));
//=> Just('NY')
//getStateCode(Maybe.of('[INVALID JSON]'));
//=> Nothing()
```

Two primary questions:
1. Why does the commented out parseJson implementation throw a type error? `S.encase` is curried by default and returns a `Maybe` but the error message seems to indicate that it is not of type `Maybe b`?
2. The example in the docs makes use of `Maybe.of` but it seems that `S.toMaybe` is better since it handles `undefined` being `Nothing`. I've had several attempts on the invalid JSON where the composition, `R.compose(Maybe.of, toUpper)` failed because `toUpperCase is not a function on undefined`. The code seems to be written with the assumption that `undefined` would be `Nothing` and therefore not have the `chain` method invoked. Is that correct?

Thanks to anyone who can provide insight :).

**Comment by davidchambers** [comment]
Before using `R.pipeK` or `R.composeK` I suggest writing the pipeline with `R.pipe` or `S.pipe`. It will then be apparent whether the Kleisli equivalent is useful. The answer is almost always no, since it's rare that every step in a pipeline will be in the form `R.chain(…)`. Note that in your case the input to `getStateCode` must be of type `Maybe String` to satisfy `R.composeK`; `String` would likely be more convenient for the caller.

Here's the function defined via regular function composition:

```javascript
//    getStateCode :: String -> Maybe String
const getStateCode =
S.pipe([S.parseJson(Object),
        R.chain(S.get(Object, 'user')),
        R.chain(S.get(Object, 'address')),
        R.chain(S.get(String, 'state')),
        R.map(S.toUpper)]);
```

The nested property access can be described more neatly via [`S.gets`][1]:

```javascript
//    getStateCode :: String -> Maybe String
const getStateCode =
S.pipe([S.parseJson(Object),
        R.chain(S.gets(String, ['user', 'address', 'state'])),
        R.map(S.toUpper)]);
```

At this point we're composing three transformations, only one of which is a Kleisli transformation. We're better off with regular function composition.

In my experience `R.pipeK` and `R.composeK` are almost never useful. YMMV.


[1]: http://sanctuary.js.org/#gets

**Comment by wwalser** [comment]
Thanks @davidchambers
