### ISSUE TITLE
group apis in documentation

### ISSUE THREAD

**Issue by zhaoyao91** [ramda/ramda#1860]
by now the apis in doc are ordered by alphabet, this is useless. it would be much more helpful to group them as docs of lodash so we can quickly see which api we should use.

**Comment by olsonpm** [comment]
I just found this out today, but if you type the category in the search box then all the functions for that category are listed.

Seems to be a reasonable workaround for now.

**Comment by CrossEye** [comment]
I would really like for our categories to turn into a collection of tags, but with similar filtering capability, and perhaps easier discoverability.

But I actually don't want the lodash-style grouping for our main display.  I often go to that page and struggle to find a function I know is there because it's not in the first (or even second) category I choose to look for.  So I resort to browser-find.  I find our alphabetic-by-default with easy category filtering more useful.

Closing without prejudice.

**Comment by olsonpm** [comment]
Yeah - coming from lodash I didn't mind the different decision on sorting.  The option to filter via search is super nice though.
