### ISSUE TITLE
Empty Pipe

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1875]
```
> R.pipe()(x)
Error: pipe requires at least one argument
    at Object.pipe (/Users/chet/Code/elmish/node_modules/ramda/dist/ramda.js:7154:19)
    at repl:1:3
    at REPLServer.defaultEval (repl.js:260:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:429:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```

I think it makes sense for an empty pipe to be the `R.identity` function.

I have a an array of modifiers that I want to apply to an object and pipe is pretty handy for this:

``` js
R.pipe(...modifiers)(obj)
```

However, if there are no modifiers, I would expect everything to work, but I get the error above.

My current workaround looks like this:

``` js
R.pipe(...R.append(R.identity, modifiers))(obj)
```

But I think this workaround shouldn't be necessary...

Is there any reason you think an empty pipe should throw an error?

**Comment by olsonpm** [comment]
One problem I see with this is identity not taking multiple arguments.

```js
R.pipe(R.add)(1, 2); // -> 3
R.pipe(R.identity)(1, 2); // -> 1
```

Granted, I don't understand why pipe's
1) first call is variadic instead of taking an array of functions thus allowing it to be curried
2) second call is variadic.  Sure it's convenient, but seems like that functionality should be handled in a different way.

If pipe's first and second calls weren't variadic, then I definitely agree R.identity should be the base case.

an example of what you're probably looking for then is
```js
const flow = R.curry(
  (fxnArr, res) => {
    R.forEach(
      aFxn => res = aFxn(res)
      , fxnArr
    );
    return res;
  }
);

flow([R.add(2)], 1); // -> 3
flow([], 1); // -> 1
```

**Comment by davidchambers** [comment]
> I don't understand why pipe's […] first call is variadic instead of taking an array of functions thus allowing it to be curried

[`S.pipe`][1] behaves as you suggest:

```javascript
> S.pipe([S.inc, Math.sqrt, S.dec])(99)
9

> S.pipe([S.inc, Math.sqrt, S.dec], 99)
9
```

> I don't understand why pipe's […] second call is variadic. Sure it's convenient, but seems like that functionality should be handled in a different way.
>
> If pipe's first and second calls weren't variadic, then I definitely agree R.identity should be the base case.

The identity function is the [identity element][2] of unary function composition. `S.pipe` operates on an array of unary functions, so the meaning of `S.pipe([])` is unambiguous:

```javascript
> S.pipe([], 42)
42
```

I'm in favour of changing `R.pipe` to behave like `S.pipe`. At least one member of the team believes that `R.pipe` should remain a reversed `R.compose`. I don't see much value in this symmetry: since it is considered good practice to use `pipe` for multiline compositions, the functions are not used interchangeably. (I'd also like `R.compose` to become a curried ternary function like [`S.compose`][3], but that's a separate issue.)


[1]: http://sanctuary.js.org/#pipe
[2]: https://en.wikipedia.org/wiki/Identity_element
[3]: http://sanctuary.js.org/#compose

**Comment by buzzdecafe** [comment]
the only counter-argument i can muster here is this is a dramatic api change -- in other words, "backward compatibility." i don't find that argument very persuasive. i'd rather get it right now than persist in less-than-ideal api choices simply because they were there first. so i am inclined to agree that `pipe` would be better sanctuary-style. 

should we go that route, i would like to see the reverse case as well, e.g. `comp :: [(y -> z), ... (b -> c), (a -> b)] -> a -> z`

let's take up `compose :: f -> g -> x -> f (g x)` elsewhere

**Comment by kedashoe** [comment]
:+1: for `pipe` taking an array of functions.

> e.g. comp :: [(y -> z), ... (b -> c), (a -> b)] -> a -> z

Are you saying we should add a new function `comp` to mirror the new `pipe`? Or that we should also change the current `compose`?

**Comment by buzzdecafe** [comment]
> Are you saying we should add a new function `comp` to mirror the new `pipe`?

Yes

>  Or that we should also change the current `compose`?

I'm open to that as well; changing `compose` from it's current variadic form to a stricter definition

**Comment by davidchambers** [comment]
I don't see much value in the `comp` function you're proposing, @buzzdecafe, since I think of `pipe` as a "multiline" composition function. As a reader I want to see…

```javascript
pipe([f,
      g,
      h])
```

rather than…

```javascript
pipe([h,
      g,
      f])
```

**Comment by buzzdecafe** [comment]
on reflection you may be right -- trying to preserve that symmetry, but it may not be meaningful

**Comment by CrossEye** [comment]
I think we really should do the function list, although I'm more bothered by the backwards compatibility issue than @buzzdecafe is.

I'm probably the one @davidchambers noted who wants to keep the `pipe`/`compose` symmetry.  To me they are simply two different ways of writing

```js
  f(g(h(...args)))
```

```js
 compose([f, g, h])(...args)
```

```js
  pipe([h,
        g,
        f])(...args)
```

They are useful for different code layouts and for different ways of focusing on code.  `pipe` gives a much more imperative 'this-then-that-then-the-other` description, where `compose` heeds closer to the mathematical notions.

**Comment by olsonpm** [comment]
>  To me they are simply two different ways of writing  

That's how I've always looked at it too, with an emphasis on two ways of reading as a result.

```js
// compose reads cleanly right to left
//  <----------------------------]
var a = compose([f, g, h])(...args)

// pipe jumps around, even though I still prefer writing in that method
//  -----------------
//  |          _____|____
//  V         /_____|     \
var a = pipe([h, g, f])(...args)
```

**Comment by CrossEye** [comment]
I find it an extremely rare case where I will define a function with `pipe` and call it at the same time.  So the interaction with `...args` makes little difference to me.  I will do so with `compose`, which I use for shorter bits, generally one-liners, so it's the association with `f(g(h(...args)))` that's important there.  For `pipe` it's more the thought of an ordered list of steps to be taken, and data-flow is a necessary, but secondary part of my understanding.

**Comment by ccorcos** [comment]
I pretty much only use compose when I'm composing two functions. When I have many functions that do certain things, I almost always use pipe.

A perfect example of using compose would be `R.reduce(R.compose, R.identity)` which ironically defines exactly the `pipe` function I'm proposing ;)
