### ISSUE TITLE
R.either performance (and performance in general)

### ISSUE THREAD

**Issue by axyz** [ramda/ramda#1913]
Hi there, I was fiddling around with Ramda and I was trying to implement a very simple `R.path` with a default fallback value.

It seems to be a very simple use case for R.either, however the performance cost of R.either seems o be quite big compared to a simple native `or` after the `R.path`

here is a fiddle: https://goo.gl/F51qxU

This is of course just an example, and is probably related to some small implementation detail (like curring and lifting the or). However I'm quite sure there maybe other cases of similar performance bottleneck hard to be discovered.

This is totally fine (abstractions always have a cost and contributing may be fun), however it is hard to fully embrace Ramda functions and style if you have to test their performance before using them.

Wouldn't be great to have something like  a benchmark suite for every function, maybe comparing speed to native implementation and maybe major competitors like lodash and keeping a result page up to date? 

That would really help out both the decision to use or not use some specific functions in production, but above all to let possible contributors immediately find out which functions have to be improved.

P.S. I'm using some Ramda functions on high traffic real world applications, but if from one side I'd like to write more functional and composable code, from the other side I'm scared about nesting and composing Ramda functions too deeply (this applies to almost all utility libraries...), I know that zero cost abstractions in javascript are quite utopic, but I've also noticed that some functions from Ramda and other utility libraries sometimes are quite fast (also faster than native alternatives), to fill this gap between the reality and the dream about writing small and nicely composable functions everywhere it is really needed to address this issue, mainly because developers should trust the implementation and the reasonable overhead cost of any abstraction out there. Otherwise these great libraries will always have a very small space (using just a couple of functions that you know are fast and without daring too much with composition).

Sorry for the long issue (that may not really look like a proper issue...), but I think this is something interesting to be discussed, also to know what is your vision and plans about that.

**Comment by buzzdecafe** [comment]
I'd be grateful for help with such a project. We have some benchmarks here:
https://github.com/ramda/ramda/tree/master/lib/bench

Any `*.bench.js` file dripped in there will get picked up by the `benchRunner` script. But we certainly haven't gone anywhere near as far as you recommend.

**Comment by CrossEye** [comment]
I really would love to get some stronger benchmarks.

There are a few places where we know that Ramda is likely to be slower than native or than other libraries with overlapping functionality, mostly those places where we do some sort of value equality testing rather than reference comparisons.  Other than that, I would expect that if Ramda has performance issues, they're correctable... but only if we know about them.  So benchmarks would be great.

-----

As to the particular questions about `either`, I think your comparison is not really apples-to-apples.  In the `either` version, you create a new function every time and then call that.  That is sure to be more expensive than your native version.  I [added a third version][rr] which does the same thing with a native function wrapper and (after running a few times to settle the JIT) I get results like this:

```shell
testA
8.305000000000291
testB
5.19999999999709
testC
8.8849999999984
```
 
(_FF46.0.1 in Ubuntu14.04_)

This seems to tell me that the function wrappers are certainly adding time, but Ramda isn't particularly adding additional time over a native version.

  [rr]: https://goo.gl/DlD7T1

**Comment by axyz** [comment]
Interesting,

```
const testC = (path, fallback, obj) => 
  ((o) => R.either(R.path(path), () => fallback))(obj)
```

this testC returns a function, I guess this is what you had in mind:
```
const testC = (path, fallback, obj) => 
  ((o) => R.either(R.path(path), () => fallback)(o))(obj)
```

in both cases however on node performance are 3 to 4 time worst than testA, while on chrome 51 everything is way more random: testA and testC are often similar but sometime one of the 2 is as much as 2 time faster than the other, while testB is always around 5 times faster.

Probably the "suggested ramda way" should be something like my new testD: https://goo.gl/lyzTDh

that on chrome behave similarly to testC, but on node seems to be a bit slower (and both C and D too slow to be used there).

Ideally the most idiomatic way should also be the faster.

**Comment by bijoythomas** [comment]
@axyz

I know you question is a general one regarding the performance of Ramda functions and I have seen such cases too in loops with large number of iterations where the issue was the creation of functions. In my case it was R.when.

But for your particular example, have you tried using R.pathOr? I have added a testE https://goo.gl/bYbjdT whose performance comes close to the native or test (testB)

**Comment by CrossEye** [comment]
> this testC returns a function, I guess this is what you had in mind:
> ```js
> const testC = (path, fallback, obj) => 
>   ((o) => R.either(R.path(path), () => fallback)(o))(obj)
> ```

Oops, yes of course.  What I was trying to point out is that the point of `either` is to generate a reusable function.  We also have [`or`][or] and [`defaultTo`][dt] and [`pathOr`][po] for related possibilities.

> [ ... ]

> Ideally the most idiomatic way should also be the faster.

I'm afraid that's a bit of a pipe dream.  It's great when we can do it, but there will be times when it's clearly beyond our reach.

  [dt]: http://ramdajs.com/docs/#defaultTo
  [or]: http://ramdajs.com/docs/#or
  [po]: http://ramdajs.com/docs/#pathOr
