### ISSUE TITLE
Could extend the original function sortby , like sortBy (fn, order)?

### ISSUE THREAD

**Issue by juanha** [ramda/ramda#1930]
the **sortBy** ,default is to sort in ascending order (+), but i  want specify descending order (-), can you provide a function that sorted according to  the comparator function like **sort**,.  

To achieve this function data in descending order ,my idea is  use **reverse** base on the sortby

```
// sort by asc or desc  
export const sortBy = (arr, key, order) => {
  const sortByKey = R.sortBy(R.prop(key));
  const newArr = order === false ? sortByKey(arr) : R.reverse(sortByKey(arr));
  return newArr;
};
```

**Comment by syaiful6** [comment]
hmm, you can achieve the descending thing just by invert your ```comparator```.

**Comment by CrossEye** [comment]
@juanha:
I wouldn't mind visiting this, but I think we'd have to look carefully at signatures, to ensure that they matched Ramda's notions of simplicity.  We're not much on boolean flags, and the parameter order above is not well-designed for easy currying.  Would it be simply to have `sortBy` and `reverseSortBy` or `sortBy` / `sortByDescending` ?

If we do this, I would rather write a version that passes an appropriate comparator to `sort` up front rather than one which sorts then reverses the result.  But that wouldn't be hard to do.  Are you interested in creating a PR for this, understanding that there is a real chance, but no guarantees that it would be accepted?


@syaiful6:
The problem is the `sortBy` does not return a `comparator`.  It creates and uses one internally, but it's not exposed.

**Comment by syaiful6** [comment]
@CrossEye hmm, correct. Looking on the ```sortBy```, we have two options for descending:

1. Invert / negate it. (only work for number)
```javascript
var pairs = [[-1, 1], [-2, 2], [-3, 3]]
var sortByFirstItem = sortBy(compose(negate, prop(0)))
sortByFirstItem(pairs) // [[-1, 1], [-2, 2], [-3, 3]]
```
2. Reverse. We can achieve it just by compose the current ```sortBy``` and ```reverse```.

**Comment by CrossEye** [comment]
...or we can rewrite slightly to allow the code that is responsible for deciding direction to have access to the comparator, and then we can simply apply `lift(negate)` against it as necessary.  This doesn't sound too hard.  The hard part here is deciding on the correct API for this.

**Comment by juanha** [comment]
@CrossEye   
 I reconsider the issue, Could we rewrite the sortBy like the following code to sort list by prop ( both ascending and descending) 
`module.exports = _curry2(function sortBy( fn, order,  list) {
return _slice(list).sort(function(a, b) {
     var aa = fn(a);
     var bb = fn(b);
  return order === 1 ?  aa - bb : bb - aa;
});
});
R.sortBy(R.prop(prop), order)(list)`

Look forward to your reply

**Comment by CrossEye** [comment]
@juanha:

I see several issues with this.

First, I think the signature is probably in the wrong order for easiest currying.  I would expect that a user would more likely want to fix the sort order/direction than sorting function itself.  So the parameter order should probably be `(order, fn, list)`.  (I might also use "direction" rather than "order", but that's minor.)

Second, the `order` parameter is unintuitive and not at all descriptive.  Why should I pass a `1` to sort ascending?  And what should I pass to sort descending?  @buzzdecafe has taken to calling this FOP, or "flag-oriented programming."  This is just as bad with a boolean, of course, although one called `isAscending` might be at least somewhat more clear.  (This would not be an issue for an internal function, by the way.  Internally, we can take such shortcuts.  This is one of the reasons that I was suggesting a public interface with two different functions.  They could simply act the same, except that they passed opposite booleans to such an internal function.)

Finally, this code would only allow sorting by numbers (or more precisely by elements with appropriate `valueOf` semantics), but the current code is more flexible than that, sorting on anything that responds to `<`.  You can see this [in the test suite][ts].

If all these issues were fixed, my answer would still be, "that's nice, but I'd prefer to make this an internal function, and publicly expose partially applied versions with the 'ascending' / 'descending' parameter partially applied.  That still feels like the cleanest public API.

  [ts]: https://github.com/ramda/ramda/blob/master/test/sortBy.js

**Comment by ahstro** [comment]
Doesn't `ascend` and `descend` in 0.23.0 make this moot?

**Comment by kedashoe** [comment]
thanks @ahstro
