### ISSUE TITLE
Why not every internal module has unit test?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#1935]

**Comment by CrossEye** [comment]
I don't know if the other core contributors share my feelings on this, but that seems correct to me.

My philosophy on unit testing is that one should only test the public behavior of systems.  Internal implementations will of course be tested in the process of testing the public behavior.   But since unit tests serve a second role as a form of API documentation, I don't ever want to commit to the internal implementation details in my documentation, only to the publicly available behavior.

This doesn't mean that I think we should *never* test internals, but I do think such tests should be quite rare.

**Comment by adispring** [comment]
I know that unit test should not be overused, but internal modules are core part of the lib, external apis rely on internal modules.
If the core part of a system is not reliable, it can hardly to say that the whole system is reliable/stable. That's my worry about it.

**Comment by CrossEye** [comment]
It's funny, I gave a talk in my day job this past week on unit testing, and this was the only point that was at all controversial.  Although the majority agreed with my point of view, there was a significant minority that likes to test the internal implementations as well as the public API.  (I don't know if it means anything but it seemed as though those with strong .NET backgrounds were more likely to feel that way.  Those with Java backgrounds or with Python/Ruby or functional language skills are more likely to agree with my idea.)

I really do think that internal implementations are just that: internal.  I should be free to change them whenever I feel like, and that should not entail changing unit tests in order to do so.

I feel as though the only tests necessary for those internal functions are those that show how the public functions behave.  If there is some hole in the internal function, it does not matter at all if cannot be exposed given the way the public functions actually call it.  

While I believe this is the more common feeling in the community, I know others do feel differently.  Why do you find it worth the cost of maintaining tests for code that you could replace on short notice?

**Comment by adispring** [comment]
Thank you, CrossEye, for your patient explain about unit test. I have learnt a lot, and have lots more have to learn.
