### ISSUE TITLE
poll: transducer usage

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1958]
**Q:** How frequently do you use Ramda's transducer functionality?

**A:** Often (:heart:), occasionally (:thumbsup:), or never (:thumbsdown:).

**Comment by kedashoe** [comment]
I do occasionally use it but I would prefer we had multiple builds and that it were not in the default.

**Comment by jigargosar** [comment]
I would love to use it, but this noob needs some examples/tutorials. Once I understand, I be willing to contribute more examples.

**Comment by MattMS** [comment]
Same here. I never get very far each time I try to figure out how to get started with it.

**Comment by jigargosar** [comment]
@kedashoe @davidchambers I rather have it in core library, unless there is a significant benefit of removing it. 

My reasons being, my functional programming improved because every time I go through Ramda docs, the functions that I haven't used reinforce the idea that I need to dig-up/learn more. 

I would like Ramda library to have even more functions. So that noobs like me, get some exposure, and start googling :)

I am not sure what the aim of the library designer is. Perhaps to keep it compact, etc. But this world needs real-functional-programming, not underscore.js , and ramda is the easiest to get started with. So, I hope that more focus is given on introducing/exposing more concepts for newly functional programmer (pun intended). 

I try to contribute as much as I can through [my publication](https://medium.com/the-functional-programmer), but I am still a noob.

**Comment by kedashoe** [comment]
> But this world needs real-functional-programming, not underscore.js , and ramda is the easiest to get started with. So, I hope that more focus is given on introducing/exposing more concepts for newly functional programmer (pun intended).

I am with you a million percent. Ramda was the first thing that finally got me to take a serious look at functional programming. This project is a great way to learn about many functional programming concepts. I do not think though that we need all these things in `ramda.js`. For example, [lenses](https://github.com/ramda/ramda-lens) and [ADTs](https://github.com/ramda/ramda-fantasy) are in separate projects. I think transducers also either belong in their own project (they might actually get even more love and attention this way!) or included in a non-default build.

**Comment by jigargosar** [comment]
@kedashoe I hope you are right. I don't mind separate/projects builds. But I still hope, there is a universal umbrella, that refers to all of them, ADT, lenses, transducers etc. 

A single opinionated package of functional goodies, that noobs can get started with, later they can pick and choose. 

Right now, Ramda is my only hope. Perhaps, I should be the one creating a bundle as separate project. But I don't know how much attentions will it get, but it is better than nothing.

If we could educate new programmers on functional style,  how wonderful will tomorrow be.

But I need to learn first ;)

**Comment by MattMS** [comment]
I'm more a fan of modular builds and then having an umbrella project of everything that can be put on CDNs.
There are a few times that I've simply wanted a few of the basic functions (like curry) and not needed all the rest.

One idea that may help would be to integrate the other projects into the [main site docs](http://ramdajs.com/docs/).
Although I haven't looked into the documentation styles of Ramda Fantasy or Lenses to see how they would fit.

As far as extra learning goes, there is a [manual](https://github.com/ramda/ramda.github.io/tree/master/manual), but it needs a fair bit of love.
Which is why it is not linked from the main site.

**Comment by CrossEye** [comment]
I'm not sure how well transducers would pull apart from the core code, but if they could become an independent module, I would be quite happy.

I also agree that it would be nice to get the documentation for these side projects onto the main site.

> As far as extra learning goes, there is a [manual][ma], but it needs a fair bit of love.
> Which is why it is not linked from the main site.

I finished up some (unrelated) writing this weekend and believe I will finally get back to working on the manual this week.  Any help would be quite welcome!

  [ma]: https://github.com/ramda/ramda.github.io/tree/master/manual

**Comment by MattMS** [comment]
I may not be able to make initial contributions to it (due to limited FP knowledge), but maybe I can still help a some point.
I know words, I have the best words.

**Comment by buzzdecafe** [comment]
> I may not be able to make initial contributions to it (due to limited FP knowledge)

bah. IMO best way to learn is to try to explain it to someone else. your contributions would be most welcome.

**Comment by jigargosar** [comment]
>  best way to learn is to try to explain it to someone else
Point taken, expect a pull request by EOD 
@buzzdecafe expecting your constructive criticism :D

**Comment by CrossEye** [comment]
Criticism is free around here.  There might be a slight surcharge for the constructive sort!  :smile:

Please do take a look at #1282, especially https://github.com/ramda/ramda/issues/1282#issuecomment-123879214.

**Comment by bjdixon** [comment]
Regarding the universal umbrella project vs smaller modules, if Ramda transitioned to using es2015 modules instead of CommonJS you may be able to have the best of both worlds. Both Rollup and Webpack 2 provide tree shaking for es2015 modules.

**Comment by CrossEye** [comment]
@bjdixon:

Would that not prevent the individual files from being used in current-generation Node?

**Comment by bjdixon** [comment]
@CrossEye you're right, es6 modules aren't fully implemented yet in node 6. I think es6 modules will be the right direction and are worth considering for the future. I may have been a little excitable when suggesting it :grimacing:

**Comment by CrossEye** [comment]
Excitement is great!  Unfortunately we need to be a bit more cautious...

**Comment by adispring** [comment]
I've translated [Transducers Explained: Part 1](http://simplectic.com/blog/2014/transducers-explained-1/) into Simple Chinese: [Transducers Explained: Part 1 中文](https://adispring.github.io/2016/10/24/Transducers-Explained-Part-1/). I am thinking about how to let more China people see this translation, and planing to translate kevinbeaty's other two [transducer articles](http://simplectic.com/blog/).

**Comment by CrossEye** [comment]
@adispring: Is this where you meant to add that comment?

**Comment by adispring** [comment]
I just mean that I can do some help to let more people know and use this, if it's not related, I will delete this two comments.

**Comment by CrossEye** [comment]
@adispring: This conversation has wound it's way all over the place.  I just wondered if you meant to attach this to the earlier discussion on Chinese translations instead.  Not a big deal.
