### ISSUE TITLE
embrace type coercion

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1967]
Since Sanctuary is available for those who dislike type coercion, perhaps Ramda should *embrace* type coercion. #1966 provides an example of "surprising" behaviour due to coercing in some cases but not others. Perhaps `String` as an input type should mean *Ramda will apply [`String`][1] to the value and use the result in the computation*. So, for example, `R.toUpper(null)` would evaluate to `'NULL'`.

This is just an idea. Feel free to react with :thumbsup: or :thumbsdown:.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_conversion

**Comment by CrossEye** [comment]
Like all the reaction emoticons I'm also :-1: in the general case, but I think there are good places for principled exceptions to our usual stronger enforcement of types.  The changes in #1926 are a good example.  Rather than sticking with the less useful String-only API, this PR expanded some functions to include a `String | Int` typedef.  There is a very straightforward argument that union types are inherently less principled than their unary counterparts, but they prove themselves useful time and again.

#1966 is a borderline case because by far the easiest -- and likely also the simplest -- way to enforce the obvious invariant is, as you say, to apply [`String`][st] to the purported key in `assoc` and `dissoc`.  I could live with this if it's documented only to work with Strings / Ints.  But I wouldn't be thrilled in seeing this implemented that way.  I really wouldn't want users intentionally using other objects' `toString` methods for this, or at least not to count on such code continuing to work between releases

So no to the general case, but that doesn't mean we shouldn't consider it where it makes sense.. 

  [st]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_conversion

**Comment by davidchambers** [comment]
> Rather than sticking with the less useful String-only API, this PR expanded some functions to include a `String | Int` typedef.

I've no problem with this. :)

> I could live with this if it's documented only to work with Strings / Ints.

This highlights one significant philosophical difference between Ramda and Sanctuary: Ramda *documents* intended usage; Sanctuary actually *enforces* its invariants.

If one day Ramda goes down the sanctuary-def route we could handle `String | Int` quite nicely:

```javascript
//    Idx :: Type
const Idx = $.NullaryType('ramda/Idx', R.either($.String._test, $.Integer._test));
```

**Comment by CrossEye** [comment]
> This highlights one significant philosophical difference between Ramda and Sanctuary: Ramda *documents* intended usage; Sanctuary actually *enforces* its invariants.

Yes.  Ramda is willing to trade some type safety in exchange for reduced exception-throwing and higher performance.  It is a significant difference.  I do think the community is stronger by having both approaches available.
