### ISSUE TITLE
Should reduceRight's argument: fn flip its args?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#1972]
Haskell foldr transformer's arguments sequence is `\x acc -> ...`,  accumulator is the second argument, and `reduceRight`'s is `fn(acc, x)`, should we flip` fn(acc,x)` to `fn(x, acc)` ?

**Comment by CrossEye** [comment]
That Haskell does it differently is a useful data point, but not entirely convincing on its own.  Care to try to make an argument for the change?

**Comment by paldepind** [comment]
Very good question @adispring.

Since we order arguments to our functions so that they are most useful for currying the "structured" argument is last. However, if one is building a new structure with `reduceRight` then the function in `reduceRight` will get the "structured" argument _first_ which is less inconvenient.

Two examples where changing the order works better:

```js
concat = (list1, list2) => R.reduceRight(R.append, list2, list1);
R.reduceRight(R.flip(R.prop)(true), {}, ["foo", "bar", "foo"]); //=> {foo: true, bar: true}
```

Changing the order also increases the symmetry between `reduce` and `reduceRight`. Reduce can be understood as placing the function between the elements in the list. If our functions `reduce` and `reduceRight` were like Haskell's the difference between the two would only be a matter of how one places parentheses. I.e. the below would be accurate.

```js
R.reduce(R.add, 0, [1, 2, 3, 4]) = (((0 + 1) + 2) + 3) + 4
R.reduceRight(R.add, 0, [1, 2, 3, 4]) = 0 + (1 + (2 + (3 + 4)))
```

Changing whether the folding function associates to the left or to the right also changes which of its arguments will be the accumulator.

However, while one can say that symmetry is increased one could also say that from another perspective something is lost because the signatures of the functions will be more different.

**Comment by CrossEye** [comment]
> If our functions `reduce` and `reduceRight` were like Haskell's the difference between the two would only be a matter of how one places parentheses. I.e. the below would be accurate.
> 
> ```js
> R.reduce(R.add, 0, [1, 2, 3, 4]) = (((0 + 1) + 2) + 3) + 4
> R.reduceRight(R.add, 0, [1, 2, 3, 4]) = 0 + (1 + (2 + (3 + 4)))
> ```

That to me is pretty convincing.  Even more interesting would be if the operation wasn't commutative, say `R.subtract`.

**Comment by adispring** [comment]
Yes, the result will be changed if the computation depends on arguments order, like `R.subtract`
I found a more symmetrical and interesting example in haskell:
```haskell
head' = foldr1 (\x _ -> x)
last' = foldl1 (\_ x -> x)
```

**Comment by semmel** [comment]
I always thought that `Array.prototype.reduceRight` and Ramda's `R.reduceRight` are *not right* 😏  because given a binary reducer function `r` they can not be imagined as *right* tree structure:
![reducerighttree](https://cloud.githubusercontent.com/assets/296476/20278061/9245fe66-aaa3-11e6-844b-91c2df0c31a6.png)
Instead they are simply a `reduce` with the array reversed, are they not?
So flipping the argument order of the reducer function makes sense for me.

**Comment by benperez** [comment]
To me it comes down to whether or not you want to think about `R.reduceRight` as "reduce with the array reversed" or "replace the commas in the list with the reducing function"/"right tree".

I think the difference between `foldl` and `foldr` in haskell is more significant because you're dealing with lazy evaluation and singly-linked lists. In ramda/Javascript everything is strictly evaluated and we also have `O(1)` access to any element in the array, so I can't really think of a way in which `reduce` and `reduceRight` are different from each other except that in `reduceRight` the array is "reversed"

**Comment by CrossEye** [comment]
I'm definitely in favor of this change.  The altered semantics of `reduceRight` make it much more a useful function than our current version.  @adispring, do you want to create a PR?

**Comment by adispring** [comment]
OK, I'll create a PR, and modify functions relate to `reduceRight`.
