### ISSUE TITLE
R.pipe is not fully compatible with R.__ or currying

### ISSUE THREAD

**Issue by Jabher** [ramda/ramda#1976]
This can be explained in the simpliest way by this code:

As a developer, I expect this to return 4
```
R.pipe(
  R.add(1),
  R.curry((a,b) => a + b)
)(1, 2)
```

However, only this notation works:
```
R.pipe(
  R.add(1),
  R.curry((a,b) => a + b)
)(1)(2)
```

Another way to solve this is using uncurry.
```
R.uncurryN(2, R.pipe(
  R.add(1),
  R.curry((a,b) => a + b)
))(1, 2)
```

Is there any possible way to omit .uncurryN usage?

**Comment by CrossEye** [comment]
> As a developer, I expect this to return 4
> ```js
> R.pipe(
>   R.add(1),
>   R.curry((a,b) => a + b)
> )(1, 2)
> ```

I guess the question is *why* you expect that.

Are you expecting something like

```js
R.add(1, R.curry((a, b) => a + b)(1, 2)); //=> 1 + 3 => 4
```

? If so, you should be using [`compose`][co] rather than [`pipe`][pi].

Or are you expecting something more like 

```js
R.curry((a, b) => a + b)(R.add(1, 1), 2); //=> 2 + 2 => 4
```
?  If so, your `uncurry` does this, but it's definitely far from how Ramda's pipe/compose are designed.  You might want to check out Sanctuary's [`meld`][me], which does work like this.



  [co]: http://ramdajs.com/docs/#compose
  [me]: https://sanctuary.js.org/#meld
  [pi]: http://ramdajs.com/docs/#compose

**Comment by davidchambers** [comment]
[`S.meld`][1] was removed in sanctuary-js/sanctuary#280, so don't get too attached to it. :stuck_out_tongue_winking_eye:


[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.11.1#meld

**Comment by benperez** [comment]
I think the intended interpretation here is that a curried function should feed its arguments through one at a time, with each one returning a new function.
```javascript
// apply the first argument, 1
R.pipe(R.add(1), R.curry((a,b) => a + b))(1);
R.pipe(R.add(1)(1), R.curry((a,b) => a + b));
R.pipe(2, R.curry((a,b) => a + b));
R.curry((a, b) => a + b)(2);
// now we have a partially applied function, still awaiting one argument
// next we apply the 2 that is waiting from the beginning
R.curry((a, b) => a + b)(2)(2)
2 + 2
4
```
I believe `S.meld` is slightly different, since you can actually feed multiple arguments to a function at a time, where `R.pipe` and `R.compose` should really only feed through one a a time.

FWIW, this is how it works in Haskell:
```
λ> let f = (+) . (+ 1)
λ>:t f
f :: Num a => a -> a -> a
λ> f 1 2
4
```
I think this has come up a few times w.r.t. `pipe` and `compose` but I can't remember why it isn't done this way.

**Comment by CrossEye** [comment]
> [`S.meld`][me] was removed in sanctuary-js/sanctuary#280, so don't get too attached to it. :stuck_out_tongue_winking_eye:

Well, I've got rotten timing!   The first time I've found an actual use for the function is a few days after you find that no one has a use for it!  Right back at you: :stuck_out_tongue_winking_eye:

[me]: https://github.com/sanctuary-js/sanctuary/tree/v0.11.1#meld

**Comment by CrossEye** [comment]
> I think the intended interpretation here is that a curried function should feed its arguments through one at a time, with each one returning a new function.

Right, that's what I tried to capture with my second example.  I think of `meld` (RIP) as a generalization of this concept that defaults to this one when fed binary functions.

> FWIW, this is how it works in Haskell:

Just remember that Haskell doesn't do polyadic functions, so `f 1 2` is `(f 1) 2`, which is what @Jabher already found would work.

As to why `pipe` / `compose` work like they do, a lot of the discussion was in #1260, #1318, and #1391.  But I'm not sure we ever really considered a version where this idea was used.  We removed the notion of calling `curry` on the resulting function, but I don't think we thought about doing sequential calls with the arguments until we had a result.

One of our examples in those discussions was (in various guises)

```js
 pipe(add, map)(10)([1, 2, 3])
```

which in a sane world *has* to return `[11, 12, 13]`.  Because #1260 broke that, and generated a great number of WTFs from users in the process, we reverted it in #1391.

The thought that this would also lead to the same result is interesting:

```js
 pipe(add, map)(10, [1, 2, 3])
```

But I don't think it's feasible.  For how would we distinguish this case?

```js
pipe(add, negate)(5, 6); //=> -11
```

Of course because we reverted #1260, this does not allow

```js
pipe(add, negate)(5)(6); //=> error
```

You'd have to manually curry the result of the `pipe` call to make that work.

So I don't see a way to get `pipe` / `compose` to do this, as interesting as it sounds.  Am I missing something?

**Comment by Jabher** [comment]
thank you @CrossEye! This is what I was trying to say. I'm just expecting auto-currying from anything in Ramda, so for me any fn produced by it - if it supports `f(a)(b)`, I expect it to support `f(a,b)` and to return the same value. If it is not supposed to work in that way, probably it should be specially noted in documentation, I suppose.

**Comment by CrossEye** [comment]
> [I]f it supports `f(a)(b)`, I expect it to support `f(a,b)` and to return the same value.

Well, that's not how currying works in Ramda.  It's the reverse.  A curried version of `f(a, b)` would also support `f(a)(b)` but there's no reason to assume the reverse.


> If it is not supposed to work in that way, probably it should be specially noted in documentation, I suppose.

Well, it [already says this][pi]:

> **Note**: The result of pipe is not automatically curried.

Can you think of something more forceful?

  [pi]: http://ramdajs.com/docs/#pipe

**Comment by Jabher** [comment]
oh. My bad, missed it :( Thank you a lot.
