### ISSUE TITLE
allPass is returning a function unexpectedly

### ISSUE THREAD

**Issue by scull7** [ramda/ramda#2006]
I'm trying to use a `allPass` to determine if an integer matches a set of predicates.  However, when calling `allPass` with 2 parameters it always returns a function.  Is this the expected behavior?

https://goo.gl/Nxff5m

```javascript
R.allPass([ f1, f2, f3 ], x) // -> function
R.allPass([ f1, f2, f3 ])(x) // -> bool
```

**Comment by davezuko** [comment]
Lurker jumping in: it looks like this is due to the fact that `allPass` [curries the generated function to the maximum arity among the supplied functions](https://github.com/ramda/ramda/blob/master/src/allPass.js#L34), so to handle this in a single invocation would in fact make `allPass` variadic.

The function's signature is documented as`[(*… → Boolean)] → (*… → Boolean)`, which demonstrates that this is in fact intentional. This says nothing of whether or not this is the ultimate desired behavior (though I think it is), just that it does act as documented.

**Comment by scull7** [comment]
Ah, that makes sense now (probably should have in the first place); the `->` indicating the curry and the `()` indicating the grouping.  Just unexpected on my part as I was thinking that the `allPass` was a curried, fixed-arity function; similar to some of the other logic functions, but its behavior does fit with it's closer relatives. Thank you @davezuko for the explanation.

**Comment by davidchambers** [comment]
[`S.allPass`][1] has the simpler type you expected, @scull7.


[1]: https://sanctuary.js.org/#allPass

**Comment by scull7** [comment]
@davidchambers Thanks for the Sanctuary.js suggestion.  very helpful.
