### ISSUE TITLE
Add groupByStreak - group values in a list by testing consecutive/adjasent values if they keep the steak going

### ISSUE THREAD

**Issue by kmamykin** [ramda/ramda#2012]
I couldn't find anything like this in the docs, and implementation using simple re-combination of existing functions was not apparent either. 
As a side note, `R.groupWith` is *almost* that, except it does not pass adjacent items in the list, but rather tests against first item in the group against each next item. "fixing" `groupWith` changes semantic, so I propose a new function: `groupByStreak`

Especially useful to group records with dates into ranges.

Here is my implementation: 
```
const streak = (sameStreak) => {
  let s = 0
  let valueSet = false
  let lastVal = null
  return (v) => {
    if(!valueSet) {
      valueSet = true
      lastVal = v
      s = 0
    } else if(!sameStreak(lastVal,v)) {
      lastVal = v
      s += 1
    } else {
      lastVal = v
    }
    return s
  }
}
const groupByStreak = fn => R.compose(
  R.map(R.map(R.nth(1))),
  R.values,
  R.groupBy(R.nth(0)),
  R.converge(R.zip,[R.map(streak(fn)), R.identity])
)

const isConsecutive = (a, b) => a + 1 == b
groupByStreak(isConsecutive)([0,1,2,3,1,2,0,4,5,6,9]) // [[0, 1, 2, 3], [1, 2], [0], [4, 5, 6], [9]]
```

Would be happy to submit PR if the owners approve.

**Comment by CrossEye** [comment]
Damn, I had thought that it *did* work that way!

Of course they're equivalent if your comparison function is transitive, which is all I've ever tried, I suppose.

Although we might want to bikeshed on the name, I'm very much in favor of this function.  Others?  @benperez?

**Comment by benperez** [comment]
I think we should fix `R.groupWith` to work this way. 

As far as the name, I think it should stay `R.groupWith`. I've never actually thought of using that function, (or haskell's equivalent `groupBy`) with anything other than equality, although as @kmamykin's example indicates, you could certainly think of it producing "streaks" instead of just "lists of equal elements". However, I think people looking for this function will find it more easily under a name containing the word "group".

**Comment by CrossEye** [comment]
The only reason I hesitate is that the current implementation is equivalent to the Haskell one; if we're going to port over the name, does it make sense to port over the behavior?

But this API is the one I find more intuitive.

**Comment by benperez** [comment]
> The only reason I hesitate is that the current implementation is equivalent to the Haskell one

There's something ironic about @CrossEye arguing to keep something because of its similarity to Haskell 😛. That is a good point though, I missed that the Haskell version works that way.

For simple equality cases, the transitive property of equality should mean that this function works the same way `a = b AND b = c -> a = c`. I'm pretty sure the Haskell function was written with this use-case in mind, so they probably implemented it that way since it's simpler (although I don't think it would make a difference in the performance of the haskell version, or our version for that matter).

I do like that you can use this version of the function for more than just equality though, so I would be in favor of changing it.

**Comment by CrossEye** [comment]
> There's something ironic about @CrossEye arguing to keep something because of its similarity to Haskell :smile:. That is a good point though, I missed that the Haskell version works that way.

That's funny, as I think of Haskell as providing one of our main inspirations, with Ramda serving dual roles of making available to JS folks some of the sorts of things normally found in languages like Haskell, and giving people coming from languages like Haskell some chance to use JS with less friction.  Whatever reputation I have for ... let's say ... obstinance has to do with the fact that I am often pushing the "for Javascript developers" part of our mantra.  I think Ramda needs to work with the grain of the language.

-----

I am all for changing this function.  My misgivings are minor.  I really doubt that anyone is counting on the current behavior of the function with a non-transitive comparison function.  And the new behavior is significantly nicer.

**Comment by benperez** [comment]
@CrossEye, I only jest. I definitely appreciate the effort and point of view you bring to the table.

@kmamykin this PR is definitely yours if you want it, otherwise I'd be happy to make the change.

**Comment by CrossEye** [comment]
@benperez: Oh, I did understand.  I was answering something else around the same time where I was supporting doing something a bit differently from how it would be done in more strongly typed languages, and the juxtaposition amused me, and made me want to justify myself.

Yes, @kmamykin, do you want to create a PR?

**Comment by kmamykin** [comment]
I will take a stub at it...
