### ISSUE TITLE
groupWith needs sorting to make groups unique

### ISSUE THREAD

**Issue by briefy** [ramda/ramda#2017]
```javascript
R.groupWith(R.equals,[0,1,1,2,1,1])
//[[0], [1, 1], [2], [1, 1]]
```
i checked the resource that its complexity is O(n2)
```js
  while (idx < len) {
    var nextidx = idx + 1;
    while (nextidx < len && fn(list[idx], list[nextidx])) {
      nextidx += 1;
    }
    res.push(list.slice(idx, nextidx));
    idx = nextidx;
  }
```
so should we make it more efficient to just return the sorted version,like below?
```javascript
R.groupWith(R.equals,[0,1,1,2,1,1])
//[[0], [1, 1, 1, 1], [2]]
```

**Comment by jeiea** [comment]
Why not use R.groupBy?
```
R.groupBy(R.identity, [1,1,2,1,2,3])
// {1: [1,1,1], 2: [2,2], 3: [3]}
```
groupWith is adopted from #1688.
I think groupWith useful due to reflection of adjacency.

**Comment by CrossEye** [comment]
@briefy: Three things:

  1. That would assume that the elements can be ordered.  There is no reason to assume that.

  2. While I haven't thought it through very deeply, that algorithm looks `O(n)` to me, actually faster than it would be if there was sorting involved.  The key steps are `n - 1` calls to the supplied comparator, a similar number of comparisons, and some probably smaller number of calls to `slice` and `push`, as well as various assignments.  Am I missing something? 

  3. This behavior is very intentional.  The behavior of `groupBy`, for objects, does group all of the related properties into separate elements.  And you can do that for lists as well by sorting first if that's what you want.  But the current behavior also allows you to collect sequential runs of related elements, which can be powerful.  The function is actually changing in a way to make this a bit more flexible. (#2012, #2016)

**Comment by briefy** [comment]
@jeiea  thx, i adotped groupBy

**Comment by briefy** [comment]
@CrossEye   Based on the issue below, i think slice is O(n)
[https://github.com/tj/node-thunkify/pull/12](url)

however,i think what you said  pretty make sense,i choose to close the issue,
Thanks a lot !
