### ISSUE TITLE
More than 10 arguments in R.lift?

### ISSUE THREAD

**Issue by philipyoungg** [ramda/ramda#2028]
I'm making an app to convert sets of array from user input into a cartesian product. Example on http://typography.philipyoungg.com 

Based on schema below...
``` javascript
title: {
      type: 'text',
      properties: {
        fontFamily: ['Lato', 'Playfair Display', 'Open Sans'],
        fontSize: ['3rem'],
        fontWeight: [500, 'bold'],
        fontStyle: ['normal'],
        textTransform: ['none', 'uppercase'],
        color: ['#333', 'mediumblue'],
        lineHeight: ['1.2'],
        marginBottom: ['8px'],
        letterSpacing: ['-0.025em'],
        text: ['Guns, Germs, and Steel'],
      },
    },

R.compose(R.apply(R.liftN(10, R.unapply(R.identity))), R.values, R.prop('properties'))(title)  // <— works well
```

I tried to add more than 10 array and got an error.
`First argument to _arity must be a non-negative integer no greater than ten`

I've tried to read the source code and it seems LiftN limit this to 10.

So I tried this.

```javascript
const arg12 = (a, b, c, d, e, f, g, h, i, j, k, l) => [a, b, c, d, e, f, g, h, i, j, k, l];
R.lift(arg12))(title)
```
and the same error still produced.

How do I solve this?

**Comment by CrossEye** [comment]
Back in #372 and #373, Ramda made the decision not to support functions of more than ten parameters.  We thought that overgenerous, thinking that more than three or four was already on pretty shaky grounds.

Although we'd certainly never thought about a case like yours, I also don't see an easy way to relax the constraints to allow it.

Any suggestions are welcome.

**Comment by philipyoungg** [comment]
@CrossEye Just looked at the source code. Now understand that it'll change Ramda's `arity` function. Guess it's easier to use another library to create the cartesian product.

Appreciate your help! Ramda is a fantastic library. 💪

**Comment by CrossEye** [comment]
@philipyoungg:

I'm glad you found something that works.  That looks like a nice implementation.  Ramda's [`xprod`][xp] is meant only for two lists.  But you can fold over it with something like

```js
const xproduct = lift(reduce(pipe(xprod, map(flatten))))(head, tail)
```

(That would take a list of lists.  To get the same variadic API, just wrap it in an `unapply`.)

Or you could create a version much like the one shown using Ramda functions with something like

```js
const xproduct = unapply(reduce(
  (acc, set) => unnest(map(x => map(y => [ ...x, y ], set), acc)),
  [[]]
));
```

I'm not suggesting either.  The function you found looks nice.  I just wanted to point out some of the Ramda options.

  [xp]: http://ramdajs.com/docs/#xprod

**Comment by philipyoungg** [comment]
@CrossEye that's cool! Gonna change it to yours.

Could you help me understand the first `xproduct`?
```javascript
const xproduct = lift(reduce(pipe(xprod, map(flatten))))(head, tail)
```
Been stuck for hours trying to understand it...

**Comment by CrossEye** [comment]
I would, except that it's the horrible result of sleepiness.  I solved the same problem twice in two different ways in that solution.  A much, much better version is the simpler:

```js
const xproduct = reduce(pipe(xprod, map(unnest)), [[]])
```

Again, this could be wrapped in `unapply` if you don't like making a list out of your inputs.

----------

If you really want to understand what was going on in that solution, a naive version would be to wrap up the results of `xprod` in some sort of fold.  Since this is `xprod`:

```js
xprod(['small', 'medium', 'large'], ['red', 'green']);
//=> [["small", "red"], ["small", "green"], ["medium", "red"] /*,  ... */]
```

would this be enough?:

```js
const xproduct = reduce(xprod, [[]])
```

No, because with this version, 

```js
xproduct([['small', 'medium', 'large']])
//=> [[[], "small"], [[], "medium"], [[], "large"]]
```

And here I went down the wrong path.  Ramda has not had `foldl1` since way back in #20.  But it's a clear thing to want, a fold that takes its initial accumulator from the head of the list.  I wrote a quick wrapper to allow this function to grab the initial accumulator from the head, rather than supplied as `[[]]` separately.  

```js
const xproduct = lift(reduce(xprod))(head, tail)
```
I do this with [`lift`][li], with the interpretation that I lift a function (`reduce(xprod)`) that operates on two values into one which operates on *functions* which return those values.  So I will pass one list into the result, which will be passed to both `head` and `tail` and then `lift` will pass the two resulting values into `reduce(xprod)`.  I could have done something very similar with [`converge`][co], which is slightly more powerful.  But `converge` is very much Ramda-specific, whereas `lift` is well known in the FP world.  If I don't need `converge`'s additional power, I will stick with `lift`.

This now works as expected for that first case:

```js
xproduct([['small', 'medium', 'large']]);
//=> ["small", "medium", "large"]
```

And it works for the next case:

```js
xproduct([['small', 'medium', 'large'], ['red', 'green']);
//=> [["small", "red"], ["small", "green"], ["medium", "red"] /*,  ... */]
```

So I could hope I was done....  However, there was a problem:

```js
xproduct([
  ['small', 'medium', 'large'], 
  ['red', 'green'], //, 'blue']
  ['shirt', 'jeans', 'shoes']
]);
//=> [[["small", "red"], "shirt"], [["small", "red"], "jeans"], [["small", "red"], "shoes"], 
//    [["small", "green"], "shirt"] /*, ... */]
```

I could see a fix for this problem.  I had to do one level of flattening as I went.  Ramda has [`flatten`][fl] and [`unnest`][un] for this.  I'll blame sleepiness for my not realizing that I could have just chosen the simpler `unnest`. So I had to change my simple `xprod` step in the fold to `pipe(xprod, map(flatten))`.

```js
const xproduct = lift(reduce(pipe(xprod, map(flatten))))(head, tail)
```
And this works for all our cases.  I sent my note (forgetting to note that this wouldn't work properly for the empty case because of the `head` call), responded to a few more issues and went to bed.

But what I didn't think about was that this second fix, adding the `flatten`, also fixed the initial problem I had as well.  I didn't need the whole `lift`/`converge` solution at all!

So this is a much better solution:

```js
 const xproduct = reduce(pipe(xprod, map(unnest)), [[]])
```
(`unnest` doesn't try to delve deeper to flatten nested lists, so it's probably better than `flatten` here, although I haven't looked back at the implementation in a while.)

So the moral of the story is not, "Don't code when you're sleepy."  It's just "Don't publish your code when you're sleepy!"  :smile:

  [co]: http://ramdajs.com/docs/#converge
  [fl]: http://ramdajs.com/docs/#flatten
  [li]: http://ramdajs.com/docs/#lift
  [un]: http://ramdajs.com/docs/#unnest

**Comment by philipyoungg** [comment]
@CrossEye fantastic. Thank you for dissecting the function step by step. Read it several times, and now starting getting hang of it. Really appreciate your help for this!

By the way, wouldn't change `xprod` to

```javascript
const xproduct = unapply(reduce(
  (acc, set) => unnest(map(x => map(y => [ ...x, y ], set), acc)),
  [[]]
));
```

...makes more sense ? It accept `n` number of arguments and return the cartesian product, while `xprod` limit it to two. ☺️

**Comment by CrossEye** [comment]
@philipyoungg:

It might make sense to have such a function in place of or alongside our simple `xprod`.  We would definitely not want exactly that version (with the `unapply`) as Ramda avoids variadic functions.  But one that took a list of lists might be a good idea.

I don't get the sense, though, that this is one used much in Ramda.  It's there because in the early days there was no one to stop me putting in functions I personally found useful even if they weren't generally applicable.  :smile:

So perhaps the best bet would be to get this on in the [Cookbook][co] and then think about moving it to the main library if there are further requests for it.


  [co]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by philipyoungg** [comment]
@CrossEye 

Agree with your view. The unapply isn't really needed. 😊 

Yes, I believe `xprod` is a very specific case and not very general function (unlike map, reduce, etc). But I think it'll helps a lot of people using this in the future.

My reasoning:
1. There's already `xprod` in Ramda. 
2. `xprod` only take 2 arguments, meanwhile eddmann's implementation took `n` number of list. Hence: more flexible.

…therefore, there's actually no loss at all implementing this one.

By the way, I'm really intrigued by your `xproduct` function before and explore it more deeply—especially the `lift` function. So I took my time to learn it and try to help the community back by answering this http://stackoverflow.com/questions/39545916/how-come-i-can-pass-functions-to-a-lifted-r-divide/41411109#41411109.

All credits to you, @CrossEye! 🤘

p.s. Happy New Year!

**Comment by venba** [comment]
My application is built in react redux which has more than 10 properties in the state. When I tried to bind the redux state with ramda, I see the above error. 

I have looked on the source code, changing the default switch in _arity.js and nAry.js seems fixed the issue. 
```js
default:
        return function (...args) {
          return fn.call(this, ...args);
        };
```

**Comment by CrossEye** [comment]
@venba: We will switch to something like that after v1.0.  Current versions of Ramda still support ES3/ES5.

**Comment by Kinrany** [comment]
I had trouble trying to type this function in TypeScript. Here's my best attempt that actually works:

```typescript
const nxprod = <T>(list: T[][]) =>
  list.reduce(
    (newlist, domain) => R.xprod(newlist, domain).map(([xs, y]) => [...xs, y]),
    [[]] as T[][]
  );
```

It's not point-free, and I had to replace `unnest` with an explicit append function. (Which should be equivalent to `flip(append))`, but somehow isn't)
