### ISSUE TITLE
TypeError: fn is not a function

### ISSUE THREAD

**Issue by waitingcheung** [ramda/ramda#2042]
I am studying the usage of the function ``liftN`` and I observed some interesting behaviour.

I have the following code as initialization:
```js
var addN = function() {
  return R.reduce(function(a, b) { return a + b; }, 0, arguments);
};

var addN2 = R.liftN(2, addN);
var addN3 = R.liftN(3, addN);
var addN4 = R.liftN(4, addN);
```

If I call ``addN3``,
```js
console.log(addN3(['Hello', ''], ['World'], ['!']));
```

I expect the following result.
```js
[ 'HelloWorld!', 'World!' ]
```

However, the actual result has a leading zero.
```js
[ '0HelloWorld!', '0World!' ]
```

If I call ``addN2``,
```js
console.log(addN2(['Hello', '', ], ['World', ], ['!', ]));
```

I expect to have the intermediate result.
```js
[ 'HelloWorld!', 'World!' ]
```

However, I am getting a TypeError.
```
            result[idx] = fn(functor[idx]);
                          ^

TypeError: fn is not a function
    at _map (/path/ramda.js:277:27)
    at map (/path/ramda:6130:20)
    at /path/ramda.js:558:23
    at f2 (/path/ramda.js:442:22)
    at XWrap.f (/path/ramda.js:6882:33)
    at XWrap.@@transducer/step (/path/ramda.js:372:25)
    at _arrayReduce (/path/ramda.js:5303:46)
    at _reduce (/path/ramda.js:5333:24)
    at ap (/path/ramda.js:6881:9)
    at XWrap.f2 [as f] (/path/ramda.js:442:22)

```

If I call ``addN4``,
```js
console.log(addN4(['Hello', '', ], ['World', ], ['!', ]));
```

I expect the following result.
```js
[ 'HelloWorld!', 'World!' ]
```

However, I am getting a function as a result.
```js
[Function]
```

**Comment by CrossEye** [comment]
I haven't dug in to see why you're getting the specific results you achieve except for the first error.  The leading zeros you get are from

> ```js
> var addN = function() {
>   return R.reduce(function(a, b) { return a + b; }, 0, arguments);
>                                                     ^^^
> };
> ```

If you used `''` there instead, you wouldn't have the leading zero issue.

Mainly, I don't understand what you're trying to do with this.  `liftN` is mostly useful as the underlying implementation of `lift`.  It is publicly exposed because it is occasionally useful -- in precisely circumstances like this when you have a variadic function that you want to fix an arity for and lift to the realm of containers.  At that point, the resulting function will accept exactly `n` containers holding your values.  The behavior if you supply more is certainly odd, and maybe buggy, but I can't see why it would be as you are expecting.

We do need to expand the documentation, as the behavior on lists is one of its least useful abilities.  If you're just playing around with it to see how it works, you might try playing with other types.  For instance with `Maybe`s:

```js
const R = require('ramda');
const Maybe = require('data.maybe');
const square = n => n * n;
const squareM = R.lift(square);

squareM(Maybe.Just(5)); //=> Maybe.Just(25)
squareM(Maybe.Nothing()); //=> Maybe.Nothing()
```

If that makes sense, then look at something a little more complex:

```js
const average = R.lift(R.divide)(R.sum, R.length);
average([8, 6, 7, 5, 3]); //=> 5.8
```

The point here is that the functions `sum` and `length` are also containers that can be lifted over.  So when we lift `divide` from a function of two values into a function of two containers of such values, those containers can be functions that yield such values.

But without digging into *why*, this one would fail with the error you saw when you tried to apply it if you were to define it with more parameters than `divide` takes, e.g. `average = lift(divide)(sum, length, head)`.  Garbage in, garbage out.  At some point when I'm not so fuzzy-brained, I will try to investigate what's actually happening.
