### ISSUE TITLE
Is it guaranteed that keys and values are enumerating in the same order?

### ISSUE THREAD

**Issue by brucou** [ramda/ramda#2065]
`R.values` 

> Returns a list of all the enumerable own properties of the supplied object. Note that the order of the output array is not guaranteed across different JS platforms.

My question is whether `values` and `keys` do enumerate in the same order. Basically I want to do

`c = someFn(zipObj(keys(a)), values(b))` where a and b have the same list of keys, but a `c` key will be matched to the right value only if both ramda functions enumerate in the same order.

**Comment by davidchambers** [comment]
The order of arrays returned by `R.keys` and `R.values` should not be relied upon. One should use `R.toPairs` when one wishes to keep keys and values paired. For example:

```javascript
const pairs  = R.toPairs(o);
const keys   = R.map(R.nth(0), pairs);
const values = R.map(R.nth(1), pairs);
```

Since you have two objects you'll want to do something like this instead:

```javascript
const aPairs = R.sortBy(R.head, R.toPairs(a));
const bPairs = R.sortBy(R.head, R.toPairs(b));
```

I'm confused, though, as to why you're using `keys(a)` if `a` and `b` have the same keys.

**Comment by brucou** [comment]
Is there a better way? Basically I have `[keys]: validateFn` on a, and `[keys]: Stream<T>` on b, and I want `[keys]: validateResult`

**Comment by davidchambers** [comment]
I suggest something like this:

```javascript
const keys = R.keys(a);
const result = R.zipObj(keys, R.map(k => a[k](b[k]), keys));
```

**Comment by CrossEye** [comment]
This has been under discussion for a long time.  You can see what turned out to be a very controversial suggestion in https://github.com/ramda/ramda/issues/1067#issuecomment-135923353.

As a matter of practice, enforced by recent specification, modern JS engines will enumerate objects in a fixed order.  But that order has nothing to do with the keys themselves, but only with the order in which they were added to the object.  Thus,

```
Object.keys({foo: 1, bar: 2}); //=> ['foo', 'bar']
Object.keys({bar: 2, foo: 1}); //=> ['bar', 'foo']
```

That is not particularly useful for Ramda, which likes to consider those two values equal.  Perhaps when I bring this issue back up, I'll get enough buy-in.

**Comment by brucou** [comment]
Good to know and that sounds a sensible choice, those two values are indeed the same for most purposes. That said, independently of the order of the keys enumeration, it is enough that `keys` and `values` do have the same ordering method, no matter what that is. Of course the safest is not to rely on extraneous assumption, I'd agree with that.

**Comment by brucou** [comment]
And thanks David for the suggestion. That `k => a[k](b[k])` actually came up in a few of my scripts. Is there a name for such a combinator?

**Comment by davidchambers** [comment]
> Is there a name for such a combinator?

A combinator is a function which only references its arguments; `k => a[k](b[k])` references `a` and `b` from outer scope. I don't know a name for this function. It looks like some sort of zipper.

**Comment by brucou** [comment]
ah sorry I was more thinking about `strMap (u -> v) -> strMap (t -> u) -> str -> v`. I am not used to ramda types, so there might some errors here. This might be generalized to more than two function easily.
