### ISSUE TITLE
Explore the possibility of using c binding for nodejs

### ISSUE THREAD

**Issue by Rafi993** [ramda/ramda#2079]
I know this will cause fury among users. But I think we should explore the possibility of using c bindings for ramdajs for node as a seperate subrepo. So that ramdajs can deal with very large arrays.

**Comment by CrossEye** [comment]
I haven't run into issues with array size.  What size arrays are causing you issues, and how would you go about writing c bindings?

**Comment by Rafi993** [comment]
@CrossEye  I have not have had issue in daily usage with array size with ramdajs. But I have been experimenting with the possibility of dealing with very large arrays to read and process more than a gb of csv files in js. I could'nt find decent library that provides those functionality. But considering the awesome function set that ramdajs provides I it had C bindings that might help it deal with those array size. It would be awesome as a seperate sub repo.

**Comment by Bradcomp** [comment]
> I haven't run into issues with array size. What size arrays are causing you issues...

For what it's worth, I use Ramda for fairly large scale data processing (CSV's with around 80K rows, thousands of log records, etc.).  While not directly related to the original issue, maybe my experience is helpful.

I've run into a couple issues that have caused me to refactor from using Ramda builtins to rolling my own algorithm.  In both cases I don't know if dropping to C would help, swapping out my algorithms gave me significant performance increases though.

1.  Set operations (namely `difference` in my case) are O n^2, and check the output in addition to the input arrays for the value on each iteration.  This makes sense because it can't assume that the values passed in are a set, but is a significant performance hit, and using the native Set was the only way to get my algo's to actually finish running in a reasonable amount of time.

2. Traverse is _really_ slow on a large array.  This is, in a sense, necessary due to the generality of the function. Because it's necessary to work on _any_ traversable and applicative, it can't use internal mutation to speed things up and reduce memory usage. By switching to a `reduce` that was aware of the internals of my data structure I was able to improve execution time by over 10x.

**Comment by svozza** [comment]
Without wanting to sound glib but if you're processing arrays that are over 1Gb in size, is JavaScript really the best choice?

**Comment by Rafi993** [comment]
@svozza I said I was experimenting. http://cs.stackexchange.com/a/4648

**Comment by CrossEye** [comment]
I'd be interested in seeing what experiments someone might try.  But my C is very rusty and wasn't particularly strong to start, so I wouldn't be much of a contributor.

I wouldn't be adverse to putting something like this in the ramda/* family, but I think we'd have to see what someone could come up with first.
