### ISSUE TITLE
Omit by function?

### ISSUE THREAD

**Issue by vkarpov15** [ramda/ramda#2084]
Lodash has a neat way to remove all null and undefined keys from an obj: `_.omit(obj, v => v == null)`. Currently `omit()` only accepts strings - can y'all make it optionally take a function parameter?

**Comment by rickmed** [comment]
@vikfroberg it works work me R.omit(['a', 'undefined', 'null'], {undefined: 1, b: 2, null: 3, d: 4});

**Comment by Bradcomp** [comment]
`R.filter` and `R.reject` will work on objects in the way you envision they would: https://goo.gl/Od3t5g

```
const o = {a: null, b: 'yo', c: 'hello there', d: 12}

filter(is(String), o)  //{"b": "yo", "c": "hello there"}
reject(isNil, o)       //{"b": "yo", "c": "hello there", "d": 12}
```

**Comment by vkarpov15** [comment]
Oh ok, thanks @Bradcomp I missed that when looking at the docs. Sorry for the noise and thanks for the great work :+1: :rocket:

**Comment by barelyfitz** [comment]
One difference, lodash omitBy seems to pass (value,key) to the function, while R.filter and R.reject only pass the value. So if your lodash code is using botht he key and value you might not be able to directly replace the cdoe without some refactoring.

**Comment by adispring** [comment]
const filterByKV = (pred, obj) => compose(
  fromPairs,
  filter(([k, v]) => pred(v, k)),
  toPairs
)(obj)

**Comment by CrossEye** [comment]
@barelyfitz:

> So if your lodash code is using the key you might not be able to directly replace the cdoe without some refactoring.

That is not at all unusual.  Ramda was never intended to be a drop-in replacement for lodash.  It's designed on different principles.  While we do draw some inspiration from other JS libraries such as Underscore and lodash, our chief inspiration is other functional languages, those of the LISP family and the ML one and other languages such as Erlang.  That there is as much overlap as there is with lodash is mostly a function of shared inspiration from these languages.

Lodash's functions often have many more configurations than their closest Ramda cousins.  This is quite intentional on our part.  We try to keep the API as simple as possible.  Lodash focuses a bit more on flexibility and power.

**Comment by phhu** [comment]
See also omitBy function in ramda adjunct: https://char0n.github.io/ramda-adjunct/2.26.0/RA.html#.omitBy
```js
const isLowerCase = (val, key) => key.toLowerCase() === key;
RA.omitBy(isLowerCase, {a: 1, b: 2, A: 3, B: 4}); //=> {A: 3, B: 4}
```
