### ISSUE TITLE
Add pluckWithPath ?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2096]
we now have pluck = map(prop), which can pick 'first level' object's property in list. 
pluckWithPath can pick any nest property with specific path, which can be defined as map(path):
```js
module.exports = _curry2(function pluckWithPath(p, list) {
  return map(path(p), list);
});
```
used as follows:

```js
const data = [
  {
    a: {
      b: 1,
    },
  },
  {
    a: {
      b: 2,
    },
  },
];
pluckWithPath(['a', 'b'], data); // => [1, 2]
```

**Comment by CrossEye** [comment]
Sorry, just catching up.  I'd like to hear that there's more support for this before just suggesting this for the Cookbook.  Because the implementation is so simple (and so in line with standard Ramda composable practices) I think there should be a strong need before including this directly in the library.

**Comment by polytypic** [comment]
Operations like these, that address elements deep inside data structures, are simple with optics.  Also, with optics you get more than just a read operation to collect the elements.  Here is [the example from the original issue with Partial Lenses](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBtAUAbywgLhjwCMiBGAGiwF9q7d8jSiAmejrAXSy1ElhQATggBuAUyEQEAGzSYAMgDpxM8QFsIlGAHIEO7TpI6eWGSADmAChjLQMtcChXhYydJnbEyAJQwfZpY2yuogcACWAGYAni4iElKy2gBKSuFgwF5ICH4B5ta2ShAArupxbome8Nm5vAD0dTBKzQhgcDDqxcAAFh0gQuJAA).

**Comment by adispring** [comment]
OK, I'll close this issue.
