### ISSUE TITLE
Add pipeMerge ?

### ISSUE THREAD

**Issue by JoshWhite** [ramda/ramda#2122]
I've implemented in a recent project and find it pretty useful. Before I create a proper pull request for this, do you think it is a viable option?

Any comments on how better it could be handled/match ramda's style?

```
// basic data
const data = {
    name: "Josh"
}

const defaults= {
    taxonomy : "human"
}

// new method to pipe through given factory functions and merge the results
const pipeMerge = function() {
    const argumentsArray = Array.prototype.slice.call(arguments);

    //used my own, but must be a node module
    const isFunction = obj => {
        return !!(obj && obj.constructor && obj.call && obj.apply);
    }

    return (data) => {
        return R.merge(
            data,
            argumentsArray.reduce((sum, current) => {
                return isFunction(current) ? R.merge(sum, current(sum)) : R.merge(sum, current);
            }, data)
        )
    }
};

// simple factory 1
const eaterFactory = (data) => {
    return {
        eat: () => console.log(data.name + ' is eating!')
    }   
}

// simple factory 2
const drinkerFactory = (data) => {
    return {
        drink: () => console.log(data.name + ' is drinking!')
    }   
}

// each factory is called with the result of the piped factory or object, each object is merged
const josh = pipeMerge(defaults, drinkerFactory, eaterFactory)(data)

josh.eat();     // "Josh is eating"
josh.drink();   // "Josh is drinking"
josh.taxonomy;  // "human"
```

**Comment by BnayaZil** [comment]
`composeMerge` could be good idea too...

**Comment by CrossEye** [comment]
@JoshWhite, @BnayaZil:

I'm sorry; this somehow slipped through the cracks.  I only noticed it when trying to clean up old open issues.

My initial thought is :-1: for two reasons: First, I don't feel that Ramda should be in the business of helping promote any particular style of OOP. Ramda is about FP, and should simply stay out of such questions.  Second, Ramda tries to avoid APIs with mixed data types, such as expressed by this:

```js
    return isFunction(current) ? R.merge(sum, current(sum)) : R.merge(sum, current);
```

Yes, we sometimes do use SumTypes, but usually there we have a clear abstraction.  Here the abstraction that contains both "Object" and "function which returns an Object" is a little hard to see.

So that's my take.

I'm going to close this issue now, as it's not gathered any attention, and as I'm trying to clean up as many issues as I can.  But if you want to reopen it, that's fine.  (If you can't do so on your own, just ping me.)
