### ISSUE TITLE
R.clone is really slow

### ISSUE THREAD

**Issue by awb99** [ramda/ramda#2134]
R.clone is quite slow. I process 1000 invoices; each invoice has 5 lineItems on average, So I am 
running R.clone 5000 times. The documentation should have some kind of warning, under which circumstances it is slow. 

```
function PackingList ( invoice ) {
    var packingList = invoice.LineItems;
    packingList = R.filter ( lineItem => !invoiceCost.IsNotShippable(lineItem), packingList );
    packingList = R.filter ( lineItem => (lineItem.ProductFound===true ), packingList );
    packingList = packingList.map ( lineItem => R.clone (lineItem) ); // we will modify the quantities, therefore we need to clone$
    R.map ( lineItem => lineItem.Quantity = parseFloat (lineItem.Quantity), packingList);
    R.map ( lineItem => lineItem.ProductWeight = lineItem.Weight /  lineItem.Quantity , packingList);
    return packingList;
}
 ```

**Comment by svozza** [comment]
I would expect a deep clone to be slow.

**Comment by awb99** [comment]
@svozza : Sure it is somehow slow, but I have numbers that are crazy: loading from db and doing all calculation: 100ms (without cloning). With cloning: 30 seconds!  The slowest operation is the database access. The cloning should not be slower than the db operation.

**Comment by svozza** [comment]
What does `lineItem` look like?

**Comment by awb99** [comment]
@svozza Really simple. 5 properties only. I use mongoose to load them from the database; this wraps getter and setter functions around the lineItems. I assume that this is the culprit.

**Comment by awb99** [comment]
@svozza I can do more detailed studies on this issues, if this might lead to the discovery of a performance problem in R.clone.

**Comment by svozza** [comment]
That would be great! These objects don't happen to have a `clone` method on their prototype? `R.clone` will dispatch to that if present.

**Comment by awb99** [comment]
Not sure yet. Will setup a test for that.

**Comment by CrossEye** [comment]
@awb99: Any news on this?  I'm curious to see what's up.

**Comment by Bradcomp** [comment]
It's likely that `clone` is copying all the mongoose cruft that gets attached to the records.  Do you still have the extensive slowdown if you're doing a `lean` query?

**Comment by awb99** [comment]
Hi! I am doing some refactoring, to make sure I can properly isolate the issue. I will post in a few days, when I have an update.

**Comment by awb99** [comment]
@CrossEye It is definitely mongoose issue. When I clone all properties that I am using,and then call R.clone, then it is fast.

**Comment by Fi3** [comment]
I have the same problem [here](https://github.com/Fi3/KyVe/blob/master/js/MemoryDb.js#L407). It take like 1.5 seconds for copy an object with 6K keys like the one below:

    Q88nDuFIygmunqlL7Isi:
      { collisionFlag: 0,
      , nextPosition: 298119
      , value: 'FTB0FIWZ7umcUYsmMyNe'
      , position: 298272
      , previousKey: '5IndNFT2dzXdQxK4NuVB'
      , nextKey: 'NVifjc1bEb9g54jGOyaV'
      , normalizedIndex: 5854
      , previousActualIndex: 1382654102
      }

**Comment by CrossEye** [comment]
@Fi3:  If you want only a shallow clone, then [you can use `merge({})`](https://goo.gl/TYKPbV).

```js
clone(obj);  // takes ~650ms on an ancient machine

merge({}, obj); // takes ~5ms on that machine
```

**Comment by romgrk** [comment]
Getting slowness issues as well. Ramda's implementation is about 17 times slower than lodash's `cloneDeep` or JSON parsing.

```
json: 33.591ms (o => JSON.parse(JSON.stringify(o)))
ramda: 626.155ms (o => R.clone(o))
lodash: 36.323ms (o => _.cloneDeep(o))
```
After warmup, testing is done with 10,000 iterations of cloning [this](https://paste.ee/p/LNvsR).

**Comment by rahulthewall** [comment]
We just came across this issue, was using ramda to clone state objects in redux. For now we have switched to `JSON.parse(JSON.stringify(o))` but it would be nice to know if an enhancement is on the horizon.

**Comment by CrossEye** [comment]
We're certainly open to PRs designed to speed this up.  I think lodash's `cloneDeep` has similar functionality, so we could look to its implementation for inspiration.  But I don't recall if there are substantive behavior differences that Ramda wants to support that are responsible for this speed issue.

**Comment by danillosl** [comment]
I just made a pool request with a modified _clone function [2985](https://github.com/ramda/ramda/pull/2985), with this modification the ramda.clone() goes from 93.228ms to 6.829ms on average after 100 iterations cloning this [object](https://paste.ee/p/LNvsR).

comparison between ramda lodash and JSON.parse(JSON.stringify(obj)) before:

max/min/avg time in ms after 100 runs
ramda clone():                               max: 124.229 min: 90.160 avg: 93.228
lodash cloneDeep():                      max: 26.819 min: 10.101 avg: 11.643
JSON.parse(JSON.stringify(obj)): max: 17.482 min: 9.535 avg: 10.851

and after : 

max/min/avg time in ms after 100 runs
ramda clone():                               max: 35.512 min: 4.916 avg: 6.829
lodash cloneDeep():                      max: 26.919 min: 9.832 avg: 10.937
JSON.parse(JSON.stringify(obj)): max: 19.063 min: 9.525 avg: 10.542

**Comment by CrossEye** [comment]
This is great to hear!  This performance has always been a bit of a bane.

However, until we hit 1.0 (which hasn't entirely stalled but has again slowed down), we're supporting older versions of the language, ones that do not include the global object `Map`.  I have more detailed notes in #2985.

**Comment by verdy-p** [comment]
I have also seen that more recent version of Mediawiki (or Scribunto) is gowiong slower and slower over time, with pages in Wikimedia now exploding their rendering time limitation of 10 seconds, only because  `recursiveClone (mwInit.lua:41)` can take more than 5 seconds alone, when in the past it took just a few hundreds of milliseconds.

It seems that this is caused not by Lua itself, but by Scribunto on the interface between Lua and PHP/Mediawiki when passing parameters or returning values. I don't know what it does not, but a "deep clone" is really overkill, when this interface is just supposed to pass strings of text. But it seems that Scribunto needs it to build temporary arrays. The same occurs in the Scribunto  module for Wikibase. Scribunto does not properly reuse the arrays and string buffer it needs to isolate each other's runtime environment. I understand that such isolation is needed, but Scribunto does not seem to use any pool of objects.

So if a wiki page makes frequent calls to Lua modules via Scribunto (mwInit.lua), or if Scributo modules make frequent calls to the MediaWiki API to use "mw.preprocess()", this is visibly where most of the time is lost now.

In Wikimedia, some pages may work... sometimes... but not later when refreshed, depending on which server will run the rendering (not all servers have the same performances, but there's no way to predict which one will do that and visibly they are not properly balanced, so the execution time varies really a lot, notably for mwInit.lua !). And a page may be forced rendered at any unpredictable time (without any change in the source). I've seen that servers in the "mw13xx" range are much slower (and will break these pages, then storing in the cache broken renderings) than servers in "mw14xx" range.

Scributo now urgently needs a performance analysis (this is already needed for Wikibase/Wikidata infoboxes, but as well in various statistics pages making many different calls to Scribunto modules, which cannot be optimized and cached because these are calls with many different parameters, so the template/module expansion cache does not help... and in fact iot may even worsen the rendering performance of these pages).

All we can do now is to limit the number of Lua/MediaWiki transitions:
* we can keep more cached values in Lua itself (in varaibles that are kept in the Lua VM across multiple invokations)
* we should limit the number of calls to `mw.parse*` functions
* we should have a way to get the $wgPageLanguage (built in the PHP API) without having to expand `{{int:Lang}}` from Lua with a call to the Mediawiki parser (for now it's impossible, there's still no `mw.*` variables for that in the mw package for Scribunto, and no builtin array of strings containing `$w*` variables exposed in the PHP API).
* Scribunto must extend what can be safely exposed from the Mediawiki PHP API (notably all variables that won't change during when rendering the same target Wiki page with the same context). For now this Scribunto interface is too weak and generates huge costs if script have to rely on performing a recursive call to the Mediawiki parser.

**Comment by romgrk** [comment]
For anyone interested in performance improvements, I recommend using [rambda](https://github.com/selfrefactor/rambda), drop-in replacement for ramda.

**Comment by CrossEye** [comment]
@romgrk:

Well, maybe [not entirely][rb] a drop-in replacement:

> Click to see the full list of 89 Ramda methods not implemented in Rambda

:wink:

   [rb]: https://github.com/selfrefactor/rambda#-missing-ramda-methods

**Comment by CrossEye** [comment]
@verdy-p: That's interesting stuff, but as far as I can tell, you're talking about Lua and PHP.  Is this related to Ramda, or to the slow-clone issue under discussion here?

**Comment by verdy-p** [comment]
My purpose was moregeneric than that, and in fact what I was exposing is a problem in Lua itself for not providing a correct or sufficient resource management system. First its implementation of tables has known issues (some of them very severe and easily reproducible, allow unbound use of resources, in terms of both CPU time and memory space), but also the way Lua can be integrated within other existing environment is not well studied: it has been only tuned when running from a single process, and its intiialization is very slow (causing major problems for other kinds of integrations, notably inside other VMs or containers).
And we already see security issues, and each attempt to fix them causes a major degradation of performances (notably in CPU time: the fixes are still focusing only the memory space, ignoring all other metrics).
So recent changes in all exeting intergations causes sudden spikes in CPU time, and there's no ezasy way to monitor the execution time. In any shared environment, there's a hard limit, a quota in execution time: we already see numerous reports in many Lua projects, about the time taken only for the isolation layer: starting a Lua instance, or passing data to Lua or from Lua in memory or via any other storage space takes considerably longer time and its CPU time is constantly growing (and not by small factors: we can see such factors like 2 or 5. This means that any modest update of Lua make a working application or service written in Lua broken (and it's really difficult to find other ways to optimize the Lua code: when we try, we just save some space, but actually no CPU time or very small improvements (and this is done by a real complexification of the Lua code, tracking to find anything that could be saved: we study the execution profiles, we only optimize small spots, but the major hotspot is not optimizable at all and not acesssible directly in Lua, and not even from the containing environment).
This is a symptom that Lua lacks a resources manager and its own integration API is insufficient to correctly track the problem (even attempts to profile apps cause additional costs, that are also growing over time without even changing any thing in this integration code).
This raises questions about the usafe and long term usage of Lua in shared environments.

May be it's time to think about rewrite Lua not on native code (with its base code written in C/C++), with help of an isolation/sandboxing layer, but directly in the hosting VM code itself (several candidates are possible: Python seems a good choice, as well as Java or Javascript, PHP apparently does not. And then provide a resources manager in the hosting environment rather than Lua itself (visibly the attempt to to that in a separate integration layer, like Scribunto for MediaWiki, is failing, and no one knows for now how to fix that, given the too simplist model used by Lua, where resource management is simply completely ignored).

Note that I found rthis thread when lokking at varuous discussions about slow R.clone: this is not a problem specific to Ramda here, but it is found in lot of other projects using other integration methods: Lua is still very difficult to integrate correctly, and as a result the Lua code must be written specifically for each environment, and we see that reusable libraries for Lua are almost inexistant (we just find some small "codelets" working in limited cases and specific environments, but adding their own problems in others, and there's still no good practices). There's an attempt in "Lua Rocks", but we are very far of what would be needed, and I see in fact no one using "Lua Rocks" solutions directly without needing to patch it; and worse, most environment are reluctant to update Lua itself: it requires really too much work to assert again the code and fix lot of new perfomance problems (some former fixes in Lua code have to be reverted or inverted, and other solutiosn need to be tested to see if they have a notable positive impact).

There's no such major problem with Python, Rust or Javascript (even if there are still works needed to secure them) but both allow these languages to support virtual hosting (e.g. running a WebAssembly in a Javascript VM, or Node.js, and the common libaries for Python, or Perl are also very large now: they are easy to integrate, easy to update for security fixes, or upgrade for new features, without causing major degradation of performance or exhaustion of reasonable quotas.

Your talk here in Ramda is still interesting, and I am still looking for solutions that other projects would have found and what can be reproduced or ported in other environment if this can solve their existing integration problems.

**Comment by CrossEye** [comment]
@verdy-p: I'm afraid that these messages are out of place.  You're posting them on the discussion of an issue users have raised for Ramda.

**Comment by verdy-p** [comment]
May be, but this problem is definitely not specific to Ramda, and seen in various projects using Lua. Many are looking for a solution and there's still no common satisfactory one (some solutions truing to profiles the use cases are even adding their own cost, in the profiler itself, a sign that Lua still does not properly support independant instrumentation like there's in other languages or VM like Java, Python, PHP...). The solutions proposed are then hard to evaluate, we never know if this will optimize things or if it will be stable over time or with other updates of Lua or in the underlying OS as the measured performances are extremely unstable and hard to reproduce.
