### ISSUE TITLE
Map signature and description are wrong

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#2166]
I guess this was mentioned somewhere (otherwise I'd be very suprised). 
But I've failed to find, so:

http://ramdajs.com/docs/#map

> Functor f => (a → b) → f a → f b

> Takes a function and a functor, applies the function to each of the functor's values, and returns a functor of the same shape.

```js
R.map(R.identity, "abc") // ["a", "b", "c"]
```

Isn't that a Haskell-ism? JS and most other languages do not unify `String` and `[Char]`.

**Comment by CrossEye** [comment]
That's an accident of implementation, not one that we would want to document.  Since our signatures, in this loosely typed language are not enforced, we describe *aspirational* signatures.  Sometimes Strings act a bit like lists, but we haven't added any checks to ensure they don't.  `map` is already one of our fairly complicated functions.  (https://goo.gl/cqO2h6)  Adding more to it scares me.
