### ISSUE TITLE
how to toggle value

### ISSUE THREAD

**Issue by roopkt** [ramda/ramda#2210]
Say I have nested object and I want to toggle one of its Boolean properties is it possible without fetching its value ? In below example I want to toggle expanded property of node which has title service or path  `path: ['tree', 'childNodes', 0, 'childNodes', 1]`
 ```

var initialState = {
  tree: {
    text: "app",
    childNodes: [{
      text: 'core',
      childNodes: [{
        text: 'store',
        childNodes: [],
        expanded: false,
        path: ['tree', 'childNodes', 0, 'childNodes', 0]
      }, {
        text: 'service',
        childNodes: [],
        expanded: false,
        path: ['tree', 'childNodes', 0, 'childNodes', 1]
      }],
      expanded: false,
      path: ['tree', 'childNodes', 0]
    }],
    expanded: false,
    path: 'tree'
  }
};
 
```
Can I do something like below ? I know we can do this in immutable.js
```R.updateIn( ['tree', 'childNodes', 0, 'childNodes', 1], (n)=>!n.expanded , initialState); ```

**Comment by Bradcomp** [comment]
You could use `over` with a lens.   

`R.over(R.lensPath(['tree', 'childNodes', 0, 'childNodes', 1]), R.not, initialState);`

`lensPath` will create a lens focused on the path you provide, and `over` will use that lens to update the value with the function you provide, in this case, `not`.

**Comment by roopkt** [comment]
@Bradcomp Thanks for the example, it worked for me.  I also looked `over` function however I was using `R. negate` and it was making the expanded value to 0. I missed `R. not` function thanks for pointing me. 

Another question is it not possible to access the properties via callbacks i don't want to hardcore `expanded` word.

**Comment by Bradcomp** [comment]
Awesome! I'm glad that worked for you. 

You can totally access the properties in your function as well, the code would be very similar to what you initially posted.

**Comment by roopkt** [comment]
@Bradcomp I did not find any sample where I can pass callback function where I can get object. Can you show me example.

**Comment by Bradcomp** [comment]
Sure.

```
const myLens = R.lensPath(['tree', 'childNodes', 0, 'childNodes', 1]);

over(myLens, (n)=>!n.expanded, initialState);
```

**Comment by roopkt** [comment]
@Bradcomp thank you! Exactly this is what I wanted!  
I like this way to update the properties of the object because, I do not need to hardcode the property names which is great for maintenance and refractory.  I already got rid of immutablejs from my project Ramda works excellent, no object conversions and no hardcodings.

**Comment by roopkt** [comment]
@Bradcomp thanks!  However I see "expanded" property hardcoding.  is it not possible to get object by lenspath and update property?  Something like this:
```
// this should focus on entire object present in this path.  

const myLens = R.lensPath(['tree', 'childNodes', 0, 'childNodes', 1]);


// do we have updatein kind of function which allows object update rather than property by their hardcoded names. 

upadateIn(myLens, (n)=> !n.expanded, initialState);
```
I do not want to hardcore property names for updating them rather I want to use object itself. 
I may be wrong but my wish is can we do something to not hardcore propertynames inorder to fetch or update them?

**Comment by Bradcomp** [comment]
I'm not really sure what you're getting at, but I might be able to help. If not, I can certainly recommend posing your question in the [gitter room](https://gitter.im/ramda/ramda), there are a lot of helpful people in there too!

`const myLens = R.lensPath(['tree', 'childNodes', 0, 'childNodes', 1]);` will give you a lens that is focused on the object. In this case, the focus will be on: 
```
 {
       text: 'service',
       childNodes: [],
       expanded: false,
       path: ['tree', 'childNodes', 0, 'childNodes', 1]
     }
```

Once you have the object you can do whatever you want with it, or any of its properties.

`(n)=> !n.expanded` is a function from `node` to `bool`, so using it with `over` will replace the entire node object with a boolean (in this case, false). Ramda can't know from the outside that the function only operates on one field, because the lens is focused on the object.

[`evolve`](http://ramdajs.com/docs/#evolve) is a helpful function for when you would like to operate on fields within an object. You could use it in this case to toggle the expanded field, but at some point you will need to tell your code which field you want to operate on.
```
const myLens = R.lensPath(['tree', 'childNodes', 0, 'childNodes', 1]);

//Evolve takes a transformation object, and applies the functions given for each property to that 
//property of the target object. You can pass in transformers for as many properties as you like
const toggleExpanded = R.evolve({ expanded: R.not })

R.over(myLens, toggleExpanded, initialState);  //This will toggle the `expanded` property now
```

Is this more along the lines of what you are looking for?

As an aside, keep in mind that Ramda won't modify your input data, so what you get back will be a new object. It won't mutate the original object you're passing in.
