### ISSUE TITLE
Ramda .isEmpty() calls jQuery .empty()

### ISSUE THREAD

**Issue by codeithuman** [ramda/ramda#2223]
When using Ramda to check if a jQuery object is empty, Ramda will call jQuery's `.empty()` on the object, which in turns removes that element's children from the DOM. 

You can see a working demo here, https://jsfiddle.net/msmh0a83/. 

I believe the error stems from here, https://github.com/ramda/ramda/blob/ef2516966351d9a27abcfdfeed0aa701cbeee15d/src/empty.js#L39.

**Comment by jamonholmgren** [comment]
Yeah, it looks like jQuery's `empty` is different in that it empties the node of children rather than checking if a node has children.

https://api.jquery.com/empty/

**Comment by codeithuman** [comment]
Correct, but it's Ramda's source code that is calling jQuery's `.empty()` instead of its own `.empty()`.

**Comment by kedashoe** [comment]
I think in the future we may have more well defined dispatching. For example here we dispatch to the `empty` method, but jQuery's `empty` was not designed with https://github.com/fantasyland/fantasy-land#empty-method in mind. Probably at some point we will drop built in support for `empty` in favor of `fantasy-land/empty`.

For now I would recommend

1. calling jQuery's methods directly
2. create wrapper functions around ramda funtcions

rather than passing jQuery objects directly as arguments to ramda functions.

**Comment by codeithuman** [comment]
Awesome @kedashoe, thanks for the quick response! Your recommendations sound good to me!

**Comment by jamonholmgren** [comment]
@codeithuman You could also pass in the node directly using `.get()`. Updated fiddle: https://jsfiddle.net/msmh0a83/1/
