### ISSUE TITLE
Not working example in the doc of "sequence" method

### ISSUE THREAD

**Issue by barbiturat** [ramda/ramda#2243]
This example from here http://ramdajs.com/docs/#sequence is not working: 
`R.sequence(R.of, Maybe.Just([1, 2, 3]));`
In reality it returns [[]]

**Comment by dustinws** [comment]
This is curious. All objects besides `Array` _have to implement sequence_ for that example to work, including the `Maybe` in question for this issue. Otherwise ramda treats the traversable as an array, which is why the output is `[[]]`.

I'm wondering if this breaks the `(Applicative f, Traversable t)` type constraint. Even if some custom type did implement `Traversable`, it's still going to get treated like an array unless it also has `sequence`.

Since traverse is implemented with sequence, this could easily be fixed by also checking for `fantasy-land/traverse` inside of `sequence` and just calling `traversable.traverse(identity, of)`.

I'm happy to submit a PR with a fix / tests if anyone is interested 😉

**Comment by buzzdecafe** [comment]
I'd love to see a fix for this, thanks

**Comment by dustinws** [comment]
Hey @buzzdecafe, I have a PR for this over [here](https://github.com/ramda/ramda/pull/2248). If you get the time to check it out, I'd really appreciate your feedback!
