### ISSUE TITLE
doc: transduce example code

### ISSUE THREAD

**Issue by Qquanwei** [ramda/ramda#2246]
doc ref: http://ramdajs.com/docs/#transduce

I think following code may be wrong
```
var isOdd = (x) => x % 2 === 1;
var firstOddTransducer = R.compose(R.filter(isOdd), R.take(1));  <------- hi there
R.transduce(firstOddTransducer, R.flip(R.append), [], R.range(0, 100)); //=> [1]
```
should be 
```
var isOdd = (x) => x % 2 === 1;
var firstOddTransducer = R.compose(R.take(1), R.filter(isOdd));     <--------- there
R.transduce(firstOddTransducer, R.flip(R.append), [], R.range(0, 100)); //=> [1]

```

**Comment by Bradcomp** [comment]
Hi @Qquanwei, 

While it seems like transducers compoe 'backwards', this is actually the expected behavior. If you run the code in the [repl](https://goo.gl/mq2iZo) you can see you get the right answer.

Check out the following issues for more background:

https://github.com/ramda/ramda/issues/2206
https://github.com/ramda/ramda/issues/2124
https://github.com/ramda/ramda/issues/1790
