### ISSUE TITLE
Add implementation for scanP

### ISSUE THREAD

**Issue by dustinws** [ramda/ramda#2247]
Hi Ramda folks!

I recently ran into a situation at work where I needed to use `R.scan` asynchronously, using promises. I wrote an implementation, and was wondering if there was any interest in getting it into the library.

---
### Usage

The type signature would look something like this
`scanP :: (a,b -> Promise a) -> a -> [b] -> Promise [a]`

In use, it would work just like the regular `R.scan`

Regular R.scan
```
R.scan(R.add, 0, [1, 2, 3]);
// [0, 1, 3, 6]
```

scanP
```
const addAsync = (a, b) =>
  Promise.resolve(a + b);

scanP(addAsync, 0, [1, 2, 3]);
// Promise [0, 1, 3, 6]
```
---

Does anyone think this has a place in the library? I'm happy to submit a PR if so.

**Comment by kedashoe** [comment]
We are pretty hesitant to add promise related functions. This is also a bit narrow of a use case imho.

**Comment by asaf-romano** [comment]
I guess it's time to be the Devil's advocate.

In our code base we have ``thatP`` (promise) variants for many of Ramda's functions (as well as promise variants of our own additions). They are invaluable in a modern, heterogeneous js environment in which functional code must integrate with common external libraries (db drivers, queue systems etc) and also with the fact the Promises are rapidly becoming first class citizens in vanilla JS, the DOM and in the JS ecosystem in general.  Ironically, our JS code base would probably be much less functional if it weren't so easy for us to make the integration with imperative code seamless.

For instance, consider an API built on top of ``applySpecP `` (~~ ``applySpec`` + ``Promise.props``). It can effortlessly integrate with imperative code in two important ways: On the one hand, an imperative consumer may ``await`` its result (especially useful alongside destructing assignment!) , ``Promise.all`` it with something else, etc. On the other hand, a property in the spec passed to ``applySpecP`` may be a messy async function implemented by someone else (or just you in the imperative day of the week). The only rule both sides have to follow is "public" immutability in their contracts - but at least from our experience that's a very low bar now and, surprisingly almost a consensus.

This is very much in the spirit of the language in general, which makes it quite easy to mix and match very different paradigms without much hassle. That's, as they say, one of the good parts about this language. The practical benefits of futures/tasks could never match this convenience. After all, there are many way to get good results - should FP require us to continuously worry about external dependencies or commit to a homogeneous code style, we would simply have to avoid it altogether. Interoperability is king.

So while I agree with the other maintainers that promises are a pretty strange, black sheep in the functional world, I think the value of playing nice with promises outweighs the shortcomings.  Having said that, implementing all those *P variants required relatively little effort, and most of the time we were able to rely on the built-in variants without re-implementing core functionality. It did not require us to fork the library or monkey-patch anything*.  That's why I generally feel fine being the quiet minority on this subject. 

_____________________
* Well, we do have a better implementation of ``pipeP`` - but that's all, I Promise.

**Comment by buzzdecafe** [comment]
Well argued, @asaf-romano . This is one of those things I would like to see out of the core lib, but pluggable when needed.

**Comment by tycho01** [comment]
If anything, there's still the cookbook!
I wish there were a version of that published as a package, but existing attempts seem kinda outdated.
I like how tree-shaking could help add things without increasing bloat for non-users, but yeah, I see the point about keeping a clean API, learning Ramda may be overwhelming as-is already.

**Comment by dustinws** [comment]
All valid points.

I must admit, I thought ramda would be a bit more open to the `thatP` alternatives now that Promises are an official part of the language. I understand this isn't really a "general purpose" library, but It is usually my first install because it makes working with the language much nicer. The `thatP` methods seem to be in line with that, and it's a pain to have to keep separate copies of these functions in each project.

I submitted this function in particular because it's relevant to a project I'm working on and it's "promisified" implementation isn't as trivial to implement as something like `map` or `reduce`.

Anyways, thanks for the feedback!

**Comment by CrossEye** [comment]
Related: @avaq's [Broken Promises][bp].

  [bp]: https://medium.com/@avaq/broken-promises-2ae92780f33

**Comment by tycho01** [comment]
As a slight consolation for alternatives, it appears RxJS expose an observable-based way to make HTTP requests. But yeah I guess much of the JS ecosystem still does promises...

**Comment by char0n** [comment]
Hi all,
I would like to contribute with some of my opinions into the discussion.

@tycho01 there is such a library, you've contributed the initial typings into it ;] It's called [ramda-adjunct](https://github.com/char0n/ramda-adjunct). I've already implemented set of cookbook functions that I've needed for my usecases like: `list`, `pickIndexes`, `mergeRight`, `paths`, `renameKeys`, `renameKeysWith`. There is a WIP in  this [issue](https://github.com/char0n/ramda-adjunct/issues/27).

@dustinws I would be happy to adopt such a function in ramda-adjunct. We already have `reduceP` and `reduceRightP` and also a WIP on this [issue](https://github.com/char0n/ramda-adjunct/issues/35) regarding *P functions.

I would also suggest the following signature to make it more robust:
`scanP :: (a,b -> PromiseOrValue a) -> PromiseOrValue a -> PromiseOrValue [b] -> Promise [a]`
`scapP` will handle wrapping the value into the Promise under the hood, if the value is not a Promise. Checkout the [reduceP](https://char0n.github.io/ramda-adjunct/1.15.0/reduceP.js.html) for reference. If you're interested just issue a PR.

@CrossEye would it be possible to direct ppl with LGTM future requests that you guys don't feel should be part of core ramda to ramda-adjunct ? They can still issue a PR to ramda-adjunct and the community may benefit from it. 

Thank you for your time.

**Comment by tycho01** [comment]
@char0n: great to hear the cookbook is still in scope :), +1 to that!

**Comment by CrossEye** [comment]
@charOn:

I think it would be a good idea to group the [Related Projects][rp] section of the wiki so that [ramda-adjunct][ra] and [rcp][rc] (not actively maintained, it looks like, but perhaps still useful) are listed as Cookbook-like community functions not incorporated directly into Ramda.  Then we could add a section to the README that points to these.

Do you feel like making these changes?  The wiki is publicly editable; the README will take a PR.

  [ra]: https://github.com/char0n/ramda-adjunct
  [rc]: https://github.com/enten/rcb
  [rp]: https://github.com/ramda/ramda/wiki#related-projects

**Comment by char0n** [comment]
@CrossEye yeah I can manage to do that.

FYI: [rcb](https://github.com/enten/rcb) was completely assimilated into ramda-adjunct. I have also created a [PR](https://github.com/enten/rcb/pull/2) that author merged to the [README](https://github.com/enten/rcb/blob/master/README.md). During the assimilation process I found a couple of bugs in the rcb and we managed to agree with author that the library in not in any way production ready. But again there are still interesting ideas that we don't have in ramda cookbook, nor are implemented in ramda-adjunct. So I would (for the time being) still keep it in related projects.
