### ISSUE TITLE
new function lensWhere

### ISSUE THREAD

**Issue by tusharmath** [ramda/ramda#2257]
Can we have a function which uses a predicate to focus on an element in an array?

```js
const lensWhere = (func) => R.lens(
  R.find(func),
  (focus, target) => R.update(R.findIndex(func, target), focus, target)
)
```

Example - https://goo.gl/eacsoa

**Comment by CrossEye** [comment]
I don't know how we could make a law-abiding lens along those lines.  

Just because we can test a predicate to find (the first) matching value, there is no reason that we can use that predicate to *create* a new value.  While the Put-Put law may hold by coincidence, any implementation would probably break the spirit of it.  And the Put-Get law would fail badly.

```js
R.pipe(
  R.set(
    lensWhere(R.propEq('id', 42)),
    {foo: 'bar'}
  ),
  R.view(
    lensWhere(R.propEq('id', 42)),
  )
)({id: 1}, {id: 2}); //=> undefined
```

**Comment by tusharmath** [comment]
@CrossEye Thanks for the feedback. 

1. I was quite surprised that this does not work. Can you explain a little bit more about why the law Put - Get fails ?

2. Is there an alternative for me to use?

3. Is this a typo —
```ts
({id: 1}, {id: 2})
```
Did it mean —
```
([{id: 1}, {id: 2}]) // with the square bracket?
```ts

**Comment by CrossEye** [comment]
3)  Yes, that is a typo.

2)  There are plenty of ways to write this.  But you don't necessarily need an alternative, if that function works for you.  It will certainly not be a problem if you're not trying to use `view` or `over` or some such only with values that actually *are* there.  But that won't do for a general-purpose library like Ramda.

1) Why doesn't this work?  For starters, the current implementation of `update` is based upon `adjust`, which treats negative indices as counting from the right.  But pairing this with `find`, which signals not-found with `-1`, we get a situation where when you search for something that doesn't exist, and try to replace it with your new value and you end up replacing the last element in your array.

But that's simply the current implementation.  In fact, it seems logically impossible to do correctly.  

You want to pass a predicate to test whether an item matches your condition.  That's straightforward, but  a lens is more than just a finder.  It also lets you put something in place.  And Ramda cannot interpret your predicate to *create* a matching item.  Say the simple case above, `propEq('id', 42)`.  It is already on the bounds of credulity to think that Ramda could reverse this, and create a value _ex nihilo_ that matches this.  But because it is a Ramda function, we might imagine that it's just possible.  Then try to imagine one that tried to use this:

```js
val => sha256(val.key) == '15ac3ad46e017604ca0e585b4900163713580bd52b25e2b63e19711885852e5a'
```

as a predicate.  How are you going to create such a value? (I promise you, you don't want to know what value produced that hash, but if you really have to know, you can see it [on runKit][rk].)

So my thought is not that this is an incorrect implementation.  Rather, the whole notion is not possible.

  [rk]: https://runkit.com/crosseye/sha256

**Comment by tusharmath** [comment]
@CrossEye thanks for the really detailed explanation. 
Even though I read it multiple times, I am still a bit confused about this — 
>In fact, it seems logically impossible to do correctly.

The definition of what is "correct" lies within the implementation of the function isn't it? We could throw an exception if the predicate doesn't match or probably just make it a no-op.

For example —

```ts
var headLens = R.lensIndex(120);
R.set(headLens, 'x', ['a', 'b', 'c']);        //=> ['a', 'b', 'c']
```

Here index `120` doesn't make sense to the lens's implementation, but that doesn't mean it is not possible to insert an element at 120th index directly.  But the implementation "chose" to not handle an out of bounds update. Similarly we could do it in the `lensWhere` function also, ie just ignore if the predicate doesn't match.

**Comment by polytypic** [comment]
@CrossEye FYI, I just wrote a short section to the Partial Lenses documentation on a related topic: [Myth: Partial Lenses are not lawful](https://github.com/calmm-js/partial.lenses/#myth-partial-lenses-are-not-lawful).  Note that the section is a subsection of the [On lens laws](https://github.com/calmm-js/partial.lenses/#on-lens-laws) section.

**Comment by tusharmath** [comment]
@CrossEye I am closing this issue because now I am quite clear with your explanation. The essence was captured here —
>The problem is that the predicate is not about the structure of the container. 
And the example really helped.

Thanks a lot! also @polytypic :)

**Comment by mcky** [comment]
@CrossEye 

So I just came across this half-way through making copies of `assocPath` which allow any Idx returning functions in the path, eg
```js
const obj = {
  items: [
    { color: 'blue', data: { count: 10 } },
    { color: 'red', data: { count: 5 } },
  ],
}

assocPath(['items', R.findIndex(R.propEq('color', 'red')), 'count'], 15, obj)
updatePath(['items', R.findIndex(R.propEq('color', 'red')), 'count'], R.inc, obj)
```

 I'm a bit lost with the get/put stuff, but it seems like assocPath etc don't follow those rules anyway? eg `-1` doesn't wrap?

Pardon me if this has already come up in discussion, but would there be any interest in having something like this in ramda? Or reasons it's a stupid idea and I shouldn't package up those for use myself.

**Comment by CrossEye** [comment]
It's not a stupid idea, not at all.  But it may not be a good fit for Ramda, which tries to keep its input more consistently typed than that.  Even introducing the `String | Int` union type used by `assocPath` is a simple concession to convenience; it remains slightly disconcerting.  One that was typed `String | Int | (a -> String) | (a -> Int)` is beyond my comfort level.
