### ISSUE TITLE
map+reduce, tricky behavior or a bug?

### ISSUE THREAD

**Issue by IMalyugin** [ramda/ramda#2265]
So this piece of code:
```
R.map(item => 
  R.reduce((result, value) => {
    result.push(value);
    return result;
  }, [], item),
  [[1], [2], [3], [4]]
)
```

returns totally expected result:
```
[
  [1],
  [2],
  [3],
  [4],
]
```

While this piece of code:
```
R.map(
  R.reduce((result, value) => {
    result.push(value);
    return result;
  }, []),
  [[1], [2], [3], [4]]
)
```

Does not:
```
[
  [1, 2, 3, 4],
  [1, 2, 3 ,4],
  [1, 2, 3, 4],
  [1, 2, 3, 4],
]
```

If you get your head around it: yes, you pass an array, yes, its passed by reference, yes, it binds once within a function, but, isn't ramda supposed to never mutate anything?

**Comment by asaf-romano** [comment]
Ramda **APIs** don't mutate anything, but they intentionally do not try to block client code from doing so (in this case the magic would be to clone the initial value passed to reduce). 

In fact, performance-sensitive code sometimes takes advantage of the current behavior:
https://github.com/ramda/ramda/blob/master/src/groupBy.js

However, if you want immutability guaranteed, using R.append (rather than array.push) would produce a consistent result in both of your examples.
