### ISSUE TITLE
R.cond is a mess!

### ISSUE THREAD

**Issue by decoursin** [ramda/ramda#2266]
R.cond returns a function, why? It doesn't make any sense.

What is more primitive, a function that resolves on invocation, or one that always returns a function?
I want to simply be able to do this:
```
    const address = R.cond([
        [email.to && email.to.includes(search), email.to],
        [email.cc && email.cc.includes(search), email.cc],
        [email.bcc && email.bcc.includes(search), email.bcc],
    ]);
```
It doesn't work! Because it returns a function.

You're example in the docs is this:
```
var fn = R.cond([
  [R.equals(0),   R.always('water freezes at 0°C')],
  [R.equals(100), R.always('water boils at 100°C')],
  [R.T,           temp => 'nothing special happens at ' + temp + '°C']
]);
fn(0); //=> 'water freezes at 0°C'
fn(50); //=> 'nothing special happens at 50°C'
fn(100); //=> 'water boils at 100°C'
```
However, if you wrote the cond how I'm suggesting, it would look like this, which is even more readable! and it allows `cond` to work more generally on more use cases:
```
var fn = (x) => R.cond([
  [x === 0 ,    'water freezes at 0°C'],
  [x === 100, 'water boils at 100°C'],
  [true,           'nothing special happens at ' + x + '°C']
]);
fn(0); //=> 'water freezes at 0°C'
fn(50); //=> 'nothing special happens at 50°C'
fn(100); //=> 'water boils at 100°C'
```
The way it is right now, how many people actual use `cond`, probably very few. I would recommend not using it and avoiding it even.

I really like Ramda, but I think you screwed up with this one, thank you.

**Comment by davidchambers** [comment]
It seems that nested ternaries are sufficient for your use case:

```javascript
const address =
  email.to && email.to.includes(search) ? email.to :
  email.cc && email.cc.includes(search) ? email.cc :
  email.bcc && email.bcc.includes(search) ? email.bcc :
  null;  // XXX
```

> The way it is right now, how many people actual use `cond`, probably very few.

The same applies to several other Ramda functions, which you're equally welcome to avoid. ;)

**Comment by decoursin** [comment]
Haha yeah I probably have which is why I didn't mention them. This one I used expecting it to work like other programming languages.

Nested ternaries are a terrible idea though, and I would never want to do that to a poor soul trying to read my code

**Comment by buzzdecafe** [comment]
i'm good with it

**Comment by CrossEye** [comment]
> I want to simply be able to do this:
> 
> ```js
> const address = R.cond([
>     [email.to && email.to.includes(search), email.to],
>     [email.cc && email.cc.includes(search), email.cc],
>     [email.bcc && email.bcc.includes(search), email.bcc],
> ]);
> ```
> It doesn't work! Because it returns a function.

Well, this is about functional programming.  :smile:

But certainly such a version would never fly with Ramda.  Ramda is never likely to be designed around expressions with free variables such as `email` and `search`.  You could create a function to do what you want, using some Ramda functions:

```js
const matching = compose(propOr(null, 1), find(head)) 
```

(with whatever default you choose in place of `null`, for those cases where it isn't found.)  But such a function would not be incorporated into Ramda itself, which insists on referential transparency, and so could never accept that sort of design.

My take is that if `cond` is a mess, it's only due to its ability to create (and therefore also to accept) variadic functions.  And that's a decision that seems pretty integral to how Ramda has proceeded.

**Comment by decoursin** [comment]
> Well, this is about functional programming.  :smile:

Functional programming is not about returning functions. Does `R.assoc` return a function? Of course not.

> But certainly such a version would never fly with Ramda. Ramda is never likely to be designed around expressions with free variables such as email and search. You could create a function to do what you want, using some Ramda functions:

You're crazy, it's called: lexical scoping, which is a functional programming paradigm. Here is `cond` in Clojure: https://clojuredocs.org/clojure.core/cond#example-542692c7c026201cdc326966, using 'n' which is lexical-scoped.

> My take is that if cond is a mess, it's only due to its ability to create (and therefore also to accept) variadic functions. And that's a decision that seems pretty integral to how Ramda has proceeded.

It's ok in some places, other's it makes no sense. Here is one example. If you changed it to how I suggest, it wouldn't go against Ramda and it's philosophies. In fact, having functions that are actual useful and `functional` (yes my approach is more functional, being more primitive, and in sync with other functional languages) is more aligned with Ramda's philosophies.

**Comment by CrossEye** [comment]
> Does R.assoc return a function?

Yes.

```js
R.assoc('foo') :: a -> Object -> Object
R.assoc('foo', a) :: Object -> Object
```

Only if you supply three parameters do you get back an Object.


> it's called: lexical scoping

The example you gave was incomplete, then.

I suppose, given your update to the example, that you are talking about something like this:

```js
const address = (email, search) => R.cond([
    [email.to && email.to.includes(search), email.to],
    [email.cc && email.cc.includes(search), email.cc],
    [email.bcc && email.bcc.includes(search), email.bcc],
]);
// ...
const myAddr = address(emailObj, 'foo@bar.com')
```

Or do you really just want an API like 

```js
myCond([
  [false, value1],
  [false, value2],
  [true, value3],
  [false, value4],)
  [true, value5]
]) //=> value3
```
?  That is what the `matching` function above does.

Ramda's version has signatures something like this:

```hs
cond :: [(a -> Bool, b)] -> (a -> b)
cond :: [((a, b) -> Bool, c)] -> ((a, b) -> c)
cond :: [((a, b, c) -> Bool, d)] -> ((a, b, c) -> d
...
```

If `cond` worked only with unary functions, I would be in favor of changing the signature to 

```hs
cond :: [(a -> Bool, b] -> a -> b
```
with Ramda's usual currying so that you could call it as `cond(pairs, val)` if you liked instead of only `cond(pairs)(val)`, but I don't think of that as a major motivator.

-----

I guess part of my problem is that I use `cond` all the time, and have never felt the pain you are describing.  But I mostly use Ramda to build a number of reusable functions which then are piped together.  So that this returns a function seems totally natural to me.

You are certainly right that this has a different API than LISP-like languages, or than Haskell, which borrowed it from them.  But by using functions rather than expressions, it also keeps some of the lazy feel of Haskell, which would not evaluate later branches if the earlier one returns `true`.

-----

I certainly do think there's room for discussion here.  Reopening.

**Comment by Bradcomp** [comment]
For me, one of the main benefits of `cond` is that it allows us to prevent evaluation of branches where the condition doesn't apply. Consider this completely contrived example.

```
var fn = R.cond([
  [R.equals(0),  () => throw new Error('You froze!')],
  [R.equals(100), () => throw new Error('You gassy!')],
  [R.T,           temp => 'nothing special happens at ' + temp + '°C']
]);
fn(0); //=> Error
fn(50); //=> 'nothing special happens at 50°C'
fn(100); //=> Error
```
whereas if `cond` accepted straight values:
```
var fn = (x) => R.cond([
  [x === 0 ,   throw new Error('You froze!')],
  [x === 100, throw new Error('You gassy!')],
  [true,           'nothing special happens at ' + x + '°C']
]);
fn(0); //=>Error
fn(50); //=> Same Error
fn(100); //=> Still the same error
```

Typically, when one is doing a conditional, we only want to evaluate the truthy branch. Due to the eager semantics of JavaScript, this would be impossible with the function you're suggesting.

**Comment by davidchambers** [comment]
@CrossEye:

> If `cond` worked only with unary functions, I would be in favor of changing the signature to
>
> ```haskell
> cond :: [(a -> Bool, b] -> a -> b
> ```

(There are a few errors in this signature, Scott.)

Everything is simpler in a world without variadic functions. :)

To avoid inventing notation I would format the signature like so:

```haskell
cond :: Array (Pair (a -> Boolean) (a -> b)) -> a -> b
```

This type is safer and potentially more useful:

```haskell
cond :: Array (a -> Maybe b) -> a -> Maybe b
```

This could be generalized to any Foldable:

```haskell
cond :: Foldable f => f (a -> Maybe b) -> a -> Maybe b
```

Now *that* is a function I could get behind. I'd like to see a pull request to add this function to Sanctuary (with a different name, perhaps). :)

**Comment by CrossEye** [comment]
@davidchambers:

Yes, there were several problems with those signatures.  I cleaned them up a bit.  Perhaps your version is cleaner.

This is certainly an interesting and potentially useful type:

```hs
:: Array (a -> Maybe b) -> a -> Maybe b
```

But generalizing it to an arbitrary `Foldable` would lose the pseudo-laziness that @Bradcomp and I were promoting, no?  There's no facility in `Foldable` (or `Traversable`) to interrupt the iteration, is there?  Am I missing something?

**Comment by davidchambers** [comment]
> But generalizing it to an arbitrary `Foldable` would lose the pseudo-laziness that @Bradcomp and I were promoting, no?

This is not the case. There's no law that requires the use of the derivable implementation for every data type. The `size` function defined in sanctuary-type-classes has a fast path for arrays:

```javascript
function size(foldable) {
  //  Fast path for arrays.
  if (Array.isArray(foldable)) return foldable.length;
  return reduce(function(n, _) { return n + 1; }, 0, foldable);
}
```

This optimization is sound because whenever we take the fast path we receive the same answer as the general path would produce. Similarly, the generalized `cond`/`firstJust` function could avoid traversing the remainder of an array once a match is found.

**Comment by CrossEye** [comment]
OK, so this would lose the laziness except where specifically optimized for it in our function.  Is that it?  The alternative I see would be that we could delegate `condXXX` as well as supplying a derived implementation, perhaps optimized for lists.  But I think I'm the only one left interested in such widespread delegation.

**Comment by Bradcomp** [comment]
`cond` has never been a function I've had a problem with. I think it follows [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and it's one I use on a regular basis. 

While the ability to handle variadic functions does add some complexity, it also adds to the usefulness, and at least it's consistent in that it _always_ returns a function, and that function acts in a predictable way. We know that exactly 0 or 1 of the functions on the 'right' will be executed.

I think a `firstJust` function (whatever the name may be) would also be useful, either in Sanctuary, or in Ramda if we ever decide to add Maybe (I'm ambivalent there...). It holds a different place than the current `cond` though, which separates the predicate functions from the transformation functions.

**Comment by davidchambers** [comment]
> OK, so this would lose the laziness except where specifically optimized for it in our function.

You could argue that this is limiting, and I would agree. But it's strictly less limiting than replacing `Foldable f => f` with `Array`, as it allows other types to participate. If I'm folding an Identity or a Maybe I won't be worried about short-circuiting. ;)

**Comment by decoursin** [comment]
> cond has never been a function I've had a problem with. I think it follows POLA and it's one I use on a regular basis.

This isn't about what works for you, it's about what's best, period, so let's please leave out of the discussion these personal sentiments.

This discussion is going in the wrong direction. `ramda` is a really nice library, but it's losing focus in it's purpose.

`cond` is just one example, I can probably find more. There's too many functions who's scope is too contrived or just not useful enough.

`ramda` should not have 245 functions! This is absurd, please split this into two libraries: `ramda` and `ramda-extra`.

I know there's many of you library maintains who really like most of 245 functions, but 98% of your users use only 100 of these, maybe. Many of the other one's are polluting the namespace and the documentation.

`cond` is a good example. I do think how it stands now it could be useful, but it's just too complicating, for the very small benefit it provides, so I would never use it. `ramda` should not be the kitchen sink of all functions.

Furthermore, above everything else, there's a certain list of functions/variable/names that you just don't touch unless it does exactly what every one expects, here's a list of some of these: `if` `class` `and` `filter` `reduce` etc. Do you know another what belongs in this category!! `cond`!!!! Yet, somehow, you've taken a function that most people, changed it's behavior, without even changing it's name! So you get some poor soul (me) who comes along expecting it to work like in most other languages that support it, doesn't read the doc because who can read the docs for everything! and of course it bombs and I gotta figure why my program doesn't work!! and `ramda` is suppose to be helpful!!

So let's change the subject. If it's ok, I'll give you a list of functions that should be completely removed off the face of `ramda`, we can discuss these, and go from there. `cond` is first and foremost.

You @Bradcomp were right about the laziness which is probably why `cond` was written like this in the first place. As such, I do not recommended adding the `cond` that I purposed.

**Comment by ecancino** [comment]
@decoursin what ramda users use ramda for is important and the size of the library is irrelevant when you can import just the one or ones you need. 

I love cond as is, and would love to keep it that way, but if there is a more useful or complete way to define it would love to read about it.

**Comment by decoursin** [comment]
I'm going to leave that comment ^, but having a second-look at `ramda`'s functions, I think many of them are useful and have their purposes, so I was bit over board on that respect sorry :).

Nonetheless, it remains that I suggest getting rid of `cond` or at least changing it's name.

**Comment by davidchambers** [comment]
> This isn't about what works for you, it's about what's best, period, so let's please leave out of the discussion these personal sentiments.

This thread contains several unsubstantiated claims which sound to me very much like personal sentiments. For example:

> Nested ternaries are a terrible idea though, and I would never want to do that to a poor soul trying to read my code.

It's clear that you care a great deal about Ramda @decoursin, which is wonderful. Everyone involved in this discussion cares a great deal about Ramda. My suggestion to you is that you consider the tone with which you convey your ideas. I welcome disagreement, but prefer people to disagree with me in a friendly manner. :)

**Comment by CrossEye** [comment]
> I know there's many of you library maintains who really like most of 245 functions, but 98% of your users use only 100 of these, maybe.


I'd love to see your list of the most important functions, but I fear that it would be very difficult to achieve a consensus. 

I'd hazard to say that a typical user generally uses even fewer than your "100".  I'm sure we could do some sort of analysis of GitHub dependents to approximate the most popular, but I know that would miss most of my personal use of it, as my use of Ramda is mostly not on GH at the moment.  I'm sure it would miss many others as well.

I really would love to reduce our footprint, but there are only a few obvious candidates for removal, and I'm betting they would be different from yours.  I certainly would not include `cond`, which I use often.

**Comment by decoursin** [comment]
> My suggestion to you is that you consider the tone with which you convey your ideas. I welcome disagreement, but prefer people to disagree with me in a friendly manner. :)

I've actually been friendly, but I'll try better to be more conservative, sorry.

> I'd hazard to say that a typical user generally uses even fewer than your "100". I'm sure we could do some sort of analysis of GitHub dependents to approximate the most popular, but I know that would miss most of my personal use of it, as my use of Ramda is mostly not on GH at the moment. I'm sure it would miss many others as well.

Yeah, as I said in my next post, I was wrong about my estimate. Most of them seem useful and important, my apologies.

**Comment by decoursin** [comment]
Compromise, rename `cond` to `condFn`?

**Comment by Bradcomp** [comment]
I don't think that a name change will help matters for a few reasons. `***Fn` isn't a convention that we use to denote higher order functions. In fact, we typically don't have a convention to denote higher order functions. There are a large number of functions that return other functions, even if you don't count currying in the number. For instance: `addIndex`, `allPass`, `always`, `anyPass`, `applySpec` all return functions per their type signature - just to cover the a's. In general, if a function returns another function it will be noted by the type signature, and possibly in the description. 

The type signature for `cond` - `[[(*… → Boolean),(*… → *)]] → (*… → *)` shows that this function returns a variadic function, as does the very first line of the description:
> Returns a function, `fn`, which encapsulates `if/else, if/else, ...` logic.

Being able to accept functions as parameters, and return them as values from functions, is a critical tool for functional programming. While the ability to handle variadic functions does make `cond` a little messy, it's also very useful. The fact that it accepts and returns functions is actually critical for its usefulness, because it ensures that only one path will be executed.

I would venture to say that `pipe` and `compose` are two of the most-used functions in Ramda. Both of them suffer the same faults as `cond`. They return a function, and they have been made to handle variadic functions.  They also suffer the additional difficulty of being variadic themselves. Despite this, they still see plenty of use.

`cond` has been around for a long time in the library, and as you've seen here, quite a few users and contributors find it useful. I think it's fine for you to avoid it, but I don't think there will be any changes to the function at this point in time.
