### ISSUE TITLE
Is R.reduced a `callCC` in Haskell?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2285]

**Comment by buzzdecafe** [comment]
interesting. My initial response was "no, `reduced` just a way to short-circuit evaluation inside `reduce`". Then I thought maybe there is something more to this question; after all, we are jumping out of the current flow and resuming a different flow (the "continuation"). 

But really the point of `reduced` is to return a value to the caller as soon as we know it; rather than the caller passing us a continuation to execute instead.

Disclaimer: I am not familiar with Haskell `callCC`, I am assuming it is similar to Scheme `call/cc`
