### ISSUE TITLE
memoize documentation

### ISSUE THREAD

**Issue by sdevmaster** [ramda/ramda#2314]
if memoize is used with function a function with function argument, it does not check for a new argument, resulting in the same result forever. This is not documented. I literally searched for hours for a bug in my code -.-

**Comment by CrossEye** [comment]
> with function a function with function argument

??  Can you provide an example?

**Comment by Steffen1996** [comment]
There was a word more than it should - "is used with a function with a function argument". I didn't have much time, so sorry for that.
What i mean is that: [Take me to the REPL](http://ramdajs.com/repl/?v=0.24.1#?let%20memo%20%3D%20R.memoize(fn%20%3D>%20fn(3))%3Bmemo(R.add(3))%20%3D%3D%3D%20memo(R.add(2))%3B%2F%2F<--%20not%20documented)
This pitfall is described nowhere in the docs. Also i suggest using a map for this, as you could use functions as keys with no performance overhead.

**Comment by CrossEye** [comment]
Sorry, playing catch-up.  Ramda (at least before 1.0, now under serious discussion) is meant to work with older versions of JS, including ones that don't supply `Map`/`Set`.  So we couldn't use them.

But even if we did, the only equality check we can do on functions is reference equality.  That is:

```js
R.add === R.add          //=> true
R.add(42) === R.add(42)  //=> false
```

So I don't think there is really any great solution to your concern.

**Comment by CrossEye** [comment]
I'm sorry, rereading, I see that you mostly suggest documenting the problem.  That's probably a good idea.  Any suggested wordings?  Or a PR?

**Comment by buzzdecafe** [comment]
note that [`memoize` is deprecated](https://github.com/ramda/ramda/commit/d3766c873dceb57cbf5d8244681e6270d93bbcb2), any docs updates should be on `memoizeWith`

**Comment by evan-king** [comment]
It would have been nice if the deprecation came with an explanation in the documentation about this function's limitations and the factors behind its deprecation/transition to `memoizeWith`.

Nothing in the description of either `memoize` or `memoizeWith` say anything about how non-string keys are handled in either function (i.e. when user-supplied hash function passes the buck), and the latter has only a trivial option that at first glance looks like a horrible idea.  (If I understand correctly, it'll just result in arguments cast to strings, so that every function, object, etc. of same type will match.)

I had to go digging through old issues like this one to figure out not only why we're here, but also where here is and what to do about it.  I totally get that for a situation like this, the worst challenges of reference equality vs value equality come into play, but that doesn't even get the briefest mention.

Could we flesh out the documentation for both methods a little even before 1.0?  Ideally, I'd like to see enough detail that people writing new code can choose an approach appropriate to use now, with the potential simplification of a narrower specific use-case.  Such whould likely include some mention of `WeakMap` and/or provide an example for `memoizeWith` that won't actually have bigger limitations than the deprecated function.

**Comment by CrossEye** [comment]
@evan-king: these sound like good ideas.  Would you be willing to raise a PR with your suggestions?

I may not respond to it away as I'm leaving very soon for a two-week vacation.  But I will look when I return.

**Comment by evan-king** [comment]
I would, though I'm unsure when I'll find time for it.  Enjoy your vacation!  By the time you return, maybe I'll have something.  I think I'll have to ponder a while how to provide sufficient information without derailing the docs as API reference.  In the mean time I did do some tooling around while formulating my comment, and I'll plop down this code sample for my own future reference and external feedback:

```js
function argMapper() {
    let uid = 0;
    const lookup = new WeakMap();
    const insert = arg => (lookup.set(arg, uid++), uid);
    const toKey = R.ifElse(lookup.has, lookup.get, insert);
    
    return (...args) => args.map(toKey).join(',');
}
```

To me it seems maximally naive yet still unweildy for a `memoizeWith` usage example.

(On a side note, trying to write the returned function the `Ramda` way is what led me to ask elsewhere why `memoizeWith` takes a variadic function instead of a unary one that accepts an array and could have looked like `R.join(',', R.map(toKey))`.)

**Comment by evan-king** [comment]
Now realizing that `memoize`'s use of `toString` generates function bodies and JSON representations of objects, I think I was a bit harsh on it.  In fact, I'm having a hard time coming up with a `memoizeWith` example that's more generally applicable and doesn't go too far into the weeds.

Examples of what not to do, or of the limitations to any particular approach, abound.  At any rate, my attempt to offer marginal improvement is offered in #2637

**Comment by IanVS** [comment]
I'd just like to say that I'm facing the move from `memoize` to `memoizeWith` as I upgrade to `0.26`, and it would be really nice if there was some kind of explanation of the change and what I should be doing to migrate.  Thanks for getting the conversation started, @evan-king.

**Comment by CrossEye** [comment]
@IanVS: I'm all ears on a proposed solution for this.  We haven't really created migration guides in the past.  Perhaps we should.  Any suggestions on how?  Any good examples of those doing this well?

**Comment by IanVS** [comment]
@CrossEye I really appreciate the upgrade guides that ramda already does, like https://github.com/ramda/ramda/issues/2702.  Those are incredibly useful.  Personally, I think a great place to add some context and explanations would be in the linked PRs, in this case, https://github.com/ramda/ramda/pull/2700.  A rationale for why this change was made would give some good background, and then a few hints about what _most_ people should do, if that's possible.  Like, if I want to maintain the previous behavior, what should I do?  Use `Ramda.identity`?  It sounds like sometimes I wouldn't want to use that, and if that's the case, when should I use something different?  I think this kind of information in the PR description or even comments would go a long way.  It's the first place I looked, at least.  Thanks again!

**Comment by CrossEye** [comment]
Ah, yes, that PR was a mess; it's rationale was lost in an ESLint upgrade.  I updated the comment to it pointing to the relevant discussions.  Thanks.

**Comment by zacnomore** [comment]
Considering how long it's been since memorize was deprecated, that may not be much of an issue. However, as of today this issue is not called out in the documentation:
> Creates a new function that, when invoked, caches the result of calling fn for a given argument set and returns the result. Subsequent calls to the memoized fn with the same argument set will not result in an additional call to fn; instead, the cached result for that set of arguments will be returned.
