### ISSUE TITLE
assocPath regression in 0.23.0

### ISSUE THREAD

**Issue by burt202** [ramda/ramda#2315]
I originally raised this in https://github.com/ramda/ramda/issues/2040 but it didnt bump the issue so i thought id raise it separately, so the other issue can be closed

-------------------------

I think Ive found another regression in assocPath in v0.23. The following code seems to work fine in v0.22.

```
const num1 = 2
const num2 = 2

const data = {
  aaa: {
    bbb: {}
  }
}

assocPath(
  ["aaa", "bbb", num1, "ccc", num2],
  {value: 333},
  data
)
```

returns...

`{"aaa": {"bbb": {"2": {"ccc": [undefined, undefined, {"value": 333}]}}}}`

instead of...

`{"aaa": {"bbb": {"2": {"ccc": {"2": {"value": 333}}}}}}`

**Comment by kedashoe** [comment]
Hi @burt202 , this does look like undesirable behavior to me, would you like to submit a PR?

**Comment by CrossEye** [comment]
@buzzdecafe fretted about this in https://github.com/ramda/ramda/pull/1926#issuecomment-252246777,
but I think this is still the best we're going to get with this.

The issue is that we now treat integers as array indices and strings as normal property operators.  That is all for the good, but it can lead as it does here to sparse arrays.  If we change `num2` to `'2'`, you would get the result we got in v0.23.  (The reason that `num1` works properly is that `aaa.bbb` is already an object, so we just add a `'2'` property.  (Actually, we add a `2` property, but JS is kind (?) enough to convert it for us.

So my take is that this is the expected result.

**Comment by IMalyugin** [comment]
In my opinion this looks more like a fix to undesirable behavior, than one of it's own.

**Comment by CrossEye** [comment]
@IMalyugin: Can you explain why?  The goal was to be able to support more data formats, so that we could address `foo` in `{a:  {b: ['foo', 'bar'], c: 'baz'}, d: 'qux'}`, via `['a', 'b', 0]` in all our *path functions.
