### ISSUE TITLE
`toString` & `contains` dist API has something wrong

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2328]
`toString` becomes `toString$1`
`contains` becomes `contains$1`

<img width="453" alt="screen shot 2017-10-11 at 11 21 37 pm" src="https://user-images.githubusercontent.com/9584123/31450040-0b11e71e-ae6e-11e7-94fd-0ddce52528a0.png">

**Comment by buzzdecafe** [comment]
i wonder if this is related to #2327

**Comment by adispring** [comment]
In https://github.com/ramda/ramda/pull/2327, trim & keys spell typos are in `source` directory, but these two typos are in `dist` directory. This seems due to `build:umd` scripts or `rollup` which produces dist/ramda.js

<img width="1319" alt="screen shot 2017-10-12 at 12 01 33 am" src="https://user-images.githubusercontent.com/9584123/31452293-24a3a23e-ae74-11e7-9c38-2fa5e454fabe.png">

**Comment by CrossEye** [comment]
ping @Andarist: Any ideas?

**Comment by Andarist** [comment]
Yeah, rollup sometimes renames identifiers like that to avoid conflicts between concatenated (scope hoisted) modules.

I had no idea that documentation is built directly from the umd build (which I guess is the case here). Gonna look into fixing this soon!

**Comment by Andarist** [comment]
So like I've stated above - rollup has renamed them due to name conflicts caused by [this](https://github.com/ramda/ramda/blob/ad09c10ebef5c6d20203ed44d2bce5a86599de36/source/keys.js#L15) and [this](https://github.com/ramda/ramda/blob/ad09c10ebef5c6d20203ed44d2bce5a86599de36/source/internal/_isArguments.js#L4).

Imho trimming those suffixes should be done in the docs script to avoid this also in the future (alternative would be to rename those 2 mentioned functions, but I dont feel like its right way to solve this). 

Need some time to figure out how this things is generated and then gonna send a PR with a fix.

**Comment by cht8687** [comment]
Hi guys, I've found the root cause for this and commited a fix for it.

https://github.com/ramda/ramda/pull/2334

**Comment by CrossEye** [comment]
Thanks, @cht8687, @adispring, and @Andarist!
