### ISSUE TITLE
R.equals is slow

### ISSUE THREAD

**Issue by Restuta** [ramda/ramda#2336]
`equals` is at the core of a lot of functions and it's fairly slow as indicated by [this test](https://github.com/ramda/ramda/issues/1500#issuecomment-334633116).

**Comment by CrossEye** [comment]
See the discussion starting with this comment:

https://github.com/ramda/ramda/issues/1500#issuecomment-334496399

**Comment by asaf-romano** [comment]
See also #1518, which could help a lot in some cases.

**Comment by asaf-romano** [comment]
One thing that is easy to spot is that `_equals` is doing way to much for two *non-equal* primitive values. e.g. here's what apparently happens for R.equals(true, false);

1. R.identical(true, false)
-- continue since they are the identical --
2. Run `R.type` for both 
-- continue since they are the identical --
3. `switch` on the (equal) type. Get to the Boolean case
4. Run `typeof` on both
-- continue since they are the identical --
5. return `identical(true.valueOf(), false.valueOf())`

**Comment by asaf-romano** [comment]
I'll PR a fix for that once #2338 is merged (it touches the same code).

**Comment by CrossEye** [comment]
ping @asaf-romano: Closing the issue for now, but hoping you'll have time for a PR.

**Comment by Restuta** [comment]
Thank you @asaf-romano!
