### ISSUE TITLE
requiring from global npm installation fails

### ISSUE THREAD

**Issue by ottonascarella** [ramda/ramda#2370]
Hi, my ramda friends

I was using our beloved library to write a script using node.
I decided to install it globally, since I use it quite a lot.

When I tried using `R.reduce` it said: _reduce is not a function_
Also, `R.assocPath` was giving me some weird errors.
After I installed it locally, all the errors were gone.

Anyone would know why that might happen?

**Comment by CrossEye** [comment]
Hmm, I've never tried to install it globally.  I wouldn't think that could be a problem.

So you did

```shell
npm install -g ramda
```

Then in your script

```js
const R = require('ramda')
// ...
// Use R
```

Is that correct?

Hmm, I can confirm that it doesn't work for me either, although I don't have a clue as to why.  Anyone have an idea?

**Comment by CrossEye** [comment]
From [the NPM docs][np\d]:


>There are two ways to install npm packages: locally or globally. You choose which kind of installation to use based on how you want to use the package.
> 
> If you want to use it as a command line tool, something like the grunt CLI, then you want to install it globally. On the other hand, if you want to depend on the package from your own module using something like Node's require, then you want to install locally.

  [nd]: https://docs.npmjs.com/getting-started/installing-npm-packages-globally

**Comment by ottonascarella** [comment]
I installed it using `yarn global add ramda`, which should just be equal to what you did.

**Comment by Izhaki** [comment]
Global `npm` or `yarn` install are for binaries; so you can run `gulp` and `grunt` and `rimraf` from command line rather than going through an npm script.

Neither Node's [module resolution](https://nodejs.org/api/modules.html#modules_all_together), nor any other module loader framework out there looks at the global node folder when you reference a module in your code(`require`, `import`, etc.). Also, if you really think about it, this wouldn't make much sense.

From [the docs](https://docs.npmjs.com/getting-started/installing-npm-packages-globally):

> If you want to use it as a command line tool, something like the grunt CLI, then you want to install it globally. On the other hand, if you want to depend on the package from your own module using something like Node's require, then you want to install locally.

And here's [a bit more](https://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation/) about it.

This issue should be closed.
