### ISSUE TITLE
Reduce + compose accumulator not resetting

### ISSUE THREAD

**Issue by Slumber86** [ramda/ramda#2378]
See this codepen:

https://codepen.io/anon/pen/KyNebP?editors=1111

Between the calls i found the accumulator keeps the values while should re-initialize itself.
Expected output is both the calls to return 3 elements the second one instead has 6

**Comment by Bradcomp** [comment]
Hi @Slumber86,

This is one of the perils of writing point free code in JS. 

Once a curried function becomes partially applied, it doesn't re-evaluate or clone its applied parameters.  This is fine for primitive values, because they are immutable, however objects are not. So once you begin assigning properties to the object, they will stay there, even across function calls because it was defined in the outer scope, and is not scoped to the function.

See [here](https://goo.gl/CjRMz9).

There  are two ways you could fix the situation. 
1, Update your reducing function so that it doesn't mutate the initial accumulator.  [Here](https://goo.gl/2ZBgFU). Once you remove the mutation by property assignment, the issue goes away.

2. Wrap the composition in a function. [Here](https://goo.gl/V1a1ZU). By wrapping the composition, you are creating a new scope, which will in essence reset the accumulator each time the function is called.

**Comment by Slumber86** [comment]
Thanks @Bradcomp!
I ended using `  reduce((acc, cat) => set(lensProp(cat.category), cat, acc), {}),`
This doesn't mutate the acc object so all keep working normally
