### ISSUE TITLE
Proposal: Add Clojure's thread-left (->>) as function

### ISSUE THREAD

**Issue by yosbelms** [ramda/ramda#2381]
What I propose is a deviation from Clojure's macro. The function should pass the first value to the rest of the functions as it where composed from left to right; functions must be unary.

Example:
```js
// thread :: (x, (a -> b), (b -> c), ... (o -> p)) -> p
let thread = (v, ...fns) => {
  return fns.reduce((acc, f) => f(acc), v)
}

thread(4, inc, add(2)) // 7
```

It looks very close to `pipe`, so, anyone can argue that similar result can be achieved with `pipe` or `compose`. But the problem it addresses (regarding all the functions that Ramda offers) is not about function nor features but code structure. I find it more readable in cases when `pipe` is needed in a not poin-free-style code, in other words, when using `pipe` or `compose` and call the resulting function immediately after the function composition.

A simple example of above could be `pipe(f, g)(a)` it could read as `compose this functions, execute passing 'a'`. The previous example could look trivial and easy to deal with, but the the things starts to get harder when dealing with large compositions. The same code could be written in terms of `thread` as `thread(a, f, g)` which I read like `pipe 'a' though the rest of functions` or `execute this pipeline starting with 'a'`. Noticeably, the second way looks more declarative than the former.

Furthermore, this `thread` function is a good complement for `pipe`, `ifElse`, `cond` or any other high order function. Lets take a look at the following two examples:
```js
// with pipe
thread(4, pipe(inc, add(2)))

// with cond
thread(n, cond([
    [gt(__, 0), always(1)],
    [lt(__, 0), always(-1)],
    [T, always(0)]
]))
```

**Comment by CrossEye** [comment]
While I think I understand your rationale, my first instinct is :-1: on this. 

Ramda is designed around functional composition with parameter order chosen to make such composition easier.

This proposal is aimed at a very different style of coding than Ramda is built around.  Do note that there are proposals to add this to the language as an operator.  (I'm on my mobile so won't look them up but just look for the proposal for the pipeline operator, `¦>`.)

To me

```js
thread(x, f, g)
```

is less readable than

```js
g(f(x)) 
```

so I'm afraid I don't see the point.

**Comment by yosbelms** [comment]
Function composition is easy with Ramda but  when calling the result of that composition inline we have to use `()()` syntax, example:
```js
pipe(
   someFunc1,
   someFunc2,
   someFunc3(),
   someFunc4(a, b),
   someFunc5(c),
   someFunc6)(x)
```
Notice passing `x` at the end of the function

Now with `thread`:
```js
thread(x,
   someFunc1,
   someFunc2,
   someFunc3(),
   someFunc4(x, f),
   someFunc5(s),
   someFunc6)
```
> To me ... is less readable than ...

The example of above with plain JS:
```js
someFunc6(
  someFunc5(x)(
    someFunc4(x, f)(
      someFunc3()(
        someFunc2(someFunc1())))))(x)
```
With just `f` and `g` should be readable anyways but if the last snippet is more readable for you I can understand that in the end of the day I'm just a _mortal-Ramda-user_ but you are not ;)

> Do note that there are proposals to add this to the language as an operator.

Yes, I'm aware. First to say is that it is still in proposal state AFAIK. Second, I don't accept it as a valid point since `ifElse` could be easily replaced by `()=>?:` (arrow function + ternary op) but the proposal of arrow functions and currently its adoption should not be -actually isn't- a valid argument to trim down some Ramda functions or features. So, I should not be acceptable against a proposal either.

**Comment by diegovdc** [comment]
Funny, I was just thinking in proposing the very same thing. But now that I read @CrossEye's response, it is clear that it is not in Ramda's data last style. 

However I think `thread` is indeed very helpful in terms of code readability, and I can see numerous use cases for it.

It would be nice to have in Ramda just to not have to import something else with it, and also to make it available to Ramda's userbase, which I think would also have a lot of use for it.  

IMHO the question would be: are those reasons enough?

**Comment by yosbelms** [comment]
This proposal should be compared in the side of `call` and `apply` instead of in `pipe/compose`. It could be useful when combined with `converge` for example:
```js
converge(thread, [identity, f, g])
```

**Comment by CrossEye** [comment]
I'm still not convinced.  My `f`/`g`  note was mostly in response to your initial example.

I do find this:

```js
add(2, inc(4))
```

easier to read than this:

```js
thread(4, inc, add(2))
```

But that is only part of it.  Ramda to me is all about being able to break things down into simpler and simpler functions.  So if 'increment-and-add-2` is a meaningful concept to me, I want to pull that into it's own function with

```js
const addTwoToInc = compose(add(2), inc)
```

and then later use that with

```js
addTwoToInc(4)
```

(and if the composition is too long for a single line, I'd usually switch to `pipe`.)

While I agree that  the `x` is hard to spot here:

```js
pipe(
   someFunc1,
   someFunc2,
   someFunc3(),
   someFunc4(a, b),
   someFunc5(c),
   someFunc6)(x)
```
I also find it hard to spot here:

```js
thread(x,
   someFunc1,
   someFunc2,
   someFunc3(),
   someFunc4(a, b),
   someFunc5(c),
   someFunc6)
```

Perhaps that's because I've been trained by using `pipe` for quite some time.

But I have much less trouble spotting it in either this:

```js
pipe(
   someFunc1,
   someFunc2,
   someFunc3(),
   someFunc4(a, b),
   someFunc5(c),
   someFunc6
)(x)
```

or, even better, this:

```js
const someCombinedFn = pipe(
   someFunc1,
   someFunc2,
   someFunc3(),
   someFunc4(a, b),
   someFunc5(c),
   someFunc6
)
someCombinedFn(x)
```
----------

I'm sorry for the confusion.  I certainly wasn't trying to suggest that the existence of a language-level proposal would preclude Ramda adopting its own function.  Many, many Ramda functions have similar behaviors to Javascript operators or built-in functions and methods.  I simply wanted to point out to you that you may get a similar behavior from the language itself soon enough.  For the same reasons I discuss here, I don't find much of interest in that proposal.

----------

I also really don't understand the example

```js
converge(thread, [h, f, g])
```

Which, supplied `x` for a parameter would return

```js
g(x, f(x, h(x)))
```

Is there something special about this I should recognize?

----------

Finally, to @diegovdc:

> It would be nice to have in Ramda just to not have to import something else with it, and also to make it available to Ramda's userbase, which I think would also have a lot of use for it.
> 
> IMHO the question would be: are those reasons enough?

My answer to that is: no, that is not enough.  There are many things that might be nice to have in Ramda.  Some of them fit with our philosophy but do not seem common enough to include in the library.  (See the [Cookbook][cb] for examples.)  Others, like this one, don't really fit the philosophy.  Even if they address a common need, they are hard to square with the rest of the library.


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by polytypic** [comment]
> add(2, inc(4))

I actually find ` 2 + (4 + 1)` or `7` even easier to read. 

More seriously, this discussion has not yet mentioned the simple property that makes the proposed `thread` function readable: you can read it [left-to-right and top-to-bottom](http://blog.jessitron.com/2014/04/left-to-right-top-to-bottom.html) without having to visually scan the expression to find where to start.  You simply start with the value being transformed and then apply operations to it one-by-one until you reach the end.

`pipe` is great when you want to introduce a name for the function, but often you don't.  Being able to program without having to name to things unnecessarily for "readability" is a feature rather than a bug.  I often refactor code from using my equivalent of `thread` to using `pipe` and vice versa.

The examples are also misleading in that the functions being used are often much more complex expressions than simple names (higher-order functions given lambda expressions) and then it becomes much more difficult to visually scan the expression to find the point from which it all begins.

BTW, the idea can be dated at least as far as [1994](https://twitter.com/dsyme/status/880768291706470401) and has been [independently discovered](http://comp.lang.functional.narkive.com/zZJZg20r/a-family-of-function-application-operators-for-standard-ml) many times.

**Comment by semmel** [comment]
I agree 100% with @polytypic:
>pipe is great when you want to introduce a name for the function, but often you don't.

With such `pipe` sequences like given above, the data flows not left to right or top to bottom but makes a crazy jump from behind before entering the pipeline. Therefore I usually prefer `compose` unless the sequence is too long.

The proposed `thread` (Btw. I don't like that name at all) sequence would be consistent to other functional pipes in my code E.g.
```javascript
fetch(url)
.then(JSON.parse)
.then(queryDb)
.then(postResult);

Bacon.fromEvent(button, 'click')
.throttle(2)
.flatMap(getUserPermission)
.filter(isOk)
.onValue(sendRequest);
```
But of course it may be just syntactic sugar.

**Comment by CrossEye** [comment]
First of all, I don't want to imply some implacable opposition to this.  I find no need and see it as somewhat contrary to the spirit of Ramda, but it's not some horrible mismatch either.  And as others join in requesting it, it seems more likely than with just a single voice.

But I'm still opposed, for several reasons.  First, I want to change `pipe`/`compose` at some point, to get rid of the only variadic functions in the library.  They would be much the same, only requiring a list of functions rather than separate arguments.  So adding another one seems backward.  This is minor, though, because we could do the same with `thread`.

But assuming we do that, and we'd call it like `thread(4, [inc, add(2)])`, we have a mismatch with the way pretty well all Ramda functions work.  Some people call this "data-last", but I tend to think about it as ordering the parameters from least likely to change to most likely to change.  Pretty well all functions that return a non-function value work this way.  `thread`, by necessity, could not.

> BTW, the idea can be dated at least as far as [1994](https://twitter.com/dsyme/status/880768291706470401) and has been [independently discovered](http://comp.lang.functional.narkive.com/zZJZg20r/a-family-of-function-application-operators-for-standard-ml) many times.

Yes, I'd seen the MSDN/Isabelle article before, although not the other one.  The idea is straightforward, and fairly obvious.  My main question is whether it's a good fit for Ramda.  I'd like to hear from others on the core team about this.  What do you think, @buzzdecafe, @davidchambers, @raine, @paldepind, @TheLudd, @kedashoe, @Bradcomp, @asaf-romano, @scott-christopher?

**Comment by buzzdecafe** [comment]
@CrossEye: FWIW, there are still a number of other variadic functions to purge: `allPass`, `anyPass`, `both`, `either`, `ifElse`, `cond`,  `call`, `complement`, `lift`(!), `memoizeWith`, `nthArg`, `partial`, `partialRight`, `tryCatch`, `unapply`, and maybe some more i missed. I agree we should get rid of 'em.

I don't have a particularly strong feeling on this proposal. I am inclined to agree with you @CrossEye, that it would be something of an odd fit. Also, as we approach 1.0, I am daydreaming about the many functions I would like to *remove* for the next version.  That makes me disinclined to add any new functions at this point.

**Comment by Bradcomp** [comment]
On my part, I agree with @CrossEye. I don't think it's something necessary to add to Ramda.

As a variadic function I think it's weird. I don't like that the first parameter is privileged, and I can't think of a good way to curry it (I know that `compose` and `pipe` aren't curried either). Like, what happens if we pass in a single parameter?

It's better with an array as the second parameter, but then it really does seem like the parameter order is flipped from what you would expect.

Lastly, we now have `R.applyTo`, which is basically the same thing, and makes `thread` trivial to implement.

```
R.applyTo(
  4,
  pipe(
    inc,
    add(2)
  )
)
```

**Comment by CrossEye** [comment]
@buzzdecafe: I was thinking about functions for which the number of parameters is not fixed, not those that accept variadic functions.  We cleaned up `useWith` and `converge` so that they take lists of functions; I would like to do the same for `pipe` and `compose`, although this is not at all urgent.  The question of not even accepting variadic functions as parameters is much broader, and much more difficult.

@Bradcomp: wow, I'd already forgotten that one!  Yes, while that's not quite as convenient as `thread`, it's pretty simple.

**Comment by semmel** [comment]
@Bradcomp : Didn't know about `R.applyTo`. Nice! Thank you!

**Comment by polytypic** [comment]
> [@CrossEye] others join in requesting it, it seems more likely than with just a single voice

Not everyone spends time in discussions here, but some of my colleagues familiar with Clojure have told that having equivalent of Clojure's `->>` is something they'd really like to have.  (Personally I already use a `seq` function that does the same thing as the proposed `thread`.)

> [@Bradcomp] Like, what happens if we pass in a single parameter?

That is simple: `thread(x) = x`.

`thread` is actually better behaved than Ramda's `pipe`, which doesn't have zero. You can't say `applyTo(2, pipe())`, but you can say `thread(2)`.

> [@CrossEye] we have a mismatch with the way pretty well all Ramda functions work [...]
> [@Bradcomp] I can't think of a good way to curry it [...]

I think there is misunderstanding as to the purpose and utility of `thread`.  It is a *notational convenience* for *consuming* Ramda style data last functions.

As an aside, it is really frustrating to see people talking about the concept as "composition".  It is not an introduction form.  It is an elimination form.

```haskell
(|>): x -> (x -> y) -> y
```

It takes a value of type `x` and an abstraction of type `x -> y` and eliminates the abstraction.  That is what I mean when I say the `thread` operation is for *consuming* Ramda style data last functions.

The codebase of the project I'm currently working on has lots of uses of `pipe` where the constructed composition is just immediately used:

```js
const fb = R.pipe(
  R.foo( /* Written on separate lines, because these are */ ),
  // ...
  R.bar( /* often long expression spanning multiple lines. */ )
)(x)
```

A function like `thread` would make all of those a bit easier to read.  Not to mention that operationally using `pipe` like that makes little sense, because it amounts to creating (allocating) a composed function, using it once, and then throwing it away.

Perhaps `|>` makes it to JS eventually, but, in the meanwhile, I recommend using something like `thread` to consume Ramda style data last functions.

**Comment by CrossEye** [comment]
@polytypic:

I don't dispute the usefulness, only whether it's a good fit for Ramda.  Ever since we removed `installTo`, back in #834, we have been able to say "No Ramda functions modify user data."  It's nice to be categorical like that.  I would like to be able to say "All Ramda functions of more than one parameter are curried".  It's just cleaner.  It makes it easier to describe how the library works, and to explain its place in the JS world.  But this function, even if changed to `thread(x, [list, of, ..., functions])`, would not be curried appropriately in Ramda.  I simply don't like those sorts of caveats.


> Not to mention that operationally using `pipe` like that makes little sense, because it amounts to creating (allocating) a composed function, using it once, and then throwing it away.

This is the most compelling point, and it also applies to the suggestion from @Bradcomp above with `applyTo`.

I know mine is not the only way people work with Ramda; it's clearly different from that of several people writing here.  I rarely use any of Ramda's combining operators (`pipe`, `compose`, `converge`, `lift`, `useWith`, _et. al._) to directly create values.  I almost always use them to create reusable functions.  Perhaps if I worked this way more often it would seem logical to me to include the function.  But I would still be loathe to say, "All Ramda functions, except `thread`,...".  And that's my biggest sticking point.

**Comment by kedashoe** [comment]
> But this function, even if changed to thread(x, [list, of, ..., functions]), would not be curried appropriately in Ramda. I simply don't like those sorts of caveats.

Why not? Is `applyTo` not curried appropriately?

**Comment by CrossEye** [comment]
>> But this function, even if changed to `thread(x, [list, of, ..., functions])`, would not be curried appropriately in Ramda. I simply don't like those sorts of caveats.

> Why not? Is `applyTo` not curried appropriately?

I think it is.  The semantics of `applyTo` involve specifically starting with a value and applying a function to it.  With this, the parameter more likely to change is actually the function.

But `thread` doesn't come across that way to me.  While it is perfectly usable, the partial application of `thread(x)` does not seems to me to have those same connotations.  Maybe I'd find it more likely with a different name, I don't know.

**Comment by kedashoe** [comment]
> The semantics of applyTo involve specifically starting with a value and applying a function to it. With this, the parameter more likely to change is actually the function.

I don't understand the distinction.. can't we say "The semantics of `thread` involve specifically starting with a value and applying one or more functions to it"

> Maybe I'd find it more likely with a different name, I don't know.

I call if `flush` in my ramda utils to keep with the plumbing theme :)

**Comment by CrossEye** [comment]
> I don't understand the distinction.. can't we say "The semantics of `thread` involve specifically starting with a value and applying one or more functions to it"

Well, of course you can say whatever you want.  But to me that doesn't at all sound like what "thread" would mean.  But I suppose that's all my own issue.  I certainly don't have an internal model of what `juxt` should mean.

**Comment by yosbelms** [comment]
Naming it `flush` makes it fit better in Ramda IMO.
 `flush :: a -> [(a -> b), (b -> c), ...., (d -> e)] -> e`
```js
let flush4 = flush(4)
flush4([inc, add(2)]) // 7
```

**Comment by polytypic** [comment]
> [@CrossEye] I would like to be able to say "All Ramda functions of more than one parameter are curried".

I sympathize with that goal.  I've spent a large chunk of my career writing ML and I appreciate functions with simple signatures.  However, it is painfully obvious to me that JS (like Lisp style languages) is not ML and the ergonomics are quite different.  In JS libraries I've authored, I've used both "template object" based functions (like `R.evolve`) and variadic functions (like `R.pipe`), because the alternative of building such functions from parts, like one would have to do those in ML, would just be cumbersome in JS.  While doing so I have always thought about the algebraic properties of such functions.  As a simple example, the astute reader should notice that [`L.choices`](https://github.com/calmm-js/partial.lenses/#L-choices) forms a semigroup (over optics in read-direction) and [`L.choice`](https://github.com/calmm-js/partial.lenses/#L-choice) is an extension of said semigroup to a monoid with [zero](https://github.com/calmm-js/partial.lenses/#L-zero).  In a way I don't think of such variadic and template based functions as functions per se.  I think of them as notations for the associated algebraic operations and in this particular case the underlying binary operation is also provided as [`L.orElse`](https://github.com/calmm-js/partial.lenses/#L-orElse) (albeit in a flipped form for practical reasons that I'm sure you can spot).

So, how about not calling the proposed `thread` a "function" and referring to it and other operations like it with some other technical term?  This way documentation could be clear about the distinction and one could indeed say that "All Ramda functions [snip] are curried".

Speaking of variadic functions and algebraic properties, while I find that `pipe` (and `compose`) in Ramda actually usually does what I want, its algebraic properties are not so nice.  It doesn't have an `identity` element (pun intended) due to the special treatment of the first argument to `pipe`.

I would also like to add that, IMO, changing a variadic function to instead take an array doesn't improve things radically.  What it mainly does is that it makes the syntax of applying such functions more verbose.  At the same time it doesn't make it really simple to access the underlying algebraic operations, because you need to do so indirectly by operating on an array of things.  It would likely be better to provide both a variadic function and the associated binary operation (which should agree, unlike with `compose` and `o`).

> [@kedashoe] I call if `flush` in my ramda utils to keep with the plumbing theme :)

🤣

**Comment by CrossEye** [comment]
> So, how about not calling the proposed `thread` a "function" and referring to it and other operations like it with some other technical term? This way documentation could be clear about the distinction and one could indeed say that "All Ramda functions [snip] are curried".

<shudder>

That sounds like playing games.

I don't mean this to be simple wordplay.  I really do want to have consistency across Ramda functions.  The "of more than one parameter" was just a way of saying "all functions where it makes sense", as there's no reason to curry functions of one parameter ([even though we do][c1]!)

But, as I said, my main objection to this lies in the internal consistencies of the library, not in some major objection to the function itself.  That I wouldn't find much need for it myself would not make me want to exclude something that has a large fan-base.  But I would want to include it only if it also seems to fit with the design of Ramda.  Even when requiring the functions to be supplied in an array, it still feels to me like a mismatch.  But there are several people arguing for it, including core team member @kedashoe, which should help.


> At the same time it doesn't make it really simple to access the underlying algebraic operations, because you need to do so indirectly by operating on an array of things.

Again, that is not really the goal.  Ideally, one should be able to simply intuit how to use a Ramda function.  Internal consistency across the library is an increasingly important factor for me.

>(which should agree, unlike with compose and o).

Are you referring to the fact that `f` and `g` have to be unary, as is `o(f, g)`, or is three some more serious concern?

  [c1]: https://github.com/ramda/ramda/blob/master/source/internal/_curry1.js

**Comment by polytypic** [comment]
> That sounds like playing games.
>
> I don't mean this to be simple wordplay.

More like the opposite of that: clearly differentiating between (curried) functions with simple fixed-arity signatures and functions with more complex signatures.

> there's no reason to curry functions of one parameter

Indeed.

> Ideally, one should be able to simply intuit how to use a Ramda function.

Based on what information?

The name?

The complete signature?

Are you *seriously* suggesting that adding one more bit of information (variadic or not) to the already quite complex signatures of Ramda functions (that include arbitrary overloading, object templates, type class constraints, n-ary functions that are sometimes curried and sometimes not, variadic functions(!), can sometimes act as transducers, and more) completely breaks down the ability to intuit how Ramda functions work?

> Are you referring to the fact that `f` and `g` have to be unary, as is `o(f, g)`, or is three some more serious concern?

That is what I'm referring to.  Quite simply, `compose(f, g)` is not equivalent to `o(f, g)`.  What could be more serious than that?  From an algebraic point of view it would make sense to have `compose(f, g, h)` to be equivalent to `o(f, o(g, h))` and also to `o(o(f, g), h)`.  It would also make sense to have `compose()` to be equivalent to `identity`.  Unfortunately none of that is the case.

**Comment by buzzdecafe** [comment]
> Are you seriously suggesting that adding one more bit of information (variadic or not) to the already quite complex signatures of Ramda functions (that include arbitrary overloading, object templates, type class constraints, n-ary functions that are sometimes curried and sometimes not, variadic functions(!), that can sometimes act as transducers, and more) completely breaks down the ability to intuit how Ramda functions work?

Zing! that one stung

**Comment by CrossEye** [comment]
>> Ideally, one should be able to simply intuit how to use a Ramda function.

> Based on what information?

Knowledge of what the function does.  The point was that if you're familiar with Ramda idioms, and you want to remember how to use the function `filter`, you would simply know that the predicate must be supplied first and the filterable data last.  This does not, of course, tell you what `filter` does.  But if you don't know that, you have to start elsewhere anyway.  That's why I'm hesitant to include a function where that intuition is wrong.  This is one place where Ramda has been very consistent.

> Are you *seriously* suggesting that adding one more bit of information (variadic or not) to the already quite complex signatures of Ramda functions (that include arbitrary overloading, object templates, type class constraints, n-ary functions that are sometimes curried and sometimes not, variadic functions(!), that can sometimes act as transducers, and more) completely breaks down the ability to intuit how Ramda functions work?

I'm suggesting that we simplify as much as we can.  AFAIK, we only have two functions right now which are variadic, `pipe` and `compose`.  (There are many others which accept variadic functions, but that's a whole other story.)  I would like to change those to take a list of functions, and certainly don't want to add any more.  Post 1.0, I would like to consider making all our functions, and all the functions we accept unary.  The point is that I want to keep simplifying, and a function that behaves differently from everything else doesn't seem the way to do that.

> Quite simply, `compose(f, g)` is not equivalent to `o(f, g)`.  What could be more serious than that?  From an algebraic point of view it would make sense to have `compose(f, g, h)` to be equivalent to `o(f, o(g, h))` and also to `o(o(f, g), h)`.  It would also make sense to have `compose()` to be equivalent to `identity`.

I actually want to address all of this.  I was wondering, though, if you saw any functions `f` and `g` that would work with `o(f, g)` that would work differently with `compose(f, g)`.  That would concern me a lot more.  That there are functions that will work with `compose` and not `o` doesn't bother me much, as `compose` is meant to work with JS's variadic functions.  (And I don't mean could you invent one.  Obviously with `arguments`, it's easy enough to create such.  I simply would like to know if there are real-world scenarios to be concerned about?)

**Comment by yosbelms** [comment]
@CrossEye 
By reshaping it to `drive :: a -> [(a -> b), (b -> c), ..., (d -> e)] -> e` would make it Ramda philosophy compliant? I think it does. In this way it is composable, and it can replace pipe in many cases.
```js
// 1. waiting for a list of unary functions
drive(obj)

// 2. waiting for the first param
drive(__, [pick(['a', 'b']), sum])

// 3. shining!
drive(obj, [pick(['a', 'b']), sum]

```

**Comment by CrossEye** [comment]
`drive` works much better to me as a name for this than `thread`.  I'm not sure why.  And yes, I think that passing the functions as a list makes it much less objectionable.  I don't think the extra brackets are a large burden.  In fact, I want to introduce them in `pipe` and `compose` too at some point.

I would not have a major objection to this proposal.  If people wanted to argue for `thread` instead of `drive` based on prior art, I would certainly be willing to listen.  But with `drive`, my objections seem to clear.

**Comment by GingerPlusPlus** [comment]
The `drive` function can be easily implemented as:

```js
const drive = R.reduce(R.applyTo)
```

[Repl](https://goo.gl/WkUm5A)

Maybe it should be added to [the cookbook](https://github.com/ramda/ramda/wiki/Cookbook).

**Comment by pvinis** [comment]
what's the final decision on this? Added nowhere?

**Comment by GingerPlusPlus** [comment]
Added to [Cookbook](https://github.com/ramda/ramda/wiki/Cookbook#drive).
