### ISSUE TITLE
addIndex on reduceWhile, provides index into predicate and not into iterator

### ISSUE THREAD

**Issue by komlev** [ramda/ramda#2397]
addIndex puts index into predicate and not into iterator

```javascript
R.addIndex(R.reduceWhile)(
  (a1, a2, a3) => {
    console.log('predicate', a1, a2, a3)
    return true
  },
  (a1, a2, a3) => {
    console.log('iterator', a1, a2, a3)
    return a1
  },
  true,
  ['a','b','c']
)
```

```
predicate true a 0
iterator true a undefined
predicate true b 1
iterator true b undefined
predicate true c 2
iterator true c undefined
```

**Comment by kedashoe** [comment]
I don't know about adding special cases to `addIndex`, but you can `flip(reduceWhile)` if you want the index on the iterator: https://goo.gl/1oc9rS

**Comment by Bradcomp** [comment]
If we look at the signatures of `addIndex` and `reduceWhile`, we can see that we can actually add an index to either the predicate or the iterator. 

`addIndex :: ((a … → b) … → [a] → *) → (a …, Int, [a] → b) … → [a] → *)`

Add index will operate on the _first_ function that gets passed to the modified function it returns. That's why `flip` will 'fix' the issue. 

Another option is to apply the predicate _before_ calling `addIndex`.

```
R.addIndex(R.reduceWhile(
  (a1, a2, a3) => {
    console.log('predicate', a1, a2, a3)
    return true
  }))(
  (a1, a2, a3) => {
    console.log('iterator', a1, a2, a3)
    return a1
  },
  true,
  ['a','b','c']
)
```

Because `reduceWhile` takes two functions, we need to specify, via partial application, which function we would like to add the index to.

**Comment by komlev** [comment]
@Bradcomp, @kedashoe, thanks for the solution! No issue here then.
