### ISSUE TITLE
Internal _isObject function returns true for null value in IE8

### ISSUE THREAD

**Issue by kamaladafrica** [ramda/ramda#2402]
In IE8 Object.prototype.toString.call(x) return [object Object] instead of [object Null]

Running this code in IE8, it throws 'Object expected'
```javascript
R.over(R.lensProp('a'), R.mergeDeepLeft({b: {c: 1}}))({a: {b: null}})
```

I could not figure out if IE8 is still supported, reading the issue  #1983

**Comment by thebedivere** [comment]
I don't think this is going to work with IE 8 without some type of polyfill. The `over` function relies on applying a function ('fn.apply()'),  which seems to not be fully supported on IE8: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

**Comment by CrossEye** [comment]
I'm loathe to put in much effort in order to support IE8, but this should be an easy fix.  Our public `is` function shouldn't have the same issue, even in IE8.

As to what browsers are supported, it's always been a funny thing.  Most of the initial development never really cared about browsers, since the data manipulation that is Ramda's strength was more likely to be done in Node.js.  And to have an official browser list, we would need to get something like SauceLabs working again.  I don't know if there's anyone with the appetite to try that.
