### ISSUE TITLE
Why should I use Ramda instead of native Array methods

### ISSUE THREAD

**Issue by gkatsanos** [ramda/ramda#2404]
After watching https://www.youtube.com/watch?v=JRzly-t4Boc I started wondering why replace `.map` and `.filter` with Ramda. I like the concise syntax and shorter code, as well as the overall mentality but wouldn't using an external library instead of native bring a performance penalty to my APP? (sorry if that question is too naive or low level for some!)
Generally I looked for reasons to switch to Ramda and - also asking in the gitter channel - didn't get any answers.
Thanks for your time, excellent work!

**Comment by CrossEye** [comment]
> wouldn't using an external library instead of native bring a performance penalty to my APP? 

Often enough, no.  The simpler APIs of Ramda's functions allowed for simpler implementations, which meant that when we wrote them, they were often faster than their native counterparts.  Of course, many of the JS engines have moved on since then, and I really don't know how they compared.

We have added more to our functions as we went, and performance may have suffered.

But to me, the reason for using these functions have very little to do with speed.

  - `map` is not just "*run a function against every element of an array and return an array of the results.*"  Our function is much more general:

    ```js
    const square = n => n * n
    map(square, [1, 2, 3]) //=> [1, 4, 9], as exptected, but also:
    map(square, Just(7)) //=> Just(49)
    map(square, Nothing) //=> Nothing
    map(square, Right(5)) //=> Right(25)
    map(square, Left('error')) //=> Left('error')
    map(square, Task((_, __) => 10)) //=> Task((_, __) => 100)
    map(square, n => n + 1)(3) //=> 16
    ```

  - `map` makes obvious the strong connection between an expression involving a value and a function which takes that value as a parameter:

    ```js
    const withTax = map(addTax, itemsBought)

    // getWithTax :: [LineItem] -> [LineItem]
    const getWithTax = map(addTax)
    ```

    Compare this to native:

    ```js
    const withTax = itemsBought.map(addTax)

    // getWithTax :: [LineItem] -> [LineItem]
    const getWithTax = itemsBought => itemsBought.map(addTax)
    ```

  - The function supplied to `map` is simpler, so you don't get as many silly results such as:

    ```js
    ['1', '2', '3'].map(parseInt) //=> [1, NaN, NaN]
    map(parseInt, ['1', '2', '3']) //=> [1, 2, 3]
    ```

  - Functional programming is about many things, but chiefly it's about working with lawful, pure functions against immutable data.  Ramda functions make this easy.  This is native:

    ```js
    const tutone = [8, 6, 7, 5, 3, 0, 9]
    totone.sort((a, b) => a - b) //=> [0, 3, 5, 6, 7, 8, 9]
    // But now 
    tutone //=> [0, 3, 5, 6, 7, 8, 9]
    ```

    This is Ramda:

    ```js
    const tutone = [8, 6, 7, 5, 3, 0, 9]
    const jenny = sort((a, b) => a - b, tutone) 
    jenny //=> [0, 3, 5, 6, 7, 8, 9]
    // But still
    tutone //=> [8, 6, 7, 5, 3, 0, 9]
    ```

In fact, I wrote a whole article on [Why Ramda?][wr]


  [wr]: http://fr.umio.us/why-ramda/#header

**Comment by gkatsanos** [comment]
I very much appreciate the time you took to write this! It seems that it makes you help more DRY code, make refactorings & logic changes easy. Seems that for complex algorithms it can also speed up development. Thanks!
