### ISSUE TITLE
Possibly oldschool typescript defs

### ISSUE THREAD

**Issue by kujon** [ramda/ramda#2416]
Ramda's homepage points to https://github.com/types/npm-ramda/ as the source of the TS definitions. DefinitelyTyped repo seems to be a universally accepted way of bringing the typings in  nowadays and it also happens to contain Ramda typings: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ramda, hence my 2 questions:
1. which one of the two resembles reality more?
2. irrespectively of which one does, should the 'better' one be maintained here https://github.com/DefinitelyTyped/DefinitelyTyped and referenced from the homepage accordingly?

**Comment by CrossEye** [comment]
Few on the core team have any expertise in this area, so we rely on whoever is interested in maintaining these.  The consensus here seems to be that npm-ramda has more accurate typings, most recently discussed in #2306.  If you can find a way to get the more common repository to become more accurate, I'm sure we'll include it on the homepage as well as or instead of npm-ramda.
