### ISSUE TITLE
R.without reorders keys

### ISSUE THREAD

**Issue by smooJitter** [ramda/ramda#2419]
I using R.without to compare to arrays of objects.  The initial objects contain the identical keys with the same order.  R.without reorders the keys after the comparison.

```
const  a = [
  {
    songId: 'apples', 
    title: 'jacks"
  }, 
  {
    songId: 'no', 
    title: 'problems"
  }]

const  b = [
  {
    songId: 'apples', 
    title: 'jacks"
  }, 
  {
    songId: 'issues', 
    title: 'now"
  }]

```
the results R.without(a, b) looks like 

```
  [{
    title: 'now",
    songId: 'issues', 
  }]

```
this becomes a problems with the second round of comparisons because the keys and key ordering no longer matches. 

Please advise

**Comment by josepot** [comment]
That doesn't make any sense. [See this](http://ramdajs.com/repl/?v=0.25.0#?const%20%20a%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20songId%3A%20%27apples%27%2C%20%0A%20%20%20%20title%3A%20%27jacks%27%0A%20%20%7D%2C%20%0A%20%20%7B%0A%20%20%20%20songId%3A%20%27no%27%2C%20%0A%20%20%20%20title%3A%20%27problems%27%0A%20%20%7D%5D%0A%0Aconst%20%20b%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20songId%3A%20%27apples%27%2C%20%0A%20%20%20%20title%3A%20%27jacks%27%0A%20%20%7D%2C%20%0A%20%20%7B%0A%20%20%20%20songId%3A%20%27issues%27%2C%20%0A%20%20%20%20title%3A%20%27now%27%0A%20%20%7D%5D%0A%0Awithout%28a%2C%20b%29%5B0%5D%20%3D%3D%3D%20b%5B1%5D).

**Comment by CrossEye** [comment]
@smooJitter:  While @josepot's example clearly shows there is an issue with the example, I think the problem is more fundamental.  Ramda doesn't care about the order of the keys.  At some point, we may choose to sort them, to avoid a number of problems.  But when we test if objects are equal, we don't take key order into account.  So if `b` started with

```js
{
  title: 'jacks',
  songId: 'apples' 
}, 
```

you would still get the same behavior from `without(a, b)`.

----------

@josepot: While creating a failing test is probably the best way to demonstrate an issue, we certainly do not insist on it around here.

**Comment by josepot** [comment]
> @josepot: While creating a failing test is probably the best way to demonstrate an issue, we certainly do not insist on it around here

Sorry about that.

> While @josepot's example clearly shows there is an issue with the example

Actually what I was trying to point out is the fact that `R.without` won't "clone" anything. Meaning that the instances of the resulting list will also belong to the list of the second parameter. I thought that was relevant because the following sentence:

> R.without reorders the keys after the comparison

implies that the OP is under the impression that `R.without` returns different instances. If I understood correctly, the OP is actually saying that`R.without` "rebuilds" those objects and I don't think that will ever be the case.

> the results R.without(a, b) looks like

^^ The OP is complaining that the instance of the resulting list is different.

I totally agree with the fact that for comparing the equality of 2 objects the order of the keys shouldn't be taken under consideration. AFAIK an Object in JS is an **unordered** collection of properties... So, even when cloning an object it would be absurd to try to preserve an "un-existing" order. However, I don't think that `R.without` will ever clone anything.

It seems to me that this is an XY Problem, that has to do with the fact that the OP is not aware that in JS Objects are unordered collections of properties.

**Comment by CrossEye** [comment]
>> @josepot: While creating a failing test is probably the best way to demonstrate an issue, we certainly do not insist on it around here

> Sorry about that.

Nothing at all to be sorry for.  You're absolutely right that that's the ideal way to demonstrate an issue.  Some people do so, and we appreciate it.  But we haven't made it a requirement here.

**Comment by smooJitter** [comment]
Thanks @CrossEye.  I learned the real issue was with Mongodb Mongoose.  Mongoose reorders the props on insertion of new objects.

**Comment by russiancow** [comment]
@smooJitter I think the real issue is that JavaScript objects are unordered as per the spec—the browser is allowed to return object keys in any arbitrary order, even for the same object. (See [this Stack Overflow answer](https://stackoverflow.com/a/5525820/104184) for more info.) Even though most (all?) modern browsers do maintain key order internally, it's not a behavior you should rely on.

**Comment by CrossEye** [comment]
@russiancow: That has been changed in later editions of the specification.  Key order is specified, but it's to my mind spectacularly unhelpful.

**Comment by russiancow** [comment]
@CrossEye: My understanding based on [this reply](https://esdiscuss.org/topic/property-ordering-of-enumerate-getownpropertynames#content-2) and other discussions I've seen is that key order is specified *for some operations* (like `Object.getOwnPropertyNames`), but not for any legacy mechanisms like `for`/`in` loops and JSON conversions. So I guess the real, technical answer is "it depends", but I still hold that it's not a behavior that should be relied on, and ultimately doesn't matter in real world code (and my reading of your comment is that you agree 😄).

**Comment by CrossEye** [comment]
Well, there's been a long-running discussion in Ramda about defining our own key order where it matters.  We have an issue where `equals({x: 1, y: 2}, {y: 2, x: 1}) //=> true` but `equals({keys(x: 1, y: 2}), keys({y: 2, x: 1})) //=> false`, and that seems a big deal.
