### ISSUE TITLE
R.either is not fully curried

### ISSUE THREAD

**Issue by LeoPapais** [ramda/ramda#2425]
Hello there,

I've noticed that to properly use the R.either function, we need to write like ```R.either(pred1, pred2)(x)``` and writing like ```R.either(pred1, pred2, x)``` will fail to use x as parameters for pred1 and pred2.

I don't see any reason to this behavior, is this a design decision for some case or should I open a pull request using ```_curry3``` instead of ```_curry2``` in it's implementation?

Thanks in advance.

**Comment by Bradcomp** [comment]
Hi @LeoPapais 
Thanks for checking on this. `R.either` is not curried to 3 parameters because it is designed so that the resultant function can take more than one parameter.

Consider a function that takes an x and a y, and returns true if the point is in the first or third quadrant of a graph: 
```
const inFirstQuadrant = (x, y) => x >= 0 && y >= 0;
const inThirdQuadrant = (x, y) => x <= 0 && y <= 0;

const inFirstOrThird = R.either(inFirstQuadrant, inThirdQuadrant);

inFirstOrThird(1, 2)  //true 
```
https://goo.gl/1guHm1

This would not be possible if R.either was curried to three parameters.

It's an open question on whether we want to continue supporting these functions that return variadic functions, but for now there are a number of functions that act like this, and typically this is the reason.

**Comment by LeoPapais** [comment]
@Bradcomp , now I understand it, thanks for your explanation.
