### ISSUE TITLE
R.chain(f, g) and R.converge(f, [g, R.identity]) behaves differently

### ISSUE THREAD

**Issue by fredrik-hjarner** [ramda/ramda#2426]
I have heard that _**R.chain(f, g)**_ will act like _**R.converge(f, [g, R.identity])**_ when f ang g are functions.

I did some experiments and noted some differences with various variants of calculating 1+1:

### 1. R.converge with _**uncurried**_ converging function.
It returns 2 as expected.
```
R.converge(
  (x, y) => x + y,
  [
    R.identity,
    R.identity,
  ],
)(1);
```

### 2. R.converge with _**curried**_ converging function.
It returns the **_function_** y => 2 + y

```
R.converge(
  x => y => x + y,
  [
    R.identity,
    R.identity,
  ],
)(1);
```

### 3. R.chain with _**curried**_ first argument.
It returns 2.

```
R.chain(
  x => y => x + y,
  R.identity,
)(1);
```

### 4. R.chain with _**uncurried**_ first argument.
It throws an exception.

```
R.chain(
  (x, y) => x + y,
  R.identity,
)(1);
```

So this might be an inconstistency between R.chain and R.converge. One requires a curried function, and the other requires an uncurried function.

### 5. R.converge gets two arguments.
It returns 4, which is correct
since (1+1) + (1+1) = 4

```
R.converge(
  (x, y) => x + y,
  [
    R.add,
    R.add,
  ],
)(1, 1);
```

### 6. R.chain gets two arguments.
It returns a function.
R.add only receives the first argument,
so R.add still waits for a value and thus
x becomes set to R.add(1).

```
R.chain(
  x => y => x + y,
  R.add,
)(1, 1);
```

I am not sure that these different behaviors are bugs, but at least I thought the functions acted a little strangely.

**Comment by CrossEye** [comment]
I think all these are as expected.

Think of `chain` specialized to functions as

```hs
chain:: (a → r → b) → (r → a) → (r → b)
```

Thus `chain(f, g)(x) ==> f(g(x), x)`, and it will *only* take a curried function (either manually curried or with `R.curry`.)  `chain` only works with unary functions.

`converge` is more complicated, and not as standardized as `chain`.  It is also older in Ramda.  It's designed to work with polyadic functions.  It's designed around usage like

```js
converge(f, [g, h])(x, y) //=> f(g(x, y), h(x, y))
```

Note that there is a slight error above:

```js
R.converge(
  x => y => x + y,
  [
    R.identity,
    R.identity,
  ],
)(1)
```

actually returns the function `y => 1 + y` (not `y => 2 + y`):

It basically calls `x => y => x + y` with the values `(1, 1)` (== `(identity(1), identity(1))`.  But that function is unary, and so it only recognizes the first parameter.

My usage these days is to often think about `converge` first, since it's more powerful and more flexible, but if the main function is or easily can become curried, and the feeder functions are unary, then I'll switch to `chain` as it's simpler, and closer to standard.

I have little appetite to try to change the behavior of these.  `chain` would have little flexibility in any case, as we try to match the [FantasyLand definition][fd].  And `converge` seems to do what it was designed to do.  The fact that you can't use `(x) => (y) => ??` when it expects `(x, y) => ??` seems to just be a part of Javascript.  (If you have a suggestion to fix that, I'm all ears.)


  [fd]: https://github.com/fantasyland/fantasy-land#chain

**Comment by CrossEye** [comment]
I'm getting old!

The other thing to discuss here is how much of `converge` can be captured by `lift`.  See #1447 for more details.
