### ISSUE TITLE
applySpec + append followed by evolve: append works only if wrapped by function

### ISSUE THREAD

**Issue by franciscotln** [ramda/ramda#2435]
I'd like to know if this is the expected behaviour although I doubt it.

Given:
```
const currentValue = {
  todos: ['a'],
};
```
I'd like to update this "todo" properties:

```
const spec = R.applySpec({ todos: p => R.append(p) }) ('b');

R.evolve(spec, currentValue);
```

When the function R.append is wrapped by this fat arrow it works as expected. The problem is when I remove the fat arrow, since R.append is curried it should work but it doesn't:
```
const spec = R.applySpec({ todos: R.append }) ('b');

R.evolve(spec, currentValue);
```

Please check the code on REPL: https://goo.gl/arZ3SH

**Comment by CrossEye** [comment]
[The problem is that `applySpec` takes its arity from the function(s) supplied.  (It uses the maximum of them).  Since `append` takes two arguments, `R.applySpec({ todos: R.append })` is also binary, and when you apply `'b'` to it, instead of getting a spec object, you get back a new function.

You can fix this as you did with an arrow function or by wrapping `append` in `unary`.

I don't think there is much else to do here.  Such things happen occasionally because Ramda tries to work as best it can with variadic functions.  It's not common, and there's usually a fairly easy solution, but it can be annoying.

**Comment by franciscotln** [comment]
Yes, I figured that out later. I think there's nothing to fix here really. But thanks for replying anyway :-) I'm closing it.
