### ISSUE TITLE
[Proposal] - Consider ramda as a mono-repository

### ISSUE THREAD

**Issue by guillaumearm** [ramda/ramda#2443]
Hi everyone, I started this proposal on #2440 thread.
considering I started to go off topic (sorry for that), I decided to create another ticket for this.

## The idea

The idea is to put the source code of `ramda-adjunct` into `ramda` repository,
assuming that `packages/ramda-adjunct/` folder have it's own `package.json` file.

Perhaps we would put [ramda-fantasy](https://github.com/ramda/ramda-fantasy) too in this folder.

Obviously, `packages/` folder is not uploaded when `ramda` is published on npm.

feel free to read https://github.com/babel/babel/blob/master/doc/design/monorepo.md

### Don't worry about users, there are no breaking changes.

`npm install ramda` and the `import * as R from 'ramda'` will still true even if we choose to work in the same repo.

### The main goal
The goal is to share the same issues, same commits, same community, same problems, same ideas, same tools.

For example, if someone propose to add a function in ramda, we will dicuss about where this function will go, and so on...

### A lot of changes
But it's a lot of work : 
- git workflow reconciliation
- use of [lerna](https://lernajs.io)
- team management
- project re-organization

### Advantages
Advantages for ramda are : 
- encourage collaboration
- ensure consistence between ramda modules
- grow ramda community through sharing
- learn new things about project management

### Disadvantages
For me, disadvantages are same as said on : https://github.com/babel/babel/blob/master/doc/design/monorepo.md 

- Codebase looks more intimidating.
- Repo is bigger in size.
- [Can't `npm install` modules directly from GitHub](https://github.com/npm/npm/issues/2974)
- ???

There are unknown factors, I will continue to dig into "monorepos" stuff to bring more feedback about it.

-----------------

I know, it sounds like fashion stuff, because lots of famous repository use monorepos.
We can easily think that is overkilled and inconvenient, but with a long term thinking, we can imagine awesome advantages.

if this proposal annoy you, I would understand, it's a big deal.

**Comment by CrossEye** [comment]
> if this proposal annoy you, I would understand, it's a big deal.

Not at all.  But the advantages and disadvantages are going to take a while to sink in.

At the moment, the main Ramda repos are 

  - **ramda**': the core library, of course
  - **ramda.github.io**: the docs repo
  - **repl**: the REPL code extracted into its own repo
  - **es-lint-plugin**: (recently added) linting rules for Ramda
  
Fairly recently deprecated is 

  - **ramda-fantasy**: Some basic [Fantsy-land][fl]-compatible types

These are not really in active development:

  - **ramda-logic**: a micro-Kanren implementation
  - **ramda-lens**: an attempt to build more sophisticated lenses in Ramda
  - **ramda-highland**: a short-lived attempt at integrating Ramda and Highland
  - **ramdangular**: an old attempt at plugging Ramda into Angular

These, I believe can safely be deleted now:

  - **jsdelivr** - an old-school mechanism to connect to JSDelivr
  - **cdnjs** - the same for CDNJS

Would you expect to include only the top four, or some of the others as well?  What other external 
 tools should be folded in besides `ramda-adjunct`?  Some of @raine's [tools][to]?  Other things?

@guillaumearm: Have you been through this transition before?  You say it's a fair bit of work.  How much?


  [fl]: https://github.com/fantasyland/fantasy-land
  [t0]: https://github.com/ramda/ramda/wiki#tools-alien

**Comment by tommmyy** [comment]
I would like you to inform you that there is more alternatives to ramda-adjunct like [ramda-extension](https://github.com/tommmyy/ramda-extension) (I am contributor). We make a lot of time and effort to further developing of the library because we are funs of ramda :)

**Comment by aizerin** [comment]
I don't see much income in mono-repo for libraries like Ramda. Ramda is a small library and it will only bring complexity for PRs, issues and versioning. Mono-repo would make sense only if the Ramda should be split into more parts or if all subsequent core repos (like @CrossEye mentioned above) should be together. I don't suppose that there will be need for multi-project merge (like I need to change Ramda because I want to do something in ramda-extension/adjunct), which it the biggest advantage of mono-repo.

The transition itself is not much work, Lerna has import feature, which will import repositories into mono-repo with git history (it can be done also with GIT only). The problem can be with choosing right versioning model and managing GitHub issue tracking. Also, there is a question if the Ramda core team would like to read PRs and issues for other libraries and participate in them since they will need to read them.

If the mono-repo will be chosen, then please look also at yarn workspaces. It is not that powerful as Lerna but it can be suitable and there will be no need to add another library/complexity to the project.

**Comment by CrossEye** [comment]
@guillaumearm:
> I never try mono-repository before, but I want to try it with [redux-polyglot][rp] and `react-redux-polyglot` (does not exists yet), I will give some feedbacks at this moment.

I very much look forward to hearing about your experiences.

----------

@aizerin: I don't have enough experience with mono-repos to have a strong opinion.  (In fact, I don't have any.)  Have you worked on mono-repo projects?


  [rp]: https://github.com/Tiqa/redux-polyglot

**Comment by aizerin** [comment]
@CrossEye I have experience with large corporate based mono-repos on Lerna or yarn workspaces. Also with merging multiple repos to mono-repo.
* They are great for multi-project development, you can change multiple packages in one PR.
* You don't have to maintain multiple repos and their dependencies, eslint, etc.
* You will have consistent coding style for every project.
* Consistent version model (most used is to have the same version for all projects, but it means that PR to ramda.github.io will increase version of Ramda itself. Or you can have independent version model, but it brings little bit more maintenance.)
* Every issue or PR in one place. Personally, I consider this as a disadvantage because you need to look at them and find out if you are interested in.
* There can be more advantages/disadvantages of this concept.

Now if I look at the Ramda ecosystem, I can imagine that the core libraries can be merged into one mono-repo (like the ramda, eslint plugin, repl, website, etc). But I'm not sure if it will bring some real advantage of mono-repo.

**Comment by guillaumearm** [comment]
@aizerin : Hum, your probably right, it will bring all PRs and issues together and surely increase complexity.

but IMO, it's the best advantages for us :  **Ramda contributors can give their opinions and submit changes** about these additional libraries.
(We need to add specific labels for each libraries to filter PRs and issues)

In fact, it let @CrossEye and the others decide which directions we should take to make grow up Ramda.

Secondly, we can easily make some strong integrations tests between libraries.

Do you see what I mean ?

Otherwise @aizerin , you seem to know well monorepos, maybe I'm wrong.

IMO, the main puropose of this proposal is not really about technical issues.
It's all about increase ramda community.

**Comment by tommmyy** [comment]
I agree with @aizerin. There must be the architectural reason to use monorepo.

Before you start working on monorepo in Ramda you should see other big projects that used them and how they used them.

**[create-react-app](https://github.com/facebookincubator/create-react-app)**
They grouped packages, that are used together - eslint-config, babel-config, their cli tool `create-react-app` that runs `react-scripts`, etc. There is no 3rd party library that they maintain along with it - no plugin, no extension.

**[babel](https://github.com/babel/babel)**
Probably closest to our case with Ramda.  It includes `core` module, lots and lots of plugins, browser, polyfill, integration to node and helpers. But again - all babel-presets and other 3rd party libs - babel-jest, babel-loader, babel-plugin-ramda 😄  is not kept in their monorepo 
Docs they keep separately.

**More examples**
- [angular](https://github.com/angular/angular)
- [material-ui](https://github.com/mui-org/material-ui) - next branch
- [jest](https://github.com/facebook/jest)
- [poi](https://github.com/egoist/poi)

**Comment by CrossEye** [comment]
I definitely have some reading to do.  But at first glance, there seems to be no compelling reason to switch.

**Comment by paldepind** [comment]
As far as I'm aware monorepos are useful when the same group of people maintains many packages that are closely connected. For Ramda that doesn't seem to be the case so I'm not sure what we'd win by switching to a mono repo.

**Comment by CrossEye** [comment]
I'd entirely forgotten this issue.

I still see little need, but if we want to do it, I think this belongs in part of a larger post-`1.0` discussion about how we manage the project altogther.

I will close for now, but tag it with `Maturation`, to potentially revisit when we get to that.
