### ISSUE TITLE
Converge doesn't work with more then 2 arguments

### ISSUE THREAD

**Issue by MaxSvargal** [ramda/ramda#2444]
For example, propSatisfies.
Let's try to pass three arguments to applied fn:
`converge(propSatisfies, [ equals(1), always('id'), identity ])({ id: 1 })`

And see an error: `t is not a function`
With functions of two arguments all is ok.

**Comment by CrossEye** [comment]
Think of `converge` here as

```js
converge(after, [f, g, h]) ~> x => after(f(x), g(x), h(x))
```

So 

```js
converge(propSatisfies, [equals(1), always('id'), identity])({id: 1}) //=>
(x => propSatisfies(equals(1)(x), always('id')(x), identity(x))({id: 1}) //=>
propSatisfies(false, 'id', {id: 1}) //=>
ERROR // since `false` is not a function
```

You can wrap `equals(1)` in `always` to get what you're looking for, I believe.

**Comment by Bradcomp** [comment]
While @CrossEye is certainly correct, may I suggest that `converge` is unnecessary for this use case? Because the first two parameters don't depend on the input, you can simply apply them to `propSatisfies` directly:  `propSatisfies(equals(1), 'id')({id: 1})`.

Now let's contrive a situation where `converge` would make more sense so we can see how it would work with 3 params. Say the objects didn't just have an ID, but also information on how it was storing the ID, and what comparison function should be used. For ease of use, the function should default to the info provided in the initial question above.

In that case, you could use `converge` to do something like [this](https://goo.gl/jw1S54):
```
const objA = {id: 1};
const obj2 = {
  _id: 1, 
  idProp: '_id'
};
const objIII = {
  _id: 3,
  idProp: '_id',
  idFn: gt(__, 2)
};

const getIdProp = propOr('id', 'idProp');
const getIdFn = propOr(equals(1), 'idFn');

const checker = converge(propSatisfies, [getIdFn, getIdProp, identity]);

map(checker, [objA, obj2, objIII]); //[true, true, true]
```

**Comment by CrossEye** [comment]
> [M]ay I suggest that converge is unnecessary for this use case?

Yes, I did mean to go there.  I was guessing this was an attempt to learn the `converge` function rather than  real production code.  But if that was mistaken, there are clearly easier ways to do this.

**Comment by MaxSvargal** [comment]
@CrossEye it was inattention and mistake, thanks for answer.

**Comment by Izhaki** [comment]
@MaxSvargal Can this issue be closed?
