### ISSUE TITLE
How to get an immutable 'assoc'?

### ISSUE THREAD

**Issue by githubaccount624** [ramda/ramda#2455]
For example, I tried this in the REPL:

https://goo.gl/ybbLz1

Shouldn't modifying the original variable (x) not modify the contents of the newer one (y)?

I see on the wiki that it says it's shallow. If this is the case, is the solution just to deep clone everything first if you need true immutability?

I did a control+f for shallow on the docs page and just got 4 results (assoc, assocPath, dissocPath, and evolve). Are these the only ones that have shallow immutability, or is there perhaps a documented list of functions that are not truly immutable?

**Comment by CrossEye** [comment]
This is very much the intent of `assoc`.  It uses structural sharing to reduce the memory overhead.  That's what was meant by, "All non-primitive properties are copied by reference," in [the docs][as].

Since Ramda is all about value equality, we expect users to prefer this.  But if you want a cloning version, you could write

```js
const cloningAssocPath = curry((prop, val, obj) => assocPath(prop, val, clone(obj)))
```


  [as]: http://ramdajs.com/docs/#assoc

**Comment by githubaccount624** [comment]
Okay, thanks
