### ISSUE TITLE
online repl returns promise on `await`

### ISSUE THREAD

**Issue by stephenhuh** [ramda/ramda#2458]
```

 function writeCaptions(videoId) {
  const result = await fetch(`http://khanacademy.org/api/internal/videos/${videoId}/transcript`);
  /* [{}] */
  const separatedCaptions = await result.json();
  //collapse the captions
  //R.reduce(R.map(R.pick(["text"])),"", separatedCaptions);
  const concat = (a, b, idx) => {
    return a + ' ' +  b;
  }
  return R.replace(/\n/g, ' ',R.reduce(concat, "", R.map((el) => el["text"], separatedCaptions)));
}

async function main(){
    let x = await writeCaptions('br7tS1t2SFE');
    return x;
}
main();

```

this code returns a Promise instead of the value of the fulfilled promise on the online repl found here:
[repl](http://ramdajs.com/repl/?v=0.25.0).

**Comment by CrossEye** [comment]
A few points:

  - The REPL has a "share" button that creates a short URL that includes all your code.  This is much easier for sharing in places like this.

  - Is your initial function supposed to have `async` in the front?  It looks like a syntax error otherwise.

  - Is this actually an issue with the REPL or with Ramda?  Or is it a basic question about async functions.  An async function should always return a Promise.  

  - Is part of the issue that you will run into CORS issues when trying to call Khan Academy from inside Ramda's GitHub-Pages-based site?

**Comment by stephenhuh** [comment]
Hi @CrossEye, thank you for your response, I just found out that this was my own problem with misunderstanding a small point of async/await i.e. that async will implicitly wrap a promise around a returned value. I will close this issue. Thanks for your time!

**Comment by CrossEye** [comment]
OK.  You should note that this is not a small point of async/await.  It's fairly central.  `await` does not turn asynchronous processing into synchronous processing.  It simply lets you *act* as though things are synchronous *inside* `async` functions.  Outside them (including their returns), you're back in an asynchronous world.
