### ISSUE TITLE
Combine omit and dissoc

### ISSUE THREAD

**Issue by edahlseng** [ramda/ramda#2468]
As of right now the only difference I see between omit and dissoc is that omit accepts an array while dissoc only accepts a single string. To simplify the API, these could be combined using `Array.isArray()` internally.

**Comment by davidchambers** [comment]
In the Rich Hickey sense of [simplicity][1], this would actually make the API more complex. ;)


[1]: https://www.infoq.com/presentations/Simple-Made-Easy

**Comment by edahlseng** [comment]
Can you explain your perspective more? From my point of view I don't understand why we would have two functions with quite different names that perform extremely similar actions. To me this makes it harder to remember which function to use when. Having one function that handles whatever input I give it seems much more simple to me.

**Comment by Bradcomp** [comment]
I think conceptually `omit` and `dissoc` are rather different, with `omit` being more similar to `pick` and `filter`. `dissoc` has a parallel in `dissocPath`, which has the same API as `omit` but does something entirely different. Combining `omit` and `dissoc` could call into question which functionality it is going for.

I would be more interested in unifying the `prop/path` type functions (`prop`, `assoc`, `dissoc`, etc.) In doing that though, I would want to keep the array syntax for consistency. That would then make the simple case slightly more painful, and so then the shortcut functions make sense again.

**Comment by edahlseng** [comment]
Admittedly, I didn't look at `dissocPath` before suggesting this. Looking at that now, I can see how combining things could get more confusing. I still wish that dissoc/omit combined to reduce the need to remember the small differences, but now I don't see a good solution that fits into the entire package.

**Comment by davidchambers** [comment]
> Can you explain your perspective more?

Rich Hickey defines complexity as intertwinement, and provides several examples of things which are “complected” (intertwined) alongside alternatives which are not.

The complexity of a function which does two things exceeds the combined complexity of two functions which each do one of those things.

**Comment by edahlseng** [comment]
Hmm, I can appreciate that philosophy, though I'm not quite sure it holds in this case. A function that was a combination of `omit` and `dissoc` wouldn't be doing two things – it would still only be omitting props from an object. The only thing that would change is that there would be less restrictions on the format of the input, which I still feel is more simple.

But I agree that there's not a path forward with this one; I'm just arguing to argue! ;)

**Comment by CrossEye** [comment]
@Bradcomp:
> I would be more interested in unifying the `prop/path` type functions (`prop`, `assoc`, `dissoc`, etc.) In doing that though, I would want to keep the array syntax for consistency. That would then make the simple case slightly more painful, and so then the shortcut functions make sense again.

I keep going through that same thought process.  I use functions like `prop` a lot and feel it should remain as simple as possible... but it's *so* close to `path`.  What I do think we should do everywhere we already haven't is to implement the single-string functions in terms of the array-of-strings ones in order to avoid any divergence of behavior.  `prop('foo')` should *never* behave differently from `path(['foo'])`.  There have been a number of misses on this.

@edahlseng:
> A function that was a combination of `omit` and `dissoc` wouldn't be doing two things – it would still only be omitting props from an object.

One of the key API decisions that has distinguished Ramda from somewhat similar counterparts -- alongside the focus on composition (often through currying) and immutability -- is its preference for simplicity of the type David discussed.  (If you haven't seen the [Rich Hickey video][rh] David mentioned, I highly recommend it.)  When Ramda seems to support multiple types for a parameter, it is simply that Ramda sees them all as representative of some common type.  `map`, for instance, takes an array or an arbitrary functor, but that's because Ramda itself is providing the implementation that makes an array a functor.  Here there is no useful common type between a string and an array of strings.  So to Ramda's eyes, a function that accepts a string is entirely different from one that accepts an array of them.


  [rh]: https://www.infoq.com/presentations/Simple-Made-Easy

**Comment by edahlseng** [comment]
> Here there is no useful common type between a string and an array of strings.

I think that was the explanation I needed.

Thanks @davidchambers and @CrossEye for pushing me towards the Rich Hickey video. I'm excited to check it out this weekend!

**Comment by klass-ivan** [comment]
Can be built using .compose and .map
`const dissocAll = (arr) => R.apply(R.compose, R.map(R.dissoc, arr));`

```
dissocAll  (['a', 'b', 'c'])   ({a: 1, b:2, c:3, d:4})
dissocAll(['a', 'b', 'c'] , {a: 1, b:2, c:3, d:4})
```

**Comment by engordon** [comment]
If `dissoc` would be renamed `omitOne` or similar, IMO it would clarify things. Just throwing that out there.
