### ISSUE TITLE
Reduce - the reducer function does not receives original array.

### ISSUE THREAD

**Issue by denniscual** [ramda/ramda#2469]
I use ramda to all of my project and it is really cool. I just have a question about the **reduce** api of ramda. Why the reducer function does not receives the original array and also the index of the current value like in the native reduce api of Array?

For an instance: 

```js
const reducerFn = (acc, value, i, array) => {
  console.log(i) // this is undefined
  console.log(array) // also undefined
}
```

In reducing an array, sometimes developers also need the index and also the original array for the computation inside the reducer function. Awesome functional utility though!

**Comment by ecancino** [comment]
@denniscual I think is because they want it to comply with [Fantasy Land Spec](https://github.com/fantasyland/fantasy-land#functor)

You can get the id tought, with [addIndex](http://ramdajs.com/docs/#addIndex)
```js
const reduceIndexed = R.addIndex(R.reduce)
reduceIndexed((acc, nxt, id) => R.merge(acc, { nxt, id }), {}, ['f', 'o', 'o', 'b', 'a', 'r']);
```

**Comment by functionalStoic** [comment]
@denniscual Just as an FYI. Ramda Adjunct just released a reduceIndexed function a few days ago that you might find helpful. 
https://github.com/char0n/ramda-adjunct/blob/master/CHANGELOG.md

**Comment by CrossEye** [comment]
>> Why the reducer function does not receives the original array and also the index of the current value like in the native reduce api of Array?

> I think is because they want it to comply with [Fantasy Land Spec][fl].

Well, we absolutely do want to comply with that spec, but it has been this way since long before we considered FantasyLand.  The main reason is API simplicity.  If you want to see a (very long and sometimes heated) discussion about this, see #452.

  [fl]: https://github.com/fantasyland/fantasy-land#functor

**Comment by denniscual** [comment]
Got it! Thanks for clarifying. Learn a lot. :thumbsup:

**Comment by denniscual** [comment]
@ecancino thank for your answer. It is more clear now and I just need to review the Fantasy Land Spec. cool :+1:

**Comment by polytypic** [comment]
@CrossEye I consider the use of `parseInt` and `parseFloat` &mdash; in particular &mdash; to justify this feature rather unconvincing &mdash; and I don't mean to say that I would strongly disagree with the choice made in Ramda.  The problem is that both `parseInt` and `parseFloat` are rather poorly designed functions.  They both go out of their way to try to find something that looks like what they want.  For example, `parseInt('  \n5.9ish')` returns `5`.  Whenever I notice someone using `parseInt` or `parseFloat` in code review, I advice them to use something else (depending on case).

**Comment by CrossEye** [comment]
@polytypic: That's just a standard understandable example.  Regardless of whether uses should ever use `parseInt`, they should never pass it to `Array.prototype.map` because of the way the signatures collide.  I use this example because it's often startling.  Most people expect `parseFloat` and `parseInt` to behave similarly.  When they don't in this case, it helps make my point that `Array.prototype.map` can do things that one wouldn't want in circumstances like this.

Of course there are many deeper reasons for our choice, and both arguments about ADTs like `Functor` and arguments about simplicity are more important.  But this sort of example often makes the point more clearly.
