### ISSUE TITLE
Examples could use const/let instead of var

### ISSUE THREAD

**Issue by andys8** [ramda/ramda#2470]
The documentation uses `var`, e.g. for [cond](http://ramdajs.com/docs/#cond).

```js
var fn = R.cond([
  [R.equals(0),   R.always('water freezes at 0°C')],
  [R.equals(100), R.always('water boils at 100°C')],
  [R.T,           temp => 'nothing special happens at ' + temp + '°C']
]);
```

I'd prefer using `const` and it should be better practice. Is there a cause why `var` is used instead? Or an opinion against?

**Comment by CrossEye** [comment]
No, there is no good reason not to switch that I see.  Since the examples have moved to fat arrows from `function` expressions, it would make sense to switch these too.  The library still mostly works with ES3, a restriction we intend to relax as soon as we hit 1.0.  But the examples should be more modern.

Feel like creating a PR?

**Comment by andys8** [comment]
@CrossEye here you go
