### ISSUE TITLE
R.equals takes a long time for same objects

### ISSUE THREAD

**Issue by masoud-msk** [ramda/ramda#2476]
assume:
```
const a = {}
const eq = (a, b) => a === b ? R.equals(a, b)
```
I ran `eq(a, a)` and `R.equals(a, a)` 100 million each and `eq` took about 17 ms but the latter took around 7800 ms which is 400 times slower. I wonder why?!
It's VERY important because `R.equals` is used in some other functions such as `uniq` which is in the order of n^2.

**Comment by CrossEye** [comment]
Hmm.

Usually when I see questions like this, they're from people who don't quite grasp why value identity is so much more important to FP than is reference equality.

But this is more interesting. 

It would be a change in behavior:

```js
eq(-0, 0) //=> true
R.equals(-0, 0) //=> false
```

But by the order of operations, it wouldn't affect the edge case that concerns me more:

```js
eq(NaN, NaN) //=> true
R.equals(NaN, NaN) //=> true
```

And I don't think that's necessarily a change for the worst.  `-0` is always an odd issue.

What do people think?  @ramda/core?

**Comment by davidchambers** [comment]
`S.equals (-0) (0)` has evaluated to `true` since support for [Ord][1] was added in sanctuary-js/sanctuary-type-classes#46. To be lawful, `-0` needs to be *less than* (strange!) or *equal to* `0`.


[1]: https://github.com/fantasyland/fantasy-land#ord

**Comment by CrossEye** [comment]
Does `NaN` simply not compare?  That is, in native, `NaN < NaN //=> false`, `NaN === NaN //=> false`, and `NaN > NaN //=> false`.  Or do you exclude `NaN` from your Number type?

**Comment by davidchambers** [comment]
`S.equals (NaN) (NaN)` evaluates to `true`.

**Comment by CrossEye** [comment]
Sorry, that was the wrong question.  How about comparing 42 and `NaN`?

**Comment by davidchambers** [comment]
The behaviour is currently incorrect (as I discovered a few days ago while working on sanctuary-js/sanctuary-type-classes#53). I decided, arbitrarily, that `NaN` will be less than any other `Number` value, but I have not yet had a chance to open a pull request for this change.

**Comment by paldepind** [comment]
@davidchambers Why does `-0` have to be equal to `0`? Couldn't `-0` be strictly less than `0`?

Having `R.equals(-0, 0)` be `true` would simplify implementation quite a bit which is nice IMO. But one downside is that it would violate the [principle](https://github.com/ramda/ramda/issues/2046#issuecomment-271864374).

```
if R.equals(x, y), then R.equals(f(x), f(y)) for any f.
```

Because `R.equals(-0, 0) === true` but `R.equals(R.divide(1, -0), R.divide(1, 0)) === false`.

**Comment by davidchambers** [comment]
> Why does `-0` have to be equal to `0`? Couldn't `-0` be strictly less than `0`?

That's right. As I mentioned, there are two possibilities:

> To be lawful, `-0` needs to be *less than* (strange!) or *equal to* `0`.

**Comment by paldepind** [comment]
Ah, yes. I see :smile:

**Comment by ecancino** [comment]
@CrossEye 

> Usually when I see questions like this, they're from people who don't quite grasp why value identity is so much more important to FP than is reference equality.

Could you point me into the path of understanding the full meaning?

Thank you.

**Comment by CrossEye** [comment]
We seem to have veered from the main question here.  @ramda/core: are we interested in updating `R.equals` by adding a short-circuiting reference equality check?  In many places it could certainly improve performance.

**Comment by paldepind** [comment]
@CrossEye Are you ok with it breaking the

```js
if R.equals(x, y), then R.equals(f(x), f(y)) for any f.
```

property?

If we change this we should also change the [internal Set](https://github.com/ramda/ramda/blob/master/source/internal/_Set.js) implementation which would be simplified quite a bit since native `Set`s has the same equality behavior as `===`.

**Comment by CrossEye** [comment]
@paldepind: I'd much rather not, even though we haven't gotten it working everywhere because of key-ordering issues.

How would this proposal change that?  (The only suggestion was to make the first check in `equals` be a reference check.  If the two arguments are `===` then they should be equals according to our current code, right?  

(Or is there some trickiness we can do with getters to update a secondary property so that each access of identical references actually returns different object properties?  Pehaps we could create something like this, but I don't know that we'd care.)

**Comment by paldepind** [comment]
@CrossEye 

> How would this proposal change that?

Did you see the example I posted above? If we do `===` in `R.equals` then `R.equals(0, -0)` is `true` but `R.equals(R.divide(1, -0), R.divide(1, 0))` is not `true`. That is because dividing by `0` gives positive infinity and dividing by `-0` gives negative infinity. It's certainly an edge case but it does violate the principle.

On the other hand, the fact that `-0` is not equal to `0` seems to violate basic knowledge from math. It's really just implementation artifacts from the floating point numbers leaking out.

I think doing `===` in `R.equals` would be nice. It will bring us closer to JS behavior, simplify the implementation and improve the performance of `R.equals` and `_Set`. Improving the performance of the later would in turn improve the performance of `uniq` and `uniqWith`.

If this is something that we want I'd be happy to do a PR.

**Comment by CrossEye** [comment]
> Did you see the example I posted above?

Sorry, just being dense.  I've discussed the same example before, but just wasn't thinking of it here, even though I'm the one who brought up `-0`.  D'oh!

> On the other hand, the fact that `-0` is not equal to `0` seems to violate basic knowledge from math. It's really just implementation artifacts from the floating point numbers leaking out.

I've always had a hard time with this.

Perhaps we need a slightly more sophisticated version that checks for a `-0` before checking primitive equality.  That wouldn't be hard to write, but is somehow less convincing.
