### ISSUE TITLE
K-combinator: There seems to be a mix-up between tap and always

### ISSUE THREAD

**Issue by mendelmichele** [ramda/ramda#2477]
1. The definition of a K-combinator is a -> b -> a
1. R.tap annotation is (a → *) → a → a
1. R.always annotation is a → (* → a), and the documentation says "This function is known as const, constant, or K (for K combinator) ..."

So: 
1. R.tap is close, but it requires a function
1. R.always is not a K-combinator
1. An implementation of K that would remove the need of R.always and R.tap could be:

```
const K = (a, b) => {
  (b instanceof Function) && b(a);
  return a;
};
```

**Comment by davidchambers** [comment]
Here's the implementation of the K combinator in JavaScript:

```javascript
//    K :: a -> b -> a
const K = a => b => a;
```

The second argument should be ignored.

**Comment by mendelmichele** [comment]
Yes, which is what I wrote, but we could make a small extension to K and replace tap and always, especially since always is not a K.

**Comment by davidchambers** [comment]
`tap` is quite different from `K`, though:

```javascript
//    tap :: (a -> b) -> a -> a
const tap = f => x => (f(x), x);
```

**Comment by mendelmichele** [comment]
I'm not saying they are the same, just that tap and always could be combined with an extended version of K. 

R.always and K not the same either, so the documentation for R.always should at least be changed.

Although tap is not exactly a K, it has been mentioned as K, e.g. by Reginald Braithwaite in his book JavaScript Allongé (https://leanpub.com/javascriptallongesix/read).

**Comment by paldepind** [comment]
I think the documentation mentions K because:

```js
R.always("a")("b"); //=> "a"
K("a")("b"); //=> "a"
```

> An implementation of K that would remove the need of `R.always` and `R.tap` could be:

I don't think that would remove the need for `R.always`. If I do `R.always(a)(b)` then `b` should be allowed to be _anything_ and I should get `a` back no matter what `b` is. If `a` happens a function then `a` should _not_ be invoked with `b`. `b` may not even be an argument that `a` accepts.

**Comment by mendelmichele** [comment]
That could be, but it's not what the annotation says. One returns a function and the other returns a value of the same type as the first input value.

**Comment by CrossEye** [comment]
`R.always` can act as the `K`-combinator.  Perhaps we should change the signature of `always`  to 

```hs
always :: a -> (b -> a)
```

But this is one of those cases where the `*` might make more sense, because in `always`, each of those is true for an arbitrary 'x'.

```js
always(x)() === x //=> true
always(x)('foo') === x //=> true
always(x)('many', 'more', 'args', 'here') === x //=> true
```

Especially important is the nullary case, which is different from the `K`-combinator.  Because several of us use it that way, we've resisted replacing this with a more strict `K`.  Any usage of `K` can be replaced by `always`, but the reverse isn't necessarily true.

We can't change the signature to the usual Haskell simplification of `(a -> b -> a)` because in Ramda that implies that you could also call it with two arguments to get your original value back, which you can't:

```
always(x, 'foo') === x //=> false
```

> 3. An implementation of K that would remove the need of R.always and R.tap could be:
> 
> ```
> const K = (a, b) => {
>   (b instanceof Function) && b(a);
>   return a;
> };
> ```

This doesn't comfortably cover either case.  Here's how I would expect to use them (never mind that the functions are nonsense):

```js
const foobar = ifElse(equals('foo'), toUpper, always('BAR'))

const transform = pipe(
  pluck('foo'),
  tap(console.log),
  map('toUpper')
)
```

> Although tap is not exactly a K, it has been mentioned as K, e.g. by Reginald Braithwaite in his book JavaScript Allongé (https://leanpub.com/javascriptallongesix/read).

I have a great deal of respect for Reg, and the first edition of that book was a major inspiration for Ramda.  But `K` and `tap` are too different.  The only reason for  `tap` is to enable side-effects in your programming, and the focus is on those side-effects.  `K` and `always` simply enable you to create a function that has a given fixed value as its result.
