### ISSUE TITLE
Creates a new list with different separator interposed between elements?

### ISSUE THREAD

**Issue by Mutefish0** [ramda/ramda#2485]
I want to transform a plain text into dom nodes of `text` and `br`(for `\n`). But the code below does not work because all the interposed `br` element are the same one. 
```js
var text = 'a\nb\nc'
var children = R.compose(
        R.intersperse(document.createElement('br')),
        R.map(R.bind(document.createTextNode, document)),
        R.split('\n')
    )(text)
```
Then i do this:
```js
var text = 'a\nb\nc'
var children = R.compose(
        R.intersperse(() => document.createElement('br')),
        R.map(R.bind(document.createTextNode, document)),
        R.split('\n')
    )(text)
children = children.map(c => typeof(c) === 'function' ? c() : c)
```

Is there something like `R.produce` can help to do this conveniently ? For example:
```js
var text = 'a\nb\nc'
var children = R.compose(
    R.intersperse(R.produce(() => document.createElement('br'))),  
    R.map(R.bind(document.createTextNode, document)),
    R.split('\n')
)(text)
```

**Comment by CrossEye** [comment]
There is nothing built-in like this.  

You couldn't really write one to work precisely as you suggest, with the thunk generated by `produce` being passed to `intersperse`, because `intersperse` itself wouldn't call it, only insert the thunk between elements.  But you could easily modify [the implementation of `intersperse`][in] to create a version which called your thunk directly.

While this would be more general than what `intersperse` currently does, especially if that function accepeted `prev` and `next` arguments, I don't know that it would be well received as a replacement to --
 or even a sister function of -- `intersperse`.  But at the very least, I would expect it to be a good candidate for the [Cookbook][cb].


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [in]: https://github.com/ramda/ramda/blob/3dfce5ee44d287b8a6c0460cf57fb9d5a2f468dc/source/intersperse.js#L22-L35

**Comment by Mutefish0** [comment]
@CrossEye Thanks for your reply! 

I've seen [the implementation of `intersperse`](https://github.com/ramda/ramda/blob/3dfce5ee44d287b8a6c0460cf57fb9d5a2f468dc/source/intersperse.js#L22-L35) and i think we could implement a sister function let's say `intersperseByThunk`. For example:
```js

/* The original function
function intersperse(separator, list) {
  var out = [];
  var idx = 0;
  var length = list.length;
  while (idx < length) {
    if (idx === length - 1) {
      out.push(list[idx]);
    } else {
      out.push(list[idx], separator);
    }
    idx += 1;
  }
  return out;
}
*/

/* The sister function */
function intersperseByThunk(thunk, list) {
  var out = [];
  var idx = 0;
  var length = list.length;
  while (idx < length) {
    if (idx === length - 1) {
      out.push(list[idx]);
    } else {
      out.push(list[idx], thunk(list[idx], list[idx + 1])); // call thunk
    }
    idx += 1;
  }
  return out;
}

/* Usage */
intersperseByThunk(
  (prev, next) => (prev + next) / 2,
  [1, 2, 3]
)
// [1, 1.5, 2, 2.5, 3]

```

**Comment by CrossEye** [comment]
Yes, that's what I was thinking.  If you want to push for including such a function in the main library, feel free to make your case here.  If not, would you be willing to add it to the [Cookbook][cb]?

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by Mutefish0** [comment]
As described in my first comment:
> I want to transform a plain text into dom nodes of text and br(for \n). But the code below does not work because all the interposed br element are the same one.

I do this:
```js
var text = 'a\nb\nc'
var children = R.compose(
        R.intersperse(() => document.createElement('br')),
        R.map(R.bind(document.createTextNode, document)),
        R.split('\n')
    )(text)
children = children.map(c => typeof(c) === 'function' ? c() : c)
```
Now with `intersperseByThunk ` becomes:
```js
var text = 'a\nb\nc'
var children = R.compose(
        R.intersperseByThunk(() => document.createElement('br')),
        R.map(R.bind(document.createTextNode, document)),
        R.split('\n')
    )(text)
```
That's my case currently met.  But sure, i will be willing to add it to Cookbook if there are no more cases.
