### ISSUE TITLE
Typescript typing issue

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ramda/ramda#2487]
I always get typing error when use transduce function. What is the proper way to write Transduce function in Typescript?

The error message report at R.flip(R.append).

```js
const numbers = [1, 2, 3, 4];
const transducer = R.compose(R.map(R.add(1)), R.take(2));
R.transduce(transducer, R.flip(R.append), [], numbers); //=> [2, 3]
```

ts
--

```ts
Argument of type '(arg1: never[], arg0?: {}) => <T>(list: ReadonlyArray<T>) => T[]' is not assignable to parameter of type '(acc: {}[], val: {}) => ReadonlyArray<{}>'.

Type '<T>(list: ReadonlyArray<T>) => T[]' is not assignable to type 'ReadonlyArray<{}>'.

Property 'concat' is missing in type '<T>(list: ReadonlyArray<T>) => T[]'.

(method) R.Static.flip<{}, U[], <T>(list: ReadonlyArray<T>) => T[]>(fn: (arg0: {}, arg1: U[]) => <T>(list: ReadonlyArray<T>) => T[]): (arg1: U[], arg0?: {}) => <T>(list: ReadonlyArray<T>) => T[] (+1 overload)
```

**Comment by nenadalm** [comment]
Hi. I didn't check into detail, but it looks like you have issues with: https://github.com/Microsoft/TypeScript/issues/9366

**Comment by code-guru** [comment]
I had the same issue, the easiest solution was to disable type checking on ramda by doing the following.
1. remove `@types/ramda`, if you already have it your project.
2. import ramda using requrie i.e. `const R = require('ramda')`

**Comment by jasonkuhrt** [comment]
FWIW I think the state of the art WTR TS + FP is https://github.com/gcanti/fp-ts

**Comment by gaballard** [comment]
@CrossEye - No offense, but that reply sounds like a total cop-out.

> Few on the core team know much about TypeScript typings

Is it that difficult to teach the core team about TypeScript typings? It shouldn't take more than an hour or two to pick up TS, unless they have absolutely no experience whatsoever with typed languages, in which case it might take an afternoon to get everyone up to speed. 

> we don't have any say at all in the typings files that exist for TypeScript or Flow.

Most developers don't have says in the external APIs/tools/libraries/etc. that their software interacts with, but they somehow manage to pull through and create software regardless. 

> But for now, we simply hope that the typings will be kept up-to-date and work for all functions

Which sounds to me like part of your job as the developers of Ramda. Can you imagine the developer of any major piece of software telling their users that they "hope" everything works?

For the record, Ramda's error checking is abysmal to non-existent; I've had functions break in completely unhelpful ways multiple times (with and without TypeScript being involved). As a counterpoint (and I know you must love hearing this name), Lodash has never given me an error, ever, and their TS typings seem to work just fine. Might be something to take a cue from!

**Comment by functionalStoic** [comment]
@gaballard Here's a tip for future @gaballard. If you start a paragraph, issue, or the like with 'No offense', let that trigger in you something along the lines of action instead of the thoughts you were about to give.

It is not the job of the 'developers of Ramda' to write anything outside of Ramda. Can you imagine a user of Ramda telling the developers of Ramda it's their job to do something that doesn't apply to all users of Ramda or that they don't have a strong opinion about? Can you imagine a user of the free to use open source software make this statement and somehow think it isn't offensive?

> For the record, Ramda's error checking is abysmal to non-existent; I've had functions break in completely unhelpful ways multiple times (with and without TypeScript being involved). As a counterpoint (and I know you must love hearing this name), Lodash has never given me an error, ever, and their TS typings seem to work just fine. Might be something to take a cue from!

I'm all for good typings (user of flow) for TS & Flow but wow. Not a productive comment on the issue.

**Comment by nenadalm** [comment]
@gaballard  the fact that you like TypeScript doesn't mean that everybody else likes it and is obliged to be compatible with it. For example I don't like TypeScript because of the limited type system compared to e.g. PureScript. I like Ramda though and many very useful functions in it are just impossible to type in TypeScript.

If you like TypeScript that much - maybe you should be working on those typings for Ramda and improving TypeScript so that it can type more. This library is **JavaScript** library and if you want it to work with your language - you should make the effort.

**Comment by CrossEye** [comment]
@gaballard:

>> Few on the core team know much about TypeScript typings

> Is it that difficult to teach the core team about TypeScript typings?

If they want to learn them, that's fine.  But saying it's that easy sounds disrespectful of those who've tried to create typings for Ramda and have only been partially successful.  As I understand it, it's not due to their lack of skills but due to the limited capabilities of the TypeScript system.

But a further point is that TypeScript is not the only environment out there.  TypeScript is popular at the moment, but a few years ago it would have been CoffeeScript we were debating.  Should we also maintain the equivalent for Flow?  Should we ensure that all Ramda functions can be used with Elm, with PureScript, with BuckleScript, with ClojureScript?  Should we ensure that we follow all the conventions of React, Vue, and Angular?  Should we try to be a drop-in replacement for lodash/underscore?  To me, all of these answers are no.   

Ramda is a library, designed for the limited purpose of bringing some of the common capabilities of functional languages into JavaScript in a convenient manner.  It sacrifices some FP purity to the norms of Javascript and some JS familiarity to the power of FP standards.  Perhaps it would do well with better error-checking.  Perhaps it would do well to try harder at integration with such type-system add-ons.  But that requires people interested in writing and maintaining such. 


>> we don't have any say at all in the typings files that exist for TypeScript or Flow.

> Most developers don't have says in the external APIs/tools/libraries/etc. that their software interacts with, but they somehow manage to pull through and create software regardless.

I think you miss the point.  Ramda is a Javascript library, created by a [great number of contributors][co].  TypeScript is a compile-to-js language, that primarily adds stronger typing to JS.  To get the TS compiler working with other JS tools, the TypeScript community publishes typing files for them.  Sometimes the Javascript library authors are involved; sometimes they're not.  In this case, the Ramda core team has not been involved.  I personally have not spent any real time trying to understand these typing files, and when those that have spent time tell me that TypeScript is not yet capable of expressing Ramda's entire API, I assume they know what they're talking about.  Such inability will not affect how Ramda decides on its API.

I hope to fix up our somewhat over-complicated signatures, and I hope that one day someone could used them to auto-generate such typing files (and the equivalent for Flow, or whatever else is the flavor of the month), but this is a very low priority for me.  But I doubt that someone will be me.  While I admired some of what TS does, and admire Flow even more, I don't find find them compelling enough to give much thought.

I've asked before if there are contributors who would like to take on the task of maintaining the typing files as part of Ramda itself.  So far there have been no takers.  If you feel strongly about this, would you like that role?  We'd be happy to have someone on board with a passion for TypeScript and the ability to write these files.


>> But for now, we simply hope that the typings will be kept up-to-date and work for all functions

> Which sounds to me like part of your job as the developers of Ramda. Can you imagine the developer of any major piece of software telling their users that they "hope" everything works?

Yes I can easily imagine this.  The developers here do there best to ensure that it works as expected.  When users start to do unusual things with it -- embed it in a different language, for instance -- then we offer them our best wishes, and will to some limited extent help to find the problem.  But we don't try to take on that integration layer ourselves, not unless we find it compelling.

Ramda was a pet project of @buzzdecafe and me that took off.  All developers here are volunteers.  If you would like to create a PR to fix this specific problem, or even better, would like to volunteer to make this a part of Ramda, we'd love to have your help.



  [co]: https://github.com/ramda/ramda/graphs/contributors

**Comment by foxbunny** [comment]
> It shouldn't take more than an hour or two to pick up TS, unless they have absolutely no experience whatsoever with typed languages, in which case it might take an afternoon to get everyone up to speed.

A few hours of TypeScript gets you nowhere near what it takes to make Ramda work as it does in plain JavaScript. You should take a look at the existing typings before you say things like that. Those are not tutorial-level stuff you are probably imagining. It's closer to magic, which is what I believe takes to make it work.

**Comment by dashuser33** [comment]
This does not address the issue at hand but I want to add another voice that fp-ts is in fact an awesome tool to so FP in typescript. I love ramda for JS projects, but for TS, fp-ts is what I use.

**Comment by ivan-kleshnin** [comment]
@dashuser33 **fp-ts** seems to provide algebraic type classes for TS so it's comparable to FolkTale / Sanctuary rather than Ramda. I don't see any functional helper like `map / reduce ` etc  being exported or implemented. Or am I wrong?

**Comment by CrossEye** [comment]
@ivan-kleshnin: I think you are slightly wrong, both about fp-ts and about Sanctuary.

fp-ts is all about algebraic types, but it also introduces functions on these more in the Haskell style than in the Ramda style.  We can look for instance at `Foldable2v`.  (I have no idea what that '2v` is for unless it's simply a way to do internal versioning during a deprecation period on `Foldable`!)  This is what your type, `F` has to implement in order to be a `Foldable2v<F>`:

```ts
interface Foldable2v<F> extends Foldable<F> {
  readonly foldMap: <M>(M: Monoid<M>) => <A>(fa: HKT<F, A>, f: (a: A) => M) => M
  readonly foldr: <A, B>(fa: HKT<F, A>, b: B, f: (a: A, b: B) => B) => B
}
```

But on implementing that type you get a number of functions available to you: `findFirst`, `fold`, `foldM`, `getFoldableComposition`, `intercalcate`, `max`, `member`, `min`, `oneOf`, `product`, `sequence_`, `sum`, `toArray`, and `traverse_`, all under the `Foldable2v` namespace.  Ramda uses a global namespace, and has many fewer functions overall, but many of them have logical types associated with them (`map` is for a logical `Functor`, and Ramda supplies implementations for `Array`, `Object`, and `Function`, dispatching for user Functors.  

This is not all that much like Folktale which is mostly about concrete classes that tend to match some of the types specified by FantasyLand.

Sanctuary, on the other hand, is much closer to Ramda.  It was originally designed to be a stricter version of what Ramda offers, and while it's grown beyond that, the few types it offers are used in support of that goal.  Ramda's `head`, for instance, could be problematic, since while `R.head([1, 2, 3]) //=> 1`, we also have `R.head([]) //=> undefined`.  Sanctuary offers the `Maybe` type so that `S.head([1, 2, 3]) => S.Just(1)` and `S.head([]) //=> Nothing()`, which lets you continue processing without error-checking.  The few types it exposes are mostly for this same sort of cleanup.  Again, this is fairly far from Folktale, and is fairly close to Ramda.

**Comment by ivan-kleshnin** [comment]
Thank you for the clarification Scott! TypeScript doesn't look like a human language to me. I can understand what's going on there only because I learned these types from other languages... My only hope is that someone will make a new typing syntax (e.g. with macros) on top of TypeScript 😢

**Comment by JasonZough** [comment]
this may help:

declare module "ramda" {
  export function F (...rest: any[]): any;
  export function T (...rest: any[]): any;
  export function __ (...rest: any[]): any;
  export function add (...rest: any[]): any;
  export function addIndex (...rest: any[]): any;
  export function adjust (...rest: any[]): any;
  export function all (...rest: any[]): any;
  export function allPass (...rest: any[]): any;
  export function always (...rest: any[]): any;
  export function and (...rest: any[]): any;
  export function any (...rest: any[]): any;
  export function anyPass (...rest: any[]): any;
  export function ap (...rest: any[]): any;
  export function aperture (...rest: any[]): any;
  export function append (...rest: any[]): any;
  export function apply (...rest: any[]): any;
  export function applySpec (...rest: any[]): any;
  export function applyTo (...rest: any[]): any;
  export function ascend (...rest: any[]): any;
  export function assoc (...rest: any[]): any;
  export function assocPath (...rest: any[]): any;
  export function binary (...rest: any[]): any;
  export function bind (...rest: any[]): any;
  export function both (...rest: any[]): any;
  export function call (...rest: any[]): any;
  export function chain (...rest: any[]): any;
  export function clamp (...rest: any[]): any;
  export function clone (...rest: any[]): any;
  export function comparator (...rest: any[]): any;
  export function complement (...rest: any[]): any;
  export function compose (...rest: any[]): any;
  export function composeK (...rest: any[]): any;
  export function composeP (...rest: any[]): any;
  export function composeWith (...rest: any[]): any;
  export function concat (...rest: any[]): any;
  export function cond (...rest: any[]): any;
  export function construct (...rest: any[]): any;
  export function constructN (...rest: any[]): any;
  export function contains (...rest: any[]): any;
  export function converge (...rest: any[]): any;
  export function countBy (...rest: any[]): any;
  export function curry (...rest: any[]): any;
  export function curryN (...rest: any[]): any;
  export function dec (...rest: any[]): any;
  export function defaultTo (...rest: any[]): any;
  export function descend (...rest: any[]): any;
  export function difference (...rest: any[]): any;
  export function differenceWith (...rest: any[]): any;
  export function dissoc (...rest: any[]): any;
  export function dissocPath (...rest: any[]): any;
  export function divide (...rest: any[]): any;
  export function drop (...rest: any[]): any;
  export function dropLast (...rest: any[]): any;
  export function dropLastWhile (...rest: any[]): any;
  export function dropRepeats (...rest: any[]): any;
  export function dropRepeatsWith (...rest: any[]): any;
  export function dropWhile (...rest: any[]): any;
  export function either (...rest: any[]): any;
  export function empty (...rest: any[]): any;
  export function endsWith (...rest: any[]): any;
  export function eqBy (...rest: any[]): any;
  export function eqProps (...rest: any[]): any;
  export function equals (...rest: any[]): any;
  export function evolve (...rest: any[]): any;
  export function filter (...rest: any[]): any;
  export function find (...rest: any[]): any;
  export function findIndex (...rest: any[]): any;
  export function findLast (...rest: any[]): any;
  export function findLastIndex (...rest: any[]): any;
  export function flatten (...rest: any[]): any;
  export function flip (...rest: any[]): any;
  export function forEach (...rest: any[]): any;
  export function forEachObjIndexed (...rest: any[]): any;
  export function fromPairs (...rest: any[]): any;
  export function groupBy (...rest: any[]): any;
  export function groupWith (...rest: any[]): any;
  export function gt (...rest: any[]): any;
  export function gte (...rest: any[]): any;
  export function has (...rest: any[]): any;
  export function hasIn (...rest: any[]): any;
  export function hasPath (...rest: any[]): any;
  export function head (...rest: any[]): any;
  export function identical (...rest: any[]): any;
  export function identity (...rest: any[]): any;
  export function ifElse (...rest: any[]): any;
  export function inc (...rest: any[]): any;
  export function includes (...rest: any[]): any;
  export function indexBy (...rest: any[]): any;
  export function indexOf (...rest: any[]): any;
  export function init (...rest: any[]): any;
  export function innerJoin (...rest: any[]): any;
  export function insert (...rest: any[]): any;
  export function insertAll (...rest: any[]): any;
  export function intersection (...rest: any[]): any;
  export function intersperse (...rest: any[]): any;
  export function into (...rest: any[]): any;
  export function invert (...rest: any[]): any;
  export function invertObj (...rest: any[]): any;
  export function invoker (...rest: any[]): any;
  export function is (...rest: any[]): any;
  export function isEmpty (...rest: any[]): any;
  export function isNil (...rest: any[]): any;
  export function join (...rest: any[]): any;
  export function juxt (...rest: any[]): any;
  export function keys (...rest: any[]): any;
  export function keysIn (...rest: any[]): any;
  export function last (...rest: any[]): any;
  export function lastIndexOf (...rest: any[]): any;
  export function length (...rest: any[]): any;
  export function lens (...rest: any[]): any;
  export function lensIndex (...rest: any[]): any;
  export function lensPath (...rest: any[]): any;
  export function lensProp (...rest: any[]): any;
  export function lift (...rest: any[]): any;
  export function liftN (...rest: any[]): any;
  export function lt (...rest: any[]): any;
  export function lte (...rest: any[]): any;
  export function map (...rest: any[]): any;
  export function mapAccum (...rest: any[]): any;
  export function mapAccumRight (...rest: any[]): any;
  export function mapObjIndexed (...rest: any[]): any;
  export function match (...rest: any[]): any;
  export function mathMod (...rest: any[]): any;
  export function max (...rest: any[]): any;
  export function maxBy (...rest: any[]): any;
  export function mean (...rest: any[]): any;
  export function median (...rest: any[]): any;
  export function memoizeWith (...rest: any[]): any;
  export function merge (...rest: any[]): any;
  export function mergeAll (...rest: any[]): any;
  export function mergeDeepLeft (...rest: any[]): any;
  export function mergeDeepRight (...rest: any[]): any;
  export function mergeDeepWith (...rest: any[]): any;
  export function mergeDeepWithKey (...rest: any[]): any;
  export function mergeLeft (...rest: any[]): any;
  export function mergeRight (...rest: any[]): any;
  export function mergeWith (...rest: any[]): any;
  export function mergeWithKey (...rest: any[]): any;
  export function min (...rest: any[]): any;
  export function minBy (...rest: any[]): any;
  export function modulo (...rest: any[]): any;
  export function move (...rest: any[]): any;
  export function multiply (...rest: any[]): any;
  export function nAry (...rest: any[]): any;
  export function negate (...rest: any[]): any;
  export function none (...rest: any[]): any;
  export function not (...rest: any[]): any;
  export function nth (...rest: any[]): any;
  export function nthArg (...rest: any[]): any;
  export function o (...rest: any[]): any;
  export function objOf (...rest: any[]): any;
  export function of (...rest: any[]): any;
  export function omit (...rest: any[]): any;
  export function once (...rest: any[]): any;
  export function or (...rest: any[]): any;
  export function otherwise (...rest: any[]): any;
  export function over (...rest: any[]): any;
  export function pair (...rest: any[]): any;
  export function partial (...rest: any[]): any;
  export function partialRight (...rest: any[]): any;
  export function partition (...rest: any[]): any;
  export function path (...rest: any[]): any;
  export function pathEq (...rest: any[]): any;
  export function pathOr (...rest: any[]): any;
  export function pathSatisfies (...rest: any[]): any;
  export function pick (...rest: any[]): any;
  export function pickAll (...rest: any[]): any;
  export function pickBy (...rest: any[]): any;
  export function pipe (...rest: any[]): any;
  export function pipeK (...rest: any[]): any;
  export function pipeP (...rest: any[]): any;
  export function pipeWith (...rest: any[]): any;
  export function pluck (...rest: any[]): any;
  export function prepend (...rest: any[]): any;
  export function product (...rest: any[]): any;
  export function project (...rest: any[]): any;
  export function prop (...rest: any[]): any;
  export function propEq (...rest: any[]): any;
  export function propIs (...rest: any[]): any;
  export function propOr (...rest: any[]): any;
  export function propSatisfies (...rest: any[]): any;
  export function props (...rest: any[]): any;
  export function range (...rest: any[]): any;
  export function reduce (...rest: any[]): any;
  export function reduceBy (...rest: any[]): any;
  export function reduceRight (...rest: any[]): any;
  export function reduceWhile (...rest: any[]): any;
  export function reduced (...rest: any[]): any;
  export function reject (...rest: any[]): any;
  export function remove (...rest: any[]): any;
  export function repeat (...rest: any[]): any;
  export function replace (...rest: any[]): any;
  export function reverse (...rest: any[]): any;
  export function scan (...rest: any[]): any;
  export function sequence (...rest: any[]): any;
  export function set (...rest: any[]): any;
  export function slice (...rest: any[]): any;
  export function sort (...rest: any[]): any;
  export function sortBy (...rest: any[]): any;
  export function sortWith (...rest: any[]): any;
  export function split (...rest: any[]): any;
  export function splitAt (...rest: any[]): any;
  export function splitEvery (...rest: any[]): any;
  export function splitWhen (...rest: any[]): any;
  export function startsWith (...rest: any[]): any;
  export function subtract (...rest: any[]): any;
  export function sum (...rest: any[]): any;
  export function symmetricDifference (...rest: any[]): any;
  export {
    default as symmetricDifferenceWith
  (...rest: any[]): any;
  export function tail (...rest: any[]): any;
  export function take (...rest: any[]): any;
  export function takeLast (...rest: any[]): any;
  export function takeLastWhile (...rest: any[]): any;
  export function takeWhile (...rest: any[]): any;
  export function tap (...rest: any[]): any;
  export function test (...rest: any[]): any;
  export function then (...rest: any[]): any;
  export function times (...rest: any[]): any;
  export function toLower (...rest: any[]): any;
  export function toPairs (...rest: any[]): any;
  export function toPairsIn (...rest: any[]): any;
  export function toString (...rest: any[]): any;
  export function toUpper (...rest: any[]): any;
  export function transduce (...rest: any[]): any;
  export function transpose (...rest: any[]): any;
  export function traverse (...rest: any[]): any;
  export function trim (...rest: any[]): any;
  export function tryCatch (...rest: any[]): any;
  export function type (...rest: any[]): any;
  export function unapply (...rest: any[]): any;
  export function unary (...rest: any[]): any;
  export function uncurryN (...rest: any[]): any;
  export function unfold (...rest: any[]): any;
  export function union (...rest: any[]): any;
  export function unionWith (...rest: any[]): any;
  export function uniq (...rest: any[]): any;
  export function uniqBy (...rest: any[]): any;
  export function uniqWith (...rest: any[]): any;
  export function unless (...rest: any[]): any;
  export function unnest (...rest: any[]): any;
  export function until (...rest: any[]): any;
  export function update (...rest: any[]): any;
  export function useWith (...rest: any[]): any;
  export function values (...rest: any[]): any;
  export function valuesIn (...rest: any[]): any;
  export function view (...rest: any[]): any;
  export function when (...rest: any[]): any;
  export function where (...rest: any[]): any;
  export function whereEq (...rest: any[]): any;
  export function without (...rest: any[]): any;
  export function xprod (...rest: any[]): any;
  export function zip (...rest: any[]): any;
  export function zipObj (...rest: any[]): any;
  export function zipWith (...rest: any[]): any;
  export function thunkify (...rest: any[]): any;
}

**Comment by SimonAM** [comment]
Regarding the discussion on fp-ts: 
It's actually [fp-ts-std](https://samhh.github.io/fp-ts-std/ramda) that offers utility functions similarly to ramda.

**Comment by philihp** [comment]
Gosh, I'm surprised no one has gone out of the way to answer this yet, it was quite a fun puzzle to figure out, and I love Ramda for the same idiosyncratic reasons that I love Typescript: they both really enable me to annoying code that we would never have the exciting opportunity to write professionally because it's so dense in meaning that anyone reading it has to think about it for 30 minutes before fully internalizing what it does. Like, we all love it when we come across this and have the time to really get into it and have fun with it, but never in my 20 years of working in this industry (that wasn't a flex, no one cares that I can write Java 1.4.2, god forbid, just saying it is a long time) have I ever had a PM who was like "sure, go have fun with that code for a while, we don't have a sisyphean list of scrum tasks for you to do". So here's my attempt at trying to figure out what even is a transducer, given that I will (openly) admit to not knowing what I'm actually doing. I'm far sooner going to do that, than to pretend I just have an internal database of queries that I send to StackOverflow to recall the knowledge I need.

And thus, I'll admit that I was unable to admit I didn't know what I was doing, so I keep coming back to this page, and shedding a small tear whenever I see a lot of words but not actually an answer to the question, just a bunch of gently caressing nudges toward what might be a solution, but as you pause on any entry with a long line of emoji reactions on it, only to feel the mounting frustration at the inevitable conclusion that the answer to how to do this is not actually on the page, and thus a you finally understand meloncholy and the infinite sadness. So dear reader, maybe this, a solution for the OP, will maybe liberate us from our own internal infinite loop.

```typescript
const numbers = [1, 2, 3, 4];
// const transducer = R.compose(R.map(R.add(1)), R.take(2));
const transducer = R.compose(R.map(R.add(1)), R.take<number>(2))

// R.transduce(transducer, R.flip(R.append), [], numbers); //=> [2, 3]
R.transduce(R.transducer, R.flip<number, number[], number[]>(R.append), [], numbers) //= > [2, 3]
```

You don't really have to give the `R.take` a type, but I think it's nice because then when I mouseover `transducer` in my IDE, typescript says it has the type `(xs: readonly number[]) => number[]` which looks a lot more reasonable than `(xs: readonly unknown[]) => number[]`, which is like bro don't tell me it's unknown, it'll be known later I promise, just chill Typescript, chill, fine okay here's your type now will you just sit still?

The way to make this work is to give explicit types to the templates of the functions, which ultimately is `R.flip` swapping the params that it would give to `R.append`, so that tells append what param types it is gonna have, which in this case is a number and the list it's gonna be appended to, and what what the result would be.

**Comment by meihuanyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
