### ISSUE TITLE
Why using R.curry produces different result in this case?

### ISSUE THREAD

**Issue by brunoscopelliti** [ramda/ramda#2488]
Hi guys.

I'm at my first experiment with ramda, and I was surprised by a particular behaviour.
I report here a test case with the hope that someone could explain to me what's going on.

```js
const sumGreaterThan =
  (x) => R.compose(R.gt(R.__, x), R.sum);

const collection = [{
  handler: sumGreaterThan(100),
  value: "Over 100"
}, {
  handler: sumGreaterThan(50),
  value: "Over half"
}, {
  handler: sumGreaterThan(25),
  value: "..."
}];

/*
 I want to find the element in `collection`
 for which the `handler` returns true for the current input
*/

const getFinder =
  (input) =>
    (entry) => entry.handler(input);

const searchIn = 
  (collection) => R.compose(R.find(R.__, collection), getFinder);

const find = searchIn(collection);

// This is a simplification of my real use case
const conditional = R.ifElse(R.always(true), find, find);

conditional([30, 21]) // ~ "Over half"
```

The above snippet works fine; but when I replace `getFinder` with a curried function it stops working. 

```js
const getFinderCurried = R.curry(
  (input, entry) => entry.handler(input)
);
```

It seems to me that the function that `getFinderCurried` returns doesn't get passed as predicate
to `R.find(R.__, ..)`... and that `getFinderCurried` still waits its second argument in order
to be executed.

I was surprised by the fact that `R.curry(function(a, b){})` is not equivalent to `function(a){ return function(b){}}`.

I just wondered if this is the intended behaviour, and what's the rationale for this.

**Comment by Zip753** [comment]
Not really related to the `R.curry` issue, but I just wanted to point out that there's [`R.cond`](http://ramdajs.com/docs/#cond) function which does something very similar to your `searchIn` function.

**Comment by CrossEye** [comment]
@brunoscopelliti: Did this get answered?  I swear I had a response to this.  Was it in another forum?

**Comment by brunoscopelliti** [comment]
@Zip753 Thanks for your response.

@CrossEye No, I'm still curious about this behaviour and I only asked this question here :)

**Comment by CrossEye** [comment]
@brunoscopelliti: Sorry for the very slow response.  I thought I'd be doing some Ramda work this weekend, but family life intervened.  For some reason, I also originally thought I'd answered this question.  I did answer a similar one around the time you posted.  I can't remember where, though.

The reason for your issue is a combination of how `curry` and `compose` work.

There is perhaps too much magic in Ramda.  `curry` is not just "turn a function of multiple arguments into one that takes the arguments one at a time, returning functions in the meantime."  Instead if 

    f = (a, b, c, d) => a + b + c + d;
    g = curry(f);

Then all of these are equivalent:

    g(2, 3, 5, 7)
    g(2, 3, 5)(7);
    g(2, 3)(5, 7);
    g(2, 3)(5)(7);
    g(2)(3, 5, 7);
    g(2)(3, 5)(7);
    g(2)(3)(5, 7);
    g(2)(3)(5)(7);

But `g` reports its arity as 4.  That seems to be the only logical value, as it's still expecting four arguments, even though it does something useful with one, two, or three parameters.

This is often convenient, and it's usually what you want to pass into a `compose` or `pipe` invocation.  But there are times like this when that doesn't work so well.  This is because `compose` and `pipe` use the first function to run (rightmost/last in `compose`, leftmost/first in `pipe`) to give the arity of the generated function.

We tried changing this before, and the issues we encountered were nicely summed up in [@davidchambers'  story][ab].

Here it's that `searchIn` returns a composition that starts with `getFinder`, so Ramda reports the returned function as having a single argument.  When you switch to `getFinderCurried`, Ramda says that the result of `searchIn` has two arguments.  And therefore `conditional`, which uses the largest arity of the functions passed to it, also has two arguments.

If `getFinderCurried` is something you need elsewhere with the Ramda currying API, then you could fix this with

    const searchIn = 
      (collection) => R.compose(R.find(R.__, collection), unary(getFinder));

If not, then I would just use the manually curried function here.

  [ab]: https://github.com/ramda/ramda/issues/1318#issuecomment-139103766

**Comment by brunoscopelliti** [comment]
@CrossEye Thanks for the clear explanation.
