### ISSUE TITLE
reduce is accumulating on subsequent calls

### ISSUE THREAD

**Issue by joeegan** [ramda/ramda#2491]
This behaviour has caught me out a couple of times, is this expected?

```javascript
const data = [
  ['a', ['foo', 'bar']], 
  ['b', ['baz', 'quux']]
]

const process = reduce((acc, [key, values]) => {
  acc.push(values)
  return acc;
}, [])

process(data)
// [["foo", "bar"], ["baz", "quux"]]
process(data)
// [["foo", "bar"], ["baz", "quux"], ["foo", "bar"], ["baz", "quux"]]

const processOk = data => data.reduce((acc, [key, values]) => {
  acc.push(values)
  return acc;
}, [])

processOk(data)
// [["foo", "bar"], ["baz", "quux"]]
processOk(data)
// [["foo", "bar"], ["baz", "quux"]]
```

**Comment by davidchambers** [comment]
This is expected behaviour. Your function mutates the array shared by every application of `process`. You either need to remove the mutation or ensure that a fresh array is created each time (as you did with `processOk`).

**Comment by CrossEye** [comment]
The reason is simple enough: you're returning and reusing your accumulator in `process`.  Ramda is a fairly low-level library, so it allows you to do such things.  There are times when it might be reasonable to do so, although they are fairly uncommon.  A slightly higher-level library might insist that this is not allowed and preemptively clone your accumulator before passing it to you.  That of course would preclude those rare cases mentioned, but might be less surprising.  It also would be *much* less performant.

This doesn't happen in `processOk` because that call involves a new invocation of the outer function (`data => ...`) which will send a new version of `[]` to `reduce`.  This would work fine even with the Ramda `reduce` and that additional invocation:

```js
const processOk = data => reduce((acc, [key, values]) => {
  acc.push(values)
  return acc;
}, [], data)
```

But, the preferred way to do this in Ramda is to not mutate and return the same accumulator but to return a new object:  

```js
const process = reduce((acc, [key, values]) => append(values, acc), [])
```

[`R.append`][ap] does not modify your original list but instead returns a new one with the new value after all those in your original.  

----------

Does this make sense?

  [ap]: http://ramdajs.com/docs/#append

**Comment by davidchambers** [comment]
Yes, but my answer was not as thorough.

**Comment by CrossEye** [comment]
We all know that I'm long-winded!

**Comment by polytypic** [comment]
BTW, I recently added a [`forEachWith`](https://github.com/calmm-js/partial.lenses/#L-forEachWith) operation to Partial Lenses, because I noticed several cases where one wanted to build an object or map from a traversal.  Many of the uses were either cumbersome

* Allocating the accumulator outside the operation.

or dangerous

* Imperatively updating the accumulator inside a fold &mdash; in which cases one has to make sure that a fresh accumulator is always allocated.

or inefficient

*  Functionally updating an object on each iteration leads to [quadratic time complexity](https://accidentallyquadratic.tumblr.com/).
* Allocating a `[key, value]` pair per element slows down the accumulation significantly due to requiring an additional allocation per element.

So, for those cases, I added [`forEachWith`](https://github.com/calmm-js/partial.lenses/#L-forEachWith), which requires you to give a thunk to allocate the accumulator and then returns the accumulator after finishing the traversal.

**Comment by CrossEye** [comment]
@polytypic: While I haven't been particularly concerned about the cumbersome or dangerous aspects here, I've spent a fair bit of time wondering about the inefficient ones.

Many uses of `R.reduce` could end up with quadratic complexity.  That simply seems the nature of working this sort of generic code in JS without equivalent data structures.  Obviously if you're accumulating to something simple (my perennial example of `sum = reduce(add, 0)`, then you're working in `O(n)`, but if you are accumulating an array or an object, you would be running into quadratic time.

I'm curious how you avoid that.  I've only glanced into the Partial Lenses code, and haven't followed everything yet.  I'll probably look at it more carefully over the weekend.  But if you have a quick gloss, I'd appreciate it.  (I understand what you're doing with the `thunk`; that helps with the other issues, but doesn't address the possibly quadratic behavior.)

But my main thought about this is simply: *is it an issue?*  I haven't had any noticeable performance problems with `reduce` nor do I recall any issues here related to it.  Maybe this is because most of the time when I'm folding into a more complex data structure, I'm not starting with a large collection.  Have you had actual performance problems with such an approach?  

And for Ramda, if there are performance issues, would it be better to leave the solutions in user land, for instance a `map` followed if necessary by a `filter`, and finally a `fromPairs` for something that folds a list into an object?  This would allow the user to have an `O(n)` implementation for this case without any new version of `reduce`.

**Comment by twelve17** [comment]
If I may make a small suggestion: can future ramda functions that operate differently than the, I suppose I could call "classic", functions they are inspired from have a different name? I _could_ see the use of a `reduce` with an accumulator that retains values across function calls, but after having worked in  several languages over the years that have a `reduce` implementation, and which all seem to work the same, running into these variants is an unpleasant experience for me coming into ramda.  I ran into the same issue with `map`, where I accidentally passed an object to it, and didn't realize until later, that this triggers an alternate mode of `map` that I had never seen in various other languages.   I know the documentation outlines the differences, but human nature brings the bias of past experience with these functions and so it seems suboptimal to re-use their names.

All this being said, maybe there aren't any future functions left that would fall into this category, after `map` and `reduce`. :)

**Comment by CrossEye** [comment]
@twelve17: I'm not sure what you think are the "classic" functions.  We take more inspiration from functional languages than from, say, the `Array.prototype` methods, but we've usually named our functions mostly to make them familiar to JS developers.  Thus `map`, `reduce`, `filter`, `find`, and many more are *intentionally* meant to invoke the similarly-named functions from the language.  (That [Fantasy-Land][fl] follow the same idea makes it very easy to integrate with its implementations.)

But `map` is something that operates [on many types][fu], and we want that behavior.  It operates much like `Array.prototype.map`, with some important differences; it's the function I would expect to reach for when I want to apply a function to the value or values in a data structure, returning a new object with the same shape but transformed values.

What is the common `reduce` behavior that you're expecting?  I couldn't tell from your message if you want something like the current `Array.prototype.reduce` behavior, one that might reuse your accumulator if you're not careful (the current Ramda behavior) or one that cloned the initial accumulator before passing it along?

What would your want from `map`?  Something that operated on arbitrary [Functors][fu], similar to Haskell's `fmap`, or a specific function for each separate type?


  [fl]: https://github.com/fantasyland/fantasy-land/
  [fu]: https://github.com/fantasyland/fantasy-land/#functor

**Comment by twelve17** [comment]
>  I'm not sure what you think are the "classic" functions.

@CrossEye This was a poor and ignorant label on my part, somewhat from my experience with Ruby and Java, not functional languages that would inspire the functions here.  Thinking about it more, I think my confusion did come from having used "map" and "reduce" in Javascript, the former working only with arrays, and the latter's accumulator to not be re-used.

The ramda documentation does point out how its implementation of `map` differs from `Array.prototype.map`:

> Ramda provides suitable map implementations for Array and Object, so this function may be applied to [1, 2, 3] or {x: 1, y: 2, z: 3}.

However, as far as I saw, ramda's `reduce` does not.  

>  the current `Array.prototype.reduce` behavior, one that might reuse your accumulator if you're not careful 

Can you elaborate on the above? I have not experienced accumulator re-use with `Array.prototype.reduce`.

**Comment by CrossEye** [comment]
@twelve17 :

>> the current `Array.prototype.reduce` behavior, one that might reuse your accumulator if you're not careful

> Can you elaborate on the above? I have not experienced accumulator re-use with `Array.prototype.reduce`.

```js
const myReduce = (fn, init) => (xs) => xs.reduce(fn, init)
const myFn = myReduce(fn, initValue)
```

Now if `fn` modifies its accumulator parameter, then each invocation of `myFn` will start with the accumulator returned by the prior one, and not a fresh `initValue`.

It's easy to not see this, as we don't tend to use the `Array` method the same way we do the Ramda equivalent.  But we can do so, and it then has that same issue.  Of course if you don't modify the the accumulator, then it won't happen in either case.

**Comment by twelve17** [comment]
> ```js
> const myReduce = (fn, init) => (xs) => xs.reduce(fn, init)
> const myFn = myReduce(fn, initValue)
> ```
> 
> Now if `fn` modifies its accumulator parameter, then each invocation of `myFn` will start with the accumulator returned by the prior one, and not a fresh `initValue`.

I realize this is a contrived example, but his is not "the current Array.prototype.reduce behavior" reusing the accumulator, but a result of having explicitly wrapping it in a function to do so.  `Array.prototype.reduce` itself is not doing something that results in such behavior.  

Sure, if you write your own version of `reduce` as you have, indeed you can make the same mistake.  I suppose I didn't envision that someone would come to Ramda by way of having written their own functional wrappers to `Array.prototype` equivalents--I was seeing it from the point of view of someone used to `Array.prototype.reduce`, with signature `reduce(fn, initialValue)` which behaves one way, to Ramda's reduce, with a seemingly equivalent signature `reduce(fn, initialValue)`, but with different results.  Ramda's `map`'s documentation points out this difference, which his helpful-- `reduce` could use similar phrasing.

**Comment by CrossEye** [comment]
If you have suggested changes to the phrasing, would you mind opening a PR with the change?

----------

As to `Array.prototype.reduce`, the point is that neither Ramda nor `Array.prototype` do anything to protect you from modifying the accumulator in place.  Perhaps this example would be clearer:

```js
const extremes = {min: Infinity, max: -Infinity};

const dangerouslyModifyAccumulator = (range, val) => {
  range.min = Math.min(range.min, val);
  range.max = Math.max(range.max, val);
  return range;
};

[8, 6, 7, 5, 3, 0, 9].reduce(dangerouslyModifyAccumulator, extremes);
//=> {max: 9, min: 0}

[4, 5, 6, 1, 1, 1, 1].reduce(dangerouslyModifyAccumulator, extremes);
//=> {max: 9, min: 0},  but should be  {max: 6, min: 1}
```

It feels a bit easier to accidentally do this in Ramda's `reduce` than in the `reduce` from `Array.prototype`, but that's mostly because when writing Ramda, we are thinking more about creating reusable functions by partial application.  In `Array.prototype`, we tend to write out all parameters explicitly.

In any case, Ramda has long held to the no hand-holding philosophy.  If a user really wants to modify an accumulator, Ramda does not try to prevent it, which we could attempt with an initial `clone`, because we let the user make the choice in this low-level library.  A somewhat higher-level library might well make a different choice.

**Comment by twelve17** [comment]
> If you have suggested changes to the phrasing, would you mind opening a PR with the change?

@CrossEye 

Yes, I could do that. The phrasing would follow the pattern existing in the `map` function documentation. Let me give it a shot.  Thanks.
