### ISSUE TITLE
isEmpty with undefined

### ISSUE THREAD

**Issue by code-guru** [ramda/ramda#2507]
Currently `isEmpty(undefined)` returns false, this behavior can cause a lot of bugs and issues.
If we also consider the semantics both `undefined` and `null` represent emptiness. 

My suggestion is to consider null, and undefined as Empty, or if there was a prior discussion about this issue, please enlighten us.

**Comment by CrossEye** [comment]
We discussed this a few months ago in relation to `NaN`.  (#2113) The conclusion seemed to be that we would stick to the documentation that says that a value is empty if it is its type's empty value.  Thus for Object, `{}`, for Array, `[]`, for String, `''`, and whatever custom types offer.  `undefined` is not the empty element for any type.

But of course we already have `isNil` which covers `undefined` and `null`.  You could always combine that with `isEmpty` if you need to.

**Comment by code-guru** [comment]
Thanks for the response @CrossEye. I checked the referenced issue, and I believe this case is completely different. 

I agree that `is(Number, NaN) === true` implementation is compleltely correct as NaN has Number type.

However, in this case, there are some exceptional _constants_  i.e. `null`, `undefined`, `NaN` which are "Empty" by nature. 

By looking at their type `typeof(undefined) === 'undefined'` and `typeof(null) === 'object'`., we see the type of `null` is Object, so we can say null is object-type's empty value. 

The same argument applies to undefined, if we agree javascript `typeof` implementation is correct, then type of undefined in Undefined, and undefined is undefined-type's empty value.

Again same logic can be applied to NaN, one can claims that since NaN doesn't contains any value of type Number then we can say NaN is Number's empty value.

at last, we tend to use a utility belt to avoid the following code, aren't we?
`const isReallyEmpty = either(isNil, isEmpty);`

**Comment by CrossEye** [comment]
I should have pointed out directly that `empty` here is meant to fulfill  [FantasyLand's `empty`][em] specification for [Monoids][mo].

The discussion I pointed to above noted that while we could create a monoid for Number where `NaN` is the empty value, it would by no means be the only or most obvious one.  So `NaN` should not be the `empty` value of `Number`.  This is not about containment ("since NaN doesn't contains any value of type Number") but only about the identity element.  

And `Object` already has a useful empty value: `{}`, which together with `merge` form a reasonable monoid.  Making `Object`'s `empty` value into `null` would cause harm.

`undefined` is, I suppose, a different case.  As you note, it is the only value of it's type, so that type could be a trivial monoid with `concat(undefined, undefined) //=> undefined` and of course the empty value of `undefined`.  That `concat` is clearly associative, so this would be legitimate, but it's also so trivial not to be useful anywhere I can see.  And I would be loathe to treat `null` and `undefined` differently.

> at last, we tend to use a utility belt to avoid the following code, aren't we?
> ```js
> const isReallyEmpty = either(isNil, isEmpty);
> ```

Perhaps, but when packing a utility belt, we have to decide how big it is allowed to grow.  We cannot include every function that might be helpful to any user.  We need to pick and choose and let users combine the functions as needed.  Sometimes it's easy to decide: `compose` and `pipe` are both so useful that we choose to include both, even though either could easily be built on the other.  Other times it's harder: `contains` and `flip(contains)` are almost equally useful.  It was a hard decision not to include both a `contains` and a `containedIn` function.  But having both didn't seem worth the bloat.  In this case, I'm seeing a good reason to keep `empty` to what it's doing, and not seeing a compelling reason to add another function which wraps `isNil` and `isEmpty`.  (I am willing to be convinced about that latter, though, if you want to try to make the case.)

  [em]: https://github.com/fantasyland/fantasy-land#empty-method
  [mo]: https://github.com/fantasyland/fantasy-land#monoid

**Comment by code-guru** [comment]
Looking at it from the monadic perspective it makes a lot of sense, but we should differentiate a strong statically typed language like Haskell from a week dynamically typed language such as JavaScript. 

I was looking at the matter from a more practical perspective. What makes the most sense to a javascript developer getting his feet wet in functional programming paradigm by replacing lodash with ramda?

I completely agree to keep it as it is if the primary purpose of the project is to provide a strict implementation of the monadic structure.

**Comment by Bradcomp** [comment]
I don't think it's simply that we want to only work on _monoidal_ structures, it just so happens that the idea of `empty` is well represented by monoids. For instance, as @CrossEye mentioned, objects form a reasonable monoid, but they don't fulfill the FL spec because we don't have a `concat` for them.  They can still be `empty` though.

If something doesn't contain other things, it can't be empty. A gas tank can be empty, a tire can be empty, but a steering wheel or a brake pedal can't be empty.

If I tried to use `null` or `undefined` in a place where I expected an empty array, I would be surprised.
```
> null.concat([1, 2, 3])
TypeError: Cannot read property 'concat' of null

> [1, 2, 3].concat(null)
[ 1, 2, 3, null ]

> [1, 2, 3].concat([])
[ 1, 2, 3 ]
```
`isEmpty` does what it says, as does `isNil`. There are times when you want to check for both, but there are also times where you _just_ want one or the other. By providing separate functions, one can build up the tools they need for their specific use case. 

This is a critical part of what Ramda is about. It provides base level tools, and then it provides nice ways of being able to combine those tools in unique and useful ways. While it has similarities with libraries like lodash, its differences are what set it apart. One of those is that it makes less assumptions about what the user meant. 

There are lots of values that a user might consider to be special in some way. Empty arrays and objects, `null` and `undefined`, `NaN`, `Nothing`, etc. But those values don't really have much in common, and may be more or less meaningful depending on the context.

We can check for all of them using `anyPass([isEmpty, isNil, Number.isNaN])` or we can mix and match depending on our context due to the fact that they are separate functions.

**Comment by CrossEye** [comment]
> as @CrossEye mentioned, objects form a reasonable monoid, but they don't fulfill the FL spec because we don't have a `concat` for them.

Damn, something else for the TODO list!

**Comment by code-guru** [comment]
Thanks @CrossEye @Bradcomp for sharing your perspectives and the logic behind the implementation.

**Comment by davidchambers** [comment]
Conceptually, `R.isEmpty` *should* behave as follows:

> __`R.isEmpty :: Monoid m => m -> Boolean`__
>
> Given a value of some monoidal type `m`, `R.isEmpty` returns `true` if and only if that value is the empty value of type `m`.

`R.isEmpty (x)` should be equivalent to `R.equals (R.empty (x)) (x)`.

`R.isEmpty (undefined)` is actually a type error, since the `Undefined` type does not satisfy the [Monoid][1] constraint.


[1]: https://github.com/fantasyland/fantasy-land#monoid
