### ISSUE TITLE
defaultTo('value')() returns a function

### ISSUE THREAD

**Issue by iansinnott** [ramda/ramda#2510]
Hey everyone, maybe this is intended behavior but I couldn't find mention of it anywhere. The `defaultTo` function does not run unless supplied with an argument. This could be confusing. For example:

```js
const getParams = pipe(
  defaultTo({
    page: 1,
    pageSize: 25
  }),
  pick(['page', 'pageSize'])
);

getParams(undefined); // { page: 1, pageSize: 25 }. As expected
getParams(); // => {}. Empty object since `pick` was passed a function type...
```

More specifically, calling a function created with `defaultTo` with no arguments will return the function itself, not the default value.

I'm guessing this has to do with how currying is implemented in Ramda, but I'm curious to know if this is intended or would be considered a bug.

**Comment by CrossEye** [comment]
This is absolutely the expected behavior.

Ramda currying is slightly different from standard currying.  But with any sort of currying this would either behave as Ramda does or throw an error.

`defaultTo` takes two parameters.  Because it's curried, you can supply these one at a time.  (Standard currying would say that you *have to* supply them one at a time.)  Ramda continues to return a function until you eventually supply the correct number of parameters.  Although this behavior was hotly debated as far back as #106, one thing we never really contemplated was to try to call the underlying function if too few parameters had been supplied.  Our current behavior is that if you pass zero arguments, you get back something equivalent to the function you called.  The only other logical option was to throw an exception.

There is nothing special about `defaultTo` here.  The only reason, I believe, that this might seem slightly surprising is that `defaultTo` *could* have a logical answer in the case the value to check is not supplied.  But in the end, it would be the same as trying to perform the underlying operation of `map` when you call `map(square)()`.  There's simply no data to process.  Again, our realistic options are to return `map(square)` again or to throw.

**Comment by iansinnott** [comment]
Great, thanks for the explanation @CrossEye
