### ISSUE TITLE
R.head(undefined) -> Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ewaltman** [ramda/ramda#2522]
I would expect 
```R.head(undefined)``` 
to produce the same output as 
```R.prop(0)(undefined)``` 
in all cases, but it appears that `R.head` produces an unhandled promise rejection with message: `Cannot read property '0' of undefined`. 

http://ramdajs.com/repl/?v=0.25.0#?R.head%28undefined%29%3B%0A

I couldn't find any existing issue related to this bug and wanted to raise it.

**Comment by CrossEye** [comment]
> I would expect 
> ```R.head(undefined)``` 
> to produce the same output as 
> ```R.prop(0)(undefined)``` 
> in all cases

I wouldn't.

`head` is related to lists, items which have reasonable heads and tails.  While our `head` is right now fairly limited, it could easily be expanded to work on other structures than the current arrays (example below).  In fact, I think we should really consider that. 

But `prop` is specific to objects.  Because JS layers arrays atop objects, it happens to work for  arrays as well.  But this is more happenstance than fundamental design.  

By the way, the error you're seeing has nothing to do with Promises.  The Type Error `Cannot read property '0' of undefined.` is what the current implementation yields: an error.  This is part of Ramda's usual Garbage In/Garbage Out philosophy.  While I am sometimes willing to add argument-checking to avoid exceptions when there is some reasonable answer -- others here are somewhat less willing -- I don't see a good answer here for `head`.

----------

Example
-------

(See [@buzzdecafe's gist][gi] for additional functions.)

```js
// simpler
// const cons = (x, y) => (pick) => pick(x, y)

// does more
const cons = (x, y) => {
    const fn = (pick) => pick(x, y);
    fn.toString = () => `(${asArray(fn).join(" ")})`;
    fn.pair = true;
    return fn;
}

const car = (f) => f((x, y) => x)
const cdr = (f) => f((x, y) => y)
const list = (...args) => args.length ? cons(args.shift(), list.apply(null, args)) : null
const asList = (arr) => list.apply(null, arr)
const asArray = (list, arr = []) => (list && car(list)) 
                ? (arr.push(car(list)), asArray(cdr(list), arr)) 
                : arr

const myList = list(2, 3, 5, 7, 11) //=> (2 3 5 7 11)

cdr(myList) //=> (3 5 7 11)
car(myList) //=> 2
car(cdr(myList)) //=> 3
```

Here are lists created out of nothing but pure functions.  They have head (`car`) and tail (`cdr`) functions that do just what you would expect.  But there are no `prop`s that matter here.  One day, it's easy to imagine Ramda's `head` expanding to work with these, but `prop(0)` would have no meaning with them.

  [gi]: https://gist.github.com/buzzdecafe/5272249

**Comment by Izhaki** [comment]
I think `R.head(undefined)` throwing an error is by far less bug-prone than it returning `undefined` (you can always write your own `safeHead`).

If anything, `R.prop(whatever, undefined)` should also throw an error as well, but as @CrossEye said - it's just a coincident that it works. But I think static type-checking is much preferable option here over run-time guards.

At any rate @ewaltman, what is the concrete use case that led you to file this issue?

**Comment by polytypic** [comment]
One reason for `R.prop(whatever, undefined)` to not throw an exception and return `undefined` is that it makes sense for it to be equivalent to `R.path([whatever], undefined)`.  In general, it would make sense for `R.prop(x, y)` to be equivalent to `R.path([x], y)` and you could explain `R.path([...xs])` as being equivalent to `R.pipe(...R.map(R.prop, xs))`.  Why is that?  Because you want to make it possible for a user of the library to reason about things in a compositional manner, because it then makes it easier to reason about library code as a whole.  Instead of an endless list of special cases for each function, you'd get a (shorter) list of equations through which you could reason about things.  Those equations and the search for a small list of equations to explain how functions behave are also powerful tools for library design.  IMHO, it is very unfortunate that many related functions in Ramda do not share such simple equivalance relations.  Instead, Ramda users are forced to, IMHO, unnecessarily treat many functions as special cases and there are many issues considering special case behaviors for particular functions.

**Comment by CrossEye** [comment]
See #2305

**Comment by sesm** [comment]
Some objections to current behaviour:
1. One reason to use functions instead of built-in `Array` methods is that functions can check their arguments in order to not fail with exception. From this perspective, `R.head(arr)` is currently no better than `arr[0]`.
2. People seeing `head` as the name of the function (as opposed to, say `first` or something) would expect it to work similar to Lisp's `head`, which returns nil for nil input.
3. 'Garbage in - garbage out' is not the same as 'garbage in - exceptions out'. See, for example, Clojure standard library, which always prefers returning garbage to throwing exceptions.

**Comment by CrossEye** [comment]
@sesm:

All these points are all related to arguments that have been discussed often and which continue to shape the Ramda API.  None are entirely decided to our collective satisfaction.

> One reason to use functions instead of built-in `Array` methods is that functions can check their arguments in order to not fail with exception.

They can, sure, but Ramda has always had a no-hand-holding philosophy.  I'm perhaps closer to your point of view than some other Ramda team members, as I really hate throwing exceptions, but I still don't want to write or maintain the sort of code necessary to hold the users' hands for every input.


> People seeing `head` as the name of the function (as opposed to, say `first` or something) would expect it to work similar to Lisp's `head`, which returns nil for nil input.

Or they might expect it to work similarly to Haskell's `head` which throws for empty input.  (We don't do that either!)  Probably more of the community here is aligned with Haskell than with LISP.  I personally waver quite a bit between the two.

Ramda decided long ago that it would take ideas from FP languages, but it would never ape their decisions.  We try to adapt them well for JS, with varying degrees of success.


>  See, for example, Clojure standard library, which always prefers returning garbage to throwing exceptions.

That's pretty horrifying and may be one of the reasons that Clojure, for all its good points, has never appealed to me.  My personal preference has evolved to be something along the lines of "Functions ask questions related to their arguments.  The return value is an answer to that question.  When we can reasonably answer that question, even in the face of bad input, then we should do so.  When we cannot, I see nothing better than throwing."

**Comment by jamesstoneco** [comment]
There is some great discussion on this issue and I understand it is closed. I just wanted to share a simple fix if someone is working with data that might end up being `undefined` but they still want to use Ramda head in a way that it would just return undefined if passed undefined.

```javascript
head(someArrayMaybeUndefined || [])
```

In this case if the array is undefined, then a blank array (list) is passed and thus the function will return undefined.
