### ISSUE TITLE
contains with map.

### ISSUE THREAD

**Issue by overflowz** [ramda/ramda#2526]
Heyya,

First of all, I'm new to functional programming paradigm and still learning it. I found Ramda library pretty powerful.

Question, I'm playing with it for a while and I faced problem like this:

Why does this work
```javascript
var isUserInRoom = R.contains(R.__, R.__);
isUserInRoom(1, [0, 1, 2, 3]); // returns true
```

and this does not?

```javascript
var isUserInRoom = R.contains(R.__, R.map(x => x, R.__));
// or R.contains(R.__, R.map(x => x)(R.__));
// or R.contains(R.__, R.map(x => x));
// or R.contains(R.__, R.map(x => x).bind(null, R.__));
isUserInRoom(1, [0, 1, 2, 3]); // returns false
```

**Comment by CrossEye** [comment]
This is actually an important question on its own:

> Why does this work
> ```js
> var isUserInRoom = R.contains(R.__, R.__);
> isUserInRoom(1, [0, 1, 2, 3]); // returns true
> ```

This works because all placeholders (`R.__`) after the last non-placeholder argument are ignored.  They mean nothing.  The placeholder is a way to say, essentially, "ignore this parameter temporarily while we bind the other ones.

`contains` is actually a very good example.  The API is `contains(needle, haystack)`.<sup>*</sup>  It's a debatable argument order.  Which is more likely to change between calls, the needle or the haystack?  Ramda choose to put the `needle` first, and so `contains` can be used either in full, as `contains(needle, haystack)` or partially applied as `contains(needle)`, which would return a function that still must be supplied the haystack.  But there are times when you want to supply the haystack and get back a function which must then be supplied a needle.  To cover these cases, we offer a [`flip`][fl] function and the more powerful placeholder.  So we can write `contains(__, haystack)` for a function that still needs to have a needle supplied.

That's what the placeholder is for.  Put in place of the `needle` parameter, it's a way of saying that we will return a function that still requires this parameter.  When used as your example suggests, as `contains(__, __)`, it says that we still require both parameters, so we get back, essentially, the `contains` function itself.

So `isUserInRoom = contains(__, __)` is functionally equivalent to `isUserInRoom = contains`. 

As to your actual question, why this doesn't work 

```js
var isUserInRoom = R.contains(R.__, R.map(x => x, R.__));
isUserInRoom(1, [0, 1, 2, 3]); // returns false
```

again, I'm guessing you're thinking of the placeholder incorrectly.

In this case, you do supply a `haystack` argument to `contains`, the function `map(x => x)`, and you get back a function that requires the `needle` one.  When  you call this new function, like this:

```js
isUserInRoom(1, [0, 1, 2, 3])
```
what you're really calling is

```js
contains(1, map(x => x))
```

Since that `map` function does not contain `1` (or any other properties), this returns false.  It could well through an error instead, since that haystack is not a list, but  that's not how it's implemented.

I assume this is either example code or learning code, since there would be no reason to map the identity function over a list, but if I were to write this, I would probably go with the simple:

```js
const isUserInRoom = (user, rooms) => contains(user, map(x => x, rooms))
```

This is clean and readable.  But if you really want to make it point-free, you could use [`useWith`][uw] like this:

```js
const isUserInRoom = useWith(contains, [identity, map(x => x)])
```

And your true transformation function could go in the place of `x => x`.  (Again, I assume this is not your real code, as `map(x => x)` doesn't do anything useful here.)

Does this make sense?

---------- 
<sup>*</sup> If these terms are not familiar to you, "looking for a needle in a haystack" is a common English expression for a search that is difficult because of how much there is to sort through, and perhaps because of how small the target is.  

  [fl]: http://ramdajs.com/docs/#flip
  [uw]: http://ramdajs.com/docs/#useWith

**Comment by overflowz** [comment]
Yup, it's not a real code, it's just for simplicity.

And thanks for your answer though, it's all clear now. Also you can close the thread.
