### ISSUE TITLE
Production documentation is odd

### ISSUE THREAD

**Issue by derekstavis** [ramda/ramda#2542]
Since some days (I sincerely don't remember when), I started seeing strange functions on production documentation. I've noticed the issue when I failed finding `__`. Here goes some screenshots:

![screenshot from 2018-05-24 19-47-43](https://user-images.githubusercontent.com/1611639/40517408-8a292db8-5f8b-11e8-9634-79bb8b03bc70.png)
![screenshot from 2018-05-24 19-47-18](https://user-images.githubusercontent.com/1611639/40517409-8a551270-5f8b-11e8-8088-8b11ca5a9139.png)

Thanks @rsmelo for pointing this :)

**Comment by CrossEye** [comment]
Well that definitely is strange!

I'll try to take a look later today.

**Comment by cab** [comment]
It seems like https://github.com/ramda/ramda/pull/2327 was supposed to fix this, but I just saw the same issue.

**Comment by CrossEye** [comment]
Thanks.  At this point, my investigation has to wait until this evening or the weekend.  But that's a great hint.

**Comment by boazblake** [comment]
this is still an issue

**Comment by MattMS** [comment]
I'm looking into this now.

**Comment by MattMS** [comment]
So it looks like this has already been fixed in Ramda (#2327 and #2328) but the latest published version of Ramda doesn't have the fixes.

To use the current build process for the site, we'll need to publish 0.25.1.

**Comment by CrossEye** [comment]
I'd really like to publish 0.26 as soon as I can squeeze out a little time.  But if anyone has time to publish 0.25.1, that would probably be a good idea.  @ramda/core ●●●●●●●●●●●●

**Comment by semmel** [comment]
@CrossEye I just briefly want to mention the discussion in #2337 where it is argued to make the next version a 1.0 and move all pending ES6 PR's and API breaking changes to 2.0.

Ramda is a solid library now. I guess that like me many people need to rely on a non-breaking major Ramda version 1.0 because it already (:smirk:  version 0.1 was released on Dec 27, 2013)  runs in production systems. It's present features, like IE11 compatibility, are still important.

Although it may be beneficial from some point of view to publish a sub version 0.25.1, that move would go completely in the other direction. I just question that such an effort is justified because the "Production documentation is odd".

**Comment by def14nt** [comment]
@semmel @CrossEye @MattMS Is the documentation getting republished anytime soon? It's *still* there.

**Comment by rpearce** [comment]
This seems to be fixed

**Comment by CrossEye** [comment]
Yes, the new version published yesterday fixed it.
