### ISSUE TITLE
find and adjust

### ISSUE THREAD

**Issue by itaied246** [ramda/ramda#2546]
Is there a way to `find` and `adjust` in 1 call?

I managed to do it like this:

```js
updatePlayer(playerId, data) {
        const playerIndex = findIndex(propEq("id", playerId), this.players);
        this.players = adjust(mergeDeepLeft(data), playerIndex, this.players);
    }
```

Something like this would be nice:

```js
findAndAdjust(mergeDeepLeft(data), propEq("id", playerId), this.players);
```

**Comment by CrossEye** [comment]
While it's clear enough that you can write your own generic version of this function, and it would be welcome in the [Cookbook][cb] (or possibly in [ramda-adjunct][ra] or [ramda-extension][re]; you can check with their maintainers.)

But I would really hesitate to include it in Ramda.  The problem is that `find`/`findIndex` can signal that the value is not found.  But `adjust` will only return the updated list.  Combining them seems to lose some important information: namely that you might not have found and updated anything.

Perhaps less importantly, there is also the issue that `find` dispatches, so it can operate on many types, but I can't see how to implement `adjust` more generically.  


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [ra]: https://github.com/char0n/ramda-adjunct
  [re]: https://github.com/tommmyy/ramda-extension

**Comment by polytypic** [comment]
>  I can't see how to implement `adjust` more generically.

Note that `adjust` can be seen as a specialized version of `over` or modification through an optic:

```js
const adjust = (fn, i, xs) => R.over(R.lensIndex(i), fn, xs)
```

and lenses can be generalized to traversals.

For example, using [Partial Lenses traversals](https://github.com/calmm-js/partial.lenses#optics) one could write:

```js
L.modify([L.elems, L.when(R.propEq('id', playerId))], R.mergeDeepLeft(data), players)
```

**Comment by jacobworrel** [comment]
@itaied246 What if the playerId prop isn't found in `this.players` and `findIndex` returns -1 ? in this case, `adjust` will apply the updater function to the last index, since negative indices start from the end of the list, which is probably not what you want.

My solution to this problem was to create a stricter version of adjust that doesnt accept negative indices, returning the input list untouched if a negative index is provided:

`
const adjustStrict = R.curry(
  (fn, idx, list) => R.ifElse(
    R.lt(R.__, 0),
    R.always(R.identity),
    R.always(R.adjust(fn, idx))
  )(idx)(list)
);
`
