### ISSUE TITLE
R.o: resulting function is not executed when invoked without parameters.

### ISSUE THREAD

**Issue by dscastillo171** [ramda/ramda#2557]
I'm not sure if its intended, but the resulting function `R.o` is not executed if called without parameters, this is not consistent with the behavior of `R.compose`:

`R.o(R.add(1), R.always(1))(); // function(), expected 2`
`R.compose(R.add(1), R.always(1))() // 2`

**Comment by CrossEye** [comment]
@buzzdecafe: A type error when the first-executed function passed to `compose`/`pipe`/`o` is nullary?  Or something else?

**Comment by buzzdecafe** [comment]
apologies, i am forgetting that `always` is not `K`, and js does not have a `unit`. what we have as a result is this `curry1` biz where if you invoke a curried function with no args you get the original function back, instead of an error. that is what is happening in the `o` case. that still sticks in my craw

**Comment by dscastillo171** [comment]
In that case I think a type error when the second function passed to `o` is nullary would be helpful. Compose however I think its ok, since it behaves like its described in the docs.

**Comment by CrossEye** [comment]
I think there is some sense in an error on an initial nullary function, especially [if we're adding `thunkify`][th].

We've always disagreed on the behavior of `curry1`.  I like the consistency, but certainly understand the objection.


  [th]: https://github.com/ramda/ramda/pull/2551

**Comment by buzzdecafe** [comment]
likewise, i understand the motivation for the current `curry1` behavior. 

back to the OP: the fact is that `compose` and `o` are significantly different in their input and output. So this raises the questions:

1. should the behavior the function output by `o` be consistent with `compose`?
2. should we commit to one and deprecate the other?
3. How does `pipe` fit into all this?
4. Can we defer this until post-1.0?

**Comment by Bradcomp** [comment]
`o` should definitely _not_ have the same behavior as the current `compose`. It was built to be a stricter version closer to the mathematical definition of compose. 

`o:: (b -> c) -> (a -> b) -> a -> c`

The issue is that the OP is not providing that final `a` because it's not required by `always`, _even though_ it's a part of the sig for `o` and is thus required.

`R.o(R.add(1), R.always(1))(null); // => 2`

Once the argument is passed in, the correct result comes out.

I like the consistency of `_curry1` even though I have experienced bugs because of it. In a typed language passing in the wrong number of variables is a type error. In Haskell, because there are no parens, you can't invoke a nullary function (am I right here?) I think returning the original function or else throwing are the only reasonable options.

Now that I am typing this out, throwing in the case of passing no parameters to a curried function seems very reasonable, if 'ramda style currying' is kept post 1.0 in lieu of moving to simple currying. I can't think of a case where passing no parameters to a 'ramda-curried' function isn't a programming error. If we move to simple currying the issue is more complicated, and will go back to the GIGO vs helpful discussion.

I agree with @CrossEye that `thunkify` would better solve this problem, or a simple lambda. It's tough to suggest an exact alternative because the function as it stands has no free variables, and thus my suggestion would be `2` or `() => 2` if you wanna be lazy.

Post 1.0, I like the tack that Sanctuary took on this, and that we are taking on `pipeWith/composeWith`. Have one function (`o` in this case, because `compose` is taken) that satisfies the mathematical definition so that we can do crazy stuff like `o(o, o)` and then a `pipe` for multiple functions that can handle variadic inputs with the functions wrapped in an array.

**Comment by dscastillo171** [comment]
Thank you for the clarifications, I've learned quite a lot reading through these comments.

`thunkify` will definitely help me out, or I can just stick to `compose. Finally although I'm not completely familiar with the project, I also support the idea of throwing an error or a warning when a curried function is called without parameters. That would be very helpful to find some bugs.

Thank you guys, I'll close the issue.

**Comment by buzzdecafe** [comment]
>  In Haskell, because there are no parens, you can't invoke a nullary function (am I right here?)

well, you can define a function from `absurd :: Void -> a` but you could never call it, since you cannot get an element of `Void`. so you could define a function from `() -> a`, but then you have to specifically pass `unit` (i.e. `()`) to it. 

js does not have a notion of `unit`, so we sort of fake it with nullary function invocation. But then we have a conflict with the notion of a function being from an argument `a` to a result `b`. 

sigh. js as a host language is really not suitable for digging too deeply into this stuff. And I think that may be @CrossEye 's point: You can't make a silk purse from a sow's ear. so we gotta decide where to draw the line.
