### ISSUE TITLE
groupWith does not work as expected

### ISSUE THREAD

**Issue by plopezlpz** [ramda/ramda#2564]
`R.groupWith((a, b) => a.a === b.a, [{a: '11'}, {a: '22'}, {a: '11'}])` returns:
`[[{"a": "11"}], [{"a": "22"}], [{"a": "11"}]]`
instead of:
`[[{"a": "11"}, {"a": "11"}], [{"a": "22"}]]`
See the bug [here](https://ramdajs.com/repl/?v=0.25.0#?R.groupWith%28%28a%2C%20b%29%20%3D%3E%20a.a%20%3D%3D%3D%20b.a%2C%20%5B%7Ba%3A%20%2711%27%7D%2C%20%7Ba%3A%20%2722%27%7D%2C%20%7Ba%3A%20%2711%27%7D%5D%29%0A%2F%2F%20should%20be%20%5B%5B%7B%22a%22%3A%20%2211%22%7D%2C%20%7B%22a%22%3A%20%2211%22%7D%5D%2C%20%5B%7B%22a%22%3A%20%2222%22%7D%5D%5D)

**Comment by Bradcomp** [comment]
Hi @plopezlpz,

This is expected behavior as can be seen in the following examples from the documentation:

```
R.groupWith((a, b) => a % 2 === b % 2, [0, 1, 1, 2, 3, 5, 8, 13, 21])
//=> [[0], [1, 1], [2], [3, 5], [8], [13, 21]]

R.groupWith(R.eqBy(isVowel), 'aestiou')
//=> ['ae', 'st', 'iou']
```

`groupWith` only takes adjacent elements into its comparison function, so is useful for finding runs, but not for your particular use case.

I would suggest using `groupBy`, and then combining with `values` if you want an array at the end: https://goo.gl/CRa5w6

**Comment by plopezlpz** [comment]
Ah ok, I'll use groupBy then
