### ISSUE TITLE
Ramda functions doesn't check for valid object existence (i.e null, undefined)

### ISSUE THREAD

**Issue by rdsedmundo** [ramda/ramda#2566]
Hi, I'd like to know if it's expected that Ramda doesn't check for object existence like in the `R.pick` function (it happens in others as well, but I'm exemplifying with it). That's it:

```javascript
const object = null;
R.pick(['test'], object); // Cannot use 'in' operator to search for 'test' in null
```

This is annoying in cases when I'm passing the `pick` as a callback, where the value can be null sometimes (especially initial state), like this:

```javascript
  connect(
    createSelector(
      getInfluencerSelector,
      pick(['email', 'name']),
    )
  ),
```

**Comment by CrossEye** [comment]
This is not specifically intended.  It's just fallout from the implementation.

Ramda has long held to a no hand-holding philosophy.  And @buzzdecafe and I disagree a bit about when to accept such type-checking, so I can't guarantee that it would be accepted, but I would welcome a PR to fix this, because it falls into my sweet spot: we have a reasonable answer to give when the input is nil.  We can just return an empty object.

But if you just need a way to make this work for you, you can always use [`tryCatch`][tc]:

```js
tryCatch(pick(['name', 'email']), always({}))
```


  [tc]: https://ramdajs.com/docs/#tryCatch

**Comment by trgwii** [comment]
I think it would be great if more functions handled undefined / null cases more gracefully (I'd enjoy if these types were just returned through). Imagine the following case:

```js
const capitalize = converge(concat, [
  compose(toUpper, head),
  tail
]);

capitalize('hello') // -> 'Hello'
```

Now this works fine for strings, but with very minor changes to the way null / undefined is handled, we could easily make it behave like so:

```js
capitalize(null) // -> null
capitalize(undefined) // -> undefined
```

I think this is pretty similar to how monads are handled within the functional world, but without actually needing to carry monads around through our functions. I know I'm fully convinced that it's preferrable to throwing in most situations.

As a side note: If we allowed prepend to work for strings, we could replace concat with prepend, and have it work well for arrays too:

```js
capitalize([ 'foo', 'bar' ]) // -> [ 'FOO', 'bar' ]
```

**Comment by customcommander** [comment]
Tangentially related to #2998.
