### ISSUE TITLE
Not seeing an upgrade guide mentioning removal of R.__

### ISSUE THREAD

**Issue by flipactual** [ramda/ramda#2568]
I like `R.__` – what am I meant to use instead?

**Comment by functionalStoic** [comment]
@flipactual Are you referring to how it isn't showing up in the docs right now?

You will find it here:

https://ramdajs.com/0.25.0/docs/#module.exports

There is an issue with the docs at the moment

**Comment by flipactual** [comment]
Thank you @functionalStoic – I thought it was gone since it isn't showing up where I expected it in the docs

**Comment by Bradcomp** [comment]
While there has been talk of removing the placeholder, it hasn't actually been removed, nor is there any plan for it in the near future (it would be post 1.0).

The docs are broken, but the placeholder is still there.

To answer your question though, I got a chuckle because the answer is right in your name 😉 

`R.contains(R.__, arr) === flip(R.contains)(arr)`

**Comment by flipactual** [comment]
@Bradcomp 😂 very good!

And what if I would like a placeholder in the middle?

**Comment by Bradcomp** [comment]
It gets tricky if you want to stay Point Free.

I am personally not on the side of removing the placeholder for that reason, as well as because it helps when using the _very_ controversial comparison functions like `gt`

```
R.gt(R.__, 5)    //this makes sense
R.flip(R.gt)(5)  //wat
R.lte(5)         //The same, but now you've lost semantics
```
