### ISSUE TITLE
performance issue with R.uniq R.uniqWith R.uniqBy

### ISSUE THREAD

**Issue by eddyLazar** [ramda/ramda#2575]
Actually it didn't work on large lists. In my case it was 60000 items in list and it just stuck on calling these functions.

**Comment by bas080** [comment]
I know that uniqWith can be slow. The other two work fine for me.

```js
const {uniq, uniqWith, uniqBy, times, identity, equals} = require('ramda')
const assert = require('assert')

const data = times(identity, 60000)

assert.deepEqual(uniq(data), data)

assert.deepEqual(uniqBy(identity, data), data)

//assert.deepEqual(uniqWith(equals, data), data)
```

`$ time node time.js`

```
real	0m0.336s
user	0m0.320s
sys	0m0.032s
```

When I uncomment the `uniqWith` line, it does "block".

**Comment by dtb11288** [comment]
In our product, we got some issue performance too, but it related to function "equals" or any function that used "equals" (propEq, uniq ...)
A suggestion is change to use your simpler equals function.

**Comment by CrossEye** [comment]
@eddyLazar: Does the analysis from @bas080 make sense to you?  `uniqWith` needs to do a lot more work than `uniqBy` or `uniq` (which is build atop `uniqBy`.)

The difference is that `uniqBy` uses a `Set` to determine which elements have already been seen.  It calls the transformer function once per element and then asks the set whether or not that element is already a key.  (It's our own implementation of `Set`, not the built-in one, because we need value equality, not reference equality checks.)

`uniqWith` is more general  You don't have to be able to make a unique key from your objects; Instead, you need to supply a binary predicate that says whether two items are equal.  But using this predicate requires testing every pair of elements to see whether they are equal.  In the example above, there are 10 elements, and therefore `(10 choose 2)`, or 45, pairs.  (`(n choose 2)` is equal to `n * (n -1) / 2`.) 

That grows quickly.  With 60,000 elements, you will need to make 1,799,970,000 comparisons.  That's unlikely to be quick.  So if you can find a way to make a key out of your values, `uniqBy` should be much faster.
