### ISSUE TITLE
filter needlessly creates new instance of an array

### ISSUE THREAD

**Issue by krzysztofpniak** [ramda/ramda#2664]
In a world of immutable structures we should avoid mutations as much as we can. For example this simple code creates new array.

```
const a = [1,2,3];
const b = filter(x => x != 10, a);
b === a // expected to be true, but it is false
```

**Comment by Bradcomp** [comment]
There's a couple of reasons why `filter` doesn't act in the way you suggest. One is predictability, and the other is performance (though I think predictability is more important).

In order to do this, we would have to check each result array to see if it's the same as it was before filtering, and use that to determine which array to return. The other option would be to first run the filtering function over the array to see if there will be any changes, and then run it through again to remove items if any of the items returned false.  In either case we're doing extra work in the 'typical' case where we actually want to filter things out.

The predictability aspect, I think, is more compelling. Right now we know that `filter` returns a new Array. If we made this change, then we wouldn't be able to rely on that. There are plenty of cases where we don't have control over whether to mutate our data, and other cases where mutation makes sense due to the specifics of the situation. By not providing a predictable function, it makes any attempt to mutate a filtered array more dangerous, by potentially propagating that mutation to the input (but not always!).

Lastly, if we did this we would want to be consistent, and that gets a lot more difficult. Should `map(x => x, arr)` also return its input? What about `evolve({x: inc}, {y: 0})`? This has the potential to effect large swaths of the library.

Lastly, it would be a breaking change. Without a significant upside, I don't see something like this making it into the library.

**Comment by foxbunny** [comment]
> In a world of immutable structures we should avoid mutations as much as we can.

I don't see any mutation in your example. I think what you really want is a better way to determine the equivalence of two values along the lines of `[1, 2, 3] === [1, 2, 3]  // => true`.

**Comment by xgbuils** [comment]
I think that the background idea of @krzysztofpniak is not creating a new object if not needed. The advantage of this is that if we have:

``` javascript
var newArr = arr.filter(pred);
```
and we ask if `newArr` is equal to `arr`, if we don't create a new array, we can check the equality using reference equality that is more efficient than checking the equality item by item.

Besides, it's a pattern extended users of `redux` library. However, I think it's difficult and a hard work trying to change all of `ramda` library to get this feature.

**Comment by CrossEye** [comment]
@xgbuils: I think that's understood, but the point @Bradcomp is making probably trumps this for Ramda: we want to be consistent.  Since we don't care how you use the values that Ramda functions return, we really don't want to be responsible for this sort of behavior:
```js
const myArr1 = [1, 2, 3]
const newArr1 = R.filter(n => n > 1, myArr1)
newArr1.push(4)
newArr1 //=> [2, 3, 4]
myArr1 //=> [1, 2, 3]

const myArr2 = [1, 2, 3]
const newArr2 = R.filter(n => n > 0, myArr2)
newArr2.push(4)
newArr2 //=> [1, 2, 3, 4]
myArr2 //=> [1, 2, 3, 4]  // HUH?  WHAT?
```

This sort of inconsistency would not matter at all if all values were immutable.  But Ramda cannot enforce that, and we wouldn't even want to try.  It's just a lot cleaner if a Ramda functions ever returns a new construct that it always does so.
