### ISSUE TITLE
`sort` method doesn't work on Node.js 11.0.0

### ISSUE THREAD

**Issue by acierto** [ramda/ramda#2679]
After upgrading to Node.js 11 function 

`R.sort(R.gt, ["Applications/B/1.0","Applications/A/2.0"])` returns back

`["Applications/B/1.0","Applications/A/2.0"]` without applying a sorting.

**Comment by CrossEye** [comment]
If something like that ever worked, it's mostly a coincidence.  `R.sort` requires a `comparator`, a function that returns a negative number, zero, or a positive number when the first number is, respectively, less than, equal to, or greater than the second one.  It's really only a thin gloss on `Array.prototype.sort`, simply cloning before sorting to preserve immutability.

`R.gt` returns a boolean, not a number.  Because of the way Booleans are translated to numbers, this will end up with a sort of reverse sort:

```js
R.sort(R.gt, [8, 6, 7, 5, 3, 0, 9]) //=>[0, 3, 5, 6, 7, 8, 9]
R.sort(R.lt, [8, 6, 7, 5, 3, 0, 9]) //=>[9, 8, 7, 6, 5, 3, 0]
```

But I would not want to count on this for anything essential.

If sorting has changed from earlier Node versions, I think it's that `sort` is now stable.  But that shouldn't matter at all if your data are strings.

You could write `R.sort(R.comparator(R.gt), yourData)` for code that should always work.

**Comment by acierto** [comment]
Thanks! Yes it was really working up to Node 10.x. 
Indeed make sense why actually it shouldn't work ;)

**Comment by CrossEye** [comment]
Again, this is because of how booleans are cast to numbers.

Think about a `bubblesort` function:   We repeatedly compare the first value with each of the subsequent ones, swapping when the other one is smaller than the first.  By the time we get through the whole list, we have the smallest one in the first position.  Then we do it again starting with the second one.  Then the third...

So if we try this:

```js
bubblesort((a, b) => a < b, [8, 6, 7, 5, 3, 0, 9])
```

the first thing our `bubblesort` would do is to call `(a, b) => a < b` with the values `8` and `6`.  That returns `false`.  But since `bubblesort` needs to use this as a number, it casts it to 0, which `bubblesort` treats as meaning that neither `a` nor `b` is smaller than the other.  So in this case, we would perform no swap.  We would proceed this way with `8` and `7`, with `8` and `5`, with `8` and `3`, and with `8` and `0`, making no swaps.  When we hit `8` and `9`, `(a, b) => a < b` is `true`.  That gets cast to `1`, which is interpreted as meaning that the second number is larger, and so it would swap them, leading to `[9, 6, 7, 5, 3, 0, 8]`, and we would proceed to compare the second value with each of the others, until we reach `[9, 8, 7, 5, 3, 0, 6]`.  And so on.

Now you could replace `(a, b) => a < b` with `R.lt` and have the same effect.

You could replace bubblesort with other sorting algorithms; the behavior might vary a bit, but it's quite possible that it would have this somewhat strange behavior.  But again, this is mostly a coincidence, based upon how JS converts booleans to numbers.  It's not something I would ever want to count on.

And it looks as though the latest Node has demonstrated why.
