### ISSUE TITLE
How to flatten the nested if statement by Ramda?

### ISSUE THREAD

**Issue by ianva** [ramda/ramda#2697]
The nested if statement like this.

``` javascript
if( isSth1() ){

  let a = doSth1();

  if( isSth2(a.p1) ){

    let b = doSth2(a);

    if( isSth3(b.p5) ){

      let c...
    }
  }
}
```

**Comment by CrossEye** [comment]
I don't know of any particular Ramda techniques to help with this.

The code as presented doesn't look to fit well with Ramda at all.  Ramda is trying to smooth the way to do more functional programming in JS.  That means programming with expressions, not mutating data, working with pure functions, etc.  

This looks likely to break several of these ideas.  For instance, `doSth1` is called with no parameters.  In the FP world that means that every time it's called, it would have the same result, and `a` would be unnecessary.  That means that the equivalent of `a.p1` would be fixed, and so on down the line.

But even if that is cleared up (perhaps by wrapping it in a function, and passing that function's parameters to `doSth1` to start things off), there is another serious issue.  You don't present any `else` blocks.  That means that this block cannot really represent an expression; the only useful things that can be done at the inner levels would be to create side-effects.  Ramda has little interest in those, and almost no appetite for making it easier to create them.

----------

Perhaps if you could explain a bit more about what you're trying to do, we could offer useful Ramda techniques.  But remember that Ramda is a library and not a framework.  You call Ramda functions; you don't fit your code into a "Ramda framework".  So it's designed to make a certain style of coding easier; it is not designed to tell you what to use and where.  And you can fit as much or as little of it as you like into your codebase.  It is not meant to tell you how to write your applications.

**Comment by Bradcomp** [comment]
From a functional programming perspective (beyond just Ramda), if the path has just the one branch (no `else` branches), this is a great opportunity to use `Maybe` to eliminate the nesting. If you have `else` cases to deal with you could use `Either`instead, but I won't demonstrate that because I'd need an example.

You can get an implementation of `Maybe` from `folktale` or `crocks`, or `Sanctuary` if you also want runtime type checking.

Assuming a basic implementation of Maybe, we can define this function, which probably exists in some form in the library we decide to use:
```
const fromPred = (pred, value) => pred(value) ? Just(value) : Nothing;
```

With that, we can start to rewrite the code:
```
R.pipe(
  fromPred(isSth1),
  R.map(doSth1),
  R.chain(fromPred(R.o(isSth2, R.prop('a')))),
  R.map(doSth2),
  R.chain(fromPred(R.o(isSth3, R.prop('p5')))),
  //...
)(null);
```

We have now flattened things. Note that if any of the predicates returns `false` we will just end up with `Nothing`.

Now that we have this much done, you can see that we have another duplicated structure:

```
const performSth = (pred, do) => R.o(R.map(do), fromPred(pred));

R.pipe(
  performSth(isSth1, doSth1),
  R.chain(performSth(doSth2, R.o(isSth2, R.prop('a')))),
  R.chain(performSth(doSth3, R.o(isSth3, R.prop('p5')))),
//...
);
```

Lastly, since we now have a `pipe` of `chains, we can use `pipeK` to factor out that part:
```
R.pipeK(
  performSth(isSth1, doSth1),
  performSth(doSth2, R.o(isSth2, R.prop('a'))),
  performSth(doSth3, R.o(isSth3, R.prop('p5'))),
//...
);
```

Of course, you could go further, using `pipeWith` instead of `pipeK` (not sure if it's released) to pull out the `performSth`, but I can leave that as an exercise for the reader.

**Comment by ianva** [comment]
Thanks for @CrossEye and @Bradcomp, I learn more for your answers.

I agree with @CrossEye the example is not fit. I just wanna flatten nested if statement because that make code unreadable.
But have some scenarios, we can do it.

@Bradcomp’s solution has more helpful. It solve the problem like 
if(isSth) => do(it)… , unless(isSth) => do Nothing…

Sometime we still need unless(isSth) return previous value.

I got the solution like

``` javascript
const listEx = [1,2,3,4];

const ifDo = ( cond, task )=> (value) => 
  cond(value) ? Either.Right(task(value)) : Either.Left(value);

const nif = (...args) => (value) => (
  args.length === 1
    ? ifDo(args[0][0], args[0][1])(value)
    : apply( pipeK,
        args.map(task=> ifDo(task[0], task[1]))
      )(value)
).value;

const result = nif(
  [pipe(length,gt(10)), append('t1')],
  [pipe(last,equals('t1')), append('next')],
  [pipe(last,equals('t2')), append('next2')]
)(listEx)
```

I have some questions about,
1. Why the pipeK must has more than two parameters?
2. What advantage dose R.o have that compare with R.compose?

**Comment by davidchambers** [comment]
I'll close this issue as there is no action to be taken, but feel free to post additional comments.
