### ISSUE TITLE
Simplifying a function

### ISSUE THREAD

**Issue by harrysolovay** [ramda/ramda#2712]
Let's say I want to simplify a function that returns whether a file exists in my root directory:

```js
const existsInRoot = fileName => fileExists(fromRoot(fileName))
```

Which uses:

```js
const {accessSync} = require('fs')
const {join} = require('fs')

const fileExists = path => {
  try {
    accessSync(path)
    return true
  } catch (e) {
    return false
  }
}

// and

const fromRoot = path => join(process.cwd(), path)
```

How would I go about simplifying my `existsInRoot` function with `curry` and `__`?

Could I do something to `fileExists` and `fromRoot` such that my `existsInRoot` function could look something like this?:

```js
const existsInRoot = fileExists(fromRoot)
```

Appologies if this is a newbie question. I really appreciate any and all help. Thank you!

**Comment by harrysolovay** [comment]
Also, why do I get the following error:

```sh
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at join (path.js:1157:7)
    at /Users/harrysolovay/Desktop/rescripts/node_modules/ramda/src/internal/_curryN.js:37:27
    at /Users/harrysolovay/Desktop/rescripts/node_modules/ramda/src/internal/_arity.js:6:19
    at Object.<anonymous> (/Users/harrysolovay/Desktop/rescripts/packages/utilities/config-loader.js:39:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

When running:

```js
const {curry, __} = require('ramda')
const {join} = require('path')

const fromRoot = curry(join)(process.cwd(), __)
console.log(fromRoot('package.json')) // error
```

(my guess is that join runs some validation on `__`... but shouldn't it only run the validation when the inner-curried function is called (aka, once the `__` is swapped out with a string)?)

Thank you so so much.

Kind regards,

Harry

**Comment by CrossEye** [comment]
First of all, while we don't mind answering questions like this here, both our [Gitter channel][gc] and [StackOverflow][so] are likely to yield quicker responses.  There are many helpful people able to answer in either place.

-----------
You can write `existsInRoot` like this:

```js
const existsInRoot = compose(fileExists, fromRoot)
```

While this is technically curried with Ramda (for some not-so-pleasant reasons!) it is a simple function on one parameter that should do what you want; the currying is mostly irrelevant.  Also, with unary function, Ramda's placeholder (`R.__`) is irrelevant.

Note that since you're using synchronous calls anyway, you don't need to write your own `fileExists`: `fs.existsSync` already does that.

------------

> Could I do something to fileExists and fromRoot such that my existsInRoot function could look something like this?:
> ```js
> const existsInRoot = fileExists(fromRoot)
> ```

I don't think that makes any real sense, not directly.  But using [`compose`][co] -- or the similar [`pipe`][pi] -- as above should do something like what you want.

-----------

This:

```js
const fromRoot = curry(join)(process.cwd(), __)
```
has several problems.  First of all, the placeholder makes no sense at all at the end of a list of parameters.  The whole point is to note the position of a missing parameter.  If it's at the end, it's not missing.   So `foo(a, b, __)` is no different from `foo(a, b)`, except for additional run-time overhead, nor is `foo(a, b, __, __, __)`.

Secondly, `path.join` is variadic (meaning it takes a varying number of parameters) and its `length` is `0`.  Ramda cannot curry it in any meaningful way.  While you could always curry a version like this:

```js
const myJoin = curry((prefix, suffix) => join(prefix, suffix))
```
there is no reason in this case, since you're hard-coding the prefix part:

```js
const fromRoot = (suffix) => join(process.cwd(), suffix)
```

  [co]: https://ramdajs.com/docs/#compose
  [gc]: https://gitter.im/ramda/ramda
  [pi]: https://ramdajs.com/docs/#pipe
  [so]: https://stackoverflow.com/questions/tagged/ramda.js

**Comment by harrysolovay** [comment]
@CrossEye thank you so much for the extremely helpful & detailed response. This is exactly what I need 💯
