### ISSUE TITLE
Ramda support freeze objects

### ISSUE THREAD

**Issue by retyui** [ramda/ramda#2714]
It would be great if you pass a frozen object, then in response you will also receive a frozen object.

```js
Object.isFrozen(R.assoc('c', '123', Object.freeze({a: 1, b: 2}))); // false
```

**Comment by retyui** [comment]
Your thoughts?

**Comment by CrossEye** [comment]
While I can see the appeal, I think there are several concerns:

  - Ramda does not mutate user data, but it doesn't go out of its way anywhere else to ensure that your immutable data is transformed into the same style.  If you used Immutable.js or mori, we do not try to ensure that you get back something of the same sort.  If you use `get` properties, we do not return an object with them.  I'm not sure I see why this would be different.  (But am willing to hear arguments for it.)

  - What would you do with multiple `Object`s, some of which are frozen and others not.  For example what would you expect from `R.merge({a: 1, b: 2}, Object.freeze({a: 10, c: 20}))`?

**Comment by retyui** [comment]
> What would you do with multiple Objects, some of which are frozen and others not

So, it’s hard to decide which solution is right.

Then it is better to use an explicit conversion to a frozen object:
```js
const freezeAssoc = R.pipe(
    R.assoc('c', '123'), 
    Object.freeze
)

Object.isFrozen(freezeAssoc(Object.freeze({ a: 1, b: 2 }))); // true

```

**Comment by CrossEye** [comment]
I believe this should probably remain in user-land.  There would be simply too many assumptions made by the library here.  @ramda/core: do you agree?

**Comment by Bradcomp** [comment]
I agree that Ramda shouldn't do this. I think that a userland solution is better. This same thing was discussed a little over a year ago too, see here for the previous discussion: https://github.com/ramda/ramda/issues/2238

**Comment by CrossEye** [comment]
@Bradcomp: Wow, how much I forget in sixteen months.  I had totally forgotten that conversation!

**Comment by rosedo** [comment]
Ensuring immutability is not easy:
- eslint-plugin-fp helps to avoid immutability in your own code, but doesn't prevent frameworks or libraries to mutate your objects (even if you want to allow that, you may want to forbid it until you know about it). Also, the no-mutating-methods rule would show an error for R.slice just because it is named slice.
- a library which maybe freezes input and returns frozen output does not allow frameworks to mutate (they mutate for a reason)
- there is performance cost in some (if not all) browsers and freeze is not supported in all browsers so you need some way to disable freeze in production
- Freezing objects one by one is not practical but it may help to do it during development and remove it later
- TypeScript support may be a pain: I actually prefer not to use the readonly keyword or the Readonly<T> utility type (and cast the result of freeze to the original type)
- seamless-immutable handles such problems but is kind of OOP and then if you mix in another library it will not behave the same way

I think ramda has a good approach of just saying "Functional programming is in good part about immutable objects and side-effect free functions. While Ramda does not enforce this, it enables such style to be as frictionless as possible."

I guess you could do something like `const icemap = fn => R.compose(Object.freeze, R.map(fn))`
and use it like this `Object.isFrozen(icemap(_ => _ * 2)([1, 2]))`

**Comment by CrossEye** [comment]
@rosedo:

I think that for those who want really frozen behavior, it would be quite trivial to write a wrapper which took Ramda and wrapped every function in one that used a recursive deep-freeze on their outputs.  This would expose an identical API to Ramda, but output only frozen objects.  It could even be swapped in and out for Ramda between development and production.  Kurt Milam made such a suggestion in https://github.com/ramda/ramda/issues/2238#issuecomment-315204534.  Anything further seems far from Ramda's core ideas.

> Also, the no-mutating-methods rule would show an error for R.slice

`Array.prototype.slice` is non-mutating.  Are you thinking of `splice`?

**Comment by rosedo** [comment]
@CrossEye Right so R.sort would be a good example. Also I just saw that the rule actually allows to exclude calling objects like `{allowedObjects: ['R']}`.

Wrapping R would be nice yes, maybe using Rolllup and selecting only the functions we really use.
