### ISSUE TITLE
deprecate R.F and R.T

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#2721]
Which is clearer, `R.T` or `() => true`? The latter is much clearer to me, as I understand the semantics without having to read documentation or source code to see how edge cases are handled.

**Comment by mattgrande** [comment]
I've started preferring `R.always(true)` to `R.T` for readability. I just don't want to have to scour my code looking for `T` and `F`!

**Comment by davidchambers** [comment]
Why `R.always (true)` rather than `() => true`, @mattgrande?

**Comment by CrossEye** [comment]
I really like `T` in `cond` statements, but that's the only place I use it.  (LISP is still a real influence on me!)

**Comment by CrossEye** [comment]
@davidchambers: Now that's a step too far!

**Comment by Bradcomp** [comment]
I don't have a strong opinion on this. I don't see us as really losing anything by dropping these functions. On the plus side it would free us up to add 1 letter combinators in the future if we ever desired, though I don't really see those as beneficial either.

**Comment by meszaros-lajos-gyorgy** [comment]
If I may add my two cents as a regular ramda user, the `() => true` code looks like an expression compared to `T`. When looking at `() => true` vs `T` I see the same dilemma as when comparing `{...a, ...b}` and `merge({}, a, b)` (see: https://stackoverflow.com/a/47684974/1806628). I like `T` and `F`, because I'm a lazy person and I like every option, which saves me from typing.

Regarding the deprecation of `cond`: would there be an alternative to that? There will be an _operator_ alternative to it, if the pattern matching proposal gets through (see: https://github.com/tc39/proposal-pattern-matching), but obviously that would not compose well with a purely functional context.

My final concern is the fact, that removing functions are breaking changes to the API. I know, that ramda didn't hit `1.0.0` yet, so the API is subject to change, but I'm literally getting afraid of upgrading ramda versions with all the recent api changes. For example 0.26 contained 2 API breaks: `contains` changed to `includes` and the parameter order for `adjust` have been flipped. While all tweaks gear the lib towards a better and more consistent API, needing to keep all these api breaking changes in mind, when working with older projects with _outdated_ ramda versions is hard.

**Comment by CrossEye** [comment]
@meszaros-lajos-gyorgy:

I personally don't think there's any likelihood we'll remove `cond` now.  I'm guessing that @davidchambers was at least partially offering that as a tease to me.

Note that your discussion of expressions versus functions is somewhat misleading.  `() => true` is an expression, true.  But it's an expression representing a function.  `T` is also an expression, one referring to a specific function. `1 + 2` is an expression representing the number `3`.  That `T` and `F` are very short and generally recognized names for the relevant functions is all that distinguishes them from their more verbose cousins.  I'm not strongly committed to either side of the question of dropping them, though.  I don't use them much, and would probably rewrite `T` or `alwaysTrue`  in my own code as needed if we did drop them.

`adjust` was definitely a breaking change.  Note that `contains => includes` was not, not yet, as we [kept the old function][re] as an alias for a deprecation period.  But breaking changes have finally settled down -- `0.25 => 0.26` was by far the longest between versions, and it had only the one breaking change.   That makes me much more confident that we can actually release 1.0 soon, as I've been trying to do.

> A possible solution for this would be, if there would be a `ramda-compat` or `ramda-migrate` repo with all the old and removed functions.

Can you suggest how that would work, and what it would mean specifically for `contains` and `adjust`?

  [re]: https://goo.gl/a6moSP

**Comment by meszaros-lajos-gyorgy** [comment]
I do agree, that the introduction of includes is not that big of an issue, since contains is kept alongside. I do prefer to remove deprecated functions from my code as soon as they get deprecated, but that is only a personal preference. The time between deprecation and removal is long enough for people to switch over from contains to includes.

The idea of `ramda-compat` comes from the `jquery-compat`, which was first created by the jquery team, because the browser detection feature was removed from version `1.9`. A lot of code did rely on `jQuery.browser`, so the jquery team moved that to a separate repo and kept moving removed features to that repo ever since.

`ramda-compat` would give home to `memoize` and possibly `contains` in the future. It could probably override the definition of `adjust` by flipping back the order of arguments to the pre 0.26 version. The `ramda-compat` lib would have to be included to one's repo along with the main `ramda` lib.

```
<!doctype html>
<html>
<head>
  <title>Ramda compat</title>
  <meta charset="utf-8" />
  <script src="http://somecdn.io/ramda.latest.min.js"></script>
  <script src="http://somecdn.io/ramda-compat.latest.min.js"></script>
  <script>
// possible solution 1:
const { memoize, curry } = R
...

// possible solution 2:
const { curry } = R
const { memoize } = R.compat
  <script>
</head>
<body>
  ...
</body>
</html>
```

Note, that ramda compat could work in 2 ways. It would either override/extend the original `R` object from ramda, or it would put all methods under a different key/different variable.

**Comment by CrossEye** [comment]
While that doesn't look like a bad thing to have, I have little interest in creating it.  This is especially true as it seems we would need to have a version of it for every release.  (You could include `ramda.compat.23`, `ramda.compat.24`, `ramda-compat.25`, in that order, to make sure your `v23` code will still run with the new features from the current `v26`.)

Is this something you feel like trying to create?  We would welcome a PR.

**Comment by def14nt** [comment]
@meszaros-lajos-gyorgy You could shorten that to this:

```js
const { curry, compat: { memoize } } = R;
```

**Comment by meszaros-lajos-gyorgy** [comment]
In my mind I see that as a separate repo. I could create a prototype and would happily help in maintaining it, but first I would love to get some feedback from others in the community to see, if they would use it.
You got it correctly, that the ramda and ramda-compat libraries would have to be kept in sync, so when a new version of ramda gets released, then ramda-compat also gets a new version.

**Comment by CrossEye** [comment]
I probably wouldn't use it.

I only update dependency versions on a project when there is a real need to do so, and then it usually means going through their changelogs anyway.  So it would not offer me very much.
