### ISSUE TITLE
Unexpected behaviour of R.curryN

### ISSUE THREAD

**Issue by mintuhouse** [ramda/ramda#2726]
`curryN` behaving strangely when the function passed to it is already curried

e.g1.  `R.curryN(2, R.nthArg(2))(1,2,3)` returns `3` instead of `undefined`

e.g2. 
````
const cf = R.unapply(R.sum)
const x = R.curryN(4, cf);
x(1,2,3,4,5) //=> 15 - instead of 10
````

**Comment by Bradcomp** [comment]
Hi @mintuhouse 

Thanks for your issue. `R.curryN` doesn't limit the number of arguments you can pass to a function. It just tells it how far you'd like to curry it.

You can use `nAry` to set a specific arity for a function, but be aware that can interact with currying as well. For instance, if you do `nAry(2, nthArg(2))` you will receive a function back instead of undefined.

```
const cf = R.unapply(R.sum)
const x = R.nAry(4, cf);
x(1,2,3,4,5) //=> 10
```

**Comment by CrossEye** [comment]
[`curryN`][cn] is not meant to limit arity, only to curry it in a way that **at least** `n` arguments are supplied.  It is really meant to help convert functions (like your `unapply(sum)`) which report arities less than the number you want them to have.

But it still supplies any additional arguments to the underlying function.

For alternatives, see [`unary`][un], [`binary`][bi], and the more general [`nAry`][na], which do limit the arities.

   [bi]: https://ramdajs.com/docs/#binary
   [cn]: https://ramdajs.com/docs/#curryN
   [na]: https://ramdajs.com/docs/#nAry
   [un]: https://ramdajs.com/docs/#unary

**Comment by mintuhouse** [comment]
That clears it. Thank you :)
