### ISSUE TITLE
Addition of 'then' function in 0.26.0 makes Ramda an incomplete thenable

### ISSUE THREAD

**Issue by tmcw** [ramda/ramda#2751]
Code to replicate:

```js
const R = require("ramda");
(async function() {
  return await R;
})();
// (node:46376) UnhandledPromiseRejectionWarning:
// TypeError: `then` expected a Promise, received function () { [native code] }
```

We’re running into this issue with Observable, in which we `await` library loads from dynamic `import()` calls, but it’ll also happen for anyone who’s using the `esm` module to do dynamic import() in Node.js now, and for anyone who uses Node.js dynamic import whenever they ship it. Here’s the dynamic import failure case:

```js
(async function() {
  const R = await import("ramda/es/index.js");
})().catch(e => console.error(e));
// TypeError: `then` expected a Promise, received function () { [native code] }
// at _assertPromise (/Users/tmcw/tmp/a/node_modules/ramda/es/internal/_assertPromise.js:6:11)
```

This code works properly in `0.25.0` and breaks in `0.26.0` and beyond, because `await` works like:

1. Await the imported code
2. Await the result of that import

Before, because Ramda was an object, the second await didn't do anything. Now, because it's a 'thenable object' - an object with a then method - `await` tries to await its eventual value and triggers the error.

---

I'm not a maintainer or contributor of this project, so my 2c on how to resolve this is likely to miss something - my only real guess for a solution would be to rename `then` to something else.

**Comment by CrossEye** [comment]
Uggh!!!

The whole point of adding `then` was to get us away from having to do anything important with Promises.

@Bradcomp, @buzzdecafe, anyone else in @ramda/core, any suggestions? 

I really, really, really hate Promises!

**Comment by Bradcomp** [comment]
Heh, that's pretty funny. Yet another example on how toxic Promises are to the ecosystem. 

I don't know much about dynamic imports, but it seems like it would be unnecessary for Ramda, given that all the exports are static. Can you provide a use case for `await`ing Ramda? I'm not suggesting this is a non-issue, I would just like some additional context.

Even though I was the one who created `R.then`, I think the best solution is just to remove the two Promise related functions and be done with it. It's clear that going down that path leads to heartache and pain, and it's plenty simple to re-create those functions in user space.

Maybe we should just add a section to the readme with reference implementations along with an explanation on why we don't recommend them. Or modify `map` and `chain` to dispatch to `then`.

> I'm not a maintainer or contributor of this project, so my 2c on how to resolve this is likely to miss something - my only real guess for a solution would be to rename then to something else.

You aren't really missing anything other than that it's really tough to come up with good names for things, especially when they are related to other things that already have names. We couldn't use `catch` for the failure case because it's a reserved keyword and had a big discussion on the name to choose instead.

**Comment by tmcw** [comment]
> I don't know much about dynamic imports, but it seems like it would be unnecessary for Ramda, given that all the exports are static.

Sure thing: if an application lazy-loads ramda. What people call [code splitting](https://webpack.js.org/guides/code-splitting/). So if you have a page deep in your application that needs to use Ramda, but you don't want to load Ramda as soon as someone loads the website. It's a common and very effective optimization.

**Comment by Bradcomp** [comment]
That makes sense. I knew about lazy loading but just didn't fully work out the implications for Promises. This is a bummer. 😢

**Comment by paldepind** [comment]
> I think the best solution is just to remove the two Promise related functions and be done with it.

I agree :+1: 

Due to the design of the promise spec it seems troublesome to add a `then` property to anything that's not a promise.

**Comment by evan-king** [comment]
Another options that I believe will read well (enough) in context is renaming `then` to `afterward`.

**Comment by foxbunny** [comment]
> Another options that I believe will read well (enough) in context is renaming then to afterward.

Or maybe call it `awkward` itstead, because that's what it is. :)

**Comment by CrossEye** [comment]
> Another options that I believe will read well (enough) in context is renaming `then` to `afterward`.

Or even `andThen` :smile:

**Comment by foxbunny** [comment]
@DeanBDean Here's a quote from @CrossEye from one of the promise-related issues:

> We've mostly been avoiding Promise-related functionality.
>
> Most regulars around here prefer Futures/Tasks and find Promises too difficult to think about.

**Comment by DeanBDean** [comment]
Thanks @foxbunny . Can one use Futures/Tasks with existing promise based libraries? Things like the aws-sdk or mongo support Promises. If this is a bigger question than I realize, then I understand not going into depth on it.

**Comment by DeanBDean** [comment]
@CrossEye Thanks so much, that is very helpful. I have been looking into Fluture, and they have something where you can "Fluture"ify a Promise, but I'm not sure what it's doing under the hood. Anywho, that's plenty to chew on, thanks for taking the time.

**Comment by sam-rad** [comment]
Is there anything I can help with publishing the `v0.27.0` to npm?
