### ISSUE TITLE
compose and composeWith have different signature

### ISSUE THREAD

**Issue by villesau** [ramda/ramda#2789]
Looks like [`compose`](https://ramdajs.com/docs/#compose) takes functions as an argument when [`composeWith`](https://ramdajs.com/docs/#composeWith) takes an array of functions. This is pretty confusing and some convention would really make sense here.

**Comment by CrossEye** [comment]
You're right.  Perhaps it was a mistake to introduce `composeWith` with the array signature.  But the goal is after v1.0 to move `pipe` and `compose` to match this, and to stop shipping any variadic functions.

So the fix for now will probably be in documentation.  Are you interested in creating a PR to document this?  (It would probably involve changing the JSDoc for `composeWith` and `pipeWith`.)

**Comment by villesau** [comment]
May I ask why is that the goal?

What comes to documentation, the behaviour is already documented in the examples. Or did you mean documenting the goal to move everything to use array syntax in 1.0?

**Comment by CrossEye** [comment]
I meant simply a note that said something like, "Note that this is subtly different from the signature of `compse`.  `composeWith` accepts an *array* of functions, not a `arguments` object full of them."

It's very hard to document variadic functions properly.  I'm not yet proposing that we disallow variadic user functions, although I hope that such use-cases will be rare.  But I would like it if all Ramda functions had fixed arities; this to my mind makes it easier to think about them.  (It should also clean up some implementations.)
