### ISSUE TITLE
R.reduce weird effect if curried

### ISSUE THREAD

**Issue by ThanosDi** [ramda/ramda#2798]
Having this code
```
const arr = [
	{
		'2019-02-01': 1,
	},
	{
		'2019-02-01': 1,
	}
];

const summarize = R.pipe(
	array => R.reduce(
		(acc, item) => {
			Object.keys(item).forEach(day => {
				acc[day] = R.propOr(0, day, item) + R.propOr(0, day, acc);
			});
			return acc;
		},
		{},
		array
	)
);

const sum1 = summarize(arr);
const sum2 = summarize(arr);
console.log(sum1);
console.log(sum2);
```

the expected outcome is as it should
```
{"2019-02-01":2}
{"2019-02-01":2}
```
REPL: https://goo.gl/TuNjyz

But removing the array on the first function of R.pipe
```
const arr = [
	{
		'2019-02-01': 1,
	},
	{
		'2019-02-01': 1,
	}
];

const summarize = R.pipe(
	R.reduce(
		(acc, item) => {
			Object.keys(item).forEach(day => {
				acc[day] = R.propOr(0, day, item) + R.propOr(0, day, acc);
			});
			return acc;
		},
		{}
	)
);

const sum1 = summarize(arr);
const sum2 = summarize(arr);
console.log(sum1);
console.log(sum2);
```
the outcome is
```
{"2019-02-01":4}
{"2019-02-01":4}
```
REPL: https://goo.gl/RCXLbf

I know I miss something here but I can't seem to grasp the reason behind.

**Comment by CrossEye** [comment]
The problem is that you're modifying an accumulator and then reusing it.

Best practice with Ramda, and with FP in general is to not modify such an accumulator but to return a new one with the changes applied.

The simplest change to your code that does this is probably to use `assoc`:

```js
const summarize = R.pipe(
  array => R.reduce(
    (acc, item) => Object.keys(item).reduce(
      (acc, day) => R.assoc(day, R.propOr(0, day, item) + R.propOr(0, day, acc), acc),
      acc
	),
    {},
    array
  )
);
```

This would allow us to replace `array => reduce(..., ..., array)` with `reduce(..., ...)`

Then, with a few more [steps of refactoring][rp], this might become

```js
const summarize = R.reduce(
  (acc, item) => Object.entries(item).reduce(
    (acc, [day, count]) => R.assoc(day, count + R.propOr(0, day, acc), acc),
    acc
  ),
  {}
)
```

(Note that the `pipe` is so far unnecessary, although you might still need it for additional processing.)

But I just want to note that I would write this in an entirely different manner:

```js
const summarize = pipe( 
  map(toPairs),
  unnest,
  groupBy(head),  
  map(map(last)),
  map(sum)
)
```

This style feels to me much more idiomatic for Ramda.


  [rp]: https://goo.gl/DA9MoF

**Comment by ThanosDi** [comment]
Thank you very much, that explains it perfectly!
Loved the pure functional approach in the end!

**Comment by Restuta** [comment]
I faced a similar issue and created an example [here](https://ramdajs.com/repl/?v=0.26.1#?%0Aconst%20buildRedfinAddressesIndex%20%3D%0A%20%20R.reduce%28acc%20%3D%3E%20%7B%0A%20%20%20%20console.log%28%27acc%3A%27%20%2B%20JSON.stringify%28acc%29%29%20%2F%2F%3F%0A%20%20%20%20acc.x%20%3D%201%3B%0A%0A%20%20%20%20return%20acc%3B%0A%20%20%7D%2C%20%7B%7D%29%3B%0A%2F%2F%0A%0A%0AbuildRedfinAddressesIndex%28%5B1%5D%29%20%2F%2F%3F%0AbuildRedfinAddressesIndex%28%5B1%5D%29%20%2F%2F%3F%0Aconsole.log%28%27done%27%29).

I am aware that I am mutating accumulator (becuase in the original code it was a performance optimization), but it still took me a while that curried function would capture "default" value in a closure as well, and that value is being mutated and then being re-used. 

I don't think there is an easy workaround to this, but maybe we should update docs pointing to this pitfal?

**Comment by CrossEye** [comment]
@Restuta:  Any suggested wording would be welcome.

**Comment by yanndebelgique** [comment]
Yes spent yesterday evening and today until now finding a bug due to this behavior. When working with Ramda , most of the time, you get side effect free pure functions when partially applying function. However when using R.reduce and partially applying it, you do not.
I would put a Note that partially applying R.reduce does not return a pure function. Or you could say that the accumulator should not be modified but instead it should be copied.
Illustrating the issue:
Current behavior
```
const make_dictionary = R.reduce((acc, element) => {
  acc[element] = element.toUpperCase()
  return acc
},{})

const a_dict = make_dictionary(['hello'])
console.log(a_dict) // {hello: 'HELLO'}

const another_dict = make_dictionary(['foo'])
console.log(another_dict) // {hello: 'HELLO', foo: 'FOO'} 
// whereas expected behavior (at least to me) would be  {foo: 'FOO'}
```

**Comment by CrossEye** [comment]
@yanndebelgique:

Yes, this is the same issue, and I don't think there's any realistic alternative.  Ramda is a fairly low-level library, and the thought of it cloning your accumulator inside a `reduce` seems quite the wrong direction for Ramda - even if we could reasonably do so.  If users do want to modify the accumulator as a performance optimization, it's hard to accept that Ramda will not let them do so; but I don't see any reasonable positions in between except the current one of "we won't mutate your data, but we won't prevent you from doing so."
