### ISSUE TITLE
Optional parameters and Curry don't mix well in Typescript

### ISSUE THREAD

**Issue by billewanick** [ramda/ramda#2809]
Hello Ramda Developers!
Apologies if this Issue is logged in the wrong repo. If you think it belongs to Typescript or DefinitelyTyped let me know and I'll create an issue there.

When using [Typescripts optional or default parameter syntax](https://www.typescriptlang.org/docs/handbook/functions.html#optional-and-default-parameters) and the curry function I get a Typescript error that says:
`Cannot invoke an expression whose type lacks a call signature. Type 'Number' has no compatible call signatures.ts(2349)
`

Reproducible Test Case: 
```
const add = (a: number, b?: number) => a + b;
const curriedAdd = curry(add);
curriedAdd(1, 2);
curriedAdd(1)(2);
```

Using Typescript 3.4.3 and Visual Studio Code 1.33.1 on Windows 10 I see the above error on line 4.
If I remove the *?* next to parameter b then the error goes away.

If I add `//@ts-ignore` above the offending line, the program runs correctly.

It looks like it happens because the parameter is optional and once you partially apply the function Typescript thinks all the required parameters are accounted for. So it thinks the return type of `curriedAdd(1)` is a Number, not a Curry function.

Not sure if this is an issue with the Ramda typings or with how VS Code is detecting the types, or if it's a Typescript problem.

I discovered this using R.flip with R.curry  and date-fns.addWeeks.
I noticed that R.flip turns a function with two required arguments into a function with the second (formerly the first) parameter as optional. I guess this is required for multiple argument functions but should it happen on functions with just two arguments?

**Comment by CrossEye** [comment]
I don't really know enough about Typescript typings to answer definitively.  They are maintained independent of Ramda itself.

But Ramda certainly will not work well with optional parameters.  That is by design, as optional parameters don't mix well with Ramda's currying.

So my guess is that TS is looking at `const add = (a: number, b?: number) => a + b;` as a function of only one parameter, so `curriedAdd(1)` will be `1 + undefined`, which is `NaN`.  That, confusingly, has type 'Number`.

Is there a good reason to include the `?`, making the parameter optional?  If so, it may simply not work well with Ramda, because Ramda won't know when you've supplied all the required parameters.

Sorry to not have anything more definitive.

**Comment by billewanick** [comment]
Thanks for the response!
I wasn't intentionally using optional parameters, but noticed that the R.flip typings list the second argument as optional. When I change the typings to not do that, everything works great.
I'll open up an issue with DefinitelyTyped and see if there's a reason behind this.

**Comment by millsp** [comment]
I wrote these typings. The typing malfunctions because it should not actually be possible to pass optional params to `curry`. `curry` cannot understand your intent in this case, will you choose to pass the optional parameter or not? `curry` can't know this. However, a case where this works - when you pass your optional parameter in the last curry step:

```ts
const addFourNumbers = (a, b, c, d = 1) => a + b + c + d;

const curriedAddFourNumbers = R.curry(addFourNumbers);
const f = curriedAddFourNumbers(1, 2);
const g = f(3, 4);
g; //=> 10
```

while this will fail:

```ts
const addFourNumbers = (a, b, c, d = 1) => a + b + c + d;

const curriedAddFourNumbers = R.curry(addFourNumbers);
const f = curriedAddFourNumbers(1, 2);
const g = f(3);
g(4); //=> fail
```

I will upgrade the types later this year to only allow this scenario.
