### ISSUE TITLE
R.complement not working on R.allPass / R.anyPass

### ISSUE THREAD

**Issue by MartinRamm** [ramda/ramda#2811]
I can't use a `notAllPass` function as shown in the code below.

While this makes sense when looking at the documentation of `allPass` (since it always returns a function), it feels unnatural to me, as I can complement almost all functions that (eventually) return booleans (except `allPass` and `anyPass`).

```
const fn = () => {};
const isFunction = is(Function);

allPass([isFunction])(fn); //true (as expected)
complement(allPass([isFunction]))(fn); //false (as expected)

const notAllPass = complement(allPass);
notAllPass([isFunction]) //false - expected function to be returned
notAllPass([isFunction])(fn) //notAllPass(...) is not a function - expected false to be returned
```

**Comment by diasbruno** [comment]
Hi @MartinRamm, 

The `complement` function expects a function that transforms a `value` into a `boolean`, and,
the function `allPass` expects a list of functions, and then, the value.

You would need something like stuff to make it work.

```js
const allPass2 = uncurryN(2, allPass);
// uncurry allPass to 'fit' on complement function
// allPass2([isFunction], fn);

const notAllPass2 = curryN(2, complement(allPass2));
// curry the complement, so it will expect to split the arguments into 2 functions

notAllPass2([isFunction])(fn); // false
notAllPass2([isFunction])(true); // true
```

It is necessary to curry the complement, because of [!fn.apply(this, [arguments])](https://github.com/ramda/ramda/blob/d6558dd2b8136af1ffcda4c9b4c54f14f27324f4/source/internal/_complement.js#L3), which would execute the function before you have a chance to pass the actual value.
