### ISSUE TITLE
Does ramda work with fluture-js?

### ISSUE THREAD

**Issue by nsinghal90** [ramda/ramda#2822]
R.chain doesn't resolve the Future. It just passes the future back.

<pre><code>import { Future } from 'fluture';
import * as R from 'ramda';
import Result from 'folktale/result';

console.log(
  R.chain(R.identity)
  (
    Future(
      (reject, resolve) => {
        resolve('future');
      }
    ).fold(Result.Error, Result.Ok)
  )
);
</code></pre>
Output
>Future {
>>  _spawn:
>>>   Future {
>>>>     _computation: [Function],
>>>>     context: { head: null, tail: [Circular] } },
>>  _actions: { 
>>>   head: { 
>>>>   mapper: [Function: f1],
>>>>   context: [Object] },
>>>     tail: { head: [Object], tail: [Object] } } }

Expected Output
> Result.Ok('future')

**Comment by Bradcomp** [comment]
Hi @nsinghal90, thanks for the question. Ramda works great with Fluture. The issue with your example is due to how Futures work. 

One difference between Futures and Promises is that Futures are lazy. In practical terms, nothing happens with a Future until one calls `fork`. So what you end up with is still an unexecuted Future, which is the reason for the weird output above.

You can take a look at the documentation for [`fold`](https://github.com/fluture-js/Fluture#fold) and notice that it still returns a Future, and thus does not run the computations.

Also, remember that due to the async nature of Futures, you can't just console.log the result. The result never gets returned to the calling code, but instead gets passed to one of the callbacks passed to `fork`. To get this code to log the result, you'll need to fork the future, passing in `console.log` as the callbacks.  You can read about consuming Futures [here](https://github.com/fluture-js/Fluture#consuming-futures).

```
R.pipe(
  R.chain(R.identity),
  R.fold(Result.Error, Result.Ok),
  F.fork(console.error, console.log)
)(F.resolve('future'));
```
