### ISSUE TITLE
Use many parameters in operator R.or

### ISSUE THREAD

**Issue by lhenriquegomescamilo** [ramda/ramda#2831]
Hello everyone, I'm beginning in use the Ramdajs and this is amazing lib to work with paradigm functional programming in JavaScript.

So I was using the operator R.or, but at the moment, the operator use only two parameters, for example:
```javascript
R.or(optionA, optionB);
```

I don't know if it's possible, but I think is a great feature, allow the operator R.or use the many parameters, for example:
```javascript
R.or(optionA, optionB, optionC, optionD, ...);
```

**Comment by CrossEye** [comment]
@lhenriquegomescamilo: Ramda avoids that sort of signature almost everywhere (I'm looking at you, `pipe*` and `compose*`!) for very important reasons.

Ramda is designed around function composition, and to support that curries pretty much everything.  But curried functions really don't work with variadic input.  So that's really not possible within the Ramda philosophy.

But it's very easy to wrap this in your own function:

```js
const orAny = reduce(or, false)
const andAll = reduce(and, true)
```

These take array of values.  If you really want that variadic signature, you can just add `unapply` (`unapply(reduce(or, false))`.)

**Comment by GingerPlusPlus** [comment]
`R.any`, `R.all`.
