### ISSUE TITLE
Feature Request - Adding removeOne function

### ISSUE THREAD

**Issue by Muhnad** [ramda/ramda#2843]
## Problem
We deal with a big amount of data ~3000 items and sometimes we need to remove a specific item from this array without worrying about items order. so using `R.remove` is not the best thing for removing one item from the list because the `remove` use `splice` and using `R.filter` also is not good so using `pop` is good for this big amount of data.

I run the [perf-test](http://jsben.ch/ZAuky) and using `pop` is good enough.

## Implementation
so I think so if we can implement a function called `removeOne` that takes index and list and replacing the index with a poping item that will be good for this purpose but we need to show an alert or something about using this function will make a change in the order of items.

```js
var removeOne = _curry3(function removeOne(index, list) {
  if (index >= list.length || index < 0) return; 
  var result = Array.prototype.slice.call(list, 0);
  var last = result.pop();
  result[index] = last;
  return result;
});
```

I didn't open a PR with the Implementation before taking a discussion about that.

**Comment by Bradcomp** [comment]
I think this is too special purpose for Ramda to implement. Because of its shortcut it becomes unusable on arrays where order matters, and leaves a trap for anybody who fails to read the documentation.

I would be more open to considering ways to make `remove` more efficient, but barring that I think you'd be better off just implementing that for your use case.

I have done some pretty big array crunching with Ramda, and there are some performance pitfalls to be aware of. Typically if I run into one I will write my own version that is specific to what I am trying to do, similar to this here.

**Comment by CrossEye** [comment]
I agree with @Bradcomp here.    This is too specialized for Ramda.

But I have no idea if our current `remove` is less efficient than it needs to be.  Would this be better?:

```js
(start, count, list) => list.slice(0, start).concat(list.slice(start + count))
```

**Comment by Muhnad** [comment]
I agree with @Bradcomp and I was thinking about that before opening the issue. but I opend the issue to maybe find a new way to deal with that or enhancing the current one.

@CrossEye the current remove is more efficient than the
```js
(start, count, list) => list.slice(0, start).concat(list.slice(start + count))
```

anyway, as @Bradcomp said sometimes you need to write your own version and that's what I did actually :D  

thanks, guys, gonna close it.

**Comment by CrossEye** [comment]
Thanks for testing.  It's good to know.  I actually left that comment there as a note to myself to check before publishing my comment, and then went ahead and published anyway!  One of those days...
