### ISSUE TITLE
Questions about Internal functions _equals

### ISSUE THREAD

**Issue by lilywang711** [ramda/ramda#2847]
Recently I was analyzing the internal code of ramda and I was a bit confused when I saw this `_equals` function.
ramda version: `0.26.1`

1、 What is the meaning of the following code?
My idea is that in the above[ two steps](https://github.com/ramda/ramda/blob/v0.26.1/source/internal/_equals.js#L35-L44), the null /undefined cases has been filtered out. Nothing will go to this step, so is the code here redundant?
source code click [here ](https://github.com/ramda/ramda/blob/v0.26.1/source/internal/_equals.js#L45)

```
 if (a == null || b == null) {
    return false;
  }

```
2、Why not put the code of the [fantasy-land specification](https://github.com/ramda/ramda/blob/v0.26.1/source/internal/_equals.js#L49-L52) or [self equals method](https://github.com/ramda/ramda/blob/v0.26.1/source/internal/_equals.js#L54-L57)  in the first step ?
My idea is that since the code caller follows the specification, it should first determine its specification, not [pre-processed](https://github.com/ramda/ramda/blob/v0.26.1/source/internal/_equals.js#L35-L43) by ramda.

3、Why not use the .then method (duck type)to decide if it is a Promise type ? like typeof obj.then === 'function'
[The Promises/A+ specification](https://promisesaplus.com/#point-53)

**Comment by CrossEye** [comment]
1. I think you're right here.  With `type` handing "Null"/"Undefined" separate from "Object", this seems unnecessary.

2. This is an attempt at an early escape.  I think it's justified.  If we know that `a === b` (and have dealt with JS's SameValue algorithm), then no further testing is necessary.  Someone who implements an `equals` which disagrees with this, already has serious issues.

3. Because despite what Promises/A+ wants to believe, not everything with a `.then` method actually is a Promise.  Ramda itself [was bitten by this][th] not too long ago.


  [th]: https://github.com/ramda/ramda/issues/2751

**Comment by lilywang711** [comment]
2 and 3  make sense, Thanks so much, that is very helpful. @CrossEye 
I will create a pr to remove the redundant code on Q1
