### ISSUE TITLE
Clone does  not do a deep clone

### ISSUE THREAD

**Issue by javahemans** [ramda/ramda#2850]
Steps to reproduce: 
1. Go to https://ramdajs.com/repl/?v=0.26.1 and open your developer console. 
2. Copy the below snippet and run it in console

```javascript
(() => {
     //
    let initialObj = [{
        attr1: 'value1',
        attr2: 'value2',
        attr3: 'value3',
        attr4: 'value4',
        attr5: 'value5',
    }];

    // the new constructed object
    let foo = {
        bar: initialObj[0],
        baz: initialObj[0]
    }


    let clonedFoo = R.clone(foo);

    console.log(clonedFoo);
    clonedFoo.bar[0] = 'valueChanged';
    console.log(clonedFoo);

})()
```

The expected behaviour: 

When the attribute(`bar`) of the cloned object(`clonedFoo`) is changed it will change the other attribute(`baz`) as well. While *deep* clone should be a complete new clone of the object...

**Comment by CrossEye** [comment]
Perhaps a simpler demo is this:

```js
let foo = {a: 1, b: 2}
let obj = {bar: foo, baz: foo}
console.log(obj)    //=> {bar :{a: 1, b: 2}, baz: {a: 1, b: 2}}
let res = R.clone(obj)
console.log(res)    //=> {bar :{a: 1, b: 2}, baz: {a: 1, b: 2}}
res.bar.a = 42
// Note that we don't change `res.baz` directly
console.log(res)    //=> {bar :{a: 42, b: 2}, baz: {a: 42, b: 2}}
```

I'm happy to hear your reasoning, but my first thought is that this is a feature, not a bug.

Note that now

```js
console.log(obj)    //=> {bar :{a: 1, b: 2}, baz: {a: 1, b: 2}}
```

So our `clone` call successfully divorced the new object from the old one.  What it also did is to preserve shared references, so that anytime the old object had two different nodes pointing to the same reference, the new tree has the equivalent nodes both pointing to a clone of that reference.

This is a stronger isomorphism with the original object, not a weaker one.  It is, I believe, impossible to be completely isomorphic (we can't, for instance, clone closures that might be incorporated into our objects) but getting closer is still an improvement.

It strikes me that the current behavior is what I'd prefer more often than not.   But I can certainly see that it could cause problems in some cases.  Why do you think this should be changed?  Do you have a convincing use-case?

**Comment by javahemans** [comment]
Thanks @CrossEye for your response. I spent a couple of hours debugging through a large codebase and at first, I never doubt that clone would not clone and preserve the reference. I went to documentation to make sure that it says it's a "deep" clone.

Because I was relying on clone function to do a "Deep" clone(copying values all the way through and not messing with references).  I mean most of the users will rely on the "deep" clone to be a complete copy of the values not reference? maybe? 

I would say what you are proposing is a different level of "Deep" clone...
A deep clone with shared references?  or a deep clone of an item that has no shared references?

Regardless, I found where was the problem and fixed the code 😂. But I believe if this is not going to change, it would be good to mention it in the documentation that it will not going to clone the shared references and include an example for it.

**Comment by CrossEye** [comment]
I share some of your reservations about the current behavior, but I'm afraid of the alternative.  And now I'm remembering the reason for this.  If we don't do this, we will lose the ability to clone cyclic structures.  Think about this:

```js
const x = {a: 42}
x.b = x

x.b.a //=> 42
x.b.b.b.a //=> 42

const y = clone(x)

y.a = 100

y.b.a //=> 100
y.b.b.b.a //=> 100

// but cloning has worked properly
x.b.b.b.a //=> 42
```

And cyclic structures come up far too often to ignore, I'm afraid.

----------

If you can suggest good wording for the documentation, I'd love to hear it.  I can see how this might bite someone.

**Comment by DanielRX** [comment]
Just adding a comment here, this is (to my mind) a deep clone, as it creates an object that matches the original object (including linked props), with no way to mutate the original.

If I _want_ references to be copied across, I can use clone, as I would expect, but if I had a "value only copy", then it would mean I would have to recreate any links that are needed (think DOM objects with references to the same prop from two button `onClick` functions or an AST object, with links to nodes duplicated when functions are used more than one).

A better way to describe the function may be "It creates an object that "can be used in place of the old object" without leaving any connection to the source object" as the key feature in my mind of a clone is being an exact structural copy (with links and loops) of the value I passed in.

I don't think my wording is perfect there but I feel the wording should describe more the relation between the two objects/values than the function itself in this case? Maybe this doesn't fit into the repository but @CrossEye, what do you think is the best way to document a function like this?

**Comment by CrossEye** [comment]
@DanielRX: Do  you feel like creating a PR for this documentation change?

Perhaps simpler might be that it "creates an object that can be used in place of the source object without retaining any references to it."

**Comment by DanielRX** [comment]
@CrossEye Sure, I will get onto that when I have a chance
Would a second PR (or combined into that one) be worth doing with a function to the tune of `cloneValues` which would behave like `clone`, but removing the structural links (if they exist)?

**Comment by CrossEye** [comment]
@DanielRX: That would definitely be a separate PR.  I'm not quite sure what it would entail.  How would it act on the structure [I described above][cy]?

  [cy]: https://github.com/ramda/ramda/issues/2850#issuecomment-503616972

**Comment by DanielRX** [comment]
@CrossEye I would say it would either: 

1. return `{a: 42, b: null | Error('Cyclic')}` (or some other magic value)
2. return `{a: 42}` (Remove all cycles). 
3. return `{}`, more akin to `R.tryCatch(JSON.stringify, R.always('{}'));`. 

All could be seen as valid since:

1. This case gives us the error location
2. This copies all "values" from a simple view (no loops or cycles)
3. There is a cycle, so it wouldn't be able to get the values directly (fail completely)

I think 3 has some value, since `cloneValues` makes no sense when talking about loops or cycles in objects, since they are infinitely large. Using 3 on a none - cyclic object would result in a full clone without structural links, which can sometimes be desired (since it would flatten out duplicate values if you wanted to separate them)

Given there are 3 cases, and that gives 2 cases that people may want but aren't covered, I'm not sure it would work to pick any of them

**Comment by CrossEye** [comment]
@DanielRX:

I agree that those seem the only reasonable answers.  But none really feels right to me.  `1` makes it very hard to compose the function, but `3` is an error that is hard to trace back.  And it's really hard to decide where to cut the links in `2`.  (Think of a doubly linked list pointing at `a`, where `a.prev` is `null`, `a.next` is `b`, `b.prev` is `a`, `b.next` is `c`, `c.prev` = `b`, and `c.next` is `null`.  this could end up as an empty object, as `a -> b -> c` with no `prev` links, or as many other structures.  Does our result depend on the lexicographic sorting of property names?  On the order properties were added to objects? Something else?)

Again, I'm willing to entertain discussion on this, and if you have an implementation you want to present, please feel free.  But I'm wary of this.

**Comment by DanielRX** [comment]
@CrossEye I added the doc change

So by "remove links" I realise now even that has two main forms

1. Remove both sides of the link (bad for most examples where the root object is referenced in the lower object)
2. Remove the link/loop when the same object is seen twice (This is then based not only on lexicographical sort but also on depth vs breath cloning)

It seems to me this is mainly an issue of "How would a looped object work?" but I think the question could be more "*Should* a looped object work, or should it be considered invalid input?" (much like your linked list would not be valid for `JSON.stringify`)

**Comment by CrossEye** [comment]
@DanielRX: I commented on the doc change.

Again, I'm willing to consider an implementation of this idea, but I'm still not convinced.  I imagine situations where `clone(foo)` and `clone(bar)` are perfectly fine but `clone({a: foo, b: bar})` would fail.  That seems to run afoul of the principle of least surprise.

**Comment by DanielRX** [comment]
@CrossEye Will get on that soon, I get that point, but when we have `cloneValues`, it's very much like
`toPaths(x) -> getValues(paths, x) -> fromPaths(paths, values)`, in this case, `toPaths(foo)` would make sense, `toPaths(bar)` would make sense, but `toPaths({a: foo, b: bar})` could be invalid due to the idea of the `paths` of the object no longer being valid (or no longer being finite).

**Comment by CrossEye** [comment]
@DanielRX: I look forward to seeing what you come up with.
