### ISSUE TITLE
Why isn't Ramda's cond curried? Is it supposed to be?

### ISSUE THREAD

**Issue by jktravis** [ramda/ramda#2859]
I have an array of predicate and transformer functions that I want to conditionally thunkify. I was thinking I could use a placeholder or `R.flip` `R.cond`, but it doesn't seem to be curried. 

```javascript
const renderThunkified = R.curry((fns, shouldThunkify, data) => {
  return R.compose(
    R.cond(R.__, data), // <== doesn't work
    R.map(([predicate, transformer]) => {
      if (shouldThunkify) {
        return [predicate, R.thunkify(transformer)]
      }
      return [predicate, transformer]
    })
  )(fns)
})
```

I'm just curious if it _should_ be, or if this was intentional.

**Comment by CrossEye** [comment]
The problem here is that `cond` can yield a function of any arity.  We could write, for instance,

```js
const smaller = cond([
  [(a, b) => a <= b, (a, b) => a],
  [(a, b) => a > b, (a, b) => b] 
])

smaller(3, 5) //=> 3
smaller(5, 3) //=> 3
smaller(4, 4) //=> 4
```

There are only a few functions like this, mostly ones that are designed not to create scalar values but do create functions, but for such functions there doesn't seem to be any good way to curry them.

**Comment by jktravis** [comment]
I see. Thank you for the explanation!
