### ISSUE TITLE
Enhanced ES6 import expression support for Code splitting

### ISSUE THREAD

**Issue by ashnamuh** [ramda/ramda#2861]
I think the following codes aren't cool.

```js
import pipe from 'ramda/src/pipe'
import find from 'ramda/src/find'
```

I hope:
```js
import { pipe, find } from 'ramda'
```

Do you have any plan for supporting this?

**Comment by CrossEye** [comment]
I usually use it the way you're looking for, generally with Webpack for front ends.  Where does it fail you?

**Comment by ashnamuh** [comment]
I am using Ramda with Vue&Nuxt project. I can't get code-splitted Ramda as i load individual functions with ES6 import. For example, i get too large-sized Ramda with `import { pipe, find } from 'ramda'`, over 500KB.

**Comment by ashnamuh** [comment]
Not Vue&Nuxt project only. The following code doesn't work as expected.

https://github.com/ashnamuh/try-something/blob/master/src/js/ramda.js

**Comment by Bradcomp** [comment]
This sounds like an issue with your compiler rather than a limitation of Ramda. Do you know what Nuxt is using for tree shaking?

In the [readme](https://github.com/ramda/ramda#usage) there is a section on how to best achieve small bundle sizes with Ramda. Have you taken a look to see if any of the examples pertain to your situation?

**Comment by ashnamuh** [comment]
I've read the README and use Manually cherry pick now. I should learn Nuxt's tree shaking build option if want to use ES6 import.

And as what you said it is not a Ramda issue.
