### ISSUE TITLE
Баран он и есть баран

### ISSUE THREAD

**Issue by glebfeklistov** [ramda/ramda#2864]
Why Bind is'n reversed? Why?

This, most simple and composible:

    map(model => pipe(
      pick(this.props.functions),
      map(Bind(model))
      )(model)
    )(models));

This is bad composition:

    map(model => pipe(
      pick(this.props.functions),
      map(value => bind(value, model))
      )(model)
    )(models));

`R.bind = R.flip(R.bind)` - maybe this correct solution?
Maybe write all function left to right stуle?

**Comment by CrossEye** [comment]
I don't know if there is a really strong argument for one versus the other.

I can just as easily imagine having a function I want to bind to various objects as I can imagine having a collection of functions I want to bind to a single object.  So when we order parameters from least likely to change to most likely to change, we don't have any real guidance.  At that point, I would go with the less important choice: put whatever seems most like out data object last.  That is the object rather than the function.

But note that the placeholder offers a fairly simple way to use it for what you want:

    map(bind(__, model))

----------

A side note: could you please change the issue title, translating it to English?  I'm afraid most of us don't read Russian.  (One semester 30 years ago didn't stick well for me!)
