### ISSUE TITLE
Enhance the trim()

### ISSUE THREAD

**Issue by lihroff** [ramda/ramda#2872]
Is there any work progress on enhancing the trim method？

`trim()` currently only cuts the whitespace. 

It's supposed to use like C# or Go that can return a new string in which all leading and trailing occurrences of a set of specified characters from the current String object are removed(It's maybe new API looks like `trimFix()`).

Examples:
```javascript

  R.trimFix('-', '---xyz---'); //=> 'xyz'
  R.trimFix('-')('---xyz---'); //=> 'xyz'

```

Discussion:
1. Is it necessary to introduce this feature?
2. The trim method needs to be reworked or a new API bring in?
3. what this new API looks like?

**Comment by CrossEye** [comment]
@Tommy-White:
My initial thought is that this is too much of a niche need to include in Ramda.  (Maybe that's because I don't think I've *ever* needed a function like this.)  Do you have any convincing argument in favor of it?

**Comment by Tommy-White** [comment]
Em, sorry for late🙈. 

I have encountered redundant characters when using regular replacement, and I would like to consider this way to solve(https://stackoverflow.com/questions/6784894/add-commas-or-spaces-to-group-every-three-digits/57140750#57140750), but recently I was wondering why I needed it, do I need to implement in another way?

I think one good point of Ramda is I may combine API for complex problems, but because Ramda is too purer and simple that I think it is difficult to extend the function in these scenarios.

**Comment by rohanjauhari13** [comment]
Hi, 
I would like to work on this issue #2872.

**Comment by CrossEye** [comment]
@lihroff:
While on vacation, I missed your response, only seeing this thread when @rohanjauhari13 chimed in.  Sorry.

>  but because Ramda is too purer and simple that I think it is difficult to extend the function in these scenarios.

That's pretty well by design.  The API is very intentionally designed to be simple: each function should do one thing and one thing only.  (That we use delegation techniques to allow a function to apply to multiple related types adds a twist, but does not contradict this; we only do this when we believe there is a common abstraction that the types share.)

While there is nothing wrong with the proposed function, I don't think it's at all what most JS users expect of a `trim` function.

I'm still not convinced that this belongs in Ramda.  But it could well go in the [Cookbook][cb] or one of the [extension][x1] [projects][x2].

@rohanjauhari13:

I personally am not convinced that this belongs in Ramda.  If you want to write an implementation, it could certainly be placed in the [Cookbook][cb], and perhaps the maintainers of one of the Ramda [extension][x1] [projects][x2] might be interested in including it.

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [x1]: https://github.com/char0n/ramda-adjunct
  [x2]: https://github.com/tommmyy/ramda-extension

**Comment by rohanjauhari13** [comment]
> Hi,
> I would like to work on this issue #2872.

@lihroff

**Comment by Powerplex** [comment]
Personally for me in JS trim() is only for whitespaces, otherwise I use String.prototype.replace() or R.replace() with a regex, it does the job.
```
const trimHyphens = replace(/^-*|-*$/g, '')

trimHyphens('----a-b-c---')
```

**Comment by lihroff** [comment]
I think this issue maybe close
