### ISSUE TITLE
CI - Continuous Deployment

### ISSUE THREAD

**Issue by hitmands** [ramda/ramda#2873]
Hi, 
I have seen that this project has a manual deployment system, 
and the CHANGELOG generation is still in a early stage.

Ramda is growing up so fast that might make sense to automate this project in the CI.

We could base the release process on the commitzen spec so that every commit on master (a merged pr) could lead to a new automatic deployment.

I'd love to submit a pr if this is of interest.

https://github.com/ramda/ramda/blob/301e46cea081aff78310f5ff597b72a732dcd7d5/.travis.yml#L1

**Comment by CrossEye** [comment]
What sort of deployment do you have in mind?

This is a library, not an application, and while we occasionally tag releases in GitHub, the only major deployment we do is on our far-too-infrequent releases, when we publish to NPM.  

I would love to automate as much of our process as we can, so I'm intrigued to hear what you're thinking about.

**Comment by hitmands** [comment]
> What sort of deployment do you have in mind?

By deployment I mean _publishing to npm_.

I would propose to have a ci in which, if a pr gets merged into master, we can automate:
1. building artifact
2. producing CHANGELOG
3. tagging github repository
4. publishing to npm

**Comment by CrossEye** [comment]
I'm afraid that I would want our releases to be better curated than that.  I definitely do not equate merging a commit with a branch being ready for a release.

Perhaps we can start working off a different branch and then do something like you suggest with `master`.  We will need to do so when we finally reach 1.0 in any case.  I have done so for some projects on my day job.  Is that what you're suggesting?

As to producing the changelog, do you have good examples?  I know a number of people pull their changelogs out of Git, but I've never really investigated how.  The [upgrade guides][ug] are time-consuming to create, but do make for an excellent way to present the information.  I doubt we can get automated output as nice as that.  But I'd love to be proven wrong.


  [ug]: https://github.com/ramda/ramda/issues?q=label%3A%22upgrade+guide%22

**Comment by hitmands** [comment]
I see your point, fair enough then :)

I work on a `master === release` fashion on my day work, but I see that is not the same everywhere. 

About the changelog, we use https://github.com/conventional-changelog/conventional-changelog and we are quite happy with it. It requires a curated commit policy by the way.

Happy for this issue to be cloesd!

**Comment by CrossEye** [comment]
@hitmands: Please don't think I was trying to shut down the conversation.  I would really like to find a way to automate some of this.  If we added a separate `release` branch and then did some cherry-picking or the like to update it from `master`, we might be able to achieve it.

As to conventional-changelog, that sounds like a tool better suited to a dedicated team rather than a loose group of volunteer contributors.  I can see the benefit, and may try to introduce it at work.  But I have a hard time imagining after a bunch of back and forth on the contents of a PR to then say, "Okay the code looks great, but now can you go format the commit message according to these guidelines?".  But perhaps it wouldn't be too hard to write a bespoke tool that generated our changelog format from a list of commits.  I'll think about it, but if anyone has some advice, I'm all ears.

**Comment by hitmands** [comment]
agreed, 
closing this issue for the time being, 
we can come up with something alike later on
