### ISSUE TITLE
tryCatch not working for promises

### ISSUE THREAD

**Issue by dteiml** [ramda/ramda#2877]
Hi,

I have code such as

```
const pr = timeout => new Promise((resolve, reject) => {
   setTimeout(() => {
      reject('Rejected')
   }, timeout)
})
const log = e => {
   console.log(`My error: ${e}`)
}
await R.tryCatch(async (timeout) => await  pr(timeout), log)(5000)
```

(This is all wrapped in an async function) Yet for some reason `log` is never called. 

What am I doing wrong?

Cheers

**Comment by dteiml** [comment]
Solved it by writing my own `tryCatch`:

```
export const tryCatch = R.curry(async (_fn, _log, _obj) => {
  try {
    return await _fn(_obj)
  } catch (e) {
    return _log(e)
  }
})
```

I'm guessing `R.tryCatch` isn't intended for Promises, only throws? Wouldn't it be better to expand its functionality, because most `.catch`es are for Promises imo.

Cheers

**Comment by Bradcomp** [comment]
Ramda has a somewhat complicated relationship with Promises. You can get some of the flavor here: https://github.com/ramda/ramda/pull/1869, and follow the links from there. 

You are correct that `R.tryCatch` is not set up to work with Promises. We currently have `andThen` and `otherwise` that deal with promises directly, as well as `composeWith` and `pipeWith` that can be leveraged to compose Promise returning functions. I am not sure if the team would be willing to add additional Promise support given the history.

**Comment by BravenxX** [comment]
I have the same problem. Working with promise in Ramda is so annoying.

**Comment by CrossEye** [comment]
> I have the same problem. Working with promise in Ramda is so annoying.

That's not particularly surprising given Ramda dislike-hate relationship with Promises.  But `andThen` /  `otherwise` should cover a *lot* of cases!

**Comment by jannala-hoxhunt** [comment]
Ramda `otherwise` function changes the return type of the `pipe` to the type that the `otherwise` returns. In most cases you don't have any kind of meaningful default value to use, and naturally the desired value is not available if the promise rejects, making the `otherwise` function completely unsuitable for the vast majority of async use cases.

**Comment by Jiia** [comment]
The Ramda `otherwise` function changes the return type of the pipe to the type that the `otherwise` function returns. In most cases you don't have any kind of meaningful default value to use, and naturally the desired value is not available if the promise rejects, making the `otherwise` function completely unsuitable for the vast majority of async use cases.
