### ISSUE TITLE
Feature request: isUndefined

### ISSUE THREAD

**Issue by olalonde** [ramda/ramda#2890]
There is `isNil` but It would be useful to have `isUndefined` for those cases where you want to distinguish `null` and `undefined`.  (example use case: `reject(isUndefined, obj)` to remove undefined props from object).

**Comment by CrossEye** [comment]
If you want to create a PR for this, I promise it will get a fair hearing.

But my first thought is that it's not a common enough requirement to distinguish `null` from `undefined` to include it in the Ramda core.  Perhaps you can convince me.

**Comment by kibertoad** [comment]
@CrossEye I can definitely come up with at least one use-case: for an example, `got` HTTP client handles nulls and undefineds differently: IIRC, it sends null as null, and breaks on undefined values, which resulted in us writing a custom reducer that removes all the undefined values, but keeps nulls. If we could use an existing function from Ramda, that would reduce amount of code we would need for that to happen.
In general I think that most common dichotomy in JS world is that `null` is an intentionally blank value, while `undefined` is something not initialized, and this distinction is often important for filtering purposes (e. g. you persist null values to remove data from DB, but ignore undefined ones).

**Comment by olalonde** [comment]
> you persist null values to remove data from DB, but ignore undefined ones

That was exactly my use case.

**Comment by CrossEye** [comment]
Again, if you want to create a PR, we will consider it.

I definitely agree with that distinction between `null` and `undefined`; it's how I often present the difference to folks.  I'm not convinced that this is either difficult to write as a custom function -- clearly it's not! -- or so extremely common that it really belongs in a utility library.  But I certainly could be convinced.

**Comment by kibertoad** [comment]
@CrossEye I believe there is one already: https://github.com/ramda/ramda/pull/2902
Most things are not difficult to implement, but having them in one place consistently is convenient. Also in this case implementation is neither large nor going to require much maintenance.

**Comment by kibertoad** [comment]
If there is something missing in PR above, I can address it.

**Comment by CrossEye** [comment]
@kibertoad: Sorry, I missed that.  I reopened that PR.

> Most things are not difficult to implement, but having them in one place consistently is convenient.

Many of the core team already consider the API to be bloated.  (Right @buzzdecafe?)  So there generally needs to be a compelling reason to include a new function.

Ramda's decisions are based on a few factors.  Functions that are not built in to the language and are more difficult for users to build themselves are more likely.  Ones that address very common needs are more likely.  Those that fit neither category are much less likely.  This is a hard call.  There are plenty of functions that were added to Ramda in its earlier days that would no longer make the cut, but we don't have any real process for removing them.  And of course all this presupposes that the function fits with Ramda's overall philosophy; not all proposals do.

While this function is a fine match with the philosophy, it doesn't seem either difficult to manage or all that common a requirement.

I don't have a major objection, exactly because I do agree with this:

> Also in this case implementation is neither large nor going to require much maintenance.

This small function would need little extra work.  It doesn't add much work for maintainers, and the additional bloat is small.  But still it's real; I think we'd need additional compelling arguments to include it.

**Comment by nfantone** [comment]
> (example use case: `reject(isUndefined, obj)` to remove undefined props from object).

Gotcha covered:

```js
reject(both(isNil, compose(isNaN, add(1)));
```

**Comment by kibertoad** [comment]
`reject(compose(isNaN, add(1));`

TBH, that is fairly difficult to read and has nowhere near the instant transparency of reject(isUndefined)

**Comment by nfantone** [comment]
🤦‍♀.

Yeah - it also doesn't work. Or was a joke.

Might wanna try `equals(undefined)`.

**Comment by customcommander** [comment]
Closing for now as there hasn't been much traction for this since then.
