### ISSUE TITLE
Feature: allow logic functions to call functions and pass value to them

### ISSUE THREAD

**Issue by Santinell** [ramda/ramda#2895]
It can be useful to combine several logic functions.
For example to filter array:

```javascript
const arr = [3, 8, true, 's', 'he', undefined, null, undefined];
const result = R.filter(
  R.or(R.is(Number), R.is(Boolean))
)(arr); // => [3, 8, true]
```
Function `R.or` could looks like:
```javascript
R.or = R.curry(function or(a, b) {
  if (a instanceof Function && b instanceof Function) {
    return function (v) {
      return a(v) || b(v);
    }
  }
  return a || b;
});
```

**Comment by CrossEye** [comment]
I'm assuming this was closed because you realized Ramda already has `or`, and also what you want here, `either`.  If not, well it does!  :smile:

**Comment by Santinell** [comment]
Yes, you are right, I have found `both` for `and`, `either` for `or`and `complement` for 'not'.
But I want to ask 2 questions
1) Why we need 2 almost the same functions?
2) Why `both`, `either` and `complement` and use only 2 arguments?
My variant:

```
function or (...args) {
  return function () {
    return args.some(v => R.is(Function, v) ? v.apply(this, arguments) : v);
  };
}

function and (...args) {
  return function () {
    return args.every(v => R.is(Function, v) ? v.apply(this, arguments) : v);
  };
}

function not (...args) {
  return function () {
    return !args.some(v => R.is(Function, v) ? v.apply(this, arguments) : v);
  };
}
```

And now you can check multiple logic conditions
```
const arr = [8000, 1, 2, 4, 0, -12, -6, null, {}, [], [1], {pi: 3.14}]
R.filter(
  R.or(R.isNil, R.and(R.is(Number), R.gt(R.__, 0), R.lt(R.__, 100)), R.isEmpty)
)(arr) // => [1, 2, 4, null, {}, []]
```

BTW it's strange to see that `R.gt` and `R.lt` using first argument as value.

**Comment by CrossEye** [comment]
@Santinell:

> Why we need 2 almost the same functions?

The most obvious ones, `and`, `or`, `not` are used for values:

```js
or (false, true) //=> true
```

The alternatives are used for functions that return values:

```js
const fn = either(x => x < 10, x => x > 20)
fn(7) //=> true
fn(13) //=> false
fn(29) //=> true
```

For the unary case, these could be implemented with `lift`, as `either = lift(or)`, `both = lift(and)`.  But these functions are polyadic.

> Why `both`, `either` and `complement` use only 2 arguments?

That's pretty much how Ramda works.  I'd love to fix the arity of the few remaining variadic functions, but that's a major breaking change, as it involves some of the most heavily used functions in the library, `compose` and `pipe`.

Because Ramda's currying is extremely important to its focus on compositional programming, we want our functions to be curried in a straightforward manner.  And there is no clear way to curry a variadic function.  The best I've seen would be to allow you to call it over and over with values, and then add an empty call to actually apply it.  This is not at all a comfortable API, and the other options I've seen have been worse.

That leaves us two choices: either use an array of values, forcing users to wrap their values in an array, or just using two.  There are problems with either:

  - If we accept an array the use cannot curry in any reasonable way.  She'd have to write a wrapper for the common case of two elements if she wanted that one curried.  

  - If we accept only two elements, and the user wants to supply many, we will have to supply her own wrapper to fold over the results.

We chose the latter.  It's trivial to write `all = reduce(and, true)` or `allPass = reduce(both, always(true))` (and in fact Ramda actually includes `all` and `allPass , etc.)  This makes it easy to build the array version atop the binary version.  The reverse it not as easy.


> BTW it's strange to see that R.gt and R.lt using first argument as value.

You're asking about things that have a long history of controversy in Ramda.  I'm afraid I don't have the strength to look up the references, as I will start re-reading all our old arguments and tedious discussions about them.  But if you search for "operator", you will find at least a dozen issues related to this.

Briefly, there is a serious tension between, for instance,

```
R.subtract(10, 3) //=> clearly should be 7
```

and 

```
const less3 = R.subtract(3)

less3(10) //=> we want this to be 7, but it's -7.
```

This is true for `gt` as well, and for any binary operator where `op(a, b) !== op(b, a)`.  We have never really found a solution we liked for this.

**Comment by Santinell** [comment]
Thanks for your answers, now I understand it more clearly.
