### ISSUE TITLE
R.difference throws error when argument is null/undefined

### ISSUE THREAD

**Issue by vwraposo** [ramda/ramda#2904]
`R.differrence` and `R.differenceWith` do not verify the arguments and tries to access the property length. 

```
R.difference(null, [1,2, 3])
> Cannot read property 'length' of null
```

I think they should handle it more gracefully, maybe treat `null` and `undefined` as an empty array.

**Comment by Bradcomp** [comment]
@vwraposo This is a deep issue, and there are different members of the team who have different ideas about how to deal with invalid input. 

`null` is not an Array, and `difference` expects Arrays as input. What should Ramda do in cases of invalid input.

* It could do type checking and throw helpful errors, similar to what a compiler does. This is the path that [Sanctuary](https://sanctuary.js.org/) takes.
* We could do something that 'seems' reasonable based on a best guess as to what the developer 'meant. This seems closest to what you are suggesting, but can lead to unexpected results and conflicts, see this: https://github.com/ramda/ramda/pull/2841
* GIGO - Garbage In Garbage Out. This means the function will treat input as though it's of the correct type, and if you pass in a bad value the behavior is undefined. This has typically been the preferred approach.

This thread: https://github.com/ramda/ramda/issues/1830 has some discussion from various members about the various approaches. There are other issues with extended discussions as well.

I think if you wanted to create a PR it would be given a fair shake, but you'll likely receive some pushback. Difference is a well known function with an understood domain and well understood behavior. Passing in null as a parameter is not a valid input to the function in any language, or as an input to the mathematical set operation it's based on.

**Comment by CrossEye** [comment]
Getting back to Ramda after a month away...

I agree with what @Bradcomp says here.  Ramda has generally adhered to a GIGO philosophy.

But we are willing to make exceptions when we can deduce the appropriate value asked by calling the function.  My favorite example of this is `propOr`  At one point this didn't return the default value when the object supplied was nil.  Here the user had clearly supplied the answer for when the object doesn't include the requisite property; that was the point of the function.  So it makes sense to fix it so that it does not error if the value is `nil`.  That's the current behavior.

It seems possible to me that this is a similar situation.  If someone wants to argue for that and create a PR, I'm all ears.
