### ISSUE TITLE
When to use R.always

### ISSUE THREAD

**Issue by tomdohnal** [ramda/ramda#2934]
Hi :)
I've been enjoying ramda a lot lately and would like to ask a question. When should I use `R.always`? Or if I put it in another way, using `R.always(something)` is equivalent to `() => something`, right? If so, why should I prefer using the former to the latter?

**Comment by CrossEye** [comment]
There is very little remaining rationale for `always`.  Ramda was started before the ubiquity of arrow functions, and it was definitely cleaner than `function() {return something}`.  Now, generally, the only normal use I see is when some code is otherwise point-free and it feels wrong to introduce a pointed function into it.  But it is more explicit than `() => something` or `_ => something`, or, worse, which I've seen `(x) => something`.  And one might still choose it for being that explicit.

There is certainly another possibility, one which I don't think I've ever seen in practice, but which I can imagine.  If the value passed to `always` is dynamically created, and then the function is supplied to another in a pipeline, then `always` without any parameters might still be useful:

```js
pipe (
    calcValue,   // :: a -> b
    always,      // :: Void -> b
    doSomething  // :: (c -> b) -> d
) // :: a -> d -- ignoring `c`.
```

I'm not immediately coming up with realistic scenarios for this, but they're certainly imaginable.

**Comment by tomdohnal** [comment]
Thank you very much for your detailed answer!
