### ISSUE TITLE
Could `chain(fn, m)` dispatch also to `m.flatMap(fn)`?

### ISSUE THREAD

**Issue by semmel** [ramda/ramda#2949]
Since [Array.prototype.flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) has arrived, one would perhaps expect that like `map`, `filter`, etc. `chain(fn, anArray)` dispatches to the native implementation `anArray.flatMap(fn)` as well?

That change would allow Ramda to work better on other types which still just expose a `.flatMap` method. ([Kefir.flatMap](https://kefirjs.github.io/kefir/#flat-map), [Bacon.flatMap](https://baconjs.github.io/api3/classes/observable.html#flatmap)). 

Though the latter is the actually the reason I am asking. Because I am too lazy to motivate to add a `chain` alias to those libraries. 🙄 

Of course it would break Ramda code which operates on a user type exposing a `.flatMap` which is not fantasy-land `chain`.

**Comment by CrossEye** [comment]
I'm mixed about this.  We haven't run into many problems with dispatching going too far -- #2223 is the only one that leaps to mind -- but it always could, and adding dispatch aliases would increase the chance of that.

But clearly it makes sense.  And there are others that would be more than reasonable:  `map`/`fmap`, and `reduce`/`fold`.  I'm not suggesting bringing back aliases for Ramda functions, only for their dispatching.

But I'm torn.

Do others have thoughts, @ramda/core?

----------

A side note: I'm very slowly working on another library, one that has a good chance of never seeing the light of day.  That one simply lets you declare types, and the functions that operate on them.  The API is still in flux, but it will probably end up something like this:

```js
const newLib = lib.addTypes([
  {
    name: 'Bacon',
    chain: (fn, val) => val.flatMap(fn),
    // ...
  }, //...
])
```

and you can choose to build your copy of the library with such types instead.  I really don't know if it's going anywhere, and clearly it's related in some ways to what Sanctuary and Bilby have done.  But I like playing with these things on my own.

**Comment by semmel** [comment]
@CrossEye The problem your "side library" addresses is really of great concern: It's tedious to write a static function collection - much like a [Static Land Module](https://github.com/fantasyland/static-land#how-to-add-compatibility-with-static-land-to-your-library) indeed - for every other useful type which only expose methods. But also for Static-Land-compatible libraries like [@most/core](https://mostcore.readthedocs.io/en/latest/) you then to need to switch between those static functions depending on the current type:
```javascript
import {map as mostMap} from 'most-core';
var incAllStream = Bacon.map(R.map(R.inc));
var incAllMStream = mostMap(R.map(R.inc));
var incAllPromise = R.andThen(R.map(R.inc));
incAllStream(Bacon.later(10, [1,2])) // -> B.Stream [2,3]
incAllPromise(Promise.resolve([1,2])) // -> Promise [2, 3]
// instead of
var incAll = R.map(R.map(R,inc))
```
With such an API as you laid out, it's the decision of the user if he/she want's e.g. Promises treated as monads.

I am curious how you plan to do type inspection on third-party objects in order to select the proper function from the API? 
I've found `Object.prototype.toString.call(obj)` quite useful to distinguish between Promise, String etc. However the third-party type then must comply and implement [[Symbol.toStringTag]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag)

**Comment by CrossEye** [comment]
@semmel:

This library is only a handful of snippets beyond vaporware.  But I've been thinking about it for several years, and am hoping to start putting it together in the next few weeks.

This is the basic idea:

```js
const newLib = lib.addTypes([
  {
    _name: 'My Type',  // possibly with some sort of namespacing: 'myTeam/project/type'?
    _extends: 'Other Type' // same namespacing considerations.
    _test: /* a unary predicate */, 
    map: /*implementation of map*/,
    filter: /*implementation of filter*/,
    // ...
  }, //...
])
```

I will probably change that from a flat object to one in which the type functions are separated (and possibly grouped by typeclass) and the metadata doesn't need the underscore prefixes.

`_test` is required: this is how you tell me that a value is of your type.  `_extends` of course allows for a hierarchy; that would be used to sort the test invocations, so that I test `Array of Integers` before `Array of Numbers`, which I would test before `Array` to find the matching function.

There will also be an `addTypeclass` method.  Modules can be reopened, so you can add a function to, say, Arrays, although someone else created the main module for them. I haven't figured out the syntax for that yet.

This certainly overlaps a great deal with StaticLand.  When it came out, I put this aside for a long time.  I think it might have some advantages, but as much as anything, I simply like to try building out things myself.

**Comment by Bradcomp** [comment]
> Since Array.prototype.flatMap has arrived, one would perhaps expect that like map, filter, etc. chain(fn, anArray) dispatches to the native implementation anArray.flatMap(fn) as well?

To the best of my knowledge, map and filter don't actually call the Array native methods. I support dispatching to flatMap, but I don't think we should be doing it for native Array, only for custom types that have `flatMap` defined but not `chain`.

**Comment by semmel** [comment]
@Bradcomp 
> I don't think we should be doing it for native Array...

Is that because of the extra arguments (index and array) in the native callbacks? I was not suggesting to change the signature of map of course.

It‘s just that looking at the source code, it (perhaps wrongly) appeared to me that dispatching to one of the possible methods does not depend on the type but only on the presence of such a method. Thus dispatching to flatMap would include native Array as well. So I may have stated my issue backwards: Array.flatMap was just an argument for dispatching to flatMap in general.

**Comment by Bradcomp** [comment]
See here: https://github.com/ramda/ramda/blob/master/source/internal/_dispatchable.js#L26

Because `map` et. al. on the native Array aren't lawful / aren't performant / are known entities on a native type we don't actually dispatch to them but allow for our own implementation. 

Given how dispatchable works I would think that if we added a dispatch to `flatMap` it should be fine - the check in dispatchable would just cause it to use the current `chain` implementation.

**Comment by semmel** [comment]
@Bradcomp 
Thanks for the reply, I see now that `Array` is exempt from dispatching.

That's ok - however it just should not be justified for the wrong reasons. I doubt that `Array.map` and `Array.flatMap` are *in general* "not performant".

I did some [naive tests](https://jsitor.com/D6vF6QBw2) on my local machine with browsers and the result is not clear cut.

µsec / iteration  (size = 10e+6)    |  `Array.flatMap` | `R.flatMap` | `Array.map` | `R.map`
------------------|--------------------------|-------------------|-------------|---------
Firefox*   | 0.06 | 0.2  | 0.01    | 0.01
Chrome  | 0.6   | 0.22 | 0.025 | 0.014
Safari      | 0.04 |0.06 | 0.007 | 0.005
iOS13**   | 0.36 |0.56 | 0.05    | 0.013

\* `privacy.reduceTimerPrecision=false`
** size = 10e+5

Obviously this is not benchmark code and memory effects may have an effect, but it's just Chrome where loops outperform the native `.map` implementations.

**Comment by Bradcomp** [comment]
Looks like native `map` is at least as slow as `R.map` in all instances here, in most cases being slower, though only a little bit so. I'm surprised you mention Chrome but not iOS, where the difference between native and Ramda is greater than it is in Chrome, unless I am misreading something. 

I have no experience with the native `flatMap` so I don't want to comment on performance there. I still think that if we know what a type is and how it's supposed to implement the function it's better to rely on our own stable implementation rather than make it dependent on the browser.

**Comment by semmel** [comment]
I'd like to retract my proposal of making `R.chain(f, m)` dispatch to `m.flatMap(f)`, and close the discussion with a summary:

- If `m` is an `Array` there are no reasons (e.g. performance) to switch to the native `.flatMap` implementation.
- For other `m` types I *now* consider the danger of unintended `.flatMap` calls greater than the benefit of using Ramda's `chain` instead of my own stupid wrapper function.

The second problem is addressed in Ramda since ever by dispatching to FantasyLand. When a library does not expose `chain` or `flatMap` through the FantasyLand interface, I'd recommend a stupid wrapper. 
When using StaticLand libs you'll need to import their `chain` method anyway:

```javascript
import {chain as chain_mst} from '@most/core'; // StaticLand lib
const chain_bacon = curry((f, m) => m.flatMap(f)); // stupid wrapper
import {chain as chain_arr} from 'ramda'; // just for Array or FL as usual
```
