### ISSUE TITLE
What should I use insted of intersectionWith?

### ISSUE THREAD

**Issue by mentaal** [ramda/ramda#2951]
I am new to JS and ramda and coming from Python where I'm used to the set semantics there. 

I have a problem where I have xs = [ [a,a] ] and ys = [ [a,a] ] and I want to get a new array with the intersection of these two lists. For example, `xs = [ [0,1], [1,1], [1,2] ]` and `ys = [ [0,1], [5,6] ] and the result should be zs = [ [0,1] ]`

When perusing the docs, I can see functions such as `difference` and `differenceWith`. Because of these and set semantics in JS I immediately looked for `intersectionWith` as the logical solution for this problem. I see that there was once an intersectionWith but it's deprecated in favor of `innerJoin`: #1868.

One observation I'd like to point out from the perspective of someone new to this library (and JS and FP in general) is that the API is not consistent. I would expect to see an intersectionWith because there is a differenceWith etc. 

Additionally, `innerJoin` doesn't provide the same semantics as `intersectionWith` because duplicates are not removed.

That aside, what would the recommended canonical way to resolve this look in Ramda? Would I need to deduplicate xs myself prior to using innerJoin?  If so, how should I do that? Does rambda provide any functionality for removing duplicates (when array elements are not primitives). I didn't see anything in the docs that would help me here. 

To rephrase, this trivial problem doesn't seem to have a trivial solution which leads me to think I am missing something obvious or going about it the wrong way. Any help here would be greatly appreciated. Thanks

**Comment by CrossEye** [comment]
I can't recall all the reasoning that went into changing `intersectionWith` into `innerJoin`, but you're right that we lost some useful consistency when we did so.  I might look at whether it's worth reverting that.

But Ramda focuses on value equality rather than reference equality, so for your problem, you should be able to simply use `intersection`.

**Comment by mentaal** [comment]
Ah yes, `intersection` works just fine for this as you say. Thank you for the prompt reply and the solution. 
I actually hadn't tested intersection before asking this question. I had naively assumed it was using object reference comparison and that the `With` version was providing the alternative.

**Comment by Bradcomp** [comment]
The issue with `intersectionWith` is that it was inconsistent in one way, and then in another.

Originally the issue was that there were a lot of cases where `intersectionWith(f, a, b) != `intersectionWith(f, b, a)`. This was because there was no guarantee that a and b contained the same type. The algorithm picked from the first Array, but if the types were different then the result could be wrong. 

As a performance improvement to a number of functions we made an optimization to always iterate over the smaller Array. Of course this fixed the initial consistency issue but created another (Result depends on the size of the Arrays).

The issue is that intersectionWith has one clear use case (improving performance where full object equality is too slow) but can also be used in another way (select all items in one array that 'match' the items in the second Array). In the first case neither issue comes up but the second use case will reveal all of those inconsistencies. 

I don't recall the exact thread but eventually we decided deprecation was the clearest alternative. If we want to bring it back (which I am not fully opposed to) we really need to work out the semantics so that we don't end up creating subtle bugs in people's code.

**Comment by mentaal** [comment]
On the topic of performance, `intersection` for the use case I mentioned above is very slow indeed. I have two arrays consisting of about 20000 elements each and I gave up with `intersection` after a few minutes and it hadn't completed.

I rolled my own naive `intersectionWith` which completed in a few seconds. 
It's full of holes in terms of error checking but it got me out of dodge:

```javascript
const intersectionWith = R.curry((hash_func, a, b) => {
    const smaller = a.length < b.length ? a : b
    const other = Object.is(smaller, a) ? b : a
    const m = new Map()
    for (const e of smaller) {
        m.set(hash_func(e), e)
    }
    const res = []
    other.forEach((v) => {
        const k = hash_func(v)
        if(m.delete(k))
        {
            res.push(v)
        }
    })
    return res
})
```

**Comment by CrossEye** [comment]
That slowness is a major part of the reason for the existence of some of these `*With` functions.  Since we're testing using value equality, we have to depend on `equals`, which due to its general nature is going to be slow.  I see no way around this.

**Comment by Bradcomp** [comment]
@mentaal I find that if you're working with large datasets it can help to use Ramda to prototype and then roll your own functions for performance bottlenecks. The set operations in general (as well as some of the less used functions like `traverse` or `sequence` have certain limitations that prevent them from being performant in the general case.

Can you use ES6 sets? It looks like you have a solution there that works so I wouldn't worry too much but it may be worth looking into.

@CrossEye I agree that we need to have the `with` functions working for all the operations. Do you have an idea for how to resolve the issues above? I also think we may be able to improve our algorithms to possibly reduce the n^2 run time we have right now.

**Comment by mentaal** [comment]
Perhaps it's because I'm still fairly new to JS but I don't see how ES6 sets will help me here because they only allow you to store primitives or object references. In my mind this limits their usefulness quite a bit. Maybe I'm just spoiled by Python's primitives!

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set): 
> The Set object lets you store unique values of any type, whether primitive values or object references.

Yes indeed, I can roll my own and I agree that in general, bottlenecks may require custom solutions to eek out better performance. However, I contend that datasets in the order of tens of thousands shouldn't be considered large at all. I quite like Ramda and the functionality it provides though I'd worry that such performance would deter any newcomers to the library or prevent its application in many cases.

**Comment by CrossEye** [comment]
@Bradcomp: I'd love to hear your ideas on this.  It seems to me that many of these are not resolvable unless the user can tell us more about her data -- a hash function, a binary predicate, something.  If not, I can't think of anything that's not `O (m * n)`.

I think it might be beneficial to restore `intersectionWith`, with the optimized behavior of picking from either set based on size, but also retain `innerJoin` -- under that or another name -- that is fixed to picking from, say, the first one.

@mentaal: I don't see a good way around this.  JS is far from the fastest language around, and two datasets with 32K elements each will involve testing one billion pairs for deep equality.  That's a lot of work, and it's why we have `*With` functions. 

If you want a value-equality based `Set` instance, you might look to Ramda's internal one: https://github.com/ramda/ramda/blob/master/source/internal/_Set.js

**Comment by mentaal** [comment]
@CrossEye do you mean without restoring `intersectionWith`?

The semantics I used in my toy example above are different in that I had the function accept a hash function instead of a binary predicate but it seems to be reasonably efficient and looks like O(m + n) to me. What about adopting such an approach where equality is done on hashes?

**Comment by CrossEye** [comment]
@mentaal: I meant that I don't see a good way around the inherent slowness of things like `intersection`.  Obviously a version with a binary predicate would still be `O(m * n)`, but the assumption is that the predicate is *fast* unlike general equality testing.  And with a hash, things could be much quicker still, approaching `O(m + n)`.  But unless the hash is guaranteed unique, there would still need to be another mechanism to settle clashes.

The issue is that `intersection` is meant to be generic.  Other similar functions such as a reconstituted `intersectionWith` or perhaps a hash based version allow the  user to hint enough to make the functions efficient.

**Comment by mentaal** [comment]
@CrossEye thanks for the clarifications.
