### ISSUE TITLE
Questions about curryN.js

### ISSUE THREAD

**Issue by Alizwell** [ramda/ramda#2952]
https://github.com/ramda/ramda/blob/bd1172e8bc8f5825cf86cb14de11e8e485aba6e8/source/curryN.js#L53
What's the purpose of function _arity  here, Why not:
``
return _curryN(length, [], fn);
``
I have made this change locally, and I didn't find any difference.

**Comment by CrossEye** [comment]
It does look unnecessary, although I haven't had time to test.

We use `_arity` to remain good neighbors with any other libraries that might use a function's `length` property for its own purposes.  Thus, when we know how many arguments are expected from a returned function but the implementation would return something different, we wrap it with `_arity` so that the function itself reports that.

But in this case, the internal `_curryN` already calls `_arity` on its output, so it looks to me at a quick glance that we could just drop it altogether.

Would you be interested in creating a pull request to fix this?

**Comment by adispring** [comment]
https://github.com/ramda/ramda/blob/bd1172e8bc/source/internal/_curryN.js#L16

The internal `_curryN` does not call `_arity` on its output, so if not wrap the output of `_curryN` with `_arity`, the curried function returned by `curryN` will lose its length.

**Comment by Alizwell** [comment]
> https://github.com/ramda/ramda/blob/bd1172e8bc/source/internal/_curryN.js#L16
> 
> ```js
> export default function _curryN(length, received, fn) {
>   return function() {...}
> }
> ```
> 
> The internal `_curryN` does not call `_arity` on its output, so if not wrap the output of `_curryN` with `_arity`, the curried function returned by `curryN` will lose its length.

Yes, you are right.

**Comment by Alizwell** [comment]
> It does look unnecessary, although I haven't had time to test.
> 
> We use `_arity` to remain good neighbors with any other libraries that might use a function's `length` property for its own purposes. Thus, when we know how many arguments are expected from a returned function but the implementation would return something different, we wrap it with `_arity` so that the function itself reports that.
> 
> But in this case, the internal `_curryN` already calls `_arity` on its output, so it looks to me at a quick glance that we could just drop it altogether.
> 
> Would you be interested in creating a pull request to fix this?

Thanks for your detailed explanation. It's my fault, with the change locally and runs the built-in test, you can find the difference.

**Comment by CrossEye** [comment]
Ahh, I was looking (too quickly, I knew even then) at https://github.com/ramda/ramda/blob/bd1172e8bc/source/internal/_curryN.js#L39
