### ISSUE TITLE
Is it right for other projects to "advertise" in the wiki?

### ISSUE THREAD

**Issue by customcommander** [ramda/ramda#2961]
Hi all,

(This is a follow up to a post of mine in Gitter)

I've noticed quite a few links in the Cookbook about how other projects would do _X_, _Y_ or _Z_ and was about to remove them but then realised that it isn't necessarily for me to make that call. 

There's already a [related projects](https://github.com/ramda/ramda/wiki#related-projects) section. Isn't that enough?

My main motive is to try to keep the Cookbook relatively "clean"; in some areas it is a bit dense and confusing.

Quite frankly I can't help thinking that  sometimes this is just irrelevant content. When I peruse the PHP documentation I don't want to be reminded all the time how one would do the same thing in Ruby for example.

What is the feeling among the project maintainers and the community at large?

**Comment by semmel** [comment]
When I find a function in the cookbook and I see that it is part of ramda-adjunct
- I am assured that, more other people solve similar problems also using this approach.
- That function is tested and maintained over in ramda-adjunct so in case of an error I could go there and file an issue.

But maybe ramda-adjunct is not what you meant  to remove?

**Comment by CrossEye** [comment]
My feeling is that this is perfectly fine.

The Cookbook started as a way to include functions that, while useful, weren't common enough to justify being put in the main library.  Other libraries such as ramda-adjunct grew out of the same need, but with the idea of providing them in a library instead of cut-and-paste recipes.  They are complementary approaches, and if our Cookbook can point to other helpful resources for this data, that's all to the good.

The same is true for entries like [inspect][in], which started as a Ramda issue, with an interesting story about why the function was useful to @icylace.  It did not appear to be an essential Ramda function, but it was certainly worth putting it in the Cookbook.  Months later, @icylace created a [separate repo][il] around it, one which would later grow to include more functions.  While it's still worth keeping this in the Cookbook, I think linking out to a tested, maintained version is quite helpful.

Part of this, though, is that I feel little sense of competition here.  Ramda was written to scratch our own itches.  While it's been extremely gratifying to see how many others find it helpful, we did not set out to build the next Underscore.  I think about Ramda from a user's perspective, mostly, not a maintainer's.  If the Cookbook can help me find an external implementation of a function I need, that's great.

  [il]: https://github.com/icylace/icylace-object-utils/tree/25480840c6d8f76abf6162498a471203e2230679
  [in]: https://github.com/ramda/ramda/wiki/Cookbook#inspect-use-a-spec-to-get-some-parts-of-a-data-structure
