### ISSUE TITLE
memoizeWith's cache may eventually lead to stack overflow?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2965]
`memoizeWith` will cache all the processed results, the cache may grow indefinitely, and lead to stack overflow eventually.

Should `memoizeWith` be optimized with some strategies, such as LRU Cache or something else?

**Comment by CrossEye** [comment]
I'd much rather simply remove the function.

I've come to feel that it's not really a match with Ramda's philosophy.  I hesitate only because I would find the need to write custom versions on a fair number of occasions.  I'm guessing others would as well.

As to adding some cache-invalidation strategy, I'd be nervous.  Ramda spends a lot of time worried about naming things.  And of course it's [well known][pk] that "*there are only two hard things in Computer Science: cache invalidation and naming things.*"<sup>1</sup>.  I'm really not sure that Ramda wants to get involved with this other hard thing.

I'm half-joking, of course.  If we're going to have this function, perhaps such a strategy makes sense.  But I really don't know how we could comfortably support it.  While we hope that user uses `memoizeWith` only with referentially transparent functions, we can't enforce that.  If they use it, for instance, to store references to DOM nodes that are later deleted from the DOM but which still contain metadata they want to access, then we'd break an application by clearing the cache. 
 Or if someone uses the memoization cache to precalculate the hard parts so that when their user asks for them, they're readily available, an ill-timed clearing of the cache could slow their application unacceptably.  Moreover, most cache-invalidation techniques are configurable in various ways; it strikes me as a nightmare to try to support that in a Ramda-friendly way.

Still, the number of small and large improvements you've made to Ramda makes me wonder if you're onto something.  Do you have any thoughts on how it would work?  Would there be any manual way to invalidate the cache?  Do users have to opt in or out of it?  And of course, do you have a proposed implementation?

----------
<sup>1</sup> Or my favorite variant: *There are only two hard things in Computer Science: cache invalidation, naming things, and off-by-one errors.*


  [pk]: https://martinfowler.com/bliki/TwoHardThings.html

**Comment by adispring** [comment]
Sorry, I haven't found any efficient way to implement it.  

[lru-cache](https://github.com/isaacs/node-lru-cache) is one related library, but it is more like a library than an Api, and it is time-related, not match Ramda's philosophy.

**Comment by CrossEye** [comment]
@adispring:

I just want to make sure that this was not triggered by an actual production problem with this function.  It's pretty clear that you sometimes look through the source code noting potential problems, which is wonderful.  But if this started because it caused you a real-world problem, I'd really like to know.

**Comment by adispring** [comment]
> I just want to make sure that this was not triggered by an actual production problem with this function. It's pretty clear that you sometimes look through the source code noting potential problems, which is wonderful. But if this started because it caused you a real-world problem, I'd really like to know.

`memoizeWith` did not cause an actual production problem. I'm writing some articles about Ramda APIs' source code and examples, and maybe find some potential problems from source code, as you said. @CrossEye

**Comment by CrossEye** [comment]
I'm closing this for now.  There doesn't seem to be anything to do here, although there is a real concern raised.
