### ISSUE TITLE
Better error messaging and type-checking

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#2998]
I tried once before to do a lot of wholesale change to make the library ready to go to 1.0.  It didn't work.  Everything fizzled out.

This time, I want to treat one issue at a time.  Please make suggestions for other issues to discuss.  But let's make one issue at a time the priority.  The idea is not necessarily to get these changes into 1.0, but to make sense of what our roadmap should be.  I'd actually prefer to publish 1.0 soon, and start making these changes in subsequent versions.  But I'm far from certain about this.

----------

Error Messaging and Type-Checking
----------------------------------------

The first topic is error messaging and type-checking

Ramda has long been a low-level library that was built on the philosophy of letting things fail when provided bad data.  @buzzdecafe described it as a library that didn't hold your hands.

That is all well and good, and made sense for the learning library that we first wrote.  But Ramda has grown since then.  We're now sometimes mentioned in state of the platform discussions.   It's used in 133K GitHub repositories and is a dependency in over 9000 NPM projects.   Lately we've been averaging a million NPM downloads per day, just above Underscore, and a quarter that of lodash.  This is -- for better or worse -- no longer just the little playground that @buzzdecafe and I started.

And our error messaging is, frankly, awful.  This is one of the easier ones to follow, and it's pretty bad:

> ```js
> > map('foo', [1, 2, 3])
> ramda.min.js:1 Uncaught TypeError: t is not a function
>     at x (ramda.min.js:1)
>     at ramda.min.js:1
>     at ramda.min.js:1
>     at t (ramda.min.js:1)
>     at <anonymous>:1:1
> ```

They get progressively worse from there.

So it might make sense to have better error messaging.  To support that we'd probably need to do more type-checking than we have historically done.

Several recent issues/pull requests go to the heart of this.

#2997 asks what happens when `reduce` is passed a nil value as the final argument.  So far, I've been perfectly willing to answer: "Just return the accumulator".  It seems perfectly reasonable to me.  It adds a quick type-check to that argument.

#2993 asks what happens when `pipe` is supplied something other than a function.  This PR suggests type-checking and throwing a specific error in that case.  I've long been hesitant to do this.  It's not the sort of code I'm particularly interested in writing or maintaining; it bloats the library; and it can easily lead to a false sense of security.  But it might be time for me to move on from this.  If Ramda is becoming an everyday workhorse for so many people, then it probably should act like one.

Proposal
----------

In some version of Ramda soon (2.0?) we start type-checking the arguments supplied to our functions.  So `pipe` for instance need to be passed only functions.  We should test that all arguments are functions, and craft a useful error message if they're not.

Sanctuary has taken the lead on this, and has some of the best error messages I've run across.  But I don't propose to go as far as Sanctuary does.  I would expect to check that `pipe` receives functions, but not to check for instance that `pipe(foo, bar)` will fail because the return of `foo` doesn't match the input of `bar`.  It's possible that we'll add a better error message for that when someone tries to call the function created, but we would not try to catch that at the call to `pipe`.  I believe that anything that attempts to do so will have to ignore the ergonomics of JS by imposing a much stronger types system than is generally comfortable.

### Implementation ###

I haven't spent any real time on how we'll do this yet.  We could do something like what [sanctuary-def][sd] does and use a new function to actually create our functions.  (This might let us skip our internal `curry` functions, and might let us gain some other benefits such as those described in Brian Lonsdorf's [Debuging Functional][df].)  Or we could add it function-by-function on a more *ad hoc* basis.  Or we might take a middle ground in which nearly every function begins with a call to an internal `checkParameters` function, something like 

```js
const map = curry2 ((fn, list) => {
  const typeError = checkParameters([fn, list], Function, [Array, Object, Function, FLMap])
  // handleTypeError
  // body of map
})
```

(or if we don't mind another function on our stack traces, let the `checkParameters` function actually throw the exception.)

I'm not thrilled with any of these options, and would welcome an alternative.

### Transition ###

I'm not sure that there's a consistent transition plan; it will probably depend on the implementation we've chosen.  But we will need to know if we want to release such changes all at once or in point-releases.  And it would need to be scheduled around another major change I'd like to see: the reimplementation with modern JS, another change that will affect every one of our functions.  While I would have no problem doing these together, it might be a very large bite to take.

Alternatives
-------------

1. There is at least one clearly viable alternative.  @davidchambers has often suggested that Ramda simply adopt [sanctuary-def][sd] in Ramda.  It would involve using a battle-tested tool instead of trying to grow our own.

   I'm reluctant for a few reasons.  First, I very much like that Ramda is dependency-free.  Second, sanctuary-def is built around a much stronger notion of typing than feels comfortable to me for Ramda.  Third, I really believe that communities are better served by competition; while they might eventually settle down on a small number of tools, I would rather see the alternatives first.

   None of this means that I reject it out of hand.  But I would take some real convincing.

2. Doing nothing.  We absolutely do not have to do this.  Ramda is being used by many, and people have certainly been willing to overlook this flaw.  Perhaps there's no reason to shake things up.

3. Other?  Any other suggestions?

Feedback
----------

Feel free to add your feedback as comments here.   Anyone is welcome to comment.  But people who've contributed to Ramda are especially invited.  We'd love to hear what you think.

@ramda/core: We could especially use your thoughts.

  [df]: https://medium.com/@drboolean/debugging-functional-7deb4688a08c
  [sd]: https://github.com/sanctuary-js/sanctuary-def

**Comment by Bradcomp** [comment]
Request for clarification: I think that there are different types of type checks being referenced in those two examples. In one we are checking in order to throw early. In the other we are checking to avoid throwing.

Do we want to discuss both these things here? They probably have separate solutions, but it might be worthwhile to discuss together.

**Comment by ku8ar** [comment]
The problem with checking types in runtime is that "typeof" is expensive. Only "isNil" has no overhead.
Sancutary is an example of code that is beautiful, but useless in practice. This is the slowest functional library in JS.
It would be nice to have type exceptions, but only in the case of developer code.
There is a special NODE_ENV in React, which in developer mode adds additional hook validation, type validation, etc. Maybe it's worth doing the same here?

Something like this:
```
const map = curry2 ((fn, list) => {
  if (NODE_ENV === "dev") {
    const typeError = checkParameters(...)
    // handleTypeError
  }
  // body of map
})
```

**Comment by Bradcomp** [comment]
Aside: @ku8ar I don't think it's helpful to say a library is useless in practice. Let's focus on looking at what's right for Ramda without criticizing other libraries that have made different tradeoffs.

It's fine to discuss the tradeoffs made (i.e. Sanctuary is slower than comparable libraries) without resorting to ad hominem.

**Comment by Bradcomp** [comment]
I think it's important for us to define our API in such a way that our users know what to expect. From that perspective I think this is super important. While I too have been fine with the no-hands-holding approach, errors are an important part of an API, and it's been neglected.

One approach that we could look at is an EAFP([ref](https://docs.python.org/3/glossary.html#term-eafp)) style to our codebase. The benefit in most cases is that 'successful' code need not take the hit, with the downside that it makes the error path a lot slower.

I also think that it comports well with GIGO, though I know that is a more controversial opinion here. Bad input would still lead to bad output, however our messaging around errors would be better.

Taking a more full-featured approach to input checking would involve different performance and maintenance tradeoffs, while improving our API. Up until now, I have been happy at pointing people toward Sanctuary, as it has already made these considerations. It's slow, and you can turn off error checking in production. It allows for a much better developer experience for a person concerned about types. Trying to address these from within Ramda would potentially lead to a very different library.

**Comment by CrossEye** [comment]
@Bradcomp:

> Do we want to discuss both [checking in order to throw early and checking in order to avoid throwing] here? They probably have separate solutions, but it might be worthwhile to discuss together.

I think we do.  This is largely about our philosophy, and whether and how much we want to alter it.  *"What will our baby be when it grows up?"*  Both questions have a bearing on that.

**Comment by Bradcomp** [comment]
Part 2: Under what circumstances should we make an assumption to return valid data when the caller is calling with invalid inputs?

On the one hand, making assumptions about what our users mean is very idiomatic JavaScript. From ASI to the Promise spec, it is really common to accept and deal with improperly formed data without throwing errors. From a pure "What would the users most expect" perspective, I think it makes sense for our code to deal with those situations. 

On the other hand, I think that many of us would agree that those are some of the places in the Javascript ecosystem where bugs can hide in otherwise reasonable code. 

I can speak to when we added `then` to Ramda, at which point it broke the workflow of at least some of our users. The problem was that when lazy loading, the mere presence of a `then` property on the Ramda object caused the lazy loading to treat the whole library as a Promise instead of a namespace.

A familiar fellow once wrote an article about [unpredictable APIs](https://fr.umio.us/ranging-near-and-far/). Articles like that one were definitely helpful to me when I was developing a particular viewpoint towards writing libraries. 

I still think the simple focused approach is best. I have tended to 'disagree and commit' in most cases where simplicity and ease of use come into conflict. I am happy to do that now, but I want to at least have my principle disagreement noted. Magic bugs are way harder to find than exceptions. Exceptions are obvious. If we start making assumptions based on invalid data I think we are making our own lives and our users lives harder than they need to be. 

I think that solving the question around error messages could alleviate the issue that drives the desire for magic. If our code can tell the user that you can't call `reduce` with `undefined` as the last argument, and instead you need an array or something else that can be folded, I think that is more helpful than just silently passing along the accumulator.

**Comment by CrossEye** [comment]
@ku8ar:
> The problem with checking types in runtime is that "typeof" is expensive.

That is certainly one major reason we've avoided it so far.  I really mean this issue as a question.  *Should* we do something here?  Then, if so, *what* will be our goals and our guiding principles?

Doing anything like this will involve trade-offs.  And the price we would have to pay may well be too high.

**Comment by adispring** [comment]
Maybe Typescript is another good choice for type checking.

**Comment by CrossEye** [comment]
@Bradcomp:
> Magic bugs are way harder to find than exceptions. Exceptions are obvious. If we start making assumptions based on invalid data I think we are making our own lives and our users lives harder than they need to be.

This is of course the biggest concern with all of this.  And I still haven't wrapped my head around it.  I could well see us simply choosing to throw on any unexpected input.  I worry about that because I'm often writing for browser-based user interfaces, where code that might bring down the whole system is much worse than code that might have occasional incorrect data.  I really don't like exceptions.  But I can easily see us making that choice.

**Comment by CrossEye** [comment]
@adispring:

I don't think Typescript can help with this problem.  We're writing a library to be used by JS code-bases.  Even if every function had strong TS typings (which last I knew wasn't even possible yet), this would offer nothing at all to the JS user, unless we tried to insist that all users write in TS and use its compiler to do their type-checking.

That would be a very different library.

**Comment by Bradcomp** [comment]
> I could well see us simply choosing to throw on any unexpected input. 

I would prefer not to go that route. Like I said - Sanctuary fills that nook well.

>  I worry about that because I'm often writing for browser-based user interfaces, where code that might bring down the whole system is much worse than code that might have occasional incorrect data. I really don't like exceptions.

I hear you on this. I don't want our library to be a source of exceptions. I think the difference for us is that I'm not as comfortable handling our user's exceptions as you are? I hope I haven't misrepresented. For the most part, I think it's fine to let code fail if it was gonna fail anyway. 

I think predicate functions are a case where it's probably OK. Like how `isEmpty` returns `false` for stuff like numbers, undefined, and null.

In cases like propOr I think it's a bit more marginal, but I think there are more issues at play there. I expect we should have a path/prop discussion like this one to iron all that out, plus negative indices, etc. Bottom line being that if we have a story around why they behave in one way rather than another on those functions it should cover this too.

I think though that my tendency would be to avoid it anywhere we don't have a clear principal at play. 

I think that a good EAFP implementation could handle fixing our error messages in cases where the user's input throws, as well as being able to handle the default values in cases where that is reasonable. I don't have a suggestion for how to come to a resolution on 'reasonable' though ;)

**Comment by CrossEye** [comment]
> I think though that my tendency would be to avoid it anywhere we don't have a clear principal at play.

Right.  I'm hoping we can clearly articulate that principle and come up with a strategy to implement it.

> I think that a good EAFP implementation could handle fixing our error messages in cases where the user's input throws, as well as being able to handle the default values in cases where that is reasonable. I don't have a suggestion for how to come to a resolution on 'reasonable' though ;)

I've been stuck for a while trying to describe my feelings on what is reasonable there.  It's still far too fuzzy, and I think we need to be explicit.

As to error messages, obviously this:

> ```js
> TypeError: g.call is not a function
> ```

is not nearly as nice as something like:

> ```js
> TypeError: `"foo"` is not a function.  
>     All arguments to `pipe` must be functions.  Argument 0 is of type "String".
> ```

or as the beautifully laid out version from Sanctuary.

But perhaps we could be happy enough with: 

> ```js
> TypeError: Bad argument supplied to `pipe`.  Expected inputs: `Function, Function, ...`
> ```

or:

> ```js
> TypeError: Bad argument supplied to `pipe`. 
>     Signature: `(((a, b, …, n) → o), (o → p), …, (x → y), (y → z)) → ((a, b, …, n) → z)`
> ```

Which might be easier to create and be less resource-intensive.  But my thoughts here are still pretty jumbled.

**Comment by Bradcomp** [comment]
In order to have something to talk about, here's pipe:

```
function pipeImplementation() {
  //Creates the function that composes the input functions
}

function validateArguments(err) {
  const args = Array.from(arguments).slice(1);
  var idx = 0;
  while (idx < args.length) {
    if (!_isFunction(args[idx])) {
      //To Discuss - I think we should have our own errors for composability purposes. 
      //To Discuss - This doesn't handle fixing the stack trace, which I think we should do and most likely can do. 
      throw new TypeError(
        'TypeError: ' + toString(args[idx]) + ' is not a function\n All arguments ... argument ' + idx + ' blah';
      );
    }
    idx += 1;
  }
  throw err;  // If our validation doesn't come up with a valid reason for the failure, just pass it up.
}

function pipe() {
  var pipedFns = pipeImplementation(...arguments);
  return function() {
    try {
      return pipedFns(...arguments);
    } catch (err) {
      return validateArguments(err, ...arguments);
    }
  }
}
```

There are a lot of open issues here, and the code is just typed in the textbox so forgive me...

Also pipe is a bit trickier because it returns a function. I think the basic design is there though.

Our validateArguments could handle determining if a reasonable default should be returned instead of throwing an error.

I think we can look at a reusable way to create these validators and 'compile' the pieces together. That could lead to additional benefits when it comes to our discussions around dispatching, currying, transducers, and other project wide initiatives.

The happy path is mainly unaffected by the checking of the arguments - it's only in the case that the inner function throws that we take the validation hit.

**Comment by CrossEye** [comment]
Just for comparison, I've been thinking about something more like this:

```js
const validateArgs = (name, types, args) => {
  // A dummy for now.  A real implementation would compare `types` and `args`
  if (isNil(args[2])) {
    throw TypeError(`Improper type supplied to '${name}'.  Expecting ArrayLike at index 2.`)
  }
}

// This function might also replace `curry1`, `curry2`, etc.
// I have many dreams about what might go in here.
const def = (name, types, fn) => {
  const res = (...args) => {
    validateArgs(name, types, args) // stack-trace fix required?
    return fn (...args)
  }
  res.toString = () => fn .toString()
  Object.defineProperty(res, 'name', {value: name, /* writable, etc.*/})
  return res
}

const foldl = def ('foldl', ['Function', 'Any', 'ArrayLike'], (fn, init, xs) => 
  xs .reduce ((a, x) => fn (a, x), init)
)

foldl((a, n) => a + n, 0, [1, 2, 3]) //=> 6
foldl((a, n) => a + n, 0, undefined) //~> Improper type supplied to 'foldl'.  Expecting ArrayLike at index 2.
```

We might well be able to combine your `try {happyPath} catch {validate}` technique with this.

I haven't really thought through our few remaining variadic functions like `pipe`.  That might be more difficult to handle with this.

**Comment by Bradcomp** [comment]
I love the idea of a def function. I think in addition to curry and errors it could also be used for stuff like dispatching and transducers. We could even use it to create custom builds.

I think I prefer try / catch to preemptive type checking philosophically. I keep saying that it's also better for perf on the happy path, but I suppose that's an assumption until we have an implementation we could test. I suppose with a custom `def` Ramda could support either implementation!

I think the idea of a type checker generator is also a good one. It seems a lot nicer than writing bespoke error handlers for our entire API. Depending on how we do it, do you think we could use it to generate type sigs too?

As for our variadic functions, and really all functions that always return a function, I have some loose thoughts around a thunk based solution to that. I can try to sketch something out. 

Are you already working on an implementation for these things?

**Comment by davidchambers** [comment]
> Are you already working on an implementation for these things?

sanctuary-def does all the things being discussed. I suggest using that as a starting point and deleting code relating to features you do not wish to provide. I am happy to provide assistance. :)

**Comment by CrossEye** [comment]
> Are you already working on an implementation for these things?

I have many pieces lying around, but I have not approached the full problem.  I'm not even sure I have a sense of that scope yet.

(I am curious to see if we can generate good sigs from this too. That would offer all sorts of possibilities.)

>I suggest using [sanctuary-def] as a starting point

While that's not the first or only such function I've seen, it is certainly the most important inspiration.  I'm sure we'll be asking plenty of questions if we do go this route, thank you.

**Comment by ku8ar** [comment]
I still have a question about `prop`/`path`. They also get runtime type checking?
If so, then redux selector like this:
```
const selectName = useSelector(
 selectUser,
 prop('name')
)
```
 we will need to change into something like this:
```
const selectName = useSelector(
 selectUser,
 tryCatch(
  prop('name'),
  always(undefined)
 )
)
```
And this code is ugly. And Redux developers will run away from Ramda :(

All this error checking is incompatible with React. It is much better to return undefined/junk for invalid data than destroy the entire render cycle.

**Comment by CrossEye** [comment]
@ku8ar:

The discussion here is about *adding* more type-checking, not removing it.

To me, `path` is mostly about gracefully handling the nil values in a chain of `prop`s.

**Comment by Bradcomp** [comment]
Now that we have given this a few weeks for input, are we ready to start moving down this path?

**Comment by CrossEye** [comment]
I've played with several partial implementations, but have nothing complete yet.

I would like to try this.  But I think there is a major question about versions.  I would really rather implement this in ES6+ code.  So I'm feeling that if we do this, it would be after 1.0.  How do you feel about that?

I don't know what else we want to do before 1.0.  I'm hoping it's very little.  But I think it might be time to create a 1.x branch for work we want in our ES3/ES5 code-base, and make master available for work like this on 2.0+-versions.  Does that make sense?

**Comment by Bradcomp** [comment]
I would prefer to have the API for our prop / path related functions set before 1.0, but that is the only thing I can think of.

**Comment by CrossEye** [comment]
Agreed on all points

**Comment by adispring** [comment]
Are there any plans to start this? 

In ramda/ramda gitter, I have seen many problems people ask for help, are just caused by incorrect use of ramda apis,  such as:
* passing string instead of array as `R.path` first argument;
* wrong ways of using `pipe/compose`: 
  * compose the result of executed functions;
  * compose functions of wrong arity;
,etc.

If ramda have a better error messageing and type-checking, I believe it will be of great help to:
* improve developers' development experience;
* give people more meaningful information of runtime errors in product environment;
* reduce the learning curve of ramda and the entry barrier;

In order to help people easy to learn, write and debug with ramda, I think this is an urgent and important thing to do now.

**Comment by CrossEye** [comment]
@adispring: We need to figure out 1.0, and soon.  I think the new modify/Path should be included as well as any open issues regarding `path`/`prop` and related functions.

After that, I'd like to start this.

**Comment by ku8ar** [comment]
@adispring 
> passing string instead of array as R.path first argument;

If someone cannot read the documentation, you can always tell him to download TS :)

**Comment by CrossEye** [comment]
@customcommander: Somehow I never saw this response before.  There's a lot to digest in this whole thread.  But I'm going to close the issue now, as something to revisit after v2.0.
