### ISSUE TITLE
R.either 's description and parameter definition contradict

### ISSUE THREAD

**Issue by MFogleman** [ramda/ramda#3017]
> (*… → Boolean) → (*… → Boolean) → (*… → Boolean)
PARAMETERS
...A function wrapping calls to the two functions in an || operation, _returning the result of the first function if it is **truth-y** and the result of the second function otherwise_. ...

The documentation implies that we can just pass functions into R.either until we get a value that is not undefined/false/null/etc.  But the parameters assert that the functions should explicitly return booleans.  I understand the Ramda team does not handle the TypeScript definitions, but this issue does muddy the intent of what restrictions should be on the type definitions for R.either.

Looking at the code, I think the description is accurate to both what is happening, and the intent, but that the parameters should be updated.  This is a probably a very minor issue, but I think it would give solid guidance to intent for the TS definition maintainers.

**Comment by CrossEye** [comment]
I'm not following precisely what you would like to see changed.

The two parameters are just listed as `predicate`s, which I would hope implies to most users a boolean-returning function.  And the signature -- ugly as it is -- only notes that the functions return booleans.

But as is often the case in Ramda, these are aspirational signatures.  And in fact, any functions can be used:

```js
either ((x) => x * x, (x) => 42) (3) //=> 9
either ((x) => x * x, (x) => 42) (0) //=> 42
```

(since `0 * 0 //=> 0`, which is false-y.)

We do  not try to enforce any Boolean constraints on the output.  But if you have a specific suggestion for a change to the signatures or the parameters, please let us know.

**Comment by MFogleman** [comment]
I agree that what `either` does is good.  The function signature of `(… → Boolean) → (… → Boolean) → (*… → Boolean)` is misleading.  `either` does not return a boolean, and its predicates are not required to return booleans.  Its predicates can be functions that return anything, and `either(f1, f2)` will return a function that can return anything.

I think a better signature would be something like the following, (using R.ifElse as inspiration)
`(*… → *) → (*… → *) → (*… → *)`

**Comment by Bradcomp** [comment]
Prior discussions:
https://github.com/ramda/ramda/pull/1218
https://github.com/ramda/ramda/pull/1335
https://github.com/ramda/ramda/pull/1971

I suggest we tread lightly here.

**Comment by MFogleman** [comment]
Just to reiterate, I am *not suggesting that we change any code or functionality*,   My whole assertion is that we should update the documentation for `R.either` from 
`(*… → Boolean) → (*… → Boolean) → (*… → Boolean)`
 to 
`(*… → *) → (*… → *) → (*… → *)`

R.either does not require its predicates to be functions that return Booleans, nor does it necessarily return a function that returns a boolean. Thus, the current documentation is incorrect.

R.either's predicates are functions which can be of the type that return any type of value, and it returns a function that can be of either of those functions' types

**Comment by CrossEye** [comment]
One of those long contentious discussions was about changing the documentation.  😦 

If we do change the signature, I would prefer to get rid of the `*`s.  Perhaps something like this:

```hs
:: (a -> b -> ... -> x) -> (a -> b -> ... -> y) -> (a -> b -> ... -> x | y)
```

**Comment by MFogleman** [comment]
I'd be fine with that too.  Would that notation be more accurate than something like:
```
:: (a -> x) -> (a -> y) -> (a -> x | y)
```
Either takes 2 functions as arguments (`a -> x`, and `a-> y`) and returns a function that takes an argument (`a`) and returns the result of either `a->x` or `a->y` invoked with `a` ?

Or am I implying something different without realizing it?

**Comment by Bradcomp** [comment]
The function returned from `either` can take more than a single parameter. That's why we would want the ellipses.

I would be OK with @CrossEye's suggestion, but I want to suggest that `x | y` as the return type is meaningless.

The type signature can still be aspirational without implying the wrong thing.

I wouldn't suggest we write a test to validate that if one passes in things of two different types that the return value is one of those two types. It seems incidental. JS wouldn't complain because it's dynamically typed, and Ramda doesn't care because it rarely type checks except to provide better error messages. I don't think we should include that sort of incidental information in a type signature for the same reason I don't think we should test for it.

If JS had an imaginary perfect type system, I would suggest that restricting the return types of the input functions to be the same is perfectly reasonable. If you want it to be a string or a number for some weird reason, create a sum type and use that. But because this is JS, you can just treat the response as a string/number without doing anything special.

That being said, I prefer*:
`:: ((a, b, ...) -> c) -> ((a, b, ...) -> c) -> ((a, b, ...) -> c)`

*Looking at the source for `either` made it clear that we should change from (a -> b ... -> c)` to `((a, b, ...) -> c)` because the resultant function isn't curried.
https://github.com/ramda/ramda/blob/master/source/either.js#L40

This may be something worth investigating, as I had assumed it would be curried to the max length of the input functions.

**Comment by CrossEye** [comment]
> That being said, I prefer*:
> ```hs
> :: ((a, b, ...) -> c) -> ((a, b, ...) -> c) -> ((a, b, ...) -> c)
> ```

That looks good to me, although I might replace `c` with `z`.

> This may be something worth investigating, as I had assumed it would be curried to the max length of the input functions.

Yes, I wonder why we didn't do so.

**Comment by customcommander** [comment]
Closing as tangentially related to #2118.
