### ISSUE TITLE
R.allPass strange behavior with missing parameters of a function inside the conditions

### ISSUE THREAD

**Issue by crash7** [ramda/ramda#3032]
Hi,

Just found this weird behavior and thought it would help raising the issue:
```
const subject = [1, 2, 3];

filter(
  allPass([
    equals(1),
    propSatisfies
  ]),
  subject
 )
```

When passing `propSatisfies` with missing parameters, the whole condition gets evaluated to true, always.
The output for the snippet above is `[1, 2, 3]` instead of `[1]`.

See repro: https://ramdajs.com/repl/?v=0.27.0#?const%20subject%20%3D%20%5B1%2C%202%2C%203%5D%3B%0A%0Afilter%28%0A%20%20allPass%28%5B%0A%20%20%20%20equals%281%29%2C%0A%20%20%20%20propSatisfies%0A%20%20%5D%29%2C%0A%20%20subject%0A%20%29

Sorry is if this is the expected, just found this in my session of functional drafting.

**Comment by hitmands** [comment]
Hi @crash7 , 
I believe this is the expected behaviour...

In the above snippet `R.propSatisfies` gets called with only 1 argument, due to its curried nature this leads to the output of a new function. [Under the hood](https://github.com/ramda/ramda/blob/master/source/allPass.js#L33) happens something similar to:

```
if (propSatisfies(1)) { 
  return true;
}
```

and, inside conditions, functions evaluate to true.

____

You might eventually expect `propSatisfies` to throw if its first argument isn't a function, 
however, Ramda doesn't make any assumption if their api isn't consumed correctly...

**Comment by crash7** [comment]
Hi @hitmands,
Yes, I agree 100% with:
>Ramda doesn't make any assumption if their api isn't consumed correctly.

But here is the interesting thing: when doing that, allPass behaves like all of the conditions were true, not filtering the array at all, but if I use another function:
```
const subject = [1, 2, 3];

filter(
  allPass([
    equals(1),
    always
  ]),
  subject
 )
```
It filters the array [correctly](https://ramdajs.com/repl/?v=0.27.0#?const%20subject%20%3D%20%5B1%2C%202%2C%203%5D%3B%0A%0Afilter%28%0A%20%20allPass%28%5B%0A%20%20%20%20equals%281%29%2C%0A%20%20%20%20always%0A%20%20%5D%29%2C%0A%20%20subject%0A%20%29).

Feels like is more a side-effect of `curry`, since this appears to happen with all the curried functions only.

**Comment by hitmands** [comment]
You're right, 
I'd expect `b` to match `b1` in this example:

[REPL](https://ramdajs.com/repl/?v=0.27.0#?const%20subject%20%3D%20%5B1%2C%202%2C%203%5D%3B%0A%0Aconst%20a%20%3D%20filter%28%0A%20%20allPass%28%5B%0A%20%20%20%20equals%281%29%2C%0A%20%20%20%20always%2C%0A%20%20%5D%29%2C%0A%20%20subject%0A%20%29%3B%0A%0Aconst%20a1%20%3D%20%5B%5D%0Afor%28let%20value%20of%20subject%29%20%7B%0A%20%20if%28equals%281%2C%20value%29%20%26%26%20always%28value%29%29%20%7B%0A%20%20%20%20a1.push%28value%29%3B%0A%20%20%7D%0A%7D%0A%0A%0Aconsole.log%28%7Ba%7D%29%3B%0Aconsole.log%28%7Ba1%7D%29%3B%0A%0A%2F%2F%20-----%0A%0Aconst%20b%20%3D%20filter%28%0A%20%20allPass%28%5B%0A%20%20%20%20equals%281%29%2C%0A%20%20%20%20propSatisfies%2C%0A%20%20%5D%29%2C%0A%20%20subject%0A%20%29%3B%0A%0A%0Aconst%20b1%20%3D%20%5B%5D%0Afor%28let%20value%20of%20subject%29%20%7B%0A%20%20if%28equals%281%2C%20value%29%20%26%26%20propSatisfies%28value%29%29%20%7B%0A%20%20%20%20b1.push%28value%29%3B%0A%20%20%7D%0A%7D%0A%0Aconsole.log%28%7Bb%7D%29%3B%0Aconsole.log%28%7Bb1%7D%29%3B%0A%27%27%3B)

**Comment by Bradcomp** [comment]
This is an expected side effect of how allPass determines the length of the function it returns.
From `allPass` docs:
> The function returned is a curried function whose arity matches that of the highest-arity predicate.

always.length is 1, so `allPass` returns a function that takes 1 parameter. Then `filter` passes in 1 parameter, and thus `allPass` returns a result (even though `always` returns a function, because `allPass` is returning it can still work based on the `equals(1)`).

propSatisfies.length is 3, so `allPass` returns a function that takes 3 parameters. When `filter` calls that function with 1 parameter, it gets back a function of 2 parameters. Since any function is truthy, `filter` will return all results.

**Comment by crash7** [comment]
Thanks clarification @Bradcomp! Closing this as I agree this is a expected side-effect.

Thanks all!
