### ISSUE TITLE
Ramda try catch with Promises

### ISSUE THREAD

**Issue by BravenxX** [ramda/ramda#3045]
Is there a way to catch an error using R.pipeP inside a R.tryCatch. Like this:

R.tryCatch( R.pipeP( ... ), () => { ... } ) 

I can't find a way to do it with asyncs functions...

**Comment by CrossEye** [comment]
I would never suggest `pipeP` at all.  It was deprecated, and should have been removed by now.  Hopefully it will be removed in the next release.

`tryCatch` was designed for exception handling, not for rejecting Promises.  I doubt that will change, given how little the core team here likes Promises.

**Comment by BravenxX** [comment]
> I would never suggest `pipeP` at all. It was deprecated, and should have been removed by now. Hopefully it will be removed in the next release.
> 
> `tryCatch` was designed for exception handling, not for rejecting Promises. I doubt that will change, given how little the core team here likes Promises.

I don't get it, why using pipeP is bad? Sorry, I'm new on Ramda

**Comment by CrossEye** [comment]
@BravenxX: It's not that using `pipeP` is bad.  It's that Ramda is removing that function and so it would make sense to move to its successor: `pipeWith`.  The discussion is scattered, but #2515 is central and links to most of the rest of it.

The idea of `pipeWith` is to consolidate `pipeK` and `pipeP` and other future pipelines that do some transformation of their step functions.  `pipeP` is replaced with `pipeWith (andThen)` and `pipeK` is replaced with `pipeWith (chain)`.  There is a minor caveat here: these new functions take arrays of input functions rather than separate arguments.  But that's pretty easy to deal with.

One thing this allows Ramda to do is to reduce its Promise-related functionality to just `andThen` and `otherwise`.  Since Promises are not lawful types (and have [many other problems][bp]), the Ramda team finds them more difficult to work with than Futures or Tasks.

  [bp]: https://medium.com/@avaq/broken-promises-2ae92780f33
