### ISSUE TITLE
Vscode Intillesense stop working because of Ramda

### ISSUE THREAD

**Issue by BravenxX** [ramda/ramda#3055]
I want to export a function as curried and no curried function to an index. 

( because I don't want to have to put null on those variables that I will not use. Ex: Using curring fn: fn(2,null,null), whitout curring: fn(2) )

The thing is that when I export those two functions in index.js vscode Intellisense stops working. 

**Example to reproduce the bug:**

Project directories:

- index.js
- function.js

```
// function.js

import R from 'ramda';

const remove = (a, b) => {
    {  . . .  } 
};

export { remove };

const curriedRemove = R.curry(remove);

export { curriedRemove };
```

```
// index.js

export * from './function'
```

For some reason, that will cause intellisense not to work.

If I remove the export line in index.js. intellisense will work (restarting vscode).

**Comment by Bradcomp** [comment]
What happens if you take out 
`export { remove }`
and change the last line to 
`export { remove, curriedRemove }`?

**Comment by BravenxX** [comment]
@Bradcomp 

Nop, still a issue. Intellisense freezes,

**Comment by CrossEye** [comment]
I don't have the same issue.  Of course I'm using a two-year old version of VS Code, so maybe something's changed.  I also had to turn back on most of the Intellisense features, as I can't personally stand all the supposed helpful hints, and only bring it up with an intentional action (CMD/CTRL-space).  But when I did that, it worked with or without those features.

What version of VS Code are you using?
