### ISSUE TITLE
Execute a function whithout passing an arg

### ISSUE THREAD

**Issue by BravenxX** [ramda/ramda#3056]
For example, if I have this:

```
const fn = ( b ) => ( a ) => {
    if(!b)
        return a + 2

    return a + b
}

const fn2 = fn(2)

const aux = ( ) => f2( )     // I just want a + 2 result

R.pipe( getSomeValue,  aux ) 
```

I don't want fn2 to get the param "b" from getSomeValue function, I want that param to be null. Is there a way to get rid of the aux with a Ramda function like R.passNullArg( fn2 )   ?? I

**Comment by Bradcomp** [comment]
The short answer is that you'll need to construct that function yourself, and you almost had it:
```
const aux = () => f2(null)
// or explicitly
const aux = (b) => f2(null)
```

This would work for manual currying and Ramda's curry function.

I suspect this is just example code, but of course the current function would return `4` for `fn(2)(0)` which might be a bug depending on the circumstances.

The longer answer is that optional parameters and currying don't really play too nicely together, and are generally seen as competing ways to solve the same issue. 

It's tough to use this case for an example, because aux could more simply be written as `() => 4` or `R.always(4)`. 

We also have `R.thunkify` to take a function and make it lazy without needing to pass arguments.

In general, with curried functions you'll want to put what would be considered optional parameters up front, so that you can use partial application to build up more specific functions from general ones. 

```
const add = curry((a, b) => a + b);
const inc = add(1);

inc(3); // => 4

const dbCall = curry((config, query) => {
  if (config == null) config = defaultConfig;
  // blah
});

const defaultDb = dbCall(null);
const myDb = dbCall(myConfig);

myDb(query);
```
Conceptually, we should separate the idea of optional parameters from the idea of turning something into a thunk, or of ignoring an argument. So `thunkify`, `always`, and `curry` all have subtly different semantics due to the differences between the goals they are trying to accomplish. With `curry` a function will expect a certain number of arguments, and it will use each one that gets passed in. If you want one to be null you have to pass in null.

The way to get true optional parameters (though I don't suggest this) would be to use `curryN` up to the number of required parameters. This still wouldn't solve your issue above though because you are actually passing in a value, you just want to ignore it. 

```
const apiCall = curryN(2, (method, url, body) => {
  var callConfig = {
    method: method || 'GET',
    url,
  };
  if (body) callConfig.body = body;
  // blah
});

const postRequest = apiCall('POST');
// This would work
postRequest('my.site.com', {stuff: 'things'});
//This would send the request without the body
postRequest('my.site.com')({stuff: 'things'});
```

**Comment by BravenxX** [comment]
@Bradcomp 

Thanks for the complete answer! It's been helpful to me.
