### ISSUE TITLE
Ramda Curry makes VsCode Intellisense stop working

### ISSUE THREAD

**Issue by BravenxX** [ramda/ramda#3057]
I reported this issue last week [Link](https://github.com/ramda/ramda/issues/3055). Now I'm curious, I have two ways to write the code but one of them makes VsCode intellisense stop working when I export it by index.js

**Directories**: 

* function.js
* index.js

```
// index.js
export * from './function'
```

This way to write the function makes VsCode insellisense stop working

 ```
// First way
// function.js 

const remove =(schema, params) => {
  const getFilterFormat = R.cond([
    [_.isPlainObject, getRealmFilter],
    [R.T, R.F],
  ]);

  const removeRegisters = R.useWith(fwRemove, [
    R.identity,
    getSchemaName,
    getFilterFormat,
  ]);

  return removeRegisters(Realm, schema, params);
};

const curriedRemove = R.curry(remove )

export { curriedRemove };

```

But this way to write the function makes no problem. (But this way I can't export remove function without currying )

 ```
// Second way
// function.js 

const curriedRemove = R.curry((schema, params) => {
  const getFilterFormat = R.cond([
    [_.isPlainObject, getRealmFilter],
    [R.T, R.F],
  ]);

  const removeRegisters = R.useWith(fwRemove, [
    R.identity,
    getSchemaName,
    getFilterFormat,
  ]);

  return removeRegisters(Realm, schema, params);
});

export { curriedRemove };
```

The second one doesn't let me to export the function without currying and that's my problem. There is something that I'm missing?

**Comment by CrossEye** [comment]
Because I can't replicate the problem, I can't offer much help.  Have you reported this to the VS Code team?  As far as I can tell, the Ramda functions are working the way they should.  But I have no idea how VS Code derives the metadata it uses for its "Intellisense" feature.

It may be that this is a long-standing problem, because I'm pretty sure most Ramda users would automatically use the latter format.  Remember that there is (perhaps too much) magic in Ramda's `curry` implementation so that wrapping `curry` around your function does not prevent you from using it as you would have without the `curry`.  It simply offers additional ways to call it. 
 That is, given this:

```js
const curriedRemove = curry ((schema, params) => { /* ... */ })
```

We can call this in several ways, all yielding the same result:

```js
const result = curriedRemove (mySchema, myParams);  //or
const result = curriedRemove (mySchema) (myParams); // or
const result = curriedRemove (__, myParams) (mySchema)
```

**Comment by BravenxX** [comment]
@CrossEye I understand, I think I'm going that way, trying to solve this exercise is making my head hurt lol. 

But, would you advice me about some good practices? Should I exports a function as a curried function (export curriedFn) or should I let the user Curry the function (just exporting fn) ? And otherwise, It's good practice to name a function curried as a curried<fnName> or just name it as <fn>? Thanks a lot.

**Comment by BravenxX** [comment]
Okay, I found the issue. The problem isn't the export or the index.js it was the importation from the index.js

Ex:

- main.js
- index.js
- function.js

I was importing remove like this: 

```
// main.js

import * as Functions from './index'
...

```

But if I import it like this everything works fine.

```
// main.js

 import {remove} from './index'
...

So that's all.

```

**Comment by BravenxX** [comment]
Ok. Now I have the the specific problem (I hope).

I'm working with react Native so I have a functional component like this:

```
import {remove} from './somewhere'

const Login = () => {
   
   onPressSubmit = (a) => {
      const logInUser = R.pipe(
         ...
        R.tap(remove('myUser') ),
        ...
        )
   
    return R.tryCatch(logInUser, showModalError)( a )
  }

   return ( ... )
}
```

If I change that to this. Now everything works okay (so far):

```
import {remove} from './somewhere'

const Login = () => {
   
   onPressSubmit = (a) => {
       const removeUser = remove('MyUser')      // => new function

      const logInUser = R.pipe(
         ...
        R.tap(removeUser),              // => using new function
        ...
        )
   
    return R.tryCatch(logInUser, showModalError)( a )
  }

   return ( ... )
}
```

I hope it comes in handy for someone who has a similar problem.

**Comment by CrossEye** [comment]
>  Should I exports a function as a curried function (export curriedFn) or should I let the user Curry the function (just exporting fn) ?

While obviously it's up to you and your user, I personally like to have Ramda-style curried functions available.  They are more flexible to use.  Do note that there is some performance cost to this flexibility.  It's usually not huge, but it exists due to the extra function invocations required.  But I find it worth it.  In fact I and a host of others have built an entire library on this premise... :wink:

> And otherwise, It's good practice to name a curried function as a curriedFn or just name it as fn? Thanks a lot.

Currying is a minor feature of your function.  The API and behavior are far more important.  Calling attention to the fact that it's curried just seems a distraction.  Document the various ways it can be called, or simply mention the currying in the documentation; that should be plenty.

**Comment by BravenxX** [comment]
@CrossEye That's make me sense. Thanks!
