### ISSUE TITLE
Ramda path

### ISSUE THREAD

**Issue by ArashKianiamphora** [ramda/ramda#3063]
Although not supported in older browsers, as far as I understand Ramda path function is the same as optional chaining and we should be able to easily replace it in our codebases.

Perhaps this is a good time to decommission this function in favor of bundle size and to promote more native coding experience. 

Just a thought! and apologies in advance if it is something that is already planned / irrelevant :)

**Comment by semmel** [comment]
@ArashKianiamphora Just out of curiosity; How is there an impact on the bundle size removing `R.path` now there is tree-shaking and you can `import { equals, … }` from 'ramda';`?

When it comes to "decomission" things which are not broken, I think "promoting coding experience" is a very  subjective thing. Apart from functional point-free coding of course, which is the thing Ramda promotes I guess. 
So if it'd fit in that last category I'd still hate to refactor our code-base for no concrete value, however at least Ramda's API surface would shrink.

**Comment by mattgrande** [comment]
Path allows you to do things like this: `R.path(['hardcodedProperty', variableProperty, 'somethingElse'], obj)`, which I don't think you can do with optional chaining?

**Comment by ArashKianiamphora** [comment]
@mattgrande keeping what optional chaining not offer is great. but having multiple ways of doing the same things is always something I work to reduce as it increases complexity. as for your example isn't code below an equivalent? 

```javascript
obj?.hardcodedProperty?[variableProperty]?. somethingElse
```

@semmel tree shaking not always works and not everyone has it setup. "promoting coding experience" is a very subjective thing I agree but removing what already exists allows for more innovative problems worth solving to surface. 

The problem I see in code bases atm is:

```javascript
import _ from ramda
import {path, isEqual} from ramda
....
return data?.value
```

sure you can educate the team and put custom linter in place but why would anyone wants to give a rope to a developer to hand themselves.

Just my thought

**Comment by ArashKianiamphora** [comment]
oh no the positive side I believe path is faster than optional changing

**Comment by semmel** [comment]
@ArashKianiamphora How would you write that without having to ponder on a proper name for `x`? `R.path(["outer", "inner"])` vs. `x => x?.outer?.inner`?

I still even use `R.prop` because to a certain level point-free is more readable, and when needed I like my variables properly named.

**Comment by ArashKianiamphora** [comment]
`R.path(["outer", "inner"], x)` is equal to `x?.outer?.inner` I assume.

**Comment by CrossEye** [comment]
@ArashKianiamphora:

Your examples all have you knowing the path at the time of source code creation.  How would optional chaining deal with truly dynamic paths?

This is a function I use a lot.  And while I can't share my employer's code, I've recently done something vaguely similar to this:

```js
const getPaths = (obj) =>
  Array .isArray (obj)
    ? obj .flatMap ((x, i) => getPaths (x) .map (p => [i, ...p]))
  : Object (obj) === obj
    ? Object .entries (obj) .flatMap (([k, v]) => getPaths (v) .map (p => [k, ...p]))
  : [[]]


const validator = Object.assign(
  (spec) => {
    const paths = getPaths(spec)
    return (obj) => paths.every(p => path(p, spec) == validator.optional || path(p, obj) != null)
  }, 
  {
    required: Symbol(), 
    optional: Symbol()
  }
)

const spec = {
  foo: validator.optional,
  bar: {
    baz: validator.required,
    qux: {
      corge: validator.required,
      grault: validator.optional
    }
  }
}

const validate = validator (spec)

validate ({foo: 1, bar: {baz: 2, qux: {corge: 3}}}) //=> true
validate ({foo: 1, bar: {box: 2, qux: {corge: 3}}}) //=> false
```

Would you simply need to recreate `path` in order to do this?  Or is there some feature of optional chaining that I'm missing?

**Comment by semmel** [comment]
@ArashKianiamphora 
> R.path(["outer", "inner"], x) is equal to x?.outer?.inner I assume.

That's not what I asked. 
For function pipelining I need to type just `R.path(["outer", "inner"])` which is essentially `x => x?.outer?.inner`. However I really don't like the `x` or any other name in the latter.

**Comment by ArashKianiamphora** [comment]
Thank you both for taking the time and answering my questions. at this time I very much feel like I might be missing something about path. 😕 

@semmel sorry I don't understand how your example is supposed to find the data to parse through

@CrossEye Thank you for your example, without path


```javascript
const getPaths = (obj) =>
  Array .isArray (obj)
    ? obj .flatMap ((x, i) => getPaths (x) .map (p => [i, ...p]))
  : Object (obj) === obj
    ? Object .entries (obj) .flatMap (([k, v]) => getPaths (v) .map (p => [k, ...p]))
  : [[]]


const validator = Object.assign(
  (spec) => {
    const paths = getPaths(spec)
    // return (obj) => paths.every(p => R.path(p, ) == validator.optional || R.path(p, obj) != null)
    return (obj) => paths.every(p => spec?.[p] === validator.optional || obj?.[p] !== null)
  }, 
  {
    required: Symbol(), 
    optional: Symbol()
  }
)

const spec = {
  foo: validator.optional,
  bar: {
    baz: validator.required,
    qux: {
      corge: validator.required,
      grault: validator.optional
    }
  }
}

const validate = validator(spec)

console.log(validate({foo: 1, bar: {baz: 2, qux: {corge: 3}}})) //=> true
```

**Comment by ArashKianiamphora** [comment]
@semmel sorry end of the day here. I had to read it again to understand 😅 , You are right! that's a good use case, I do not think exists out of the box.

**May I suggest a documentation update or rename to something like pathCallback instead.** 

either way, I am going to close this issue, as I see use for it now.

**Comment by CrossEye** [comment]
@ArashKianiamphora:

These two lines definitely don't do the same thing:

```js
    return (obj) => paths.every(p => path(p, spec) == validator.optional || path(p, obj) != null)
    return (obj) => paths.every(p => spec?.[p] === validator.optional || obj?.[p] !== null)
```

For instance, when looking at a required path of `p = [ "bar", "qux", "corge" ]`, `path(p, obj)` does something quite different from `obj?.[p]`, which would be the equivalent of the nonsensical `obj?.[[ "bar", "qux", "corge" ]]`.

Nor do I understand the suggestion of `pathCallback`.  `path` is a function which takes an array of node names and an object, and returns the value found on that object along the path represented by that array, or `undefined` if any of those nodes does not exist.  Or, given Ramda's currying, more commonly it's a function which takes such an array and returns a function that takes an object returning the value described.

I have no idea what `pathCallback` would be.

Also note that now and up until v1.0, Ramda has been code that can run in very old versions of JS.  Even after that, I don't know how soon we would adopt newer features such as optional chaining.  We certainly wouldn't abandon a function simply because the latest spec gives an alternate way to do the same thing.  We would not abandon `chain` because `Array.prototype.flatMap` has been introduced.  Not only is it not a full replacement (try it on functions, say), but it offers a different interface.  Ramda presents composable *functions*, and prototype *methods* or language *syntax* will never be a complete substitute.

Perhaps I'm just beating a dead horse, as this issue is already closed.  But such a suggestion makes me wonder if you understand the purpose of Ramda.  The goal is to make it simple to code in the style @semmel suggested above.

**Comment by ArashKianiamphora** [comment]
That was amazing, thank you both for making the time and explaining. I diffently agree using Ramda in a style that semmel suggested could benefit from utlising Ramda.
