### ISSUE TITLE
QUESTION: is this properly maintained?

### ISSUE THREAD

**Issue by woss** [ramda/ramda#3076]
Hi, i want to say i love the this lib and I would really love to use it longterm but amount of the PRs and issues is worrying for a project like this.

Is it actively maintained? Do you need help? i wouldn't mind sponsoring you if you choose to do so.

**Comment by CrossEye** [comment]
There's little chance of Ramda switching implementation to TS.  See the reasons and discussions in #2976.  But we are looking at how to improve the TS support.

I'd suggest that most of the Ramda tutorials (at least those since 2015) are probably still fairly accurate.  And, as a library, it will never have the sort of documentation that framework have and need.  There is room -- plenty of room! -- to improve the documentation.  And tutorials are among the best ways to do that.  That is one way that you could easily help.  Write a tutorial about some part of Ramda that interests you but you don't think is well-documented.  Tell us about it and we'll add it to the wiki.  Or simply add a wiki page with it if you don't want to host your tutorial somewhere else.
