### ISSUE TITLE
Ramda curry/uncurry issue with ES6 default parameter syntax

### ISSUE THREAD

**Issue by maciejmiklas** [ramda/ramda#3101]
Please fix this problem: https://stackoverflow.com/questions/44526331/ramda-curry-uncurry-issue-with-es6-default-parameter-syntax

**Comment by CrossEye** [comment]
@maciejmiklas:

How?  Do you have any suggestions?

As one of the comments suggested, this is basically unsolvable.  Default arguments simply do not play well with this sort of API.

**Comment by maciejmiklas** [comment]
No - I do not have, but I was hoping that after some time the solution could come up.

**Comment by CrossEye** [comment]
There are some interesting problems with default arguments.

For instance:

```js
const sum = ([x, ...xs], total = 0) => 
  x == undefined ? total : sum(xs, x + total)

const xss = [[1, 2, 3, 4, 5], [2, 3, 5, 7, 11], [1, 4, 9, 16, 25]];

[sum (xss [0]), sum (xss [1]), sum (xss [2])]; //=> [15, 28, 55] // correct

xss .map (sum); //=> [15, 29, 57]  // WTF?
```

(this is because the `index` parameter of `Array.prototype.map` supplies the `total` variable, and so the default value is ignored.)

I can see no way to make `uncurryN` (or a number of other Ramda functions) work comfortably with default parameters.  If you see one, I'd love to hear it.
