### ISSUE TITLE
Unexpected behavior when using R.any

### ISSUE THREAD

**Issue by hmust92** [ramda/ramda#3103]
I am noticing some behavior when using R.any that I wouldn't expect. Here's the scenario:

`const person = {name: 'hasan'}`
`const people = [person]`

`any(equals)(people) // I am expecting this to return false, but it returns true.`
`any(equals())(people) // I am expecting this to return false, but it returns true.`

`any(equals(undefined))(people) // I am expecting this to return false, and as expected it returns false`
`any(equals(person))(people) // I am expecting this to return true, and as expected it returns true`

It seems if you do one of the following:
1. Provide the function definition as the first argument to R.any
2. Invoke the function with no argument as the first argument to R.any

It doesn't actual do the comparison and returns true by default?

**Comment by Bradcomp** [comment]
This is the way it is because of currying, combined with the rules in JS for coercing to booleans. 

`any` is expecting a function that takes one parameter and returns a boolean, that parameter being each item in the array. `equals` takes 2 parameters, and is curried so it can take one parameter at a time.

Because of how currying works, `equals`, and `equals()` both resolve to the function `equals`, which takes two parameters, since in both cases we aren't applying any arguments to the function.

So then `any(equals)(array)`and `any(equals())(array)` are functionally equivalent, and we can look at what they do:

`any(equals)(array)` will call `equals` on each item in the array. Since `equals` is curried and accepts two parameters, the result of `equals(item)` is a function, which gets coerced into `true` since all functions are truthy in Javascript.

`equals(undefined)` is taking `undefined` as the first parameter, so it's returning a function that takes a single parameter. That function will then take a parameter and return true if the parameter is undefined, and false otherwise.

So then each item in the array will call `equals(undefined)` on each item in the array, and return what would be expected.

**Comment by Bradcomp** [comment]
If we create an uncurried version of `equals` it would work as expected: 

```
// create a function that isn't curried but does the same thing as equals
// myEquals(person) will evaluate to equals(person, undefined)
const myEquals = (a, b) => equals(a, b)

const person = {name: 'hasan'}
const people = [person]

any(myEquals)(people) // false, as expected
```

**Comment by CrossEye** [comment]
Another way to think about 

```js
any (equals) (people)
```

is that it's similar to 

```js
people .some (a => b => a == b)
```

which in turn is like <sup>*</sup>

```js
(b => people [0] == b) || (b => people [1] == b) || (b => people [2] == b) || ...  || (b => people [n -1] == b)
```

which is interpreted as something like 

```js
<some function cast as boolean> || (b => people [1] == b) || (b => people [2] == b) || ...  || (b => people [n -1] == b)
```

and then to 

```js
true || (b => people [1] == b) || (b => people [2] == b) || ...  || (b => people [n -1] == b)
```

which, of course always yields `true`.  What we presumably  want instead is to pass `b => person == b` to the `some` call

This is an imperfect analogy, as Ramda's currying allows you to pass numbers of arguments and still get something useful, and of course Ramda's `equals` is more sophisticated than `==`, but the basic idea is the same. 

As Brad points out, this also applies to `equals()`, which in Ramda's curried world is just like `equals`.

----------
<sup>*</sup> Of course this is an idealization.  In fact JS interpreters don't convert all expressions for `any` at once, but one at a time until they find a truthy one.

**Comment by hmust92** [comment]
Thanks a lot @Bradcomp and @CrossEye ! I think I was confusing myself because I expected the function to return a function definition, but forgot that R.any will run a JS truthy check on it. Thanks so much for the response. I'll close this issue as I have understood the underlying mechanics of the function better now.
