### ISSUE TITLE
Curry bug when a function has a default value in params

### ISSUE THREAD

**Issue by BravenxX** [ramda/ramda#3105]
I reproduce the error in Ramda REPL: 

[Link](https://ramdajs.com/repl/?v=0.27.0#?%0A%0Aconst%20getUniqueValuesByKeys%20%3D%20R.curry%28%28init%20%3D%20%7B%7D%2C%20keys%2C%20data%29%20%3D%3E%0A%20%20data.reduce%28%28acc%2C%20item%29%20%3D%3E%20%7B%0A%20%20%20%20const%20x%20%3D%20%7B%20...acc%20%7D%3B%0A%0A%20%20%20%20for%20%28const%20i%20of%20keys%29%20%7B%0A%20%20%20%20%20%20if%20%28%21Array.isArray%28x%5Bi%5D%29%29%20x%5Bi%5D%20%3D%20%5B%5D%3B%0A%0A%20%20%20%20%20%20if%20%28%21_.isNil%28item%5Bi%5D%29%20%26%26%20%21_.includes%28x%5Bi%5D%2C%20item%5Bi%5D%29%29%20%7B%0A%20%20%20%20%20%20%20%20x%5Bi%5D%20%3D%20%5B...x%5Bi%5D%2C%20item%5Bi%5D%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20x%3B%0A%20%20%7D%2C%20init%20%29%2C%0A%29%3B%0A%0Aconst%20getNameValue%20%3D%20getUniqueValuesByKeys%28%7Bname%3A%20%5B%27hi%27%5D%7D%29%0A%0Aconsole.log%28%22It%20doesn%27t%20work%20because%20%28init%20%3D%20%7B%7D%29%22%2C%20getNameValue%29%20%0A%0A%2F%2F%20BUT%20IF%20YOU%20TRY%20-%3E%0A%0A%2F%2A%20%0Aconst%20getUniqueValuesByKeys%20%3D%20R.curry%28%28init%2C%20keys%2C%20data%29%20%3D%3E%0A%20%20data.reduce%28%28acc%2C%20item%29%20%3D%3E%20%7B%0A%20%20%20%20const%20x%20%3D%20%7B%20...acc%20%7D%3B%0A%0A%20%20%20%20for%20%28const%20i%20of%20keys%29%20%7B%0A%20%20%20%20%20%20if%20%28%21Array.isArray%28x%5Bi%5D%29%29%20x%5Bi%5D%20%3D%20%5B%5D%3B%0A%0A%20%20%20%20%20%20if%20%28%21_.isNil%28item%5Bi%5D%29%20%26%26%20%21_.includes%28x%5Bi%5D%2C%20item%5Bi%5D%29%29%20%7B%0A%20%20%20%20%20%20%20%20x%5Bi%5D%20%3D%20%5B...x%5Bi%5D%2C%20item%5Bi%5D%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20x%3B%0A%20%20%7D%2C%20init%20%29%2C%0A%29%3B%0A%0Aconst%20getNameValue%20%3D%20getUniqueValuesByKeys%28%7Bname%3A%20%5B%27hi%27%5D%7D%29%0A%0Aconsole.log%28%22It%20works%22%2C%20getNameValue%29%20%0A%2A%2F)

This function doesn't work

```
const getUniqueValuesByKeys = R.curry((init = {}, keys, data) =>
  data.reduce((acc, item) => {
    const x = { ...acc };

    for (const i of keys) {
      if (!Array.isArray(x[i])) x[i] = [];

      if (!_.isNil(item[i]) && !_.includes(x[i], item[i])) {
        x[i] = [...x[i], item[i]];
      }
    }
    return x;
  }, init ),
);
```

But if params are set like this: (init, keys, data) without init default value it works.

**Comment by CrossEye** [comment]
Well, first of all, there [are problems][md] with non-defaulted parameters after defaulted ones.  They are simply overridden at call time:

```js
const foo = (a, b, c) => ({a, b, c})

foo (6, 7, 8) //=> {a: 6, b: 7, c: 8}
foo (6, 7)    //=> {a: 6, b: 7, c: undefined}  // as expected
foo .length   //=> 3


const bar = (a = 42, b, c) => ({a, b, c})

bar (6, 7, 8) //=> {a: 6, b: 7, c: 8}
bar (6, 7)    //=> {a: 6, b: 7, c: undefined}  // note that the default is overridden
bar .length   //=> 0
```

From Ramda's point-of-view, though, the larger problem is the function arity.  Note that `bar.length` is `0`.  That's because any default parameters (as well as any subsequent ones) are not counted towards the function arity.  And the arity is critical in how Ramda curries functions.

Because of this, Ramda does not play very well with default parameters, or really with any other technique of handling optional parameters except for the common FP idiom of partially applying initial parameters to one function to get another:  `const derivedFn = baseFn (defaultVal)`, where `baseFn` is curried.

So this is something central that Ramda could not fix if it wanted to.  For your case, I would suggest not using the default parameter, and simply do something like

```js
const yourFnNameHere = getUniqueValuesByKeys ({name: ['hi']})
```

and then using `yourFnNameHere` instead of the original.

  [md]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Parameters_without_defaults_after_default_parameters

**Comment by sugoidesune** [comment]
@BravenxX  you could use `R.curryN(3, myFunction)` this will fix the arity at 3.
