### ISSUE TITLE
Comparing to compose+reduce, what's the benefit transduce give us?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#3112]
Except no intermediate results, dose transduce have other advantage?

**Comment by CrossEye** [comment]
Well, the whole point is to skip the intermediate results.  That's all transducers are really about.  There's a good argument that they are not worth the complexity in a library like Ramda.  One of the places they shine the most, though, is when you include `take(n)` on a potential infinite stream.  You get to write the simple transformations, filters, etc., and not have to do any particular gymnastics in order to collect the first `n` values.

**Comment by adispring** [comment]
@CrossEye , Thanks very much. You just make me begin to realize the value of `transducers`, which confused me so long before now.

> One of the places they shine the most, though, is when you include take(n) on a potential infinite stream. 

And as describes in [Clojure](https://clojure.org/reference/transducers):

> Because transducers are decoupled from input or output sources, they can be used in many different processes - collections, streams, channels, observables, etc. 

With `transducers`, we can process different type of collection in the same way, [as follows](https://codepen.io/adispring/pen/xxEKQae?editors=0010):

```js
const isEven = (x) => x % 2 === 0;

const transducer = R.compose(
  R.take(6),
  R.map(R.prop("count")),
  R.filter(isEven)
);

const sum = R.transduce(transducer, R.add, 0);

const arr = R.map((x) => ({ count: x }), [0, 1, 2, 3, 4, 5, 6, 7, 8]);
function* naturalGenerator() {
  let i = 0;
  while (true) {
    yield { count: i++ };
  }
}
const arrSum = sum(arr);
const generatorSum = sum(naturalGenerator());

console.log(arrSum); // 6
console.log(generatorSum); // 6
```
Without `transducers`, we have to implement different methods for different kinds of Data Structures.

Thanks again.
