### ISSUE TITLE
how to use traverse?

### ISSUE THREAD

**Issue by cieldon32** [ramda/ramda#3118]
The official demo can't run.
And then I guess:
const safeDiv = n => d => {
  return d < n ? fn(d) : fn(n);
}

const fn = (data) => {
  console.log(data);
  return data;
}

R.traverse(fn, safeDiv(10), [2, 4, 5]);

But it's not work. And I can't understand about traverse. 
I wanner use traverse to deep map/ filter / find / has.
Please tell me how to use traverse

**Comment by CrossEye** [comment]
It's not working in the REPL because the REPL is no longer properly loading the few FantasyLand type it had.  We really need to figure out why.  In the meantime, you can see it on [RunKit][rk].  While you can look at [`traverse`][tr] in the spec, I think that [TomHarding's series][th] explaining these types is the best I've seen and Part 12 discusses [`Traversable`][tt] (and the underlying `sequence`.)

  [rk]: https://runkit.com/crosseye/ramda-traverse
  [th]: http://www.tomharding.me/fantasy-land/
  [tr]: https://github.com/fantasyland/fantasy-land#traversable
  [tt]: http://www.tomharding.me/2017/05/08/fantas-eel-and-specification-12/

**Comment by customcommander** [comment]
Just tried now and seems to work. Assuming it has been fixed one way or another after the initial issue. Closing for now.
