### ISSUE TITLE
integrate mapIndex into ramda?

### ISSUE THREAD

**Issue by natinati8520** [ramda/ramda#3145]
instead of using addIndex(map), is it possible to integrate mapIndex as documented to Ramda?

**Comment by CrossEye** [comment]
It's certainly possible.  But Ramda is about simple things.  And `map` is a genuinely powerful concept that extends beyond indexed types such as arrays.  You can map an object.  You can map a `Maybe`, ideally you could map a `Promise`, and you certainly can map more disciplined types like `Future`. 

So we would never change `map` to handle this.  See the long discussion about this in #452, if you have a few hours to kill.

We could add `mapIndexed` easily enough.  But what's the gain?  It's the odd case, and trivial to implement in your own code as 
`const mapIndexed = addIndex(map)`, so I don't see the advantage.

Feel free to try to convince me otherwise, though.

**Comment by natinati8520** [comment]
Ramda mapping, as I see, is about arrays and objects (I guess I'm wrong here?), both of which have indexing.
A lot of JS mapping algorithms do include the index, and therefor I thought it could really fit (and easily as you said).

But you know better, thanks for the quick response anyways :)

**Comment by CrossEye** [comment]
Ramda handles mapping for arrays, objects, and functions (which is essentially composition), and delegates for any [Fantasy-land compatible Functor][fu].  Hence

```js
map (square) ([1, 2, 3, 4]) //=> [1, 4, 9, 16]
map (square) ({a: 1, b: 2, c: 3}) //=> {a: 1, b: 4, c : 9}
map (square) (add (1)) (6) //=> 49
map (square) (Just (5)) //=> Just (25)    
map (square) (Nothing()) //=> Nothing()
map (square) (Left ('error message')) //=> Left ('error message')
map (square) (Right (9)) //=> Right (81)
```

and so on.  One of the reasons that `map` does not include an index is that it gets very confusing when supplied a function with optional parameters:

```js
['1', '2', '3''] .map (parseInt) //=> [1, NaN, NaN] // Oops! Who knew `parseInt` accepted a `radix` parameter?
```

But

```js
map (parseInt) (['1', '2', '3'])//=>  [1, 2, 3] // Ahh
```

But this is not central.  The main issue is that a general purpose mapping can have no notion of an index.  Thus in early days, Ramda supplied a function namespaced inside `map`, so you could do ``map.idx((x, i) => `${i}: ${x}`)`` or some such.  And now such namespaced functions have been replaced with the general `addIndex`.

  [fu]: https://github.com/fantasyland/fantasy-land/tree/v4.0.1#functor

**Comment by natinati8520** [comment]
Thanks for the detailed answer :)
