### ISSUE TITLE
use Promise.all after ap, raise error  

### ISSUE THREAD

**Issue by HoKangInfo** [ramda/ramda#3157]
ex:
```
pipe(
  of,
  ap([
    () => Promise.resolve('a'),
    () => Promise.resolve('b')
  ]),
  Promise.all,  // TypeError: #<Object> is not a constructor
  // x => Promise.all(x),  // OK
  andThen(x => console.log(x))  // -> [ 'a', 'b' ]
)('test')
```
 UnhandledPromiseRejectionWarning: TypeError: #<Object> is not a constructor
    at all (<anonymous>)

**Comment by kedashoe** [comment]
Hi @HoKangInfo , this is a javascript thing rather than a ramda thing. When passing `Promise.all` (or any function!) to `pipe` (or anywhere!) the function loses its context. See for example https://stackoverflow.com/questions/44632732/why-passing-directly-promise-all-to-a-then-function-throws-an-error. As you observed, putting it in a lambda works. You could also use `bind` as in that stackoverflow answer. Hope that helps.

**Comment by CrossEye** [comment]
I usually write a quick helper such as `const allPromises = (ps) => Promises.all(ps)` to use in pipelines.

**Comment by HoKangInfo** [comment]
or add function `allThen` 
ex:
```
allThen (func, pss) => Promises.all(pss).then(func)
```

**Comment by HoKangInfo** [comment]
Thx
