### ISSUE TITLE
Feature Request: Add sameAndDifference and sameAndDifferenceWith

### ISSUE THREAD

**Issue by JMackie80** [ramda/ramda#3162]
Add functions similar to difference and differenceWith except returning an object with two arrays that contain the same objects and the different objects.

https://jsfiddle.net/gd36f4ow/1/

**Comment by CrossEye** [comment]
@JMackie80:  Please don't just post a link.  Explain in greater detail what your function does, provide some justification for why it belongs in Ramda, and show how much of a burden it would be to implement in users' own projects if Ramda did not include it.

Ramda cannot possibly include all functions that might be useful.  So we need to balance between the factors above.


(@ramda/core : I think we're going to need to start adding issue templates here.  Does anyone have a collection they really like?)

**Comment by JMackie80** [comment]
Apologies @CrossEye . Below is the code I linked to. The purpose of the function would be to do what the difference function does, but to return both the differences and the objects that are the same. I believe right now users need to implement this themselves or possible call the difference function multiple times which causes multiple iterations. Please let me know if more information is needed. Thank you for you consideration.

const _includesWith = (pred, x, list) => {
  let idx = 0;
  const len = list.length;

  while (idx < len) {
    if (pred(x, list[idx])) {
      return true;
    }
    idx += 1;
  }
  return false;
}

const sameAndDifferenceWith = (pred, first, second) => {
  const same = [];
  const different = [];
  let out = { same, different };
  let idx = 0;
  const firstLen = first.length;
  while (idx < firstLen) {
    if (!_includesWith(pred, first[idx], second) &&
        !_includesWith(pred, first[idx], out)) {
      different.push(first[idx]);
    } else {
    	same.push(first[idx]);
    }
    idx += 1;
  }
  return out;
};

console.log(sameAndDifferenceWith((a,b) => a.id === b.id, [{id: 1}, {id: 2}, {id: 3}],[{id: 1}, {id: 4}, {id: 5}]));

**Comment by CrossEye** [comment]
@JMackie80: Thanks for the update  I'm glad to have the code here in the issue, but that wasn't the main point.

I don't think I personally have ever had the need for this function.  Like everyone, I imagine, I use that as a proxy to determine just how widely useful a function is.  And so this one comes up short.  But my own experiences aren't everyone.  Here we try to give a fair hearing, even to those ideas that are not immediately obvious to the core team.

What I'm hoping you can do, then, is to show one of two reasons this should be included in Ramda, either:

  - Why this function fills a widespread need that much of the Ramda-using community could well have (even if they don't know it yet), _or_

  - How tricky is is for uses implementing this on their own to get this right, either because there is a lot of code or because there are unsuspected edge cases and special conditions.

If it meets neither of those conditions, then it's probably not worth adding to Ramda's already-large interface.  But either of them might be a good reason to implement it.  So I'm hoping you might have arguments along one of those lines.

If not, it can always be added to the [Cookbook][cb] or proposed to [ramda-adjunct][ra], which tries to pick up the widely useful functions that don't fit with Ramda.

/ping @char0n 

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [ra]: https://github.com/char0n/ramda-adjunct

**Comment by JMackie80** [comment]
Thanks @CrossEye , I will try to address those 2. If it doesn't meet the threshold to be added, I completely understand and it would be great if @char0n would consider it for Cookbook or ramda-adjunct.

Why this function fills a widespread need that much of the Ramda-using community could well have (even if they don't know it yet)

- The use case is the same as with the difference function, except that both same and different objects are returned. This would be needed when anyone wants to do one thing with the different objects and another with the same objects, which is what we are facing.

How tricky is is for uses implementing this on their own to get this right, either because there is a lot of code or because there are unsuspected edge cases and special conditions.

- I don't see this as tricky, just a lot of code that people don't want to write like the difference function itself.

**Comment by CrossEye** [comment]
I don't have time to really think this through now, but let me just put out this untested implementation that may do what you want:

```js
const sameAndDifferenceWith = applySpec ({
  different: differenceWith,
  same: innerJoin
})
```

It would have to loop through the data twice, but it seems fairly elegant.

**Comment by JMackie80** [comment]
Thanks, but was trying to avoid the multiple iterations. After thinking about it more though, it looks like this could be accomplished with a groupBy. Thanks for your help @CrossEye , sorry to take your time.

`R.groupBy((b) => [{id: 1}, {id: 4}, {id: 5}].findIndex(a => a.id === b.id) >= 0 ? 'same' : 'different', [{id: 1}, {id: 2}, {id: 3}]);`

**Comment by CrossEye** [comment]
@JMackie80:

> it looks like this could be accomplished with a groupBy

Yes, and there's probably a decent solution with `partition` followed by `zipObj(['different', 'same'])`.  If we tried, we could probably come up with many more techniques.

>  Thanks for your help @CrossEye , sorry to take your time.

Not at all.  We look forward to discussing possible new functions, even when most of them don't make the cut.
