### ISSUE TITLE
package.json "exports" field gone when installing from npm

### ISSUE THREAD

**Issue by erwin-k** [ramda/ramda#3189]
Like the title says, the "exports" field is missing and this disables esbuild's tree shaking.

**Comment by semmel** [comment]
The reason is that the ["Fix for importing Ramda in ESM-compatible nodes"](#2999) (also see the [diff](https://github.com/ramda/ramda/commit/87d90ba3c0e116a49718cc5cb7a181d5acf8bee2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)) landed *31 March 2020*, but Ramda version `v0.27` was released *26 May 2019*.

`v0.27.1` although released later did not pick up changes in-between because of failing (imo way too complicated) build scripts which also involve building the documentation and stuff. All that is automatic but seems no longer to work. See e.g. #3062. 
So the latest `v0.27.1` is essentially `v0.27.0` shipping source code today about 1 1/2 years old.

For someone with npm publishing rights it should be [straight-forward](https://github.com/ramda/ramda/issues/3062#issuecomment-764863771) to knock out a fresh release though. Sad it still did not happen.

Sorry but for over a year now this has been a very frustrating issue for me. 😞

**Comment by erwin-k** [comment]
@semmel You can use `@erwink/ramda` for now if you'd like

`"dependencies: { "ramda": "npm:@erwink/ramda@^0.27.1-erwink.0" }`
