### ISSUE TITLE
v0.28.0 is coming!

### ISSUE THREAD

**Issue by customcommander** [ramda/ramda#3211]
Hi all and happy new year!

We intend to release v0.28.0 by the end of next week (Jan 16th).

Release notes will be shared in due time but please be aware that this release will have some breaking changes (we're still in v0).

The following functions have been removed:

- `composeK` (see `composeWith`)
- `composeP` (see `composeWith`)
- `contains` (see `includes`)
- `merge` (see `mergeAll`, `mergeRight` and `mergeLeft`)
- `pipeK` (see `pipeWith`)
- `pipeP` (see `pipeWith`)

The reported vulnerability (see https://github.com/ramda/ramda/pull/3177) has been addressed and the fix will ship in that release too.

Thank you all for your continued support and patience.

*PS: It is possible that the documentation site will be temporarily out of date by the time we release v0.28.0. We're working on it ;)*

**Comment by tonytamps** [comment]
I am eagerly awaiting this release because of the upstream security issues it's causing, so thank you.

I'm feeling a little put off by the comment about the breaking changes though. This package has been in development for over 7 years and is used in some of the most popular node packages in the ecosystem. I feel like these things should create an obligation to move to a stable 1.x.x release and prevent braking changes in the future. Is there a reason this hasn't had a stable release?

Security fixes bundled with breaking changes as a child dependency of a dependency is a recipe for disaster for many applications.

**Comment by ap-shahar** [comment]
Thank you @customcommander, this update is long waiting and going to solve a big problem we have in our project.

Can I quickly suggest, if possible, if there's a way to release the security update before the breaking changes? 
In my project, we use a 3rd party package, and while they fixed a bug that I need fixed, I can't upgrade since they are using this package and my organization's security scan blocks the PR for the update. The best scenario would be if we follow here what @tonytamps suggested which is to release a version without breaking changes as 0.28.X and the one with the breaking changes as 1.X.

What are your thoughts?

**Comment by semmel** [comment]
> The best scenario would be ...  to release a version without breaking changes as 0.28.X and the one with the breaking changes as 1.X.

@ap-shahar IMO the `master` branch already contains breaking changes wrt `v0.27.1`. Considering the duration since the last release, my guess is that a best-of-both-worlds scenario is not possible. (Though I am no git expert)

**Comment by ap-shahar** [comment]
> > The best scenario would be ...  to release a version without breaking changes as 0.28.X and the one with the breaking changes as 1.X.
> 
> @ap-shahar IMO the `master` branch already contains breaking changes wrt `v0.27.1`. Considering the duration since the last release, my guess is that a best-of-both-worlds scenario is not possible. (Though I am no git expert)

One option I can think of if the authors of this package are open to it would be to create a new commit that brings back `composeK` and `composeP` that will make a call to `composeWith` and also print a console warning that this will be deprecated in a next version and to use `composeWith` instead. And do the same with the rest of the breaking changes.

**Comment by customcommander** [comment]
Hi folks,

Thank you for your feedback!

We've decided to release the security patch for the ReDoS vulnerability in `v0.27.2` (see #3216).

**Comment by tonytamps** [comment]
Thank you 🙇
