### ISSUE TITLE
typescript .d.ts structure

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#3274]
From #3264 

> files structure? Should we keep the one-giant-index.d.ts or should we split each function into its own file?

Aside from the costs/benefits for those working on the types here in the ramda repo, are there any consequences one way or the other for the end users who will be using ramda/the types? Does it change how things can be imported?

**Comment by CrossEye** [comment]
I would definitely prefer separate files, at least for maintenance. If we combine them with a build step, that's fine, but I don't want us to have to maintain them in a single file.

**Comment by essenmitsosse** [comment]
I'd say the end user doesn't really care, since they rarely go into the definition files and if they do, they get there via their IDE. And if they want to get their by hand one-file-per-function is probably easier to navigate then the current structure. So my vote would also be for separate files. @adispring @somebody1234 @valerii15298 any thoughts?

**Comment by somebody1234** [comment]
I don't mind either way, but worth noting that it becomes quite a pain scrolling through 100+ files in the file tree on the side panel, rather than doing a Ctrl+F. This is probably why many JS libraries choose to have a single monolithic `index.d.ts`.

Also worth noting that if they click on `{@link }`s they are taken to the source, and I'd assume they'd prefer it to *not* open up 7 different files - that said, I don't think very many users would click the `{@link}`s in the first place

No clue whether it affects how files can be imported, the DT types needed to be reexported to the proper file structure IIRC? But if it works it works

**Comment by kedashoe** [comment]
quoting @essenmitsosse from the other thread

> right now all the JSDoc comments are manually mirrored for the d.ts

Ah! I did not realize that, I think I follow now what you were saying about the JSDocs. Personally I prefer a single .d.ts file, but maybe if we want to have a script that adds the current JSDocs to our .d.ts files it would be easier if we split out the definitions. Seems that most would prefer file-per-function as well.

Since the ultimate location of the .d.ts files will be in the unversioned `/es` directory during builds, would we rather

1. add a new directory such as `/types` for our .d.ts files?
2. put them alongside the js source files in `/source`?
3. something else?

I'd vote for 1

**Comment by essenmitsosse** [comment]
Intuition tells me to go with 1 as well.

**Comment by CrossEye** [comment]
:+1: on option 1.

**Comment by kedashoe** [comment]
Alright #3280 has been merged and new version has been published.

I've got a list of issues from that PR from @adispring (thanks again!). I'm going to hold off on creating those for now, as any more work we do on ts will benefit from #3273, so I think we do that one next.
