### ISSUE TITLE
starting point for .d.ts

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#3275]
quoting @somebody1234

> not too sure about using such an old version of the types, there's a huge amount of work on the types that will need to be carried over... it's probably easier/better to start with the latest version and gradually remove ts-toolbelt

My thinking here is starting from a version with no dependencies, we can incrementally improve and publish at any point.

If we start with dependencies, it could be difficult to remove them and we'd get ourselves stuck.

**Comment by somebody1234** [comment]
I'm guessing it's several years old though. So that's several years of work we'd have to redo, vs reimplementing a few types from ts-toolbelt

**Comment by somebody1234** [comment]
Well... more importantly, it risks reopening any bugs etc. that may have been fixed during that time

**Comment by kedashoe** [comment]
Does anyone else have an opinion on this? I disagree, but I'll update our index.d.ts if that is the way yall want to go.

It's true it's been several years, but time isn't really what matters here. How many changes to ramda have there been in that time and how many commits to the DT file? Not many changes to ramda, and say about 70 commits in DT? And how many of those were bugs vs DT specific refactoring?

On the other hand, the [current ramda .d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts) has 42 calls to ts-toolbelt (mostly Curry, but also Take, NumberOf, Flatten, Parameters, Merge, Return, UnNest) and there are 36ish DT helpers used, which themselves use about 8 more ts-toolbelt functions. This doesn't sound very easy to me to re-implement.

**Comment by somebody1234** [comment]
Worth noting that commits are squashed, so that's not 70 commits, that is 70 separate changes, each potentially with several commits.

Note also:
- `UnNest` - [removed in my (abandoned) PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59677/files)
- `Merge`, `Return` - also used once. worst case we can just remove the definition completely
- `Parameters` - in the PR, there was only one use remaining - the one with `Merge` and `Return`
- `NumberOf` - also completely removed.
- `Take` - *also* completely removed

In `tools.d.ts`:
- `A.x` - this is a simple interface, trivial to implement.
  - Worth noting though, it does have special behavior in some ts-toolbelt types. That said, it mostly affects `Curry`, and the fate of placeholders in the typings is in limbo anyway - not to mention we want to remove ts-toolbelt types anyway...
- `A.Clean` - firstly, QoL only. can be removed. secondly it doesn't exist in current ts-toolbelt anyway
- `M.Primitive` - simple union, trivial to implement.
- `O.MergeUp`, `O.AssignUp` - these ones may pose a problem
- `T.ObjectOf`, `T.UnionOf` - these are only used where `O.*` are
  - worth noting it's not too hard to just completely reimplement these types

So I think for the most part, most of the work of reimplementing/removing ts-toolbelt is either easy, or already done

**Comment by somebody1234** [comment]
Also worth noting that removing ts-toolbelt would be a huge decrease in QoL IMO - I'd rather have one dependency rather than make the types a lot less usable

**Comment by adispring** [comment]
> How many changes to ramda have there been in that time and how many commits to the DT file? Not many changes to ramda, and say about 70 commits in DT? And how many of those were bugs vs DT specific refactoring?

Before @types/ramda@v0.27, There are many wrong typed api signatures, I fixed lots of them in v0.27. So I also do not think it's a good idea to start at 0.25.

As @somebody1234 said, most of ts-toolbelt helper types are easy to implement by ourself, even if the helper type is not easy to implement, if it only be used once or less than 3(the number is just an eixtimate number) times, we can use `any` to implement the ramda api types which use these ts-toolbelt helpers.

**Comment by kedashoe** [comment]
Alright, thanks for the feedback. Let's go with the latest version and see where that gets us. PR up [here](https://github.com/ramda/ramda/pull/3277)

**Comment by kedashoe** [comment]
Alright, closed via https://github.com/ramda/ramda/commit/0756cb308e8dbd0a769dd4e87d72db983efd3422

We are now using the latest DT types.

If anyone had previously pulled down the ts branch, you'll need to reset and pull again, as I deleted some commits which caused some confusion with the tags here in the ramda repo. I've released the typescript stuff now as version 0.40.1, still under `ramda-ts-self`.
