### ISSUE TITLE
Adjust type inconsistencies with strings

### ISSUE THREAD

**Issue by JuanGalilea** [ramda/ramda#3339]
The `adjust` function behaves weird with strings, when given an empty string it returns the same empty string. but when its given any other string it breaks it up into an array of characters.
![image](https://user-images.githubusercontent.com/17620917/203569203-627bbfd1-d561-435e-ace1-f0d3fa5ff930.png)

**Comment by semmel** [comment]
According to the documentation `adjust` does not work on strings, just on "List" aka `Array`. In theory it could be expanded to work on strings. Then it would have to check that the given function `(a → a)` maps characters on characters. Otherwise it would return something else than a string.

**Comment by JuanGalilea** [comment]
True, maybe i should just make a PR expanding the functionality to strings (and solve that issue)

**Comment by semmel** [comment]
>  Then it would have to check that the given function `(a → a)` maps characters on characters.

Maybe **not such a good idea** after all because one cannot guarantee that for every character argument.  So depending on the source string `adjust` would return something else. But the output type should be consistent! 
E.g. `map` *guarantees* that it returns the *same collection type* as goes in. Regardless of the actual data values in that collection. 

Does that make sense?

**Comment by JuanGalilea** [comment]
true, will build it in-house as a different function.
Perhaps having it as a different function here could help
