### ISSUE TITLE
pathEq types are not consistent with the code in 0.29.0

### ISSUE THREAD

**Issue by dibell** [ramda/ramda#3378]
0.29.0 added a breaking change to pathEq, swapping the parameter order: val, path, obj
The types-ramda 0.29.2 package is not in line with this: path, val, obj

types-ramda *is* correct in the develop branch. This needs to be pushed out to match the 0.29.0 release.

**Comment by Harris-Miller** [comment]
@dibell fix was released in `types-ramda@0.29.3`: https://github.com/ramda/types/releases/tag/v0.29.3

**Comment by codan84** [comment]
This doesn't seem to be available on nom yet:
https://www.npmjs.com/package/@types/ramda?activeTab=versions
Latest is 0.29.2

**Comment by Harris-Miller** [comment]
@codan84 `@types/ramda` is `0.29.2` but it utilizes `types-ramda` `0.29.3`. `types-ramda` is a path release ahead due to a bad initial release. See [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/package.json#L4).

Playground example of `pathEq` being the correct argument order: https://tsplay.dev/WoxQ9w

**Comment by kedashoe** [comment]
@Harris-Miller not sure that playground example is pointing to the right place? In any event, installing @types/ramda looks like it grabs types-ramda 0.29.3, ty!
