### ISSUE TITLE
R.find and R.propEq

### ISSUE THREAD

**Issue by NiclasKa** [ramda/ramda#3380]
There is an issue with R.find when used with R.propEq with Ramda version 0.29.0.

The following code on Ramda documentation is not working:
`const xs = [{a: 1}, {a: 2}, {a: 3}];`
`R.find(R.propEq('a', 2))(xs); //=> {a: 2}`
`R.find(R.propEq('a', 4))(xs); //=> undefined`

Both are giving undefined now. [https://ramdajs.com/docs/#find](url)

I have tested this on my own environment and by running the code on the documentation page.

**Comment by kedashoe** [comment]
Hi @NiclasKa , thank you for reporting the issue. This was fixed in https://github.com/ramda/ramda/pull/3373/files, however the documentation website has not been updated. We've not had a way to publish new docs without publishing a new version of ramda, I'll see if I can get around that limitation and get the doc changes up.

**Comment by kedashoe** [comment]
OK should be updated now, ty again for the report
