### ISSUE TITLE
callback args

### ISSUE THREAD

**Issue by jdalton** [ramda/ramda#452]
Not sure if this has been brought up but many of your methods like `map` and `some` only provide the `value` to their callbacks instead of the traditional `value, index, object`. Other functional currying-by-default libs, like [FKit](https://github.com/nullobject/fkit), do pass the traditionally expected arguments.

**Comment by CrossEye** [comment]
Above we allow @jdalton to have an open-ended say about his suggestion that Ramda change its API in a way that would make it more like Lo-Dash's.  There are about twenty comments from him above, and the conversation was allowed to continue as long as participants cared about it, even though it grew rather acrimonious; a vigorous exchange of ideas is important to us.

But when I [make the inverse suggestion][ld844] on the Lo-Dash list, that its API get expanded in a way more consistent with Ramda's, he locked the issue, preventing further comment after only my fourth comment on the thread.

What gives?  Why would someone work so hard to promote changing someone else's library, but care so little about criticism of his own that he cuts off debate so soon?

For the record, below was what I was planning on as my final comment on that thread.

  [ld844]: https://github.com/lodash/lodash/issues/844 

----------

>> With the radical changes that `_.rearg` will allow, you still don't offer this simple functionality that other libraries and languages do.

> Sure it does. Devs are free to use `_.ary` and `_.rearg` on any function, Lo-Dash or otherwise. We provide `_.runInContext` and `_.mixin` to allow creating and extending lodash instances. The functionality is simple enough.

It's the difference between

    var res1 = _.mapNoIdx(coll_1, thirdPartyFn);
    // ...
    var res2 = _.mapNoIdx(coll_2, thirdPartyFn);

and 

    var wrappedThirdPartyFn = _.ary(thirdPartyFn, 1);
    // ...
    var res1 = _.map(coll_1, wrappedThirdPartyFn );
    // ...
    var res2 = _.map(coll_2, wrappedThirdPartyFn);

To me, the former is substantially simpler.  And even if you forgo the named function and only wrap the function anonymously, this makes you write code that tweaks the library rather than code that expresses your intent.  To my mind, higher-level libraries should not be doing this.

> Added complexity is minimal with no impact on performance of the common case and low risk due to its narrow check. The result is happy, not annoyed devs.

I'll take your word on performance.  As I've said before, that's not one of my strong suits.  But I am strongly concerned about API design.  And the above smacks of a lazy design.  

>> Moreover, how do you respond to the reasonable request that map extend to other types than array, string, and object?

> I'm fine with map's designation as a collection method. We're not looking to expand "collection" at the moment.

But do you recognize the rationale for this?  Mapping is a pretty essential notion, and the simple idea of extracting the element or elements of a collection, running a given function against them and wrapping the results into the same sort of collection is pretty straightforward.  Libraries like [Highland][hl], [Transducers][tr] and [Lazy][la] demonstrate this clearly, and the [FantasyLand spec][fl] makes it explicit.  Mapping is a fairly generic notion and limiting it to indexable collections is fairly limited.  There are similar points for many similar functions.

  [fl]: https://github.com/fantasyland/fantasy-land#functor
  [hl]: http://highlandjs.org/#map
  [la]: http://danieltao.com/lazy.js/docs/#Sequence-map
  [tr]: https://github.com/cognitect-labs/transducers-js

**Comment by jdalton** [comment]
> What gives?

Ya sorry about that but I've said all there is to say really.
I'm not obligated to engage in endless debate with you.

**Comment by CrossEye** [comment]
>> What gives?

> Ya sorry about that, but I've said all there is to say really.

No.

Perhaps you've said all you mean to say, but I had one more round in me.

> I'm not obligated to engage in endless rounds of debate/tit-for-tat with you.

No, but do you feel you always have to have the last word?

Closing on ongoing debate that had not gotten heated, had not turned into a flamefest, had not at all lowered the discourse is simply puerile.  You could have simply walked away.  In fact, I was expecting to do so myself after the message above.
