### ISSUE TITLE
standardize capitalization of JSDoc type annotations

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#528]
We use `{Boolean}`/`{Number}`/`{String}` in some places and `{boolean}`/`{number}`/`{string}` in others. Let me know the preferred capitalization and I'll make the appropriate tweaks.

**Comment by TimeForAChange** [comment]
It's a bit late commenting maybe, but "number" and "Number" are two different types in Javascript. One is a primitive, the other is an object.

**Comment by CrossEye** [comment]
Ramda doesn't really have any particular dealings with the wrapper types.  Obviously you could pass them to Ramda functions, where they would be treated like any other object.

But this issue was really about our type signatures.  So, for instance, `size :: [a] -> Number` instead of `size :: [a] -> number`.
