### ISSUE TITLE
Introduce R.bindAll

### ISSUE THREAD

**Issue by anton-rudeshko** [ramda/ramda#559]
Its absence really ties me back to lodash =(

https://lodash.com/docs#bindAll

What do you think?

**Comment by eteeselink** [comment]
I was looking for the same, turns out this issue ranks high enough on google for "ramda bindAll". So if anyone else comes here the same way, I temporarily worked around the "lack" of bindAll with this stopgap.

    R.bindAllIn = function bindAllIn(thisObj) {
        function bind(method) {
            thisObj[method] = R.bind(thisObj[method], thisObj);
        };
        R.forEach(bind, R.functionsIn(thisObj));
    }

I named it `bindAllIn` because it includes functions from the prototype. Turns out the various bindAll implementations in the wild differ in opinion on that - some include the prototype, some only the own properties. Figured we might as well immediately follow Ramda conventions while we're at it (a matching `bindAll` is made by replacing `functionsIn` by `functions`).

Sorry if this is deemed an inappropriate place to post this. Thanks for Ramda!

**Comment by CrossEye** [comment]
This is a very appropriate place to post it.

There is one very good reason that the Ramda team resists this so strongly: Ramda has made a firm commitment to never modify user data. 

It's easy to mistake Ramda for a Underscore/Lo-Dash style library because there is a large overlap in the functionality.   But Ramda was designed for a different purpose, to enable you to more easily work with functional pipelines in JS.  This focus on functional programming means that we always avoid mutation.

And that's why `bindAll` doesn't fit, except possibly in the `impure` extension.

**Comment by eteeselink** [comment]
Oh, sorry, I left that out: I'm aware of your reasons and I strongly agree with them :-) I think that in reality, if we forget about chronology for a while, you could easily say that Underscore is a Ramda style library, and not the other way around. It has all the functional helpers you'd expect (weirdly implemented though, with inconsistent argument order, random "do what i mean"-style thinking, and occasional "hey let me just mutate that for you" in unexpected places) and then like 5 other functions that happen to involve side-effects (such as `bindAll`).

I do, however, think that there's good grounds for further developing the `impure` extension (I wasn't aware it's actually there by now, the above discussion happened before then), if only to better compete with Underscore and friends. The overlapping surface area is so big that it'd be great if Ramda could be a complete enough replacement, which it can't without such an impure extension. 

I'd contribute `bindAllIn` to https://github.com/ramda/ramda/tree/master/ext/impure if I'd understand how it works: the `setProp` function isn't bound to `R` anywhere yet the test calls `R.setProp`. Am I missing some magic here?

All that said, I just realized that there is may well be ways to make `bindAll`-style functionality available without mutating user objects or giving up performance. For example, by decorating constructor functions.

I often call `_.bindAll(this)` as the first call on a constructor function, so that objects it generates have auto-bound functions (React does something similar on component instances, for example). I'm sure some people call `bindAll` on objects created elsewhere, but in all honesty that feels hacky, even though I guess you can't always avoid it.

I could imagine something like 

    var Banana = R.allBound(function() {
         this.foo = 'bar';
         ...
    });
    Banana.prototype = { .. many functions .. };

for defining a constructor function. The function returned by `allBound`, will call `bindAllIn` on `this` before invoking the user's constructor function.

I could also imagine a use for a `bindAll`-style function which *only* copies functions, *only* from the prototype, onto a new object itself (otherwise assigning the same prototype). This has the exact same effect as `_.bindAll` when called first thing in a constructor function like `this = R.bindAllPrototypeFunctions(this)`. Or something.

OK, I'm done braindumping. I'll be happy to help with the impure extension!

**Comment by CrossEye** [comment]
I agree with everything you say except for the last paragraph, which doesn't make much sense to me.  I would think that you would need to c opy pretty well of of an object's properties, and bind those methods you wanted (all of them?) onto your new object if any of the functions make reference to `this.something`.  Such a function might be worth considering, but it could well still have surprising behavior for those used to an impure `bindAll`: not only will this only work with the newly-created object, but it could be broken entirely if the functions used local closure references to items on the original object.

(There's also an issue with your Banana example.  I don't  know if its fixable.  The trouble is that the anonymous function on which `allBound` would be working is not the actual Banana object with the prototype that gets set.)

We still have work to do on the build to allow us to include various extensions inside Ramda.  Or at least that had been my idea; I think the other collaborators may have moved on from this notion.  But the tests of these extensions aren't being automatically run.  In fact, not much has been done with these extensions since they were first written.  I would like to change that before the next release.

I do believe this would be a good addition to the `impure` extension.  And I think it's time to do something more useful with the extensions.  Any help, any suggestions, would be welcome.
