### ISSUE TITLE
Ramda, React and FRP libraries

### ISSUE THREAD

**Issue by yemi** [ramda/ramda#640]
I really like how Ramda lets you write javascript in a functional manner and really want to incorporate this in one of my new projects that is being built with React.js.

So my question is whether there is a way that makes sense to use Ramda for all the jsx iterators common in react apps?

Example iterator:

``` Javascript
render: function() {
  var listItems = this.props.items.map(function (item) {
    return (
    <li className="item" key={item}>
      {item}
    </li>
    );
  });
  return (
  <ul>
    {listItems}
  </ul>
  );
}
```

If it doesn't make sense to use Ramda for this kind of use and only/mostly for returning regular objects/values please let me know.

There is another thing that I'm pretty confused about:

**Whats the relationship between Ramda and FRP libraries like Baconjs/Rxjs?**

I know that Baconjs/Rxjs is for handling different kind of events but since everything can be an eventstream (eg. JSON response) which could be manipulated by a stream of filter/map/reduce methods it seems like you can solve the same problems with both Ramda and Baconjs/Rxjs, or am I getting this completely wrong?

If these are just different libraries that help solving the same _kind_ of problems, then;

**What are the pros/cons with using Ramda over Baconjs/Rxjs?**

**Comment by loganpowell** [comment]
Love this thread! I could also use some advice on this topic. Here's my current thinking:

### ? Is it about the view ? 

A: Use Ramda, because it allows us to compose our React components more functionally. Ramda is more focused on static functions rather than things (e.g., events) that change over time.

### ? Is about state ?

A: Use RxJS, because it allows us to stream our state through our components (e.g., using something like [Recompose's Observable Utils](https://github.com/acdlite/recompose/blob/master/docs/API.md#observable-utilities))

### ? Is it about composition in general (e.g., reusing functions and/or streams) ?

Here's where I'm confused: It seems to me that both Ramda and RxJS have some part to play here. For example, there's this great [egghead tutorial](https://egghead.io/lessons/react-make-reusable-react-props-streams-with-lenses) that uses Ramda [`lens`](http://ramdajs.com/docs/#lens) with RxJS and the Observable Utils from Recompose to make a reusable React "prop stream." Here's the code:

[![Edit react-rxjs-lessons](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lxwv7j7l4m)

I'd really love to just settle on a toolset that I can grow old with and I'm zero'ing in on these three libraries to get married to (until they are made obsolete by better tools - hopefully far - down the road). Are the thoughts above missing some key parts? I.e., I feel like I'm missing something within the [Known | Unknown](https://www.youtube.com/watch?v=i1IjkfcwoHs) quadrant 😆

**Comment by kurtmilam** [comment]
@loganpowell It sounds like you're missing [calmm-js](https://github.com/calmm-js), with its outstanding [partial.lenses](https://github.com/calmm-js/partial.lenses) library + utilities that included versions of most Ramda functions lifted to work with observables.

Drop by the [calmm Gitter room](https://gitter.im/calmm-js/chat) if you'd like to ask questions in addition to perusing the documentation and libraries.

**Comment by loganpowell** [comment]
@kurtmilam `partial.lenses` looks incredibly comprehensive! Intimidatingly so 😆 IYO, is it worth learning an entirely separate lenses library? I'm not opposed of course, just trying to stay as lean as possible on the library dependencies. Can you help me understand its advantages?

**Comment by loganpowell** [comment]
Awe man, `calmm` looks like it really fits the bill nicely 😭 Can it replace Ramda entirely?

**Comment by kurtmilam** [comment]
I'd say it's definitely worth it, but note that the partial.lenses library is only one component in the larger calmm-js ecosystem.

Calmm-js allows you to embed observables directly in React (and some other vdom implementations) components. It's all about managing state via observables (atoms and streams) and lenses. If you're a fan of lenses and working with observables, I think you should definitely take a close look at calmm.

Hit the Gitter room and ask a few questions. The author, @polytypic , is super helpful, and he can answer your questions way better than I can.

> Can it replace Ramda entirely?

Calmm is very Ramda-friendly. I usually use them together, but calmm also offers versions of many/most Ramda functions that are lifted to work directly with observables. It's some of the coolest stuff I have seen.

**Comment by loganpowell** [comment]
OMG. I am reading more about `calmm` and I'm getting serious shiny object brain. I think this is exactly what I was looking for man. @kurtmilam you're my hero.
