### ISSUE TITLE
Allow empty parameters in curried functions

### ISSUE THREAD

**Issue by jon49** [ramda/ramda#690]
I have a function like so:

```
var identity = function(val) {
  return val;
}

var doLater = r.curryN(2, identity)
```

then I want to add the first value to the identity function

```
onclick(doLater(5))
```

but when `onclick` calls `doLater` it throws an error. This seems like poor behavior. I should be able to decide if I care if something is passed or not, not the curried function.

**Comment by babakness** [comment]
Perhaps this solution is kind of ugly but when exposing to the real world and need a function that takes no parameters to be execute like so `foobar()` instead of `foobar(undefined)`, perhaps one could do something like this

```javascript

R.compose( R.always, R.apply(R.__,[undefined]) )

```

This would only work if the function can only accept undefined as a parameter.
