### ISSUE TITLE
Some function is not curried in this chain?

### ISSUE THREAD

**Issue by alejandroiglesias** [ramda/ramda#693]
Hey guys, I have a question. I'm trying to replace the following function with Ramda sugar.

```javascript
// var query = 'string';
return list.map(function(item) {
    var indexOfAdvertiserName;
    var indexOfName;
    indexOfName = (('' + item.name).toLowerCase().indexOf(query) > -1);

    // Check first item.advertiser property exists because if item is 
    // shallow copy, it won't have it.
    indexOfAdvertiserName = (item.advertiser) ? (('' + item.advertiser.name).toLowerCase().indexOf(query) > -1) : false;

    if (!indexOfName && !indexOfAdvertiserName) return;
    return item;
});
```

Ramda version:

```javascript
// var query = 'string';
return R.map(R.pipe(
    R.ifElse(
        R.or(
            R.strIndexOf(query, R.prop('name')) > -1,
            R.strIndexOf(query, R.path('advertiser.name')) > -1
        ),
        R.identity,
        R.always(undefined)
    )
), list);
```

I understand that `R.strIndexOf` takes strings as both parameters, but isn't the context passed into `R.prop` in this case for it to return the string? To my mind it seems that either `R.ifElse` or `R.or` are not passing the item from the list. But most probably I'm doing something wrong?
Thanks!

**Comment by CrossEye** [comment]
Can this be closed?

**Comment by alejandroiglesias** [comment]
Sorry guys, but not sure if fully understood the problem and proposed solution.

**Comment by CrossEye** [comment]
I'm not sure anyone proposed a full solution to your problem.

I didn't know if you'd solved it based on what was said here or on anything else.  I never really tried to put together a solution for you.  I think perhaps the most relevant response to your original code, though, was @kedashoe's comment:

> The arguments to or should be functions. Right now you have test expressions, which I think is what is causing things to appear that they are not curried

In other words,

    R.or(
        R.strIndexOf(query, R.prop('name')) > -1,
        R.strIndexOf(query, R.path('advertiser.name')) > -1
    ),

has an issue because `R.or` accepts functions, and you're supplying

    R.or(
        someFunction > -1,
        anotherFunction > -1
    )

which resolves to

    R.or(
        false,
        false,
    )

and those are not function parameters.

If you're still having problems solving your initial problem, let us know, and we'll see if we can help.

**Comment by CrossEye** [comment]
Closing for now.  If this needs another look, please let us know.
