### ISSUE TITLE
Add anyIndexed function

### ISSUE THREAD

**Issue by honzabrecka** [ramda/ramda#729]
Hi, I'm trying to implement something like this:

```
R.some.idx(function(value, i, list) { return value != R.nth((i + 1) % R.length(list), list); });
```

But Ramda doesn't provide indexed `some` or `any`. Wouldn't it be worth to add `anyIndexed` function?

**Comment by buzzdecafe** [comment]
I don't understand what this predicate proves: 

`function(value, i, list) { return value != R.nth(i, list); }`

as i read this, it says, "`true`, when the value at index `i` is not equal to the value at index `i`". Am I missing something?

we've been over the indexing thing before. I think what we would all like is a way to decorate iterators to take extra args, but default to the single arg case. What do you propose for `anyIndexed`? What is the API/signature?

**Comment by CrossEye** [comment]
We had a long, fairly rancorous discussion about this issue in #452.

There is a proposal, which I'm hoping to revive for version 0.10.0 in #484 to remove the `.idx` functions but allow you to wrap `reduce`, `map`, `filter`, `some`, etc like this:

    addIdx(map)(function(val, idx, all) { /* ... */ }, list);

But I don't understand what you're trying to do in that code block.  Can explain in more detail?

**Comment by honzabrecka** [comment]
Sorry guys, I made a mistake in my example, now it's ok. I would expect that `index` and `list` are extra params.

**Comment by CrossEye** [comment]
This will probably be available when we get the `addIdx` feature in place.  In the meantime, if I understand the code block above, all you're trying to do really is return `true` if there are two or more distinct values in the input list, `false` if the list contains all the same value.  If that's all you want, this would probably do the same:

    pipe(uniq, length, gt(R.__, 1))

There are many other possibilities.

When I have a few minutes, I'll try to explain my philosophical objection to these `idx` functions in general.

**Comment by CrossEye** [comment]
I wanted to discuss my reasons for objecting to the indexed versions of functions like `map`, `filter`, `reduce`, etc.  We had a long discussion about adding them to `some` and `any` back in #452, and a pass at how to replace them with a common wrapper function in #484.  But I never really articulated one of my major reasons for not liking them.

Of course the Transducers effort is underway now, but I've had a similar dream since very early on.  I wondered if we might be able to unify various data structures under our fairly straightforward API.  I thought about it then in perhaps simpler terms than I'm about to suggest here, but I've been headed this way for some time.  Then I thought chiefly about unifying things like arrays and streams; Highland beat us to that.  We added the dynamic dispatch originally for the lazy lists, and expanded it so that we could handle the [FantasyLand][fl] specification.  These are all very useful and important.  But I also would really like to extend many of our key functions to many other data types beyond these algebraic types.

Think about `map` for a moment.  In essence, mapping is really simple:  You accept a function and a data structure containing elements in the domain of the function.  You return an equivalent data structure with elements in the co-domain of the function.  The corresponding elements in the returned structure are the result of running the function on the elements of the original structure.  This is clear enough for a list: the new structure has a head which is the function applied to head of the original list and a tail which is the mapping of the function to the tail of the original list.  The recursion bottoms out with an empty list, which returns an empty list.  It's pretty simple.

But let's look at another data structure.  Why can't we easily map over a tree?

Say we had this tree, `tree1`:

                   A
        +----------^----------+
        |          |          |
        B          C          D
    +---^---+  +---^---+  +---^---+
    |   |   |  |       |  |   |   |
    1   E   4  6       7  8   F   4
      +-^-+                   |
      |   |                   |
      2   3                   6
      
      
Then if we wanted to map `square` over that tree, the result should be pretty obvious:

    map(square, tree1); //=>
    
                   A
        +----------^----------+
        |          |          |
        B          C          D
    +---^---+  +---^---+  +---^---+
    |   |   |  |       |  |   |   |
    1   E  16 36      49 64   F  16
      +-^-+                   |
      |   |                   |
      4   9                  36
      

Similarly if we wanted to run filter over the tree:

    filter(odd, tree1); //=>
      
             A      
        +----^-----+
        |          |
        B          C
    +---^---+      |    
    |       |      |
    1       E      7
            |            
            |
            3

It would be extremely useful if a number of our functions could work on a data type such as a tree.  Or a stream.  Or a monad.  Or ... there are many possibilities.  I don't really expect to get these ideas working particularly soon, but would like to keep them in mind as we work with the API.  The `index` API, however, ties us to array-like data structures.  It seems to tie our hands for the future.  And I'm loathe to do that.

Trees do not have indices.  Streams do not have indices.  Even lists really don't have indices, although we can find a simple-enough way to simulate them.  Vectors and arrays have indicese.  Tying ourselves down this way seems far too limiting.

In any case, that's one of my reasons.  Does this make sense?
            

  [fl]: https://github.com/fantasyland/fantasy-land

**Comment by honzabrecka** [comment]
I totally understand, I haven't thought about that this way. Thanks for the explanation.

My real world example is that I have a polygon defined by N vertices (x, y) and I want to compute its axes, vectors between two vertices (N, N + 1). Maybe I'm missing something, but to do this, I need to know current index and N:

```js
var axes = R.map.idx(function(vertex, i, vertices) {
    return Vector(
      vertices[i],
      vertices[(i + 1) % vertices.length]
    );
});
```

**Comment by buzzdecafe** [comment]
> I want to compute its axes, vectors between two vertices (N, N + 1).

treating elements of array-like objects in pairwise fashion is the argument I usually see for the index parameter. And it's true that without it, pairwise iteration is awkward without the index parameter.

So I guess this issue is another incentive to fill that gap ...

**Comment by davidchambers** [comment]
@honzabrecka, I would write it this way:

```javascript
var axes = R.compose(R.map(R.apply(Vector)),
                     R.converge(R.zip,
                                R.identity,
                                R.converge(R.concat,
                                           R.skip(1),
                                           R.take(1))));
```

I defined the following function to allow me to test this in the REPL:

```javascript
function Vector(x, y) { return [x, y]; }
```

**Comment by CrossEye** [comment]
@honzabrecka: 

I saw what you were looking for earlier in the day, far from my computer, and came up with a solution almost identical to @davidchambers' version.  But as mine is broken down into distinct parts, it might be worth seeing independently:

```javascript
var rotate = R.converge(R.append, R.head, R.tail); // [a, b, c, d] => [b, c, d, a] 
var pairs = R.converge(R.zip, R.identity, rotate); // [a, b, c] => [[a, b], [b, c], [c, a]]
var axes = R.pipe(pairs, R.map(R.apply(vector)));
```

This is for the case as David suggested and `vector` is a plain binary function.  If it's a 2-arg constructor, you could use this instead:

```javascript
var axes = R.pipe(pairs, R.map(R.apply(R.construct(Vector))));
```

Again, this is functionally no different from David's version, but obviously the code is structured a bit differently.

**Comment by davidchambers** [comment]
Naming the components is nice. I don't like using `R.head`, though, due to the empty list case. `R.zip([], [undefined])` gives `[]`, which is what we want, but it's cleaner to use `R.take(1)` and `R.concat` so we always apply `R.zip` to lists of equal length. :)
