### ISSUE TITLE
data structures

### ISSUE THREAD

**Issue by honzabrecka** [ramda/ramda#772]
Hi,

how would you transform items on just those specified indices without mutating the items?

```
var state = {
  items: [{...}, {...}, ...],
  indices: [3, 8]
};
```

This is just one example of how I use Ramda to manipulate state in my real world prototype based on React.

Haven't you thought about developing your own data structures? Or supporting for example Immutable.js?

Thanks

**Comment by buzzdecafe** [comment]
> how would you transform items on just those specified indices without mutating the items?

you could use a [`lens`](http://ramdajs.com/docs/#lens) to do this, or perhaps you could use [`evolve`](http://ramdajs.com/docs/#evolve).

> Haven't you thought about developing your own data structures? Or supporting for example Immutable.js?

Sounds good to me -- we try to be compatible with the [fantasy-land](https://github.com/fantasyland/fantasy-land) spec (although there are gaps), but that means you can use ramda seamlessly with other functor-containing libraries, e.g. Bacon, Highland, etc. Also, please check out [ramda-fantasy](/ramda/ramda-fantasy) and [Sanctuary](/plaid/sanctuary).

**Comment by CrossEye** [comment]
As well as the suggestions from @buzzdecafe, I was going to suggest [`assoc`][as], but as it turns out (#773), it doesn't work properly on arrays.

While, as Mike said, you can work seamlessly with other functors, I am very much interested in expanding our interoperability through the dispatch.  I'm thinking part of that might happen through the transducers effort, if we end up being able to support the [Transformers Protocol][tp].  More might happen simply by dispatching additional functions (and possibly, I'm afraid to say, by adding back certain aliases, or making it easy for users to hook into our aliasing feature.)  I'm less certain about creating our own data structures, however.  Working with lists and objects is difficult enough.  Adding further options to the library directly is a frightening prospect.

  [as]: http://ramdajs.com/docs/#assoc
  [tp]: https://github.com/jlongster/transducers.js?files=1#the-transformer-protocol

**Comment by kevinbeaty** [comment]
See #878

**Comment by honzabrecka** [comment]
@kevinbeaty That's awesome!

**Comment by ArnoBuschmann** [comment]
@honzabrecka I'd be interested to know, how you use Ramda together with React. Did you have Ramda working together with Immutable.js? Or did you use Ramda directly and if so, does its immutability serve well with React?

**Comment by fyyyyy** [comment]
Instead of using Immutable.js, consider https://github.com/rtfeldman/seamless-immutable
ramda should work well with this, will try this soon
