### ISSUE TITLE
R.init(arguments) => TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by raine** [ramda/ramda#839]
Is this a known issue?

[Ramda REPL](http://goo.gl/hyAdQ7)

**Comment by buzzdecafe** [comment]
hmmm. i'm seeing `TypeError: n[t] is undefined` which is not particularly illuminating

**Comment by CrossEye** [comment]
Errors in the REPL are going to be based on minimized code, so might not be all that helpful.

I get the same error as @buzzdecafe.  And it makes sense, since `init` is defined in terms of our public `slice`, which simply calls `slice` as a method of the target object.  That won't work with an `arguments` object.

Although it's not documented to work with anything but `[a]`, I think it would be best to reimplement this so that it works with anything that passes `isArrayLike`.
