### ISSUE TITLE
deprecated functions

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#844]
there is a `@deprecated` tag. let's use that before removing functions in future. http://usejsdoc.org/tags-deprecated.html

**Comment by CrossEye** [comment]
Yes.  Perhaps something like this

    /*
     * @deprecated as of v0.10.1.  Removal planned: v0.12.0
     */

**Comment by buzzdecafe** [comment]
will have to update the jsdoc template to reflect that status. `blink` tag, anyone?

**Comment by honzabrecka** [comment]
I'll do it.

**Comment by buzzdecafe** [comment]
:tada: that's fantastic! thanks

**Comment by davidchambers** [comment]
I'm now believe keeping unwanted functions around for one or two releases to be a bad idea. Let's consider a concrete example, `R.propOf`, which will either be removed or deprecated in 0.11.0 (see #831).

First, let's consider what will happen if `R.propOf` is removed in 0.11.0 from the perspective of Alice, a Ramda user keen to upgrade:

1.  Alice will read the release notes and see that the function has been removed.

2.  Alice will replace occurrences of `R.propOf` with `R.prop(R.__)`.

Next, let's consider what would happen were we instead to deprecate `R.propOf`:

1.  Alice will read the release notes and see that the function has been deprecated.

2.  Alice will replace occurrences of `R.propOf` with `R.prop(R.__)`.

3.  For the next couple of months, Alice will do her best to remember not to use `R.propOf`, and will remind her peers during code reviews that `R.propOf` is deprecated and suggest they use `R.prop(R.__)` instead.

4.  At some point in the future a Ramda release will remove `R.propOf`. Alice, knowing that occurrences of `R.propOf` are likely to have crept back in, will repeat step 2.

Since Alice will end up doing a second pass to remove occurrences of `R.propOf`, she needn't bother to make any changes in response to the deprecation notice. In fact, her best course of action is to _ignore deprecations_. If she does so, she'll end up in exactly the same position as in the scenario in which `R.propOf` is removed without notice (just a couple of months later). Deprecations simply postpone the work required to upgrade. This sounds like a win until one realizes that in order to start using version N one must do the work one put off when upgrading to version N − 1.

Deprecating functions doesn't reduce the effort required to upgrade to a new version of Ramda. It does, however, increase complexity for those developing and documenting Ramda. I'm in favour of continuing to rip the plaster off in one go. :)

**Comment by TheLudd** [comment]
@davidchambers 
I think the major difference with deprecated functions is that Alice can:
 1. Upgrade to the new version with deprecated functions
 2. Not have anything break
 3. Change to the new functions piece by piece without ever breaking anything, all tests pass all the time.
 4. Move to the next version again, where the previously deprecated function has been removed, and still not have anything break.

This is not possible with the current strategy, it guarantees that your code will be broken at some point. And if 5 functions change that you use all over your project, this is a LOT of breakage. 

Does anyone know a library with a big user base that upgrades the way ramda has done so far?

And here is the recommendation from [semver](http://semver.org) on how to handle breaking functionality. I know they are talking about versions > 1.0.0 but I believe we have agreed that that is not really important now.

> How should I handle deprecating functionality?

> Deprecating existing functionality is a normal part of software development and is often required to make forward progress. When you deprecate part of your public API, you should do two things: (1) update your documentation to let users know about the change, (2) issue a new minor release with the deprecation in place. Before you completely remove the functionality in a new major release there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.

**Comment by donnut** [comment]
I've seen libraries warning about the use of deprecated functions in the console. In that way you can still use them, but you are reminded in such a way that you want to get rid of them asap ;)

**Comment by TheLudd** [comment]
@donnut #786

**Comment by davidchambers** [comment]
> Change to the new functions piece by piece without ever breaking anything, all tests pass all the time.

This is where you lose me. I don't understand the desire to make changes piecemeal rather than all at once:

```console
$ find lib -name '*.js' -print0 | xargs -0 sed -i '' 's/R[.]propOf/R.prop(R.__)/g'
```

**Comment by TheLudd** [comment]
@davidchambers 
I think it is easier for you than for others to do these changes. Because if you didn't make the change yourself to ramda then you probably approved the merge or at least reviewed it. You are very aware of what has been changed between two versions. You are one of those that make the decisions on what to change knowing what effects it will have on your projects. This is not true for everyone else.

I am pretty active here which makes me somewhat aware but not fully and it is even worse for the casual user. 

Even with a changelog, it can be pretty difficult to realize all functions that are used in my project. There are other people working my code as well. This is especially true for a changelog as big as `0.9.0` and `0.10.0`.

The update `0.8.0` -> `0.10.0` took me 2 hours. Perhaps I could have done it better, smarter but not everyone works in the same way and has the same pre conditions. 

Your way might be a good way but I don't think it can be considered to be *the* way to do stuff, and neither can mine of course. And judging by the issues/comments ramda gets when breaking changes are introduced it seems I am not alone in thinking that it is just search/replace.  

And if I loose you when I explain how I do stuff, then *I* am totally lost in the case against deprecation, a widely applied way of handling breaking changes in the coding community.

**Comment by CrossEye** [comment]
I'm going to agree with @TheLudd here.  @davidchambers, you know I envy your working environment.  But imagine one where developers are working in time zones ten hours apart, communicating through emails that are often skipped, through a cumbersome, if powerful code review tool, with thirty or more pairs of hands in the same code-base, still using Subversion for SCM.  Imagine now that half of these are fairly junior developers who need hand-holding to do more complex tasks, and some of the others are grizzled veterans whose transitions from COBOL to .NET to Javascript fills them with such pride that they have a hard time hearing anything against their latest 50-line imperative implementation of `mixin`.

Now think of the codebase of several hundred thousand lines of Javascript, as well as many ancillary systems.  Oh, and the corporate standards only give you Windows desktops for development.  Macs are viewed with deep skepticism.  *nix desktops are just a distant rumor.  If you're one of the lucky ones, you're developing with the IntelliJ product, WebStorm, which is IMHO, actually a decent tool for doing front-end work.  If not, you're trying to do this in Visual Studio or Eclipse.

The most knowledgeable developers in the systems might have reasonable understanding of 40% of the system.  There is decent unit test coverage, but it's a UI and the functional/integration test coverage is woefully inadequate (not that I've ever seen it otherwise.)

In an environment like this, an upgrade to a core library is not a quick fix.  It's almost never measured in hours.  Days or weeks are much more likely.  So a chance to use a deprecation period to do this carefully and check it before it becomes a hard choice is very useful.  And it often is a hard choice, with a library still adding useful features.  "I really want the new `foobar` function, but it'll take four days to upgrade from 0.9.1 to 0.10.0, and I can't afford that at this stage of the project," sounds all too familiar.

And if none of that is convincing: it would be nice to be in the right habits to match the semver discipline after we reach 1.0.

**Comment by buzzdecafe** [comment]
:+1: @CrossEye 

Have you considered writing horror stories? You have a knack for it ....

**Comment by davidchambers** [comment]
Okay, I'm on board. I'll open pull requests to deprecate a handful of functions in 0.11.0.

**Comment by jeduden** [comment]
@CrossEye :+1:
