### ISSUE TITLE
stop updating dist/ramda.js with each commit

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#849]
Updating __dist/ramda.js__ with each commit is problematic for several reasons:

  - it makes contributing more difficult, particularly for documentation tweaks;
  - it adds a lot of noise, making pull requests more difficult to review; and
  - it increases the likelihood of merge conflicts.

While there are some benefits to having __dist/ramda.js__ up to date at all times, they do not justify the costs. I suggest this file only be built at release time (as is the case with __dist/ramda.min.js__).

**Comment by TheLudd** [comment]
Totally agree. Such a step is (at least for me) unexpected and seems to be the number 1 confusion when people contribute.

**Comment by megawac** [comment]
+1

**Comment by CrossEye** [comment]
:+1:, although I would actually like to have the file in the Github downloads and just add it to `.gitignore`.  I was hoping Travis would upload it for us on a successful build, but there [are issues][t929] with trying to run a script after all the independent builds run.  I think until we figure that out, our best bet is to simply stop including the file here.

We'll have to update the README to describe how to use it if you're getting the code from Github.


  [t929]: https://github.com/travis-ci/travis-ci/issues/929

**Comment by buzzdecafe** [comment]
let's make building the dist artifact a post-install script, since you have to `npm install` anyways

**Comment by CrossEye** [comment]
But now you don't have to.  You need to do that only if you want to modify Ramda.  If you just want to get the latest, use it and look at the source, right now everything comes down with `git clone`.  That's what I would find it a shame to lose.  But since I don't have a solution, I think this is the best we can do for now.  I looked at the Python script in that Travis issue, and am not particularly interested.  Travis closed the issue months ago, saying in essence, "We know it's a problem.  We'll get to it some day.   Maybe."
