### ISSUE TITLE
R.__ in anticommutative functions  divide, subtract, modulo

### ISSUE THREAD

**Issue by bobiblazeski** [ramda/ramda#854]
Why did you decided to allow R.__ into anticommutative functions  divide, subtract, modulo versus adding another version of those functions with arguments switched ?

**Comment by CrossEye** [comment]
Mostly as a matter of simplifying our API.  We had two versions of these at one point, but they are so redundant, they always seemed bothersome.  We tried a brief experiment with distinguishing what should be infix operators such as these from prefix functions and gave different semantics to currying them so that, e.g. `subtract(10)` was a function that subtracted ten from the supplied parameter.  But that was also problematic.

What we've settled on recently is to allow placeholders everywhere as well as offering the `flip` function for those who want it.  This give users the chance to define `divideBy = R.flip(R.divide)` if they need to, or simply use `var divideBy10 = R.divide(R.__, 10);`.  It's not beautiful, but it's consistent with the rest of the library and keeps the footprint a bit smaller.

Does that make sense?

(BTW, is there some sense in which one could define `modulo` as anticommutative?  It's obvious for `subtract` and `divide`, but I can't see it for `modulo`.)

**Comment by bobiblazeski** [comment]
From my usage it seems that flipped  versions of subtract, divide & modulo are far more common then vice versa. 

```javascript
var isOdd = R.modulo(R.__, 2);
var isOdd = R.remainder(2);

var minus5 = R.subtract(R.__, 5);
var minus5 = R.difference( 5);

var half = R.divide(R.__, 2);
var half = R. quotient(2);
```
Since you're using R.__  far too often having a single version seems like the right choice. Maybe check the usage after a while, and keep just the flipped versions as defaults.

**Comment by buzzdecafe** [comment]
i agree the flipped versions of the operators are more useful. however, we are taking infix `a op b` and converting it to `op a b`. IMO it is confusing to say that for infix style operations the argument order is flipped, i.e. `op b a`

**Comment by CrossEye** [comment]
The problem for reversing the sense of these functions is that it would work great when you curry them that way, but not when you call them fully-qualified:

    R.subtract(12, 7); //=> really seems like it should be 5, not -5
    R.modulo(14, 6); //=> definitely feels like 2, not 6

Since we've lost the `op` notion, I've toyed with adding the functions back in, but since they are such minor syntactic sugar with only minor gain, it's hard to justify cluttering the API.

Just note that there's absolutely nothing to prevent you from attaching your version to Ramda's namespace if you choose:

    R.quotient = R.flip(R.divide);
    // ... later
    var half = R.quotient(2);
