### ISSUE TITLE
Monad "do" notation using generators

### ISSUE THREAD

**Issue by scott-christopher** [ramda/ramda#992]
I'm curious to know whether there is any interest in supporting something like the following in Ramda, which essentially allows for syntax similar to Haskell's `do` notation when composing monads that implement the fantasy land spec (such as those in ramda-fantasy).

```js
// genDo :: (a -> b -> .. -> z)* -> (a -> b -> .. -> z) -> Monad
module.exports = function genDo(genFn) {
  return function() {
    var generator = genFn.apply(this, arguments);
    function cont(arg) {
      var result = generator.next(arg),
          value = result.value;
      return result.done ? value : value.chain(cont);
    }
    return cont();
  };
}
```

The function takes an ES6 generator that yields fantasy land monad values and returns a function whose arguments are passed through to create the generator instance.

Some examples:
```js
const
  genDo = require('./gen-do'),
  Promise = require('fantasy-promises'),
 
  delay = (n, v) =>
    new Promise(resolve => setTimeout(() => resolve(v), n)),
 
  afterDelay = genDo(function*(v1, v2) {
    // console.log('waiting for v1');
    const _v1 = yield delay(500, v1);
    // console.log('got: ' + _v1);
 
    // console.log('waiting for v2');
    const _v2 = yield delay(500, v2);
    // console.log('got: ' + _v2);
 
    return Promise.of(_v1 + " " + v2);
  });
 
afterDelay("Hello", "World!").fork(str => console.log(str));
```
```js
const
  genDo = require('./gen-do'),
  Option = require('fantasy-options'),
 
  phonebook = { 'schristo': '+61491570156' },
  govDb     = { '+61491570156': 'abc123' },
  taxDb     = { 'abc123': 'def456' },
 
  lookup = (k, obj) =>
    (k in obj) ? Option.Some(obj[k]) : Option.None,
 
  taxCodeLookup = genDo(function*(name) {
    const number = yield lookup(name, phonebook);
    const reg = yield lookup(number, govDb);
    return lookup(reg, taxDb);
  });
 
console.log('Searching for "schristo": ' + taxCodeLookup('schristo').getOrElse('Not found'));
console.log('Searching for "_schristo": ' + taxCodeLookup('_schristo').getOrElse('Not found'));
```

Now for the caveat: while the `genDo` function is ES5 compliant, it obviously depends on an ES6 generator to be of any use, meaning it would require some ES6 support to add test cases. This could be alleviated by pre-compiling some ES6 generators to ES5 compliant code using something like babel, but it's currently a caveat nonetheless.

**Comment by scott-christopher** [comment]
And to clarify, the following code:
```js
genDo(function*(v1, v2) {
  const _v1 = yield delay(500, v1);
  const _v2 = yield delay(500, v2);
  return Promise.of(_v1 + " " + v2);
});
```
is equivalent to something like:
```js
function (v1, v2) {
  return delay(500, v1).chain(function(_v1) {
    return delay(500, v2).chain(function(_v2) {
      return Promise.of(_v1 + " " + v2);
    });
  })
}
```

**Comment by buzzdecafe** [comment]
i think this makes sense for ramda-fantasy. (I also think `commute` and `commuteMap` should move to ramda-fantasy.)

The other issue is this: http://kangax.github.io/compat-table/es6/

generators are not widely supported yet.

**Comment by bergus** [comment]
No @scott-christopher they are not equivalent. They would work only for monads that wrap at most a single value and call their callbacks at most once, i.e. Maybes and their async counterpart Promises. It does not work for other monads such as lists or functions, which are common enough to avoid supporting this `genDo`.
Those monads are impossible to support using generator syntax, because ES6 generators cannot be cloned of forked. It was discussed on esdiscuss, but was found to be too complicated and errorprone.

I think we should leave this territory to promise libraries (which also can properly handle rejections and cancellations). And for those who want monadic `do`-notation, they can still use transpilers (as they would for ES6 generators anyway) such as http://livescript.net/#functions-backcalls, https://www.npmjs.com/package/monadic, http://www.purescript.org/, http://lispyscript.com/ or http://lattejs.com/#monads

**Comment by scott-christopher** [comment]
@bergus: The makes complete sense and something I overlooked.
